#
# Makefile for MStar ALSA audio device drivers.
#

obj-$(CONFIG_MSTAR_ALSA_AUDIO_DRIVER_DRV)           += alsa_audio_driver/drv/
obj-$(CONFIG_MSTAR_ALSA_AUDIO_DRIVER_HAL)           += alsa_audio_driver/hal/
