#
# Makefile for MStar Semutex device drivers.
#

# general options
EXTRA_CFLAGS      +=  -Idrivers/mstar/include
EXTRA_CFLAGS      +=  -Idrivers/mstar/semutex

# specific options
EXTRA_CFLAGS      +=

# files
obj-$(CONFIG_MSTAR_SEMUTEX)	+= mdrv-semutex.o
mdrv-semutex-objs			+= mdrv_semutex.o
