////////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 2006-2008 MStar Semiconductor, Inc.
// All rights reserved.
//
// Unless otherwise stipulated in writing, any and all information contained
// herein regardless in any format shall remain the sole proprietary of
// MStar Semiconductor Inc. and be kept in strict confidence
// (¡§MStar Confidential Information¡¨) by the recipient.
// Any unauthorized act including without limitation unauthorized disclosure,
// copying, use, reproduction, sale, distribution, modification, disassembling,
// reverse engineering and compiling of the contents of MStar Confidential
// Information is unlawful and strictly prohibited. MStar hereby reserves the
// rights to any and all damages, losses, costs and expenses resulting therefrom.
//
////////////////////////////////////////////////////////////////////////////////

// This file is generated by script, please do not edit it directly
#ifndef _MSD3102EQ_H_
#define _MSD3102EQ_H_

// PIN number to PAD name mapping
#define PIN_1               PAD_GPIO_PM5        // PAD_GPIO_PM5
#define PIN_2               PAD_GPIO_PM6        // PAD_GPIO_PM6
#define PIN_9               PAD_DDCDB_DA        // PAD_DDCDB_DA//
#define PIN_12              PAD_HOTPLUGB        // PAD_HOTPLUGB/
#define PIN_18              PAD_DDCDB_CK        // PAD_DDCDB_CK
#define PIN_29              PAD_HOTPLUGA        // PAD_HOTPLUGA
#define PIN_31              PAD_DDCDA_DA        // PAD_DDCDA_DA
#define PIN_32              PAD_DDCDA_CK        // PAD_DDCDA_CK
#define PIN_45              PAD_CVBS3P          // PAD_CVBS3P
#define PIN_46              PAD_CVBS2P          // PAD_CVBS2P
#define PIN_47              PAD_CVBS1P          // PAD_CVBS1P
#define PIN_49              PAD_CVBS0P          // PAD_CVBS0P
#define PIN_57              PAD_DDCA_DA         // PAD_DDCA_DA
#define PIN_58              PAD_DDCA_CK         // PAD_DDCA_CK
#define PIN_78              PAD_TS0_D0          // PAD_TS0_D[0]
#define PIN_79              PAD_TS0_D1          // PAD_TS0_D[1]
#define PIN_80              PAD_TS0_D2          // PAD_TS0_D[2]
#define PIN_81              PAD_TS0_D3          // PAD_TS0_D[3]
#define PIN_82              PAD_TS0_D4          // PAD_TS0_D[4]
#define PIN_83              PAD_TS0_D5          // PAD_TS0_D[5]
#define PIN_84              PAD_TS0_D6          // PAD_TS0_D[6]
#define PIN_85              PAD_TS0_D7          // PAD_TS0_D[7]
#define PIN_86              PAD_TS0_VLD         // PAD_TS0_VLD
#define PIN_87              PAD_TS0_SYNC        // PAD_TS0_SYNC
#define PIN_88              PAD_TS0_CLK         // PAD_TS0_CLK
#define PIN_89              PAD_PCM_D3          // PCM_D3/CI_D3
#define PIN_90              PAD_PCM_D4          // PCM_D4/CI_D4
#define PIN_91              PAD_PCM_D5          // PCM_D5/CI_D5
#define PIN_92              PAD_PCM_D6          // PCM_D6/CI_D6
#define PIN_93              PAD_PCM_D7          // PCM_D7/CI_D7
#define PIN_94              PAD_PCM_CE_N        // PCM_CE_N/CI_CS
#define PIN_95              PAD_PCM_A10         // PCM_A10/CI_A10
#define PIN_96              PAD_PCM_OE_N        // PCM_OE_N
#define PIN_98              PAD_PCM_A11         // PCM_A11/CI_A11
#define PIN_99              PAD_PCM_IORD_N      // PCM_IORD_N/CI_RD
#define PIN_100             PAD_PCM_A9          // PCM_A9/CI_A9
#define PIN_101             PAD_PCM_IOWR_N      // PCM_IOWR_N/CI_WR
#define PIN_102             PAD_PCM_A8          // PCM_A8/CI_A8
#define PIN_103             PAD_PCM_A13         // PCM_A9/CI_A13
#define PIN_104             PAD_PCM_A14         // PCM_A14/CI_A14
#define PIN_105             PAD_PCM_WE_N        // PCM_WE_N
#define PIN_106             PAD_PCM_IRQA_N      // PCM_IRQA_N/CI_INT
#define PIN_107             PAD_PCM_A12         // PCM_A12/CI_A12
#define PIN_108             PAD_PCM_A7          // PCM_A7/CI_A7
#define PIN_109             PAD_PCM_A6          // PCM_A6/CI_A6
#define PIN_110             PAD_PCM_A5          // PCM_A5/CI_A5
#define PIN_111             PAD_PCM_WAIT_N      // PCM_WAIT_N/CI_WACK
#define PIN_112             PAD_PCM_A4          // PCM_A4/CI_A4
#define PIN_113             PAD_PCM2_CE_N       // CI_RESET
#define PIN_114             PAD_PCM2_IRQA_N     // CI_CD
#define PIN_116             PAD_DDCDC_CK        // PAD_DDCDC_CK
#define PIN_119             PAD_DDCDC_DA        // PAD_DDCDC_DA
#define PIN_128             PAD_HOTPLUGC        // PAD_HOTPLUGC
#define PIN_129             PAD_SPI_CK          // PAD_SPI_CK
#define PIN_130             PAD_SPI_DI          // PAD_SPI_DI
#define PIN_131             PAD_SPI_DO          // PAD_SPI_DO
#define PIN_132             PAD_SPI_CZ          // PAD_SPI_CZ
#define PIN_133             PAD_PWM0            // PAD_PWM0
#define PIN_134             PAD_PWM1            // PAD_PWM1
#define PIN_135             PAD_B_ODD0          // PAD_B_ODD[0]
#define PIN_136             PAD_B_ODD1          // PAD_B_ODD[1]
#define PIN_137             PAD_B_ODD2          // PAD_B_ODD[2]
#define PIN_138             PAD_B_ODD3          // PAD_B_ODD[3]
#define PIN_139             PAD_B_ODD4          // PAD_B_ODD[4]
#define PIN_140             PAD_B_ODD5          // PAD_B_ODD[5]
#define PIN_141             PAD_B_ODD6          // PAD_B_ODD[6]
#define PIN_142             PAD_B_ODD7          // PAD_B_ODD[7]
#define PIN_143             PAD_G_ODD0          // PAD_G_ODD[0]
#define PIN_144             PAD_G_ODD1          // PAD_G_ODD[1]
#define PIN_145             PAD_G_ODD2          // PAD_G_ODD[2]
#define PIN_146             PAD_G_ODD3          // PAD_G_ODD[3]
#define PIN_148             PAD_G_ODD4          // PAD_G_ODD[4]
#define PIN_149             PAD_G_ODD5          // PAD_G_ODD[5]
#define PIN_150             PAD_G_ODD6          // PAD_G_ODD[6]
#define PIN_151             PAD_G_ODD7          // PAD_G_ODD[7]
#define PIN_152             PAD_R_ODD0          // PAD_R_ODD[0]
#define PIN_153             PAD_R_ODD1          // PAD_R_ODD[1]
#define PIN_154             PAD_R_ODD2          // PAD_R_ODD[2]
#define PIN_155             PAD_R_ODD3          // PAD_R_ODD[3]
#define PIN_156             PAD_R_ODD4          // PAD_R_ODD[4]
#define PIN_157             PAD_R_ODD5          // PAD_R_ODD[5]
#define PIN_158             PAD_R_ODD6          // PAD_R_ODD[6]
#define PIN_159             PAD_R_ODD7          // PAD_R_ODD[7]
#define PIN_163             PAD_PCM_A3          // PAD_PCM_A3/CI_A3
#define PIN_164             PAD_PCM_A2          // PAD_PCM_A2/CI_A2
#define PIN_165             PAD_PCM_REG_N       // PAD_PCM_REG_N/CI_CLK
#define PIN_166             PAD_PCM_A1          // PAD_PCM_A1/CI_A1
#define PIN_167             PAD_PCM_A0          // PAD_PCM_A0/CI_A0
#define PIN_168             PAD_PCM_D0          // PAD_PCM_D0/CI_D0
#define PIN_169             PAD_PCM_D1          // PAD_PCM_D1/CI_D1
#define PIN_170             PAD_PCM_D2          // PAD_PCM_D2/CI_D2
#define PIN_172             PAD_TS1_D0          // PAD_TS1_D0
#define PIN_173             PAD_TS1_VLD         // PAD_TS1_VLD
#define PIN_174             PAD_TS1_SYNC        // PAD_TS1_SYNC
#define PIN_175             PAD_TS1_CLK         // PAD_TS1_CLK
#define PIN_250             PAD_ET_COL          // Jupiter GPIO
#define PIN_251             PAD_ET_TXD1         // Jupiter GPIO
#define PIN_252             PAD_ET_TXD0         // Jupiter GPIO
#define PIN_253             PAD_ET_TX_EN        // Jupiter GPIO
#define PIN_254             PAD_ET_TX_CLK       // Jupiter GPIO
#define PIN_255             PAD_ET_RXD0         // Jupiter GPIO
#define PIN_256             PAD_I2S_IN_WS       // PAD_I2S_IN_WS/Jupiter GPIO
#define PIN_257             PAD_I2S_IN_BCK      // PAD_I2S_IN_BCK/Jupiter GPIO
#define PIN_258             PAD_I2S_IN_SD       // PAD_I2S_IN_SD
#define PIN_259             PAD_SPDIF_IN        // PAD_SPDIF_IN
#define PIN_260             PAD_I2S_OUT_MCK     // PAD_I2S_OUT_MCK
#define PIN_261             PAD_I2S_OUT_WS      // PAD_I2S_OUT_WS
#define PIN_265             PAD_I2S_OUT_BCK     // PAD_I2S_OUT_BCK
#define PIN_266             PAD_I2S_OUT_SD      // PAD_I2S_OUT_SD
#define PIN_267             PAD_SPDIF_OUT       // PAD_SPDIF_OUT
#define PIN_268             PAD_DDCR_DA2        // PAD_DDCR_DA2
#define PIN_269             PAD_DDCR_CK2        // PAD_DDCR_CK2
#define PIN_270             PAD_LHSYNC2         // PAD_I2S_OUT_MUTE/UART_RX1
#define PIN_271             PAD_LVSYNC2         // Jupiter GPIO/UART_TX1
#define PIN_272             PAD_GPIO12          // UART_RX2/Jupiter GPIO
#define PIN_273             PAD_GPIO13          // UART_TX2/Jupiter GPIO
#define PIN_274             PAD_GPIO14          // PAD_PWM2
#define PIN_275             PAD_GPIO15          // PAD_PWM3
#define PIN_291             PAD_GPIO_PM0        // PAD_GPIO_PM0
#define PIN_292             PAD_GPIO_PM1        // PAD_GPIO_PM1
#define PIN_293             PAD_GPIO_PM2        // PAD_GPIO_PM2
#define PIN_294             PAD_GPIO_PM3        // PAD_GPIO_PM3
#define PIN_295             PAD_GPIO_PM4        // PAD_GPIO_PM4

// PAD name to index
#define PAD_NC              9999
#define PAD_GND             0

#define PAD_GPIO_PM7        1
#define PAD_GPIO_PM8        2
#define PAD_GPIO_PM9        3
#define PAD_GPIO_PM10       4
#define PAD_GPIO_PM5        5
#define PAD_GPIO_PM6        6
#define PAD_DDCDB_DA        15
#define PAD_HOTPLUGB        18
#define PAD_DDCDB_CK        23
#define PAD_HOTPLUGA        32
#define PAD_DDCDA_DA        34
#define PAD_DDCDA_CK        35
#define PAD_CVBS7P          59
#define PAD_CVBS6P          60
#define PAD_CVBS5P          61
#define PAD_CVBS4P          62
#define PAD_CVBS3P          64
#define PAD_CVBS2P          65
#define PAD_CVBS1P          66
#define PAD_CVBS0P          68
#define PAD_DDCA_DA         76
#define PAD_DDCA_CK         77
#define PAD_TS0_D0          112
#define PAD_TS0_D1          113
#define PAD_TS0_D2          114
#define PAD_TS0_D3          115
#define PAD_TS0_D4          116
#define PAD_TS0_D5          117
#define PAD_TS0_D6          118
#define PAD_TS0_D7          119
#define PAD_TS0_VLD         120
#define PAD_TS0_SYNC        121
#define PAD_TS0_CLK         122
#define PAD_PCM_D3          123
#define PAD_PCM_D4          124
#define PAD_PCM_D5          125
#define PAD_PCM_D6          126
#define PAD_PCM_D7          127
#define PAD_PCM_CE_N        128
#define PAD_PCM_A10         129
#define PAD_PCM_OE_N        130
#define PAD_PCM_A11         131
#define PAD_PCM_IORD_N      132
#define PAD_PCM_A9          133
#define PAD_PCM_IOWR_N      134
#define PAD_PCM_A8          135
#define PAD_PCM_A13         136
#define PAD_PCM_A14         137
#define PAD_PCM_WE_N        138
#define PAD_PCM_IRQA_N      139
#define PAD_PCM_A12         140
#define PAD_PCM_A7          141
#define PAD_PCM_A6          142
#define PAD_PCM_A5          143
#define PAD_PCM_WAIT_N      144
#define PAD_PCM_A4          145
#define PAD_PCM2_CE_N       146
#define PAD_PCM2_IRQA_N     147
#define PAD_PCM2_WAIT_N     148
#define PAD_UART_RX2        149
#define PAD_UART_TX2        150
#define PAD_PF_AD15         151
#define PAD_PF_ALE          152
#define PAD_PF_CE0Z         153
#define PAD_PF_CE1Z         154
#define PAD_PF_OEZ          155
#define PAD_PF_WEZ          156
#define PAD_F_RBZ           157
#define PAD_DDCDC_CK        158
#define PAD_DDCDC_DA        161
#define PAD_HOTPLUGC        168
#define PAD_SPI_CK          169
#define PAD_SPI_DI          170
#define PAD_SPI_DO          171
#define PAD_SPI_CZ          172
#define PAD_PWM0            173
#define PAD_PWM1            174
#define PAD_PWM2            175
#define PAD_PWM3            176
#define PAD_DDCR_DAT        177
#define PAD_DDCR_CLK        178
#define PAD_B_ODD0          179
#define PAD_B_ODD1          180
#define PAD_B_ODD2          181
#define PAD_B_ODD3          182
#define PAD_B_ODD4          183
#define PAD_B_ODD5          184
#define PAD_B_ODD6          185
#define PAD_B_ODD7          186
#define PAD_G_ODD0          187
#define PAD_G_ODD1          188
#define PAD_G_ODD2          189
#define PAD_G_ODD3          190
#define PAD_G_ODD4          191
#define PAD_G_ODD5          192
#define PAD_G_ODD6          193
#define PAD_G_ODD7          194
#define PAD_R_ODD0          195
#define PAD_R_ODD1          196
#define PAD_R_ODD2          197
#define PAD_R_ODD3          198
#define PAD_R_ODD4          199
#define PAD_R_ODD5          200
#define PAD_R_ODD6          201
#define PAD_R_ODD7          202
#define PAD_LCK             203
#define PAD_LDE             204
#define PAD_LHSYNC          205
#define PAD_LVSYNC          206
#define PAD_PCM_A3          207
#define PAD_PCM_A2          208
#define PAD_PCM_REG_N       209
#define PAD_PCM_A1          210
#define PAD_PCM_A0          211
#define PAD_PCM_D0          212
#define PAD_PCM_D1          213
#define PAD_PCM_D2          214
#define PAD_PCM_RESET       215
#define PAD_PCM2_RESET      216
#define PAD_PCM_CD_N        217
#define PAD_PCM2_CD_N       218
#define PAD_TS1_D0          219
#define PAD_TS1_VLD         220
#define PAD_TS1_SYNC        221
#define PAD_TS1_CLK         222
#define PAD_ET_COL          329
#define PAD_ET_TXD1         330
#define PAD_ET_TXD0         331
#define PAD_ET_TX_EN        332
#define PAD_ET_TX_CLK       333
#define PAD_ET_RXD0         334
#define PAD_I2S_IN_WS       335
#define PAD_I2S_IN_BCK      336
#define PAD_I2S_IN_SD       337
#define PAD_SPDIF_IN        338
#define PAD_I2S_OUT_MCK     339
#define PAD_I2S_OUT_WS      340
#define PAD_ET_CRS          341
#define PAD_ET_TXD3         342
#define PAD_I2S_OUT_BCK     343
#define PAD_ET_TXD2         344
#define PAD_I2S_OUT_SD      345
#define PAD_ET_TRXER        346
#define PAD_SPDIF_OUT       347
#define PAD_ET_RXER         348
#define PAD_DDCR_DA2        349
#define PAD_ET_RX_CLK       350
#define PAD_DDCR_CK2        351
#define PAD_ET_RX_DV        352
#define PAD_LHSYNC2         353
#define PAD_LVSYNC2         354
#define PAD_ET_RXD1         355
#define PAD_GPIO12          356
#define PAD_ET_RXD2         357
#define PAD_GPIO13          358
#define PAD_ET_RXD3         359
#define PAD_GPIO14          360
#define PAD_ET_MDC          361
#define PAD_GPIO15          362
#define PAD_ET_MDIO         363
#define PAD_GPIO_PM0        376
#define PAD_GPIO_PM1        377
#define PAD_GPIO_PM2        378
#define PAD_GPIO_PM3        379
#define PAD_GPIO_PM4        380

// PADS group name to index
#define PADS_DDCR           382
#define PADS_DDCR2          383
#define PADS_TS0            384
#define PADS_TS1            385
#define PADS_GPIO1_GPIO2    386
#define PADS_LHSYNC2_LVSYNC2 387
#define PADS_PCI_AD20_AD21  388
#define PADS_PCI            389
#define PADS_PCM            389
#define PADS_SAR            390
#define PADS_DOUT           391
#define PADS_DIN            392
#define PADS_ATCON_MODE1    393
#define PADS_ATCON_MODE2    394
#define PADS_DTCON_MODE1    395
#define PADS_FCIE_CONFIG1   396
#define PADS_FCIE_CONFIG2   397
#define PADS_I2S            398
#define PADS_PF             399
#define PADS_EMAC           400
#define PADS_UART1_MODE1    401
#define PADS_UART1_MODE2    402
#define PADS_UART1_MODE3    403
#define PADS_UART2_MODE1    404
#define PADS_UART2_MODE2    405
#define PADS_UART2_MODE3    406
#define PADS_WF_MODE1       407
#define PADS_WF_MODE2       408
#define PADS_WF_MODE3       409
#define PADS_ET_MODE0       410
#define PADS_ET_MODE1       411
#define PADS_ET_MODE2       412

// PAD index to GPIO number mapping
#define GPIO_PAD_161        GPIO_DDCD2_SDA
#define GPIO_PAD_168        GPIO_HPDC
#define GPIO_PAD_353        GPIO78
#define GPIO_PAD_136        GPIO33
#define GPIO_PAD_134        GPIO31
#define GPIO_PAD_198        GPIO125
#define GPIO_PAD_181        GPIO108
#define GPIO_PAD_128        GPIO25
#define GPIO_PAD_114        GPIO4
#define GPIO_PAD_139        GPIO35
#define GPIO_PAD_117        GPIO7
#define GPIO_PAD_170        GPIO81
#define GPIO_PAD_116        GPIO6
#define GPIO_PAD_129        GPIO26
#define GPIO_PAD_185        GPIO112
#define GPIO_PAD_172        GPIO82
#define GPIO_PAD_112        GPIO2
#define GPIO_PAD_188        GPIO115
#define GPIO_PAD_370        GPIO146
#define GPIO_PAD_77         GPIO_DDCA0_SCL
#define GPIO_PAD_219        GPIO63
#define GPIO_PAD_121        GPIO11
#define GPIO_PAD_125        GPIO22
#define GPIO_PAD_18         GPIO_HPDB
#define GPIO_PAD_329        GPIO89
#define GPIO_PAD_336        GPIO68
#define GPIO_PAD_372        GPIO148
#define GPIO_PAD_221        GPIO65
#define GPIO_PAD_214        GPIO58
#define GPIO_PAD_349        GPIO76
#define GPIO_PAD_220        GPIO64
#define GPIO_PAD_195        GPIO122
#define GPIO_PAD_23         GPIO_DDCD1_SCL
#define GPIO_PAD_189        GPIO116
#define GPIO_PAD_207        GPIO51
#define GPIO_PAD_332        GPIO94
#define GPIO_PAD_147        GPIO43
#define GPIO_PAD_140        GPIO36
#define GPIO_PAD_358        GPIO85
#define GPIO_PAD_120        GPIO10
#define GPIO_PAD_380        GPIO138
#define GPIO_PAD_192        GPIO119
#define GPIO_PAD_351        GPIO77
#define GPIO_PAD_173        GPIO45
#define GPIO_PAD_127        GPIO24
#define GPIO_PAD_333        GPIO95
#define GPIO_PAD_142        GPIO38
#define GPIO_PAD_331        GPIO93
#define GPIO_PAD_362        GPIO87
#define GPIO_PAD_211        GPIO55
#define GPIO_PAD_143        GPIO39
#define GPIO_PAD_377        GPIO135
#define GPIO_PAD_200        GPIO127
#define GPIO_PAD_6          GPIO140
#define GPIO_PAD_187        GPIO114
#define GPIO_PAD_130        GPIO27
#define GPIO_PAD_118        GPIO8
#define GPIO_PAD_356        GPIO84
#define GPIO_PAD_115        GPIO5
#define GPIO_PAD_133        GPIO30
#define GPIO_PAD_194        GPIO121
#define GPIO_PAD_345        GPIO74
#define GPIO_PAD_184        GPIO111
#define GPIO_PAD_158        GPIO_DDCD2_SCL
#define GPIO_PAD_212        GPIO56
#define GPIO_PAD_15         GPIO_DDCD1_SDA
#define GPIO_PAD_180        GPIO107
#define GPIO_PAD_373        GPIO149
#define GPIO_PAD_132        GPIO29
#define GPIO_PAD_337        GPIO69
#define GPIO_PAD_34         GPIO_DDCD0_SDA
#define GPIO_PAD_354        GPIO79
#define GPIO_PAD_343        GPIO73
#define GPIO_PAD_340        GPIO72
#define GPIO_PAD_202        GPIO129
#define GPIO_PAD_213        GPIO57
#define GPIO_PAD_191        GPIO118
#define GPIO_PAD_137        GPIO34
#define GPIO_PAD_334        GPIO100
#define GPIO_PAD_123        GPIO20
#define GPIO_PAD_122        GPIO12
#define GPIO_PAD_126        GPIO23
#define GPIO_PAD_171        GPIO83
#define GPIO_PAD_183        GPIO110
#define GPIO_PAD_208        GPIO52
#define GPIO_PAD_144        GPIO40
#define GPIO_PAD_222        GPIO66
#define GPIO_PAD_131        GPIO28
#define GPIO_PAD_145        GPIO41
#define GPIO_PAD_196        GPIO123
#define GPIO_PAD_371        GPIO147
#define GPIO_PAD_146        GPIO42
#define GPIO_PAD_32         GPIO_HPDA
#define GPIO_PAD_113        GPIO3
#define GPIO_PAD_360        GPIO86
#define GPIO_PAD_190        GPIO117
#define GPIO_PAD_201        GPIO128
#define GPIO_PAD_209        GPIO53
#define GPIO_PAD_124        GPIO21
#define GPIO_PAD_193        GPIO120
#define GPIO_PAD_186        GPIO113
#define GPIO_PAD_174        GPIO46
#define GPIO_PAD_339        GPIO71
#define GPIO_PAD_119        GPIO9
#define GPIO_PAD_182        GPIO109
#define GPIO_PAD_197        GPIO124
#define GPIO_PAD_169        GPIO80
#define GPIO_PAD_210        GPIO54
#define GPIO_PAD_141        GPIO37
#define GPIO_PAD_347        GPIO75
#define GPIO_PAD_379        GPIO137
#define GPIO_PAD_135        GPIO32
#define GPIO_PAD_335        GPIO67
#define GPIO_PAD_376        GPIO134
#define GPIO_PAD_338        GPIO70
#define GPIO_PAD_199        GPIO126
#define GPIO_PAD_378        GPIO136
#define GPIO_PAD_76         GPIO_DDCA0_SDA
#define GPIO_PAD_330        GPIO92
#define GPIO_PAD_35         GPIO_DDCD0_SCL
#define GPIO_PAD_179        GPIO106
#define GPIO_PAD_5          GPIO139
#define GPIO_PAD_9999       GPIO_NC

// default GPIO setting
#define PAD_ET_TXD3_IS_GPIO 0
#ifndef PIN_119_IS_GPIO
#define PIN_119_IS_GPIO 0
#endif
#ifndef PAD_DDCDC_DA_IS_GPIO
#define PAD_DDCDC_DA_IS_GPIO PIN_119_IS_GPIO
#endif
#ifndef PIN_128_IS_GPIO
#define PIN_128_IS_GPIO 0
#endif
#ifndef PAD_HOTPLUGC_IS_GPIO
#define PAD_HOTPLUGC_IS_GPIO PIN_128_IS_GPIO
#endif
#ifndef PIN_270_IS_GPIO
#define PIN_270_IS_GPIO 0
#endif
#ifndef PAD_LHSYNC2_IS_GPIO
#define PAD_LHSYNC2_IS_GPIO PIN_270_IS_GPIO
#endif
#ifndef PIN_103_IS_GPIO
#define PIN_103_IS_GPIO 0
#endif
#ifndef PAD_PCM_A13_IS_GPIO
#define PAD_PCM_A13_IS_GPIO PIN_103_IS_GPIO
#endif
#ifndef PIN_101_IS_GPIO
#define PIN_101_IS_GPIO 0
#endif
#ifndef PAD_PCM_IOWR_N_IS_GPIO
#define PAD_PCM_IOWR_N_IS_GPIO PIN_101_IS_GPIO
#endif
#ifndef PIN_155_IS_GPIO
#define PIN_155_IS_GPIO 0
#endif
#ifndef PAD_R_ODD3_IS_GPIO
#define PAD_R_ODD3_IS_GPIO PIN_155_IS_GPIO
#endif
#define PAD_GPIO_PM9_IS_GPIO 0
#ifndef PIN_137_IS_GPIO
#define PIN_137_IS_GPIO 0
#endif
#ifndef PAD_B_ODD2_IS_GPIO
#define PAD_B_ODD2_IS_GPIO PIN_137_IS_GPIO
#endif
#ifndef PIN_94_IS_GPIO
#define PIN_94_IS_GPIO  0
#endif
#ifndef PAD_PCM_CE_N_IS_GPIO
#define PAD_PCM_CE_N_IS_GPIO PIN_94_IS_GPIO
#endif
#ifndef PIN_80_IS_GPIO
#define PIN_80_IS_GPIO  0
#endif
#ifndef PAD_TS0_D2_IS_GPIO
#define PAD_TS0_D2_IS_GPIO PIN_80_IS_GPIO
#endif
#ifndef PIN_106_IS_GPIO
#define PIN_106_IS_GPIO 0
#endif
#ifndef PAD_PCM_IRQA_N_IS_GPIO
#define PAD_PCM_IRQA_N_IS_GPIO PIN_106_IS_GPIO
#endif
#ifndef PIN_83_IS_GPIO
#define PIN_83_IS_GPIO  0
#endif
#ifndef PAD_TS0_D5_IS_GPIO
#define PAD_TS0_D5_IS_GPIO PIN_83_IS_GPIO
#endif
#define PAD_ET_RX_CLK_IS_GPIO 0
#ifndef PIN_130_IS_GPIO
#define PIN_130_IS_GPIO 0
#endif
#ifndef PAD_SPI_DI_IS_GPIO
#define PAD_SPI_DI_IS_GPIO PIN_130_IS_GPIO
#endif
#define PAD_PWM2_IS_GPIO 0
#define PAD_ET_RXD2_IS_GPIO 0
#ifndef PIN_82_IS_GPIO
#define PIN_82_IS_GPIO  0
#endif
#ifndef PAD_TS0_D4_IS_GPIO
#define PAD_TS0_D4_IS_GPIO PIN_82_IS_GPIO
#endif
#ifndef PIN_95_IS_GPIO
#define PIN_95_IS_GPIO  0
#endif
#ifndef PAD_PCM_A10_IS_GPIO
#define PAD_PCM_A10_IS_GPIO PIN_95_IS_GPIO
#endif
#ifndef PIN_141_IS_GPIO
#define PIN_141_IS_GPIO 0
#endif
#ifndef PAD_B_ODD6_IS_GPIO
#define PAD_B_ODD6_IS_GPIO PIN_141_IS_GPIO
#endif
#ifndef PIN_132_IS_GPIO
#define PIN_132_IS_GPIO 0
#endif
#ifndef PAD_SPI_CZ_IS_GPIO
#define PAD_SPI_CZ_IS_GPIO PIN_132_IS_GPIO
#endif
#define PAD_ET_CRS_IS_GPIO 0
#define PAD_GPIO_PM7_IS_GPIO 0
#ifndef PIN_78_IS_GPIO
#define PIN_78_IS_GPIO  0
#endif
#ifndef PAD_TS0_D0_IS_GPIO
#define PAD_TS0_D0_IS_GPIO PIN_78_IS_GPIO
#endif
#ifndef PIN_144_IS_GPIO
#define PIN_144_IS_GPIO 0
#endif
#ifndef PAD_G_ODD1_IS_GPIO
#define PAD_G_ODD1_IS_GPIO PIN_144_IS_GPIO
#endif
#define PAD_ET_RXER_IS_GPIO 0
#ifndef PIN_284_IS_GPIO
#define PIN_284_IS_GPIO 0
#endif
#ifndef PAD_SAR0_IS_GPIO
#define PAD_SAR0_IS_GPIO PIN_284_IS_GPIO
#endif
#define PAD_ET_MDC_IS_GPIO 0
#ifndef PIN_58_IS_GPIO
#define PIN_58_IS_GPIO  0
#endif
#ifndef PAD_DDCA_CK_IS_GPIO
#define PAD_DDCA_CK_IS_GPIO PIN_58_IS_GPIO
#endif
#ifndef PIN_172_IS_GPIO
#define PIN_172_IS_GPIO 0
#endif
#ifndef PAD_TS1_D0_IS_GPIO
#define PAD_TS1_D0_IS_GPIO PIN_172_IS_GPIO
#endif
#ifndef PIN_87_IS_GPIO
#define PIN_87_IS_GPIO  0
#endif
#ifndef PAD_TS0_SYNC_IS_GPIO
#define PAD_TS0_SYNC_IS_GPIO PIN_87_IS_GPIO
#endif
#ifndef PIN_91_IS_GPIO
#define PIN_91_IS_GPIO  0
#endif
#ifndef PAD_PCM_D5_IS_GPIO
#define PAD_PCM_D5_IS_GPIO PIN_91_IS_GPIO
#endif
#ifndef PIN_12_IS_GPIO
#define PIN_12_IS_GPIO  0
#endif
#ifndef PAD_HOTPLUGB_IS_GPIO
#define PAD_HOTPLUGB_IS_GPIO PIN_12_IS_GPIO
#endif
#ifndef PIN_250_IS_GPIO
#define PIN_250_IS_GPIO 0
#endif
#ifndef PAD_ET_COL_IS_GPIO
#define PAD_ET_COL_IS_GPIO PIN_250_IS_GPIO
#endif
#ifndef PIN_257_IS_GPIO
#define PIN_257_IS_GPIO 0
#endif
#ifndef PAD_I2S_IN_BCK_IS_GPIO
#define PAD_I2S_IN_BCK_IS_GPIO PIN_257_IS_GPIO
#endif
#define PAD_PF_WEZ_IS_GPIO 0
#ifndef PIN_286_IS_GPIO
#define PIN_286_IS_GPIO 0
#endif
#ifndef PAD_SAR2_IS_GPIO
#define PAD_SAR2_IS_GPIO PIN_286_IS_GPIO
#endif
#ifndef PIN_174_IS_GPIO
#define PIN_174_IS_GPIO 0
#endif
#ifndef PAD_TS1_SYNC_IS_GPIO
#define PAD_TS1_SYNC_IS_GPIO PIN_174_IS_GPIO
#endif
#ifndef PIN_170_IS_GPIO
#define PIN_170_IS_GPIO 0
#endif
#ifndef PAD_PCM_D2_IS_GPIO
#define PAD_PCM_D2_IS_GPIO PIN_170_IS_GPIO
#endif
#ifndef PIN_268_IS_GPIO
#define PIN_268_IS_GPIO 0
#endif
#ifndef PAD_DDCR_DA2_IS_GPIO
#define PAD_DDCR_DA2_IS_GPIO PIN_268_IS_GPIO
#endif
#ifndef PIN_173_IS_GPIO
#define PIN_173_IS_GPIO 0
#endif
#ifndef PAD_TS1_VLD_IS_GPIO
#define PAD_TS1_VLD_IS_GPIO PIN_173_IS_GPIO
#endif
#define PAD_PCM2_WAIT_N_IS_GPIO 0
#ifndef PIN_152_IS_GPIO
#define PIN_152_IS_GPIO 0
#endif
#ifndef PAD_R_ODD0_IS_GPIO
#define PAD_R_ODD0_IS_GPIO PIN_152_IS_GPIO
#endif
#define PAD_ET_MDIO_IS_GPIO 0
#ifndef PIN_18_IS_GPIO
#define PIN_18_IS_GPIO  0
#endif
#ifndef PAD_DDCDB_CK_IS_GPIO
#define PAD_DDCDB_CK_IS_GPIO PIN_18_IS_GPIO
#endif
#ifndef PIN_145_IS_GPIO
#define PIN_145_IS_GPIO 0
#endif
#ifndef PAD_G_ODD2_IS_GPIO
#define PAD_G_ODD2_IS_GPIO PIN_145_IS_GPIO
#endif
#ifndef PIN_163_IS_GPIO
#define PIN_163_IS_GPIO 0
#endif
#ifndef PAD_PCM_A3_IS_GPIO
#define PAD_PCM_A3_IS_GPIO PIN_163_IS_GPIO
#endif
#ifndef PIN_253_IS_GPIO
#define PIN_253_IS_GPIO 0
#endif
#ifndef PAD_ET_TX_EN_IS_GPIO
#define PAD_ET_TX_EN_IS_GPIO PIN_253_IS_GPIO
#endif
#ifndef PIN_114_IS_GPIO
#define PIN_114_IS_GPIO 0
#endif
#ifndef PAD_PCM2_IRQA_N_IS_GPIO
#define PAD_PCM2_IRQA_N_IS_GPIO PIN_114_IS_GPIO
#endif
#ifndef PIN_107_IS_GPIO
#define PIN_107_IS_GPIO 0
#endif
#ifndef PAD_PCM_A12_IS_GPIO
#define PAD_PCM_A12_IS_GPIO PIN_107_IS_GPIO
#endif
#define PAD_LDE_IS_GPIO 0
#ifndef PIN_273_IS_GPIO
#define PIN_273_IS_GPIO 0
#endif
#ifndef PAD_GPIO13_IS_GPIO
#define PAD_GPIO13_IS_GPIO PIN_273_IS_GPIO
#endif
#define PAD_LHSYNC_IS_GPIO 0
#ifndef PIN_86_IS_GPIO
#define PIN_86_IS_GPIO  0
#endif
#ifndef PAD_TS0_VLD_IS_GPIO
#define PAD_TS0_VLD_IS_GPIO PIN_86_IS_GPIO
#endif
#define PAD_PF_CE1Z_IS_GPIO 0
#ifndef PIN_295_IS_GPIO
#define PIN_295_IS_GPIO 0
#endif
#ifndef PAD_GPIO_PM4_IS_GPIO
#define PAD_GPIO_PM4_IS_GPIO PIN_295_IS_GPIO
#endif
#ifndef PIN_149_IS_GPIO
#define PIN_149_IS_GPIO 0
#endif
#ifndef PAD_G_ODD5_IS_GPIO
#define PAD_G_ODD5_IS_GPIO PIN_149_IS_GPIO
#endif
#define PAD_ET_TXER_IS_GPIO 0
#ifndef PIN_269_IS_GPIO
#define PIN_269_IS_GPIO 0
#endif
#ifndef PAD_DDCR_CK2_IS_GPIO
#define PAD_DDCR_CK2_IS_GPIO PIN_269_IS_GPIO
#endif
#ifndef PIN_133_IS_GPIO
#define PIN_133_IS_GPIO 0
#endif
#ifndef PAD_PWM0_IS_GPIO
#define PAD_PWM0_IS_GPIO PIN_133_IS_GPIO
#endif
#define PAD_PWM3_IS_GPIO 0
#define PAD_GPIO_PM10_IS_GPIO 0
#ifndef PIN_93_IS_GPIO
#define PIN_93_IS_GPIO  0
#endif
#ifndef PAD_PCM_D7_IS_GPIO
#define PAD_PCM_D7_IS_GPIO PIN_93_IS_GPIO
#endif
#ifndef PIN_254_IS_GPIO
#define PIN_254_IS_GPIO 0
#endif
#ifndef PAD_ET_TX_CLK_IS_GPIO
#define PAD_ET_TX_CLK_IS_GPIO PIN_254_IS_GPIO
#endif
#ifndef PIN_109_IS_GPIO
#define PIN_109_IS_GPIO 0
#endif
#ifndef PAD_PCM_A6_IS_GPIO
#define PAD_PCM_A6_IS_GPIO PIN_109_IS_GPIO
#endif
#ifndef PIN_252_IS_GPIO
#define PIN_252_IS_GPIO 0
#endif
#ifndef PAD_ET_TXD0_IS_GPIO
#define PAD_ET_TXD0_IS_GPIO PIN_252_IS_GPIO
#endif
#ifndef PIN_275_IS_GPIO
#define PIN_275_IS_GPIO 0
#endif
#ifndef PAD_GPIO15_IS_GPIO
#define PAD_GPIO15_IS_GPIO PIN_275_IS_GPIO
#endif
#ifndef PIN_167_IS_GPIO
#define PIN_167_IS_GPIO 0
#endif
#ifndef PAD_PCM_A0_IS_GPIO
#define PAD_PCM_A0_IS_GPIO PIN_167_IS_GPIO
#endif
#ifndef PIN_110_IS_GPIO
#define PIN_110_IS_GPIO 0
#endif
#ifndef PAD_PCM_A5_IS_GPIO
#define PAD_PCM_A5_IS_GPIO PIN_110_IS_GPIO
#endif
#ifndef PIN_292_IS_GPIO
#define PIN_292_IS_GPIO 0
#endif
#ifndef PAD_GPIO_PM1_IS_GPIO
#define PAD_GPIO_PM1_IS_GPIO PIN_292_IS_GPIO
#endif
#ifndef PIN_157_IS_GPIO
#define PIN_157_IS_GPIO 0
#endif
#ifndef PAD_R_ODD5_IS_GPIO
#define PAD_R_ODD5_IS_GPIO PIN_157_IS_GPIO
#endif
#ifndef PIN_2_IS_GPIO
#define PIN_2_IS_GPIO   0
#endif
#ifndef PAD_GPIO_PM6_IS_GPIO
#define PAD_GPIO_PM6_IS_GPIO PIN_2_IS_GPIO
#endif
#ifndef PIN_143_IS_GPIO
#define PIN_143_IS_GPIO 0
#endif
#ifndef PAD_G_ODD0_IS_GPIO
#define PAD_G_ODD0_IS_GPIO PIN_143_IS_GPIO
#endif
#ifndef PIN_96_IS_GPIO
#define PIN_96_IS_GPIO  0
#endif
#ifndef PAD_PCM_OE_N_IS_GPIO
#define PAD_PCM_OE_N_IS_GPIO PIN_96_IS_GPIO
#endif
#ifndef PIN_84_IS_GPIO
#define PIN_84_IS_GPIO  0
#endif
#ifndef PAD_TS0_D6_IS_GPIO
#define PAD_TS0_D6_IS_GPIO PIN_84_IS_GPIO
#endif
#define PAD_GPIO_PM8_IS_GPIO 0
#ifndef PIN_272_IS_GPIO
#define PIN_272_IS_GPIO 0
#endif
#ifndef PAD_GPIO12_IS_GPIO
#define PAD_GPIO12_IS_GPIO PIN_272_IS_GPIO
#endif
#ifndef PIN_81_IS_GPIO
#define PIN_81_IS_GPIO  0
#endif
#ifndef PAD_TS0_D3_IS_GPIO
#define PAD_TS0_D3_IS_GPIO PIN_81_IS_GPIO
#endif
#ifndef PIN_100_IS_GPIO
#define PIN_100_IS_GPIO 0
#endif
#ifndef PAD_PCM_A9_IS_GPIO
#define PAD_PCM_A9_IS_GPIO PIN_100_IS_GPIO
#endif
#ifndef PIN_151_IS_GPIO
#define PIN_151_IS_GPIO 0
#endif
#ifndef PAD_G_ODD7_IS_GPIO
#define PAD_G_ODD7_IS_GPIO PIN_151_IS_GPIO
#endif
#ifndef PIN_266_IS_GPIO
#define PIN_266_IS_GPIO 0
#endif
#ifndef PAD_I2S_OUT_SD_IS_GPIO
#define PAD_I2S_OUT_SD_IS_GPIO PIN_266_IS_GPIO
#endif
#define PAD_ET_RXD3_IS_GPIO 0
#define PAD_PF_OEZ_IS_GPIO 0
#ifndef PIN_140_IS_GPIO
#define PIN_140_IS_GPIO 0
#endif
#ifndef PAD_B_ODD5_IS_GPIO
#define PAD_B_ODD5_IS_GPIO PIN_140_IS_GPIO
#endif
#ifndef PIN_116_IS_GPIO
#define PIN_116_IS_GPIO 0
#endif
#ifndef PAD_DDCDC_CK_IS_GPIO
#define PAD_DDCDC_CK_IS_GPIO PIN_116_IS_GPIO
#endif
#ifndef PIN_168_IS_GPIO
#define PIN_168_IS_GPIO 0
#endif
#ifndef PAD_PCM_D0_IS_GPIO
#define PAD_PCM_D0_IS_GPIO PIN_168_IS_GPIO
#endif
#ifndef PIN_9_IS_GPIO
#define PIN_9_IS_GPIO   0
#endif
#ifndef PAD_DDCDB_DA_IS_GPIO
#define PAD_DDCDB_DA_IS_GPIO PIN_9_IS_GPIO
#endif
#ifndef PIN_136_IS_GPIO
#define PIN_136_IS_GPIO 0
#endif
#ifndef PAD_B_ODD1_IS_GPIO
#define PAD_B_ODD1_IS_GPIO PIN_136_IS_GPIO
#endif
#ifndef PIN_287_IS_GPIO
#define PIN_287_IS_GPIO 0
#endif
#ifndef PAD_SAR3_IS_GPIO
#define PAD_SAR3_IS_GPIO PIN_287_IS_GPIO
#endif
#ifndef PIN_99_IS_GPIO
#define PIN_99_IS_GPIO  0
#endif
#ifndef PAD_PCM_IORD_N_IS_GPIO
#define PAD_PCM_IORD_N_IS_GPIO PIN_99_IS_GPIO
#endif
#ifndef PIN_258_IS_GPIO
#define PIN_258_IS_GPIO 0
#endif
#ifndef PAD_I2S_IN_SD_IS_GPIO
#define PAD_I2S_IN_SD_IS_GPIO PIN_258_IS_GPIO
#endif
#ifndef PIN_31_IS_GPIO
#define PIN_31_IS_GPIO  0
#endif
#ifndef PAD_DDCDA_DA_IS_GPIO
#define PAD_DDCDA_DA_IS_GPIO PIN_31_IS_GPIO
#endif
#ifndef PIN_271_IS_GPIO
#define PIN_271_IS_GPIO 0
#endif
#ifndef PAD_LVSYNC2_IS_GPIO
#define PAD_LVSYNC2_IS_GPIO PIN_271_IS_GPIO
#endif
#ifndef PIN_265_IS_GPIO
#define PIN_265_IS_GPIO 0
#endif
#ifndef PAD_I2S_OUT_BCK_IS_GPIO
#define PAD_I2S_OUT_BCK_IS_GPIO PIN_265_IS_GPIO
#endif
#ifndef PIN_261_IS_GPIO
#define PIN_261_IS_GPIO 0
#endif
#ifndef PAD_I2S_OUT_WS_IS_GPIO
#define PAD_I2S_OUT_WS_IS_GPIO PIN_261_IS_GPIO
#endif
#ifndef PIN_159_IS_GPIO
#define PIN_159_IS_GPIO 0
#endif
#ifndef PAD_R_ODD7_IS_GPIO
#define PAD_R_ODD7_IS_GPIO PIN_159_IS_GPIO
#endif
#ifndef PIN_169_IS_GPIO
#define PIN_169_IS_GPIO 0
#endif
#ifndef PAD_PCM_D1_IS_GPIO
#define PAD_PCM_D1_IS_GPIO PIN_169_IS_GPIO
#endif
#ifndef PIN_148_IS_GPIO
#define PIN_148_IS_GPIO 0
#endif
#ifndef PAD_G_ODD4_IS_GPIO
#define PAD_G_ODD4_IS_GPIO PIN_148_IS_GPIO
#endif
#ifndef PIN_104_IS_GPIO
#define PIN_104_IS_GPIO 0
#endif
#ifndef PAD_PCM_A14_IS_GPIO
#define PAD_PCM_A14_IS_GPIO PIN_104_IS_GPIO
#endif
#ifndef PIN_255_IS_GPIO
#define PIN_255_IS_GPIO 0
#endif
#ifndef PAD_ET_RXD0_IS_GPIO
#define PAD_ET_RXD0_IS_GPIO PIN_255_IS_GPIO
#endif
#define PAD_ET_TXD2_IS_GPIO 0
#ifndef PIN_89_IS_GPIO
#define PIN_89_IS_GPIO  0
#endif
#ifndef PAD_PCM_D3_IS_GPIO
#define PAD_PCM_D3_IS_GPIO PIN_89_IS_GPIO
#endif
#define PAD_PCM2_CD_N_IS_GPIO 0
#ifndef PIN_88_IS_GPIO
#define PIN_88_IS_GPIO  0
#endif
#ifndef PAD_TS0_CLK_IS_GPIO
#define PAD_TS0_CLK_IS_GPIO PIN_88_IS_GPIO
#endif
#define PAD_UART_RX2_IS_GPIO 0
#ifndef PIN_92_IS_GPIO
#define PIN_92_IS_GPIO  0
#endif
#ifndef PAD_PCM_D6_IS_GPIO
#define PAD_PCM_D6_IS_GPIO PIN_92_IS_GPIO
#endif
#ifndef PIN_131_IS_GPIO
#define PIN_131_IS_GPIO 0
#endif
#ifndef PAD_SPI_DO_IS_GPIO
#define PAD_SPI_DO_IS_GPIO PIN_131_IS_GPIO
#endif
#define PAD_PF_ALE_IS_GPIO 0
#define PAD_ET_RXD1_IS_GPIO 0
#ifndef PIN_139_IS_GPIO
#define PIN_139_IS_GPIO 0
#endif
#ifndef PAD_B_ODD4_IS_GPIO
#define PAD_B_ODD4_IS_GPIO PIN_139_IS_GPIO
#endif
#ifndef PIN_164_IS_GPIO
#define PIN_164_IS_GPIO 0
#endif
#ifndef PAD_PCM_A2_IS_GPIO
#define PAD_PCM_A2_IS_GPIO PIN_164_IS_GPIO
#endif
#ifndef PIN_111_IS_GPIO
#define PIN_111_IS_GPIO 0
#endif
#ifndef PAD_PCM_WAIT_N_IS_GPIO
#define PAD_PCM_WAIT_N_IS_GPIO PIN_111_IS_GPIO
#endif
#ifndef PIN_175_IS_GPIO
#define PIN_175_IS_GPIO 0
#endif
#ifndef PAD_TS1_CLK_IS_GPIO
#define PAD_TS1_CLK_IS_GPIO PIN_175_IS_GPIO
#endif
#define PAD_F_RBZ_IS_GPIO 0
#ifndef PIN_98_IS_GPIO
#define PIN_98_IS_GPIO  0
#endif
#ifndef PAD_PCM_A11_IS_GPIO
#define PAD_PCM_A11_IS_GPIO PIN_98_IS_GPIO
#endif
#ifndef PIN_112_IS_GPIO
#define PIN_112_IS_GPIO 0
#endif
#ifndef PAD_PCM_A4_IS_GPIO
#define PAD_PCM_A4_IS_GPIO PIN_112_IS_GPIO
#endif
#define PAD_PF_AD15_IS_GPIO 0
#ifndef PIN_153_IS_GPIO
#define PIN_153_IS_GPIO 0
#endif
#ifndef PAD_R_ODD1_IS_GPIO
#define PAD_R_ODD1_IS_GPIO PIN_153_IS_GPIO
#endif
#ifndef PIN_285_IS_GPIO
#define PIN_285_IS_GPIO 0
#endif
#ifndef PAD_SAR1_IS_GPIO
#define PAD_SAR1_IS_GPIO PIN_285_IS_GPIO
#endif
#define PAD_LVSYNC_IS_GPIO 0
#ifndef PIN_113_IS_GPIO
#define PIN_113_IS_GPIO 0
#endif
#ifndef PAD_PCM2_CE_N_IS_GPIO
#define PAD_PCM2_CE_N_IS_GPIO PIN_113_IS_GPIO
#endif
#ifndef PIN_29_IS_GPIO
#define PIN_29_IS_GPIO  0
#endif
#ifndef PAD_HOTPLUGA_IS_GPIO
#define PAD_HOTPLUGA_IS_GPIO PIN_29_IS_GPIO
#endif
#define PAD_UART_TX2_IS_GPIO 0
#ifndef PIN_79_IS_GPIO
#define PIN_79_IS_GPIO  0
#endif
#ifndef PAD_TS0_D1_IS_GPIO
#define PAD_TS0_D1_IS_GPIO PIN_79_IS_GPIO
#endif
#ifndef PIN_274_IS_GPIO
#define PIN_274_IS_GPIO 0
#endif
#ifndef PAD_GPIO14_IS_GPIO
#define PAD_GPIO14_IS_GPIO PIN_274_IS_GPIO
#endif
#ifndef PIN_146_IS_GPIO
#define PIN_146_IS_GPIO 0
#endif
#ifndef PAD_G_ODD3_IS_GPIO
#define PAD_G_ODD3_IS_GPIO PIN_146_IS_GPIO
#endif
#ifndef PIN_158_IS_GPIO
#define PIN_158_IS_GPIO 0
#endif
#ifndef PAD_R_ODD6_IS_GPIO
#define PAD_R_ODD6_IS_GPIO PIN_158_IS_GPIO
#endif
#define PAD_PCM_CD_N_IS_GPIO 0
#define PAD_DDCR_CLK_IS_GPIO 0
#ifndef PIN_165_IS_GPIO
#define PIN_165_IS_GPIO 0
#endif
#ifndef PAD_PCM_REG_N_IS_GPIO
#define PAD_PCM_REG_N_IS_GPIO PIN_165_IS_GPIO
#endif
#define PAD_PF_CE0Z_IS_GPIO 0
#ifndef PIN_90_IS_GPIO
#define PIN_90_IS_GPIO  0
#endif
#ifndef PAD_PCM_D4_IS_GPIO
#define PAD_PCM_D4_IS_GPIO PIN_90_IS_GPIO
#endif
#ifndef PIN_150_IS_GPIO
#define PIN_150_IS_GPIO 0
#endif
#ifndef PAD_G_ODD6_IS_GPIO
#define PAD_G_ODD6_IS_GPIO PIN_150_IS_GPIO
#endif
#ifndef PIN_142_IS_GPIO
#define PIN_142_IS_GPIO 0
#endif
#ifndef PAD_B_ODD7_IS_GPIO
#define PAD_B_ODD7_IS_GPIO PIN_142_IS_GPIO
#endif
#ifndef PIN_134_IS_GPIO
#define PIN_134_IS_GPIO 0
#endif
#ifndef PAD_PWM1_IS_GPIO
#define PAD_PWM1_IS_GPIO PIN_134_IS_GPIO
#endif
#define PAD_PCM2_RESET_IS_GPIO 0
#ifndef PIN_260_IS_GPIO
#define PIN_260_IS_GPIO 0
#endif
#ifndef PAD_I2S_OUT_MCK_IS_GPIO
#define PAD_I2S_OUT_MCK_IS_GPIO PIN_260_IS_GPIO
#endif
#ifndef PIN_85_IS_GPIO
#define PIN_85_IS_GPIO  0
#endif
#ifndef PAD_TS0_D7_IS_GPIO
#define PAD_TS0_D7_IS_GPIO PIN_85_IS_GPIO
#endif
#ifndef PIN_138_IS_GPIO
#define PIN_138_IS_GPIO 0
#endif
#ifndef PAD_B_ODD3_IS_GPIO
#define PAD_B_ODD3_IS_GPIO PIN_138_IS_GPIO
#endif
#ifndef PIN_154_IS_GPIO
#define PIN_154_IS_GPIO 0
#endif
#ifndef PAD_R_ODD2_IS_GPIO
#define PAD_R_ODD2_IS_GPIO PIN_154_IS_GPIO
#endif
#ifndef PIN_129_IS_GPIO
#define PIN_129_IS_GPIO 0
#endif
#ifndef PAD_SPI_CK_IS_GPIO
#define PAD_SPI_CK_IS_GPIO PIN_129_IS_GPIO
#endif
#define PAD_PCM_RESET_IS_GPIO 0
#ifndef PIN_166_IS_GPIO
#define PIN_166_IS_GPIO 0
#endif
#ifndef PAD_PCM_A1_IS_GPIO
#define PAD_PCM_A1_IS_GPIO PIN_166_IS_GPIO
#endif
#ifndef PIN_108_IS_GPIO
#define PIN_108_IS_GPIO 0
#endif
#ifndef PAD_PCM_A7_IS_GPIO
#define PAD_PCM_A7_IS_GPIO PIN_108_IS_GPIO
#endif
#define PAD_LCK_IS_GPIO 0
#ifndef PIN_267_IS_GPIO
#define PIN_267_IS_GPIO 0
#endif
#ifndef PAD_SPDIF_OUT_IS_GPIO
#define PAD_SPDIF_OUT_IS_GPIO PIN_267_IS_GPIO
#endif
#ifndef PIN_294_IS_GPIO
#define PIN_294_IS_GPIO 0
#endif
#ifndef PAD_GPIO_PM3_IS_GPIO
#define PAD_GPIO_PM3_IS_GPIO PIN_294_IS_GPIO
#endif
#define PAD_ET_RX_DV_IS_GPIO 0
#ifndef PIN_102_IS_GPIO
#define PIN_102_IS_GPIO 0
#endif
#ifndef PAD_PCM_A8_IS_GPIO
#define PAD_PCM_A8_IS_GPIO PIN_102_IS_GPIO
#endif
#define PAD_DDCR_DAT_IS_GPIO 0
#ifndef PIN_256_IS_GPIO
#define PIN_256_IS_GPIO 0
#endif
#ifndef PAD_I2S_IN_WS_IS_GPIO
#define PAD_I2S_IN_WS_IS_GPIO PIN_256_IS_GPIO
#endif
#ifndef PIN_291_IS_GPIO
#define PIN_291_IS_GPIO 0
#endif
#ifndef PAD_GPIO_PM0_IS_GPIO
#define PAD_GPIO_PM0_IS_GPIO PIN_291_IS_GPIO
#endif
#ifndef PIN_259_IS_GPIO
#define PIN_259_IS_GPIO 0
#endif
#ifndef PAD_SPDIF_IN_IS_GPIO
#define PAD_SPDIF_IN_IS_GPIO PIN_259_IS_GPIO
#endif
#ifndef PIN_156_IS_GPIO
#define PIN_156_IS_GPIO 0
#endif
#ifndef PAD_R_ODD4_IS_GPIO
#define PAD_R_ODD4_IS_GPIO PIN_156_IS_GPIO
#endif
#ifndef PIN_293_IS_GPIO
#define PIN_293_IS_GPIO 0
#endif
#ifndef PAD_GPIO_PM2_IS_GPIO
#define PAD_GPIO_PM2_IS_GPIO PIN_293_IS_GPIO
#endif
#ifndef PIN_57_IS_GPIO
#define PIN_57_IS_GPIO  0
#endif
#ifndef PAD_DDCA_DA_IS_GPIO
#define PAD_DDCA_DA_IS_GPIO PIN_57_IS_GPIO
#endif
#ifndef PIN_251_IS_GPIO
#define PIN_251_IS_GPIO 0
#endif
#ifndef PAD_ET_TXD1_IS_GPIO
#define PAD_ET_TXD1_IS_GPIO PIN_251_IS_GPIO
#endif
#ifndef PIN_32_IS_GPIO
#define PIN_32_IS_GPIO  0
#endif
#ifndef PAD_DDCDA_CK_IS_GPIO
#define PAD_DDCDA_CK_IS_GPIO PIN_32_IS_GPIO
#endif
#ifndef PIN_135_IS_GPIO
#define PIN_135_IS_GPIO 0
#endif
#ifndef PAD_B_ODD0_IS_GPIO
#define PAD_B_ODD0_IS_GPIO PIN_135_IS_GPIO
#endif
#ifndef PIN_1_IS_GPIO
#define PIN_1_IS_GPIO   0
#endif
#ifndef PAD_GPIO_PM5_IS_GPIO
#define PAD_GPIO_PM5_IS_GPIO PIN_1_IS_GPIO
#endif

// chip capbilities
#define CHIP_HAS_BT656_IN          0
#define CHIP_HAS_TS0               1 // PIN# 88 87 86 78 79 80 81 82 83 84 85
#define CHIP_HAS_TS1               1 // PIN# 175 174 173 172
#define CHIP_HAS_LVDS_10BIT_X2     1
#define CHIP_HAS_LVDS_8BIT_X2      1
#define CHIP_HAS_LVDS_8BIT_X1      1
#define CHIP_HAS_DTCON_MODE1       0
#define CHIP_HAS_ATCON_MODE1       0
#define CHIP_HAS_ATCON_MODE2       0
#define CHIP_HAS_CCFL              0
#define CHIP_HAS_CIMAX             0
#define CHIP_HAS_FCIE_CONFIG1      0
#define CHIP_HAS_FCIE_CONFIG2      0
#define CHIP_HAS_USB               1
#define CHIP_HAS_UART1_MODE1       0
#define CHIP_HAS_UART1_MODE2       1 // PIN# 270 271
#define CHIP_HAS_UART1_MODE3       1 // PIN# 274 275
#define CHIP_HAS_PCMCIA1           1
#define CHIP_HAS_PCMCIA2           0
#define CHIP_HAS_PCMCIA            1
#define CHIP_HAS_UART2_MODE1       0
#define CHIP_HAS_UART2_MODE2       1 // PIN# 268 269
#define CHIP_HAS_UART2_MODE3       1 // PIN# 272 273
#define CHIP_HAS_RGB_A             1 // PIN# 42 39 37 40
#define CHIP_HAS_RGB_B             0
#define CHIP_HAS_RGB_C             0
#define CHIP_HAS_HDMI_A            1 // PIN# 19 20 21 22 24 25 27 28 30 31 32
#define CHIP_HAS_HDMI_B            1 // PIN# 7 8 10 11 13 14 16 17 30 9 18
#define CHIP_HAS_HDMI_C            1 // PIN# 117 118 120 121 123 124 126 127 30 119 116
#define CHIP_HAS_SPI_CZ1           1 // PIN# 91 257
#define CHIP_HAS_SPI_CZ2           1 // PIN# 92 270
#define CHIP_HAS_SPI_CZ3           1 // PIN# 256 271 163
#define CHIP_HAS_DDCR              0
#define CHIP_HAS_DDCR2             1 // PIN# 268 269
#define CHIP_HAS_I2S_IN            1 // PIN# 256 257 258
#define CHIP_HAS_I2S_OUT           1 // PIN# 261 265 261 266
#define CHIP_HAS_SPDIF_IN          1 // PIN# 259
#define CHIP_HAS_SPDIF_OUT         1 // PIN# 267
#define CHIP_HAS_DDR_A_CMD         1
#define CHIP_HAS_DDR_A_DATA        0
#define CHIP_HAS_DDR_B_CMD         0
#define CHIP_HAS_DDR_B_DATA        1
#define CHIP_USE_PCM_CDN_IN_PCM2   1
#define CHIP_USE_I2S_IN_IN_PCM     0
#define CHIP_USE_I2S_OUT_IN_PCM    0
#define CHIP_USE_SPDIF_IN_IN_PCM   0
#define CHIP_USE_SPDIF_OUT_IN_PCM  0
#define CHIP_USE_IIC_IN_DDCR2      1
#define CHIP_USE_PWM2_IN_GPIO14    1
#define CHIP_USE_PWM3_IN_GPIO15    1

// chip additional information
#define BONDING_TYPE               BONDING_MSD3102EQ
#define CHIP_FAMILY_TYPE           CHIP_FAMILY_S4L

#endif /* _MSD3102EQ_H_ */
