////////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 2006-2008 MStar Semiconductor, Inc.
// All rights reserved.
//
// Unless otherwise stipulated in writing, any and all information contained
// herein regardless in any format shall remain the sole proprietary of
// MStar Semiconductor Inc. and be kept in strict confidence
// (¡§MStar Confidential Information¡¨) by the recipient.
// Any unauthorized act including without limitation unauthorized disclosure,
// copying, use, reproduction, sale, distribution, modification, disassembling,
// reverse engineering and compiling of the contents of MStar Confidential
// Information is unlawful and strictly prohibited. MStar hereby reserves the
// rights to any and all damages, losses, costs and expenses resulting therefrom.
//
////////////////////////////////////////////////////////////////////////////////

// This file is generated by script, please do not edit it directly
#ifndef _MSD3388GV_H_
#define _MSD3388GV_H_

// PIN number to PAD name mapping
#define BALL_G6             PAD_GPIO_PM5        // 
#define BALL_H6             PAD_GPIO_PM6        // 
#define BALL_E1             PAD_DDCDB_DA        // 
#define BALL_E2             PAD_HOTPLUGB        // 
#define BALL_F3             PAD_DDCDB_CK        // 
#define BALL_A2             PAD_HOTPLUGA        // 
#define BALL_A1             PAD_DDCDA_DA        // 
#define BALL_B2             PAD_DDCDA_CK        // 
#define BALL_M3             PAD_CVBS7P          // 
#define BALL_M2             PAD_CVBS6P          // 
#define BALL_N3             PAD_CVBS5P          // 
#define BALL_M1             PAD_CVBS4P          // 
#define BALL_T1             PAD_CVBS3P          // 
#define BALL_U2             PAD_CVBS2P          // 
#define BALL_U3             PAD_CVBS1P          // 
#define BALL_W1             PAD_CVBS0P          // 
#define BALL_J2             PAD_DDCA_DA         // 
#define BALL_J1             PAD_DDCA_CK         // 
#define BALL_AA8            PAD_TS0_D0          // 
#define BALL_Y8             PAD_TS0_D1          // 
#define BALL_Y9             PAD_TS0_D2          // 
#define BALL_AB7            PAD_TS0_D3          // 
#define BALL_AA6            PAD_TS0_D4          // 
#define BALL_AB6            PAD_TS0_D5          // 
#define BALL_U4             PAD_TS0_D6          // 
#define BALL_AC5            PAD_TS0_D7          // 
#define BALL_AD5            PAD_TS0_VLD         // 
#define BALL_AC4            PAD_TS0_SYNC        // 
#define BALL_AB4            PAD_TS0_CLK         // 
#define BALL_AC6            PAD_PCM_D3          // 
#define BALL_AB10           PAD_PCM_D4          // 
#define BALL_AA10           PAD_PCM_D5          // 
#define BALL_AA11           PAD_PCM_D6          // 
#define BALL_AA12           PAD_PCM_D7          // 
#define BALL_T4             PAD_PCM_CE_N        // 
#define BALL_V4             PAD_PCM_A10         // 
#define BALL_Y5             PAD_PCM_OE_N        // 
#define BALL_Y4             PAD_PCM_A11         // 
#define BALL_W4             PAD_PCM_IORD_N      // 
#define BALL_AA4            PAD_PCM_A9          // 
#define BALL_AA5            PAD_PCM_IOWR_N      // 
#define BALL_AB5            PAD_PCM_A8          // 
#define BALL_AA7            PAD_PCM_A13         // 
#define BALL_AD6            PAD_PCM_A14         // 
#define BALL_AC7            PAD_PCM_WE_N        // 
#define BALL_AC8            PAD_PCM_IRQA_N      // 
#define BALL_AB9            PAD_PCM_A12         // 
#define BALL_AA9            PAD_PCM_A7          // 
#define BALL_AC12           PAD_PCM_A6          // 
#define BALL_AB8            PAD_PCM_A5          // 
#define BALL_AC10           PAD_PCM_WAIT_N      // 
#define BALL_AC13           PAD_PCM_A4          // 
#define BALL_AF5            PAD_PCM2_CE_N       // 
#define BALL_AD10           PAD_PCM2_IRQA_N     // 
#define BALL_AD11           PAD_PCM2_WAIT_N     // 
#define BALL_W5             PAD_UART_RX2        // 
#define BALL_V5             PAD_UART_TX2        // 
#define BALL_Y12            PAD_PF_AD15         // 
#define BALL_AC9            PAD_PF_ALE          // 
#define BALL_AE6            PAD_PF_CE0Z         // 
#define BALL_AF6            PAD_PF_CE1Z         // 
#define BALL_AB12           PAD_PF_OEZ          // 
#define BALL_AB11           PAD_PF_WEZ          // 
#define BALL_AC11           PAD_F_RBZ           // 
#define BALL_AF7            PAD_DDCDC_CK        // 
#define BALL_AE7            PAD_DDCDC_DA        // 
#define BALL_AD7            PAD_HOTPLUGC        // 
#define BALL_AE12           PAD_SPI_CK          // 
#define BALL_AF12           PAD_SPI_DI          // 
#define BALL_AF13           PAD_SPI_DO          // 
#define BALL_AD12           PAD_SPI_CZ          // 
#define BALL_AC18           PAD_PWM0            // 
#define BALL_AB18           PAD_PWM1            // 
#define BALL_AC19           PAD_PWM2            // 
#define BALL_AB19           PAD_PWM3            // 
#define BALL_AC21           PAD_DDCR_DAT        // 
#define BALL_AC20           PAD_DDCR_CLK        // 
#define BALL_AE16           PAD_B_ODD0          // 
#define BALL_AF16           PAD_B_ODD1          // 
#define BALL_AD15           PAD_B_ODD2          // 
#define BALL_AE15           PAD_B_ODD3          // 
#define BALL_AF15           PAD_B_ODD4          // 
#define BALL_AD14           PAD_B_ODD5          // 
#define BALL_AE14           PAD_B_ODD6          // 
#define BALL_AF14           PAD_B_ODD7          // 
#define BALL_AE13           PAD_G_ODD0          // 
#define BALL_AD13           PAD_G_ODD1          // 
#define BALL_AC25           PAD_G_ODD2          // 
#define BALL_AC24           PAD_G_ODD3          // 
#define BALL_AD26           PAD_G_ODD4          // 
#define BALL_AD25           PAD_G_ODD5          // 
#define BALL_AD24           PAD_G_ODD6          // 
#define BALL_AE26           PAD_G_ODD7          // 
#define BALL_AE25           PAD_R_ODD0          // 
#define BALL_AE24           PAD_R_ODD1          // 
#define BALL_AF26           PAD_R_ODD2          // 
#define BALL_AF25           PAD_R_ODD3          // 
#define BALL_AF24           PAD_R_ODD4          // 
#define BALL_AD23           PAD_R_ODD5          // 
#define BALL_AE23           PAD_R_ODD6          // 
#define BALL_AF23           PAD_R_ODD7          // 
#define BALL_AD22           PAD_LCK             // 
#define BALL_AE22           PAD_LDE             // 
#define BALL_AF22           PAD_LHSYNC          // 
#define BALL_AD21           PAD_LVSYNC          // 
#define BALL_AF21           PAD_TCON0           // 
#define BALL_AD20           PAD_TCON1           // 
#define BALL_AD19           PAD_TCON2           // 
#define BALL_AE19           PAD_TCON3           // 
#define BALL_AF20           PAD_TCON4           // 
#define BALL_AE21           PAD_TCON5           // 
#define BALL_AB25           PAD_TCON6           // 
#define BALL_AC23           PAD_TCON7           // 
#define BALL_AB23           PAD_TCON8           // 
#define BALL_AB24           PAD_TCON9           // 
#define BALL_AC26           PAD_TCON10          // 
#define BALL_AE20           PAD_TCON11          // 
#define BALL_AA24           PAD_TCON12          // 
#define BALL_AA25           PAD_TCON13          // 
#define BALL_AB26           PAD_TCON14          // 
#define BALL_AA26           PAD_TCON15          // 
#define BALL_AA23           PAD_TCON16          // 
#define BALL_AB14           PAD_PCM_A3          // 
#define BALL_AC14           PAD_PCM_A2          // 
#define BALL_AB15           PAD_PCM_REG_N       // 
#define BALL_AC15           PAD_PCM_A1          // 
#define BALL_AC16           PAD_PCM_A0          // 
#define BALL_AA17           PAD_PCM_D0          // 
#define BALL_AA15           PAD_PCM_D1          // 
#define BALL_AB16           PAD_PCM_D2          // 
#define BALL_AA14           PAD_PCM_RESET       // 
#define BALL_AB17           PAD_PCM2_RESET      // 
#define BALL_AC17           PAD_PCM_CD_N        // 
#define BALL_AA16           PAD_PCM2_CD_N       // 
#define BALL_AB13           PAD_TS1_D0          // 
#define BALL_AA13           PAD_TS1_VLD         // 
#define BALL_Y14            PAD_TS1_SYNC        // 
#define BALL_Y13            PAD_TS1_CLK         // 
#define BALL_A11            PAD_ET_COL          // 
#define BALL_B11            PAD_ET_TXD1         // 
#define BALL_C10            PAD_ET_TXD0         // 
#define BALL_B10            PAD_ET_TX_EN        // 
#define BALL_A9             PAD_ET_TX_CLK       // 
#define BALL_C11            PAD_ET_RXD0         // 
#define BALL_A7             PAD_I2S_IN_WS       // 
#define BALL_B8             PAD_I2S_IN_BCK      // 
#define BALL_C8             PAD_I2S_IN_SD       // 
#define BALL_F11            PAD_SPDIF_IN        // 
#define BALL_A8             PAD_I2S_OUT_MCK     // 
#define BALL_B7             PAD_I2S_OUT_WS      // 
#define BALL_D10            PAD_ET_CRS          // 
#define BALL_D7             PAD_ET_TXD3         // 
#define BALL_C7             PAD_I2S_OUT_BCK     // 
#define BALL_E11            PAD_ET_TXD2         // 
#define BALL_D8             PAD_I2S_OUT_SD      // 
#define BALL_D9             PAD_ET_TXER         // 
#define BALL_E9             PAD_SPDIF_OUT       // 
#define BALL_E8             PAD_ET_RXER         // 
#define BALL_D11            PAD_DDCR_DA2        // 
#define BALL_E10            PAD_ET_RX_CLK       // 
#define BALL_F8             PAD_DDCR_CK2        // 
#define BALL_D6             PAD_ET_RX_DV        // 
#define BALL_E7             PAD_LHSYNC2         // 
#define BALL_C6             PAD_LVSYNC2         // 
#define BALL_C9             PAD_ET_RXD1         // 
#define BALL_F9             PAD_GPIO12          // 
#define BALL_C5             PAD_ET_RXD2         // 
#define BALL_F10            PAD_GPIO13          // 
#define BALL_D5             PAD_ET_RXD3         // 
#define BALL_A6             PAD_GPIO14          // 
#define BALL_A10            PAD_ET_MDC          // 
#define BALL_B6             PAD_GPIO15          // 
#define BALL_B9             PAD_ET_MDIO         // 
#define BALL_E5             PAD_GPIO_PM0        // 
#define BALL_F5             PAD_GPIO_PM1        // 
#define BALL_G5             PAD_GPIO_PM2        // 
#define BALL_H5             PAD_GPIO_PM3        // 
#define BALL_F6             PAD_GPIO_PM4        // 

// PAD name to index
#define PAD_NC              9999
#define PAD_GND             0

#define PAD_GPIO_PM7        1
#define PAD_GPIO_PM8        2
#define PAD_GPIO_PM9        3
#define PAD_GPIO_PM10       4
#define PAD_GPIO_PM5        5
#define PAD_GPIO_PM6        6
#define PAD_DDCDB_DA        15
#define PAD_HOTPLUGB        18
#define PAD_DDCDB_CK        23
#define PAD_HOTPLUGA        32
#define PAD_DDCDA_DA        34
#define PAD_DDCDA_CK        35
#define PAD_CVBS7P          59
#define PAD_CVBS6P          60
#define PAD_CVBS5P          61
#define PAD_CVBS4P          62
#define PAD_CVBS3P          64
#define PAD_CVBS2P          65
#define PAD_CVBS1P          66
#define PAD_CVBS0P          68
#define PAD_DDCA_DA         74
#define PAD_DDCA_CK         75
#define PAD_TS0_D0          113
#define PAD_TS0_D1          114
#define PAD_TS0_D2          115
#define PAD_TS0_D3          116
#define PAD_TS0_D4          117
#define PAD_TS0_D5          118
#define PAD_TS0_D6          119
#define PAD_TS0_D7          120
#define PAD_TS0_VLD         121
#define PAD_TS0_SYNC        122
#define PAD_TS0_CLK         123
#define PAD_PCM_D3          124
#define PAD_PCM_D4          125
#define PAD_PCM_D5          126
#define PAD_PCM_D6          127
#define PAD_PCM_D7          128
#define PAD_PCM_CE_N        129
#define PAD_PCM_A10         130
#define PAD_PCM_OE_N        131
#define PAD_PCM_A11         132
#define PAD_PCM_IORD_N      133
#define PAD_PCM_A9          134
#define PAD_PCM_IOWR_N      135
#define PAD_PCM_A8          136
#define PAD_PCM_A13         137
#define PAD_PCM_A14         138
#define PAD_PCM_WE_N        139
#define PAD_PCM_IRQA_N      140
#define PAD_PCM_A12         141
#define PAD_PCM_A7          142
#define PAD_PCM_A6          143
#define PAD_PCM_A5          144
#define PAD_PCM_WAIT_N      145
#define PAD_PCM_A4          146
#define PAD_PCM2_CE_N       147
#define PAD_PCM2_IRQA_N     148
#define PAD_PCM2_WAIT_N     149
#define PAD_UART_RX2        150
#define PAD_UART_TX2        151
#define PAD_PF_AD15         152
#define PAD_PF_ALE          153
#define PAD_PF_CE0Z         154
#define PAD_PF_CE1Z         155
#define PAD_PF_OEZ          156
#define PAD_PF_WEZ          157
#define PAD_F_RBZ           158
#define PAD_DDCDC_CK        159
#define PAD_DDCDC_DA        162
#define PAD_HOTPLUGC        169
#define PAD_SPI_CK          175
#define PAD_SPI_DI          176
#define PAD_SPI_DO          177
#define PAD_SPI_CZ          178
#define PAD_PWM0            179
#define PAD_PWM1            180
#define PAD_PWM2            181
#define PAD_PWM3            182
#define PAD_DDCR_DAT        183
#define PAD_DDCR_CLK        184
#define PAD_B_ODD0          193
#define PAD_B_ODD1          194
#define PAD_B_ODD2          195
#define PAD_B_ODD3          196
#define PAD_B_ODD4          197
#define PAD_B_ODD5          198
#define PAD_B_ODD6          199
#define PAD_B_ODD7          200
#define PAD_G_ODD0          201
#define PAD_G_ODD1          202
#define PAD_G_ODD2          203
#define PAD_G_ODD3          204
#define PAD_G_ODD4          205
#define PAD_G_ODD5          206
#define PAD_G_ODD6          207
#define PAD_G_ODD7          208
#define PAD_R_ODD0          209
#define PAD_R_ODD1          210
#define PAD_R_ODD2          211
#define PAD_R_ODD3          212
#define PAD_R_ODD4          213
#define PAD_R_ODD5          214
#define PAD_R_ODD6          215
#define PAD_R_ODD7          216
#define PAD_LCK             217
#define PAD_LDE             218
#define PAD_LHSYNC          219
#define PAD_LVSYNC          220
#define PAD_TCON0           221
#define PAD_TCON1           222
#define PAD_TCON2           223
#define PAD_TCON3           224
#define PAD_TCON4           225
#define PAD_TCON5           226
#define PAD_TCON6           227
#define PAD_TCON7           228
#define PAD_TCON8           229
#define PAD_TCON9           230
#define PAD_TCON10          231
#define PAD_TCON11          232
#define PAD_TCON12          233
#define PAD_TCON13          234
#define PAD_TCON14          235
#define PAD_TCON15          236
#define PAD_TCON16          237
#define PAD_PCM_A3          238
#define PAD_PCM_A2          239
#define PAD_PCM_REG_N       240
#define PAD_PCM_A1          241
#define PAD_PCM_A0          242
#define PAD_PCM_D0          243
#define PAD_PCM_D1          244
#define PAD_PCM_D2          245
#define PAD_PCM_RESET       246
#define PAD_PCM2_RESET      247
#define PAD_PCM_CD_N        248
#define PAD_PCM2_CD_N       249
#define PAD_TS1_D0          250
#define PAD_TS1_VLD         251
#define PAD_TS1_SYNC        252
#define PAD_TS1_CLK         253
#define PAD_ET_COL          345
#define PAD_ET_TXD1         346
#define PAD_ET_TXD0         347
#define PAD_ET_TX_EN        348
#define PAD_ET_TX_CLK       349
#define PAD_ET_RXD0         350
#define PAD_I2S_IN_WS       351
#define PAD_I2S_IN_BCK      352
#define PAD_I2S_IN_SD       353
#define PAD_SPDIF_IN        354
#define PAD_I2S_OUT_MCK     355
#define PAD_I2S_OUT_WS      356
#define PAD_ET_CRS          357
#define PAD_ET_TXD3         358
#define PAD_I2S_OUT_BCK     359
#define PAD_ET_TXD2         360
#define PAD_I2S_OUT_SD      361
#define PAD_ET_TXER         362
#define PAD_SPDIF_OUT       363
#define PAD_ET_RXER         364
#define PAD_DDCR_DA2        365
#define PAD_ET_RX_CLK       366
#define PAD_DDCR_CK2        367
#define PAD_ET_RX_DV        368
#define PAD_LHSYNC2         369
#define PAD_LVSYNC2         370
#define PAD_ET_RXD1         371
#define PAD_GPIO12          372
#define PAD_ET_RXD2         373
#define PAD_GPIO13          374
#define PAD_ET_RXD3         375
#define PAD_GPIO14          376
#define PAD_ET_MDC          377
#define PAD_GPIO15          378
#define PAD_ET_MDIO         379
#define PAD_GPIO_PM0        392
#define PAD_GPIO_PM1        393
#define PAD_GPIO_PM2        394
#define PAD_GPIO_PM3        395
#define PAD_GPIO_PM4        396

// PADS group name to index
#define PADS_DDCR           400
#define PADS_DDCR2          401
#define PADS_TS0            402
#define PADS_TS1            403
#define PADS_GPIO1_GPIO2    404
#define PADS_LHSYNC2_LVSYNC2 405
#define PADS_PCI_AD20_AD21  406
#define PADS_PCI            407
#define PADS_PCM            408
#define PADS_SAR            409
#define PADS_DOUT           410
#define PADS_DIN            411
#define PADS_I2S            412
#define PADS_PF             413
#define PADS_EMAC           414
#define PADS_TCON           415
#define PADS_UART1_MODE1    416
#define PADS_UART1_MODE2    417
#define PADS_UART1_MODE3    418
#define PADS_UART2_MODE1    419
#define PADS_UART2_MODE2    420
#define PADS_UART2_MODE3    421
#define PADS_ET_MODE0       422
#define PADS_ET_MODE1       423
#define PADS_ET_MODE2       424

// PAD index to GPIO number mapping
#define GPIO_PAD_236        GPIO165
#define GPIO_PAD_358        GPIO90
#define GPIO_PAD_162        GPIO_DDCD2_SDA
#define GPIO_PAD_169        GPIO169
#define GPIO_PAD_369        GPIO78
#define GPIO_PAD_137        GPIO33
#define GPIO_PAD_135        GPIO31
#define GPIO_PAD_212        GPIO125
#define GPIO_PAD_234        GPIO163
#define GPIO_PAD_195        GPIO108
#define GPIO_PAD_129        GPIO25
#define GPIO_PAD_115        GPIO4
#define GPIO_PAD_140        GPIO35
#define GPIO_PAD_118        GPIO7
#define GPIO_PAD_366        GPIO98
#define GPIO_PAD_223        GPIO152
#define GPIO_PAD_176        GPIO81
#define GPIO_PAD_181        GPIO47
#define GPIO_PAD_373        GPIO102
#define GPIO_PAD_228        GPIO157
#define GPIO_PAD_117        GPIO6
#define GPIO_PAD_130        GPIO26
#define GPIO_PAD_199        GPIO112
#define GPIO_PAD_178        GPIO82
#define GPIO_PAD_357        GPIO88
#define GPIO_PAD_113        GPIO2
#define GPIO_PAD_202        GPIO115
#define GPIO_PAD_364        GPIO97
#define GPIO_PAD_386        GPIO146
#define GPIO_PAD_377        GPIO104
#define GPIO_PAD_75         GPIO_DDCA0_SCL
#define GPIO_PAD_250        GPIO63
#define GPIO_PAD_122        GPIO11
#define GPIO_PAD_126        GPIO22
#define GPIO_PAD_18         GPIO167
#define GPIO_PAD_345        GPIO89
#define GPIO_PAD_352        GPIO68
#define GPIO_PAD_157        GPIO17
#define GPIO_PAD_388        GPIO148
#define GPIO_PAD_252        GPIO65
#define GPIO_PAD_245        GPIO58
#define GPIO_PAD_365        GPIO76
#define GPIO_PAD_251        GPIO64
#define GPIO_PAD_149        GPIO44
#define GPIO_PAD_209        GPIO122
#define GPIO_PAD_379        GPIO105
#define GPIO_PAD_23         GPIO_DDCD1_SCL
#define GPIO_PAD_203        GPIO116
#define GPIO_PAD_238        GPIO51
#define GPIO_PAD_348        GPIO94
#define GPIO_PAD_148        GPIO43
#define GPIO_PAD_141        GPIO36
#define GPIO_PAD_226        GPIO155
#define GPIO_PAD_218        GPIO131
#define GPIO_PAD_374        GPIO85
#define GPIO_PAD_219        GPIO132
#define GPIO_PAD_121        GPIO10
#define GPIO_PAD_155        GPIO15
#define GPIO_PAD_396        GPIO138
#define GPIO_PAD_206        GPIO119
#define GPIO_PAD_362        GPIO96
#define GPIO_PAD_367        GPIO77
#define GPIO_PAD_179        GPIO45
#define GPIO_PAD_182        GPIO48
#define GPIO_PAD_128        GPIO24
#define GPIO_PAD_349        GPIO95
#define GPIO_PAD_143        GPIO38
#define GPIO_PAD_221        GPIO150
#define GPIO_PAD_231        GPIO160
#define GPIO_PAD_347        GPIO93
#define GPIO_PAD_378        GPIO87
#define GPIO_PAD_242        GPIO55
#define GPIO_PAD_144        GPIO39
#define GPIO_PAD_393        GPIO135
#define GPIO_PAD_214        GPIO127
#define GPIO_PAD_201        GPIO114
#define GPIO_PAD_131        GPIO27
#define GPIO_PAD_119        GPIO8
#define GPIO_PAD_372        GPIO84
#define GPIO_PAD_116        GPIO5
#define GPIO_PAD_134        GPIO30
#define GPIO_PAD_208        GPIO121
#define GPIO_PAD_361        GPIO74
#define GPIO_PAD_375        GPIO103
#define GPIO_PAD_156        GPIO16
#define GPIO_PAD_198        GPIO111
#define GPIO_PAD_159        GPIO_DDCD2_SCL
#define GPIO_PAD_224        GPIO153
#define GPIO_PAD_227        GPIO156
#define GPIO_PAD_243        GPIO56
#define GPIO_PAD_15         GPIO_DDCD1_SDA
#define GPIO_PAD_235        GPIO164
#define GPIO_PAD_194        GPIO107
#define GPIO_PAD_389        GPIO149
#define GPIO_PAD_133        GPIO29
#define GPIO_PAD_353        GPIO69
#define GPIO_PAD_34         GPIO_DDCD0_SDA
#define GPIO_PAD_370        GPIO79
#define GPIO_PAD_359        GPIO73
#define GPIO_PAD_356        GPIO72
#define GPIO_PAD_216        GPIO129
#define GPIO_PAD_244        GPIO57
#define GPIO_PAD_205        GPIO118
#define GPIO_PAD_138        GPIO34
#define GPIO_PAD_350        GPIO100
#define GPIO_PAD_360        GPIO91
#define GPIO_PAD_237        GPIO166
#define GPIO_PAD_124        GPIO20
#define GPIO_PAD_249        GPIO62
#define GPIO_PAD_123        GPIO12
#define GPIO_PAD_233        GPIO162
#define GPIO_PAD_150        GPIO0
#define GPIO_PAD_127        GPIO23
#define GPIO_PAD_177        GPIO83
#define GPIO_PAD_153        GPIO18
#define GPIO_PAD_371        GPIO101
#define GPIO_PAD_197        GPIO110
#define GPIO_PAD_239        GPIO52
#define GPIO_PAD_145        GPIO40
#define GPIO_PAD_253        GPIO66
#define GPIO_PAD_158        GPIO19
#define GPIO_PAD_132        GPIO28
#define GPIO_PAD_146        GPIO41
#define GPIO_PAD_152        GPIO13
#define GPIO_PAD_210        GPIO123
#define GPIO_PAD_387        GPIO147
#define GPIO_PAD_220        GPIO133
#define GPIO_PAD_147        GPIO42
#define GPIO_PAD_32         GPIO168
#define GPIO_PAD_151        GPIO1
#define GPIO_PAD_114        GPIO3
#define GPIO_PAD_230        GPIO159
#define GPIO_PAD_229        GPIO158
#define GPIO_PAD_376        GPIO86
#define GPIO_PAD_204        GPIO117
#define GPIO_PAD_215        GPIO128
#define GPIO_PAD_248        GPIO61
#define GPIO_PAD_184        GPIO50
#define GPIO_PAD_240        GPIO53
#define GPIO_PAD_154        GPIO14
#define GPIO_PAD_125        GPIO21
#define GPIO_PAD_207        GPIO120
#define GPIO_PAD_200        GPIO113
#define GPIO_PAD_180        GPIO46
#define GPIO_PAD_222        GPIO151
#define GPIO_PAD_247        GPIO60
#define GPIO_PAD_355        GPIO71
#define GPIO_PAD_120        GPIO9
#define GPIO_PAD_196        GPIO109
#define GPIO_PAD_211        GPIO124
#define GPIO_PAD_232        GPIO161
#define GPIO_PAD_175        GPIO80
#define GPIO_PAD_246        GPIO59
#define GPIO_PAD_241        GPIO54
#define GPIO_PAD_142        GPIO37
#define GPIO_PAD_217        GPIO130
#define GPIO_PAD_363        GPIO75
#define GPIO_PAD_395        GPIO137
#define GPIO_PAD_368        GPIO99
#define GPIO_PAD_136        GPIO32
#define GPIO_PAD_183        GPIO49
#define GPIO_PAD_225        GPIO154
#define GPIO_PAD_351        GPIO67
#define GPIO_PAD_392        GPIO134
#define GPIO_PAD_354        GPIO70
#define GPIO_PAD_213        GPIO126
#define GPIO_PAD_394        GPIO136
#define GPIO_PAD_74         GPIO_DDCA0_SDA
#define GPIO_PAD_346        GPIO92
#define GPIO_PAD_35         GPIO_DDCD0_SCL
#define GPIO_PAD_193        GPIO106
#define GPIO_PAD_9999       GPIO_NC

// default GPIO setting
#ifndef BALL_AA26_IS_GPIO
#define BALL_AA26_IS_GPIO 0
#endif
#ifndef PAD_TCON15_IS_GPIO
#define PAD_TCON15_IS_GPIO BALL_AA26_IS_GPIO
#endif
#ifndef BALL_D7_IS_GPIO
#define BALL_D7_IS_GPIO 0
#endif
#ifndef PAD_ET_TXD3_IS_GPIO
#define PAD_ET_TXD3_IS_GPIO BALL_D7_IS_GPIO
#endif
#ifndef BALL_AE7_IS_GPIO
#define BALL_AE7_IS_GPIO 0
#endif
#ifndef PAD_DDCDC_DA_IS_GPIO
#define PAD_DDCDC_DA_IS_GPIO BALL_AE7_IS_GPIO
#endif
#ifndef BALL_AD7_IS_GPIO
#define BALL_AD7_IS_GPIO 0
#endif
#ifndef PAD_HOTPLUGC_IS_GPIO
#define PAD_HOTPLUGC_IS_GPIO BALL_AD7_IS_GPIO
#endif
#ifndef BALL_E7_IS_GPIO
#define BALL_E7_IS_GPIO 0
#endif
#ifndef PAD_LHSYNC2_IS_GPIO
#define PAD_LHSYNC2_IS_GPIO BALL_E7_IS_GPIO
#endif
#ifndef BALL_AA7_IS_GPIO
#define BALL_AA7_IS_GPIO 0
#endif
#ifndef PAD_PCM_A13_IS_GPIO
#define PAD_PCM_A13_IS_GPIO BALL_AA7_IS_GPIO
#endif
#ifndef BALL_AA5_IS_GPIO
#define BALL_AA5_IS_GPIO 0
#endif
#ifndef PAD_PCM_IOWR_N_IS_GPIO
#define PAD_PCM_IOWR_N_IS_GPIO BALL_AA5_IS_GPIO
#endif
#ifndef BALL_AF25_IS_GPIO
#define BALL_AF25_IS_GPIO 0
#endif
#ifndef PAD_R_ODD3_IS_GPIO
#define PAD_R_ODD3_IS_GPIO BALL_AF25_IS_GPIO
#endif
#define PAD_GPIO_PM9_IS_GPIO 0
#ifndef BALL_AA25_IS_GPIO
#define BALL_AA25_IS_GPIO 0
#endif
#ifndef PAD_TCON13_IS_GPIO
#define PAD_TCON13_IS_GPIO BALL_AA25_IS_GPIO
#endif
#ifndef BALL_AD15_IS_GPIO
#define BALL_AD15_IS_GPIO 0
#endif
#ifndef PAD_B_ODD2_IS_GPIO
#define PAD_B_ODD2_IS_GPIO BALL_AD15_IS_GPIO
#endif
#ifndef BALL_T4_IS_GPIO
#define BALL_T4_IS_GPIO 0
#endif
#ifndef PAD_PCM_CE_N_IS_GPIO
#define PAD_PCM_CE_N_IS_GPIO BALL_T4_IS_GPIO
#endif
#ifndef BALL_Y9_IS_GPIO
#define BALL_Y9_IS_GPIO 0
#endif
#ifndef PAD_TS0_D2_IS_GPIO
#define PAD_TS0_D2_IS_GPIO BALL_Y9_IS_GPIO
#endif
#ifndef BALL_AC8_IS_GPIO
#define BALL_AC8_IS_GPIO 0
#endif
#ifndef PAD_PCM_IRQA_N_IS_GPIO
#define PAD_PCM_IRQA_N_IS_GPIO BALL_AC8_IS_GPIO
#endif
#ifndef BALL_AB6_IS_GPIO
#define BALL_AB6_IS_GPIO 0
#endif
#ifndef PAD_TS0_D5_IS_GPIO
#define PAD_TS0_D5_IS_GPIO BALL_AB6_IS_GPIO
#endif
#ifndef BALL_E10_IS_GPIO
#define BALL_E10_IS_GPIO 0
#endif
#ifndef PAD_ET_RX_CLK_IS_GPIO
#define PAD_ET_RX_CLK_IS_GPIO BALL_E10_IS_GPIO
#endif
#ifndef BALL_AD19_IS_GPIO
#define BALL_AD19_IS_GPIO 0
#endif
#ifndef PAD_TCON2_IS_GPIO
#define PAD_TCON2_IS_GPIO BALL_AD19_IS_GPIO
#endif
#ifndef BALL_AF12_IS_GPIO
#define BALL_AF12_IS_GPIO 0
#endif
#ifndef PAD_SPI_DI_IS_GPIO
#define PAD_SPI_DI_IS_GPIO BALL_AF12_IS_GPIO
#endif
#ifndef BALL_AC19_IS_GPIO
#define BALL_AC19_IS_GPIO 0
#endif
#ifndef PAD_PWM2_IS_GPIO
#define PAD_PWM2_IS_GPIO BALL_AC19_IS_GPIO
#endif
#ifndef BALL_C5_IS_GPIO
#define BALL_C5_IS_GPIO 0
#endif
#ifndef PAD_ET_RXD2_IS_GPIO
#define PAD_ET_RXD2_IS_GPIO BALL_C5_IS_GPIO
#endif
#ifndef BALL_AC23_IS_GPIO
#define BALL_AC23_IS_GPIO 0
#endif
#ifndef PAD_TCON7_IS_GPIO
#define PAD_TCON7_IS_GPIO BALL_AC23_IS_GPIO
#endif
#ifndef BALL_AA6_IS_GPIO
#define BALL_AA6_IS_GPIO 0
#endif
#ifndef PAD_TS0_D4_IS_GPIO
#define PAD_TS0_D4_IS_GPIO BALL_AA6_IS_GPIO
#endif
#ifndef BALL_V4_IS_GPIO
#define BALL_V4_IS_GPIO 0
#endif
#ifndef PAD_PCM_A10_IS_GPIO
#define PAD_PCM_A10_IS_GPIO BALL_V4_IS_GPIO
#endif
#ifndef BALL_AE14_IS_GPIO
#define BALL_AE14_IS_GPIO 0
#endif
#ifndef PAD_B_ODD6_IS_GPIO
#define PAD_B_ODD6_IS_GPIO BALL_AE14_IS_GPIO
#endif
#ifndef BALL_AD12_IS_GPIO
#define BALL_AD12_IS_GPIO 0
#endif
#ifndef PAD_SPI_CZ_IS_GPIO
#define PAD_SPI_CZ_IS_GPIO BALL_AD12_IS_GPIO
#endif
#ifndef BALL_D10_IS_GPIO
#define BALL_D10_IS_GPIO 0
#endif
#ifndef PAD_ET_CRS_IS_GPIO
#define PAD_ET_CRS_IS_GPIO BALL_D10_IS_GPIO
#endif
#define PAD_GPIO_PM7_IS_GPIO 0
#ifndef BALL_AA8_IS_GPIO
#define BALL_AA8_IS_GPIO 0
#endif
#ifndef PAD_TS0_D0_IS_GPIO
#define PAD_TS0_D0_IS_GPIO BALL_AA8_IS_GPIO
#endif
#ifndef BALL_AD13_IS_GPIO
#define BALL_AD13_IS_GPIO 0
#endif
#ifndef PAD_G_ODD1_IS_GPIO
#define PAD_G_ODD1_IS_GPIO BALL_AD13_IS_GPIO
#endif
#ifndef BALL_E8_IS_GPIO
#define BALL_E8_IS_GPIO 0
#endif
#ifndef PAD_ET_RXER_IS_GPIO
#define PAD_ET_RXER_IS_GPIO BALL_E8_IS_GPIO
#endif
#ifndef BALL_A4_IS_GPIO
#define BALL_A4_IS_GPIO 0
#endif
#ifndef PAD_SAR0_IS_GPIO
#define PAD_SAR0_IS_GPIO BALL_A4_IS_GPIO
#endif
#ifndef BALL_A10_IS_GPIO
#define BALL_A10_IS_GPIO 0
#endif
#ifndef PAD_ET_MDC_IS_GPIO
#define PAD_ET_MDC_IS_GPIO BALL_A10_IS_GPIO
#endif
#ifndef BALL_J1_IS_GPIO
#define BALL_J1_IS_GPIO 0
#endif
#ifndef PAD_DDCA_CK_IS_GPIO
#define PAD_DDCA_CK_IS_GPIO BALL_J1_IS_GPIO
#endif
#ifndef BALL_AB13_IS_GPIO
#define BALL_AB13_IS_GPIO 0
#endif
#ifndef PAD_TS1_D0_IS_GPIO
#define PAD_TS1_D0_IS_GPIO BALL_AB13_IS_GPIO
#endif
#ifndef BALL_AC4_IS_GPIO
#define BALL_AC4_IS_GPIO 0
#endif
#ifndef PAD_TS0_SYNC_IS_GPIO
#define PAD_TS0_SYNC_IS_GPIO BALL_AC4_IS_GPIO
#endif
#ifndef BALL_AA10_IS_GPIO
#define BALL_AA10_IS_GPIO 0
#endif
#ifndef PAD_PCM_D5_IS_GPIO
#define PAD_PCM_D5_IS_GPIO BALL_AA10_IS_GPIO
#endif
#ifndef BALL_E2_IS_GPIO
#define BALL_E2_IS_GPIO 0
#endif
#ifndef PAD_HOTPLUGB_IS_GPIO
#define PAD_HOTPLUGB_IS_GPIO BALL_E2_IS_GPIO
#endif
#ifndef BALL_A11_IS_GPIO
#define BALL_A11_IS_GPIO 0
#endif
#ifndef PAD_ET_COL_IS_GPIO
#define PAD_ET_COL_IS_GPIO BALL_A11_IS_GPIO
#endif
#ifndef BALL_B8_IS_GPIO
#define BALL_B8_IS_GPIO 0
#endif
#ifndef PAD_I2S_IN_BCK_IS_GPIO
#define PAD_I2S_IN_BCK_IS_GPIO BALL_B8_IS_GPIO
#endif
#ifndef BALL_AB11_IS_GPIO
#define BALL_AB11_IS_GPIO 0
#endif
#ifndef PAD_PF_WEZ_IS_GPIO
#define PAD_PF_WEZ_IS_GPIO BALL_AB11_IS_GPIO
#endif
#ifndef BALL_F4_IS_GPIO
#define BALL_F4_IS_GPIO 0
#endif
#ifndef PAD_SAR2_IS_GPIO
#define PAD_SAR2_IS_GPIO BALL_F4_IS_GPIO
#endif
#ifndef BALL_Y14_IS_GPIO
#define BALL_Y14_IS_GPIO 0
#endif
#ifndef PAD_TS1_SYNC_IS_GPIO
#define PAD_TS1_SYNC_IS_GPIO BALL_Y14_IS_GPIO
#endif
#ifndef BALL_AB16_IS_GPIO
#define BALL_AB16_IS_GPIO 0
#endif
#ifndef PAD_PCM_D2_IS_GPIO
#define PAD_PCM_D2_IS_GPIO BALL_AB16_IS_GPIO
#endif
#ifndef BALL_D11_IS_GPIO
#define BALL_D11_IS_GPIO 0
#endif
#ifndef PAD_DDCR_DA2_IS_GPIO
#define PAD_DDCR_DA2_IS_GPIO BALL_D11_IS_GPIO
#endif
#ifndef BALL_AA13_IS_GPIO
#define BALL_AA13_IS_GPIO 0
#endif
#ifndef PAD_TS1_VLD_IS_GPIO
#define PAD_TS1_VLD_IS_GPIO BALL_AA13_IS_GPIO
#endif
#ifndef BALL_AD11_IS_GPIO
#define BALL_AD11_IS_GPIO 0
#endif
#ifndef PAD_PCM2_WAIT_N_IS_GPIO
#define PAD_PCM2_WAIT_N_IS_GPIO BALL_AD11_IS_GPIO
#endif
#ifndef BALL_AE25_IS_GPIO
#define BALL_AE25_IS_GPIO 0
#endif
#ifndef PAD_R_ODD0_IS_GPIO
#define PAD_R_ODD0_IS_GPIO BALL_AE25_IS_GPIO
#endif
#ifndef BALL_B9_IS_GPIO
#define BALL_B9_IS_GPIO 0
#endif
#ifndef PAD_ET_MDIO_IS_GPIO
#define PAD_ET_MDIO_IS_GPIO BALL_B9_IS_GPIO
#endif
#ifndef BALL_F3_IS_GPIO
#define BALL_F3_IS_GPIO 0
#endif
#ifndef PAD_DDCDB_CK_IS_GPIO
#define PAD_DDCDB_CK_IS_GPIO BALL_F3_IS_GPIO
#endif
#ifndef BALL_AC25_IS_GPIO
#define BALL_AC25_IS_GPIO 0
#endif
#ifndef PAD_G_ODD2_IS_GPIO
#define PAD_G_ODD2_IS_GPIO BALL_AC25_IS_GPIO
#endif
#ifndef BALL_AB14_IS_GPIO
#define BALL_AB14_IS_GPIO 0
#endif
#ifndef PAD_PCM_A3_IS_GPIO
#define PAD_PCM_A3_IS_GPIO BALL_AB14_IS_GPIO
#endif
#ifndef BALL_B10_IS_GPIO
#define BALL_B10_IS_GPIO 0
#endif
#ifndef PAD_ET_TX_EN_IS_GPIO
#define PAD_ET_TX_EN_IS_GPIO BALL_B10_IS_GPIO
#endif
#ifndef BALL_AD10_IS_GPIO
#define BALL_AD10_IS_GPIO 0
#endif
#ifndef PAD_PCM2_IRQA_N_IS_GPIO
#define PAD_PCM2_IRQA_N_IS_GPIO BALL_AD10_IS_GPIO
#endif
#ifndef BALL_AB9_IS_GPIO
#define BALL_AB9_IS_GPIO 0
#endif
#ifndef PAD_PCM_A12_IS_GPIO
#define PAD_PCM_A12_IS_GPIO BALL_AB9_IS_GPIO
#endif
#ifndef BALL_AE21_IS_GPIO
#define BALL_AE21_IS_GPIO 0
#endif
#ifndef PAD_TCON5_IS_GPIO
#define PAD_TCON5_IS_GPIO BALL_AE21_IS_GPIO
#endif
#ifndef BALL_AE22_IS_GPIO
#define BALL_AE22_IS_GPIO 0
#endif
#ifndef PAD_LDE_IS_GPIO
#define PAD_LDE_IS_GPIO BALL_AE22_IS_GPIO
#endif
#ifndef BALL_F10_IS_GPIO
#define BALL_F10_IS_GPIO 0
#endif
#ifndef PAD_GPIO13_IS_GPIO
#define PAD_GPIO13_IS_GPIO BALL_F10_IS_GPIO
#endif
#ifndef BALL_AF22_IS_GPIO
#define BALL_AF22_IS_GPIO 0
#endif
#ifndef PAD_LHSYNC_IS_GPIO
#define PAD_LHSYNC_IS_GPIO BALL_AF22_IS_GPIO
#endif
#ifndef BALL_AD5_IS_GPIO
#define BALL_AD5_IS_GPIO 0
#endif
#ifndef PAD_TS0_VLD_IS_GPIO
#define PAD_TS0_VLD_IS_GPIO BALL_AD5_IS_GPIO
#endif
#ifndef BALL_AF6_IS_GPIO
#define BALL_AF6_IS_GPIO 0
#endif
#ifndef PAD_PF_CE1Z_IS_GPIO
#define PAD_PF_CE1Z_IS_GPIO BALL_AF6_IS_GPIO
#endif
#ifndef BALL_F6_IS_GPIO
#define BALL_F6_IS_GPIO 0
#endif
#ifndef PAD_GPIO_PM4_IS_GPIO
#define PAD_GPIO_PM4_IS_GPIO BALL_F6_IS_GPIO
#endif
#ifndef BALL_AD25_IS_GPIO
#define BALL_AD25_IS_GPIO 0
#endif
#ifndef PAD_G_ODD5_IS_GPIO
#define PAD_G_ODD5_IS_GPIO BALL_AD25_IS_GPIO
#endif
#ifndef BALL_D9_IS_GPIO
#define BALL_D9_IS_GPIO 0
#endif
#ifndef PAD_ET_TXER_IS_GPIO
#define PAD_ET_TXER_IS_GPIO BALL_D9_IS_GPIO
#endif
#ifndef BALL_F8_IS_GPIO
#define BALL_F8_IS_GPIO 0
#endif
#ifndef PAD_DDCR_CK2_IS_GPIO
#define PAD_DDCR_CK2_IS_GPIO BALL_F8_IS_GPIO
#endif
#ifndef BALL_AC18_IS_GPIO
#define BALL_AC18_IS_GPIO 0
#endif
#ifndef PAD_PWM0_IS_GPIO
#define PAD_PWM0_IS_GPIO BALL_AC18_IS_GPIO
#endif
#ifndef BALL_AB19_IS_GPIO
#define BALL_AB19_IS_GPIO 0
#endif
#ifndef PAD_PWM3_IS_GPIO
#define PAD_PWM3_IS_GPIO BALL_AB19_IS_GPIO
#endif
#define PAD_GPIO_PM10_IS_GPIO 0
#ifndef BALL_AA12_IS_GPIO
#define BALL_AA12_IS_GPIO 0
#endif
#ifndef PAD_PCM_D7_IS_GPIO
#define PAD_PCM_D7_IS_GPIO BALL_AA12_IS_GPIO
#endif
#ifndef BALL_A9_IS_GPIO
#define BALL_A9_IS_GPIO 0
#endif
#ifndef PAD_ET_TX_CLK_IS_GPIO
#define PAD_ET_TX_CLK_IS_GPIO BALL_A9_IS_GPIO
#endif
#ifndef BALL_AC12_IS_GPIO
#define BALL_AC12_IS_GPIO 0
#endif
#ifndef PAD_PCM_A6_IS_GPIO
#define PAD_PCM_A6_IS_GPIO BALL_AC12_IS_GPIO
#endif
#ifndef BALL_AF21_IS_GPIO
#define BALL_AF21_IS_GPIO 0
#endif
#ifndef PAD_TCON0_IS_GPIO
#define PAD_TCON0_IS_GPIO BALL_AF21_IS_GPIO
#endif
#ifndef BALL_AC26_IS_GPIO
#define BALL_AC26_IS_GPIO 0
#endif
#ifndef PAD_TCON10_IS_GPIO
#define PAD_TCON10_IS_GPIO BALL_AC26_IS_GPIO
#endif
#ifndef BALL_C10_IS_GPIO
#define BALL_C10_IS_GPIO 0
#endif
#ifndef PAD_ET_TXD0_IS_GPIO
#define PAD_ET_TXD0_IS_GPIO BALL_C10_IS_GPIO
#endif
#ifndef BALL_B6_IS_GPIO
#define BALL_B6_IS_GPIO 0
#endif
#ifndef PAD_GPIO15_IS_GPIO
#define PAD_GPIO15_IS_GPIO BALL_B6_IS_GPIO
#endif
#ifndef BALL_AC16_IS_GPIO
#define BALL_AC16_IS_GPIO 0
#endif
#ifndef PAD_PCM_A0_IS_GPIO
#define PAD_PCM_A0_IS_GPIO BALL_AC16_IS_GPIO
#endif
#ifndef BALL_AB8_IS_GPIO
#define BALL_AB8_IS_GPIO 0
#endif
#ifndef PAD_PCM_A5_IS_GPIO
#define PAD_PCM_A5_IS_GPIO BALL_AB8_IS_GPIO
#endif
#ifndef BALL_F5_IS_GPIO
#define BALL_F5_IS_GPIO 0
#endif
#ifndef PAD_GPIO_PM1_IS_GPIO
#define PAD_GPIO_PM1_IS_GPIO BALL_F5_IS_GPIO
#endif
#ifndef BALL_AD23_IS_GPIO
#define BALL_AD23_IS_GPIO 0
#endif
#ifndef PAD_R_ODD5_IS_GPIO
#define PAD_R_ODD5_IS_GPIO BALL_AD23_IS_GPIO
#endif
#define PAD_GPIO_PM6_IS_GPIO 0
#ifndef BALL_AE13_IS_GPIO
#define BALL_AE13_IS_GPIO 0
#endif
#ifndef PAD_G_ODD0_IS_GPIO
#define PAD_G_ODD0_IS_GPIO BALL_AE13_IS_GPIO
#endif
#ifndef BALL_Y5_IS_GPIO
#define BALL_Y5_IS_GPIO 0
#endif
#ifndef PAD_PCM_OE_N_IS_GPIO
#define PAD_PCM_OE_N_IS_GPIO BALL_Y5_IS_GPIO
#endif
#ifndef BALL_U4_IS_GPIO
#define BALL_U4_IS_GPIO 0
#endif
#ifndef PAD_TS0_D6_IS_GPIO
#define PAD_TS0_D6_IS_GPIO BALL_U4_IS_GPIO
#endif
#define PAD_GPIO_PM8_IS_GPIO 0
#ifndef BALL_F9_IS_GPIO
#define BALL_F9_IS_GPIO 0
#endif
#ifndef PAD_GPIO12_IS_GPIO
#define PAD_GPIO12_IS_GPIO BALL_F9_IS_GPIO
#endif
#ifndef BALL_AB7_IS_GPIO
#define BALL_AB7_IS_GPIO 0
#endif
#ifndef PAD_TS0_D3_IS_GPIO
#define PAD_TS0_D3_IS_GPIO BALL_AB7_IS_GPIO
#endif
#ifndef BALL_AA4_IS_GPIO
#define BALL_AA4_IS_GPIO 0
#endif
#ifndef PAD_PCM_A9_IS_GPIO
#define PAD_PCM_A9_IS_GPIO BALL_AA4_IS_GPIO
#endif
#ifndef BALL_AE26_IS_GPIO
#define BALL_AE26_IS_GPIO 0
#endif
#ifndef PAD_G_ODD7_IS_GPIO
#define PAD_G_ODD7_IS_GPIO BALL_AE26_IS_GPIO
#endif
#ifndef BALL_D8_IS_GPIO
#define BALL_D8_IS_GPIO 0
#endif
#ifndef PAD_I2S_OUT_SD_IS_GPIO
#define PAD_I2S_OUT_SD_IS_GPIO BALL_D8_IS_GPIO
#endif
#ifndef BALL_D5_IS_GPIO
#define BALL_D5_IS_GPIO 0
#endif
#ifndef PAD_ET_RXD3_IS_GPIO
#define PAD_ET_RXD3_IS_GPIO BALL_D5_IS_GPIO
#endif
#ifndef BALL_AB12_IS_GPIO
#define BALL_AB12_IS_GPIO 0
#endif
#ifndef PAD_PF_OEZ_IS_GPIO
#define PAD_PF_OEZ_IS_GPIO BALL_AB12_IS_GPIO
#endif
#ifndef BALL_AD14_IS_GPIO
#define BALL_AD14_IS_GPIO 0
#endif
#ifndef PAD_B_ODD5_IS_GPIO
#define PAD_B_ODD5_IS_GPIO BALL_AD14_IS_GPIO
#endif
#ifndef BALL_AF7_IS_GPIO
#define BALL_AF7_IS_GPIO 0
#endif
#ifndef PAD_DDCDC_CK_IS_GPIO
#define PAD_DDCDC_CK_IS_GPIO BALL_AF7_IS_GPIO
#endif
#ifndef BALL_AE19_IS_GPIO
#define BALL_AE19_IS_GPIO 0
#endif
#ifndef PAD_TCON3_IS_GPIO
#define PAD_TCON3_IS_GPIO BALL_AE19_IS_GPIO
#endif
#ifndef BALL_AB25_IS_GPIO
#define BALL_AB25_IS_GPIO 0
#endif
#ifndef PAD_TCON6_IS_GPIO
#define PAD_TCON6_IS_GPIO BALL_AB25_IS_GPIO
#endif
#ifndef BALL_AA17_IS_GPIO
#define BALL_AA17_IS_GPIO 0
#endif
#ifndef PAD_PCM_D0_IS_GPIO
#define PAD_PCM_D0_IS_GPIO BALL_AA17_IS_GPIO
#endif
#ifndef BALL_E1_IS_GPIO
#define BALL_E1_IS_GPIO 0
#endif
#ifndef PAD_DDCDB_DA_IS_GPIO
#define PAD_DDCDB_DA_IS_GPIO BALL_E1_IS_GPIO
#endif
#ifndef BALL_AB26_IS_GPIO
#define BALL_AB26_IS_GPIO 0
#endif
#ifndef PAD_TCON14_IS_GPIO
#define PAD_TCON14_IS_GPIO BALL_AB26_IS_GPIO
#endif
#ifndef BALL_AF16_IS_GPIO
#define BALL_AF16_IS_GPIO 0
#endif
#ifndef PAD_B_ODD1_IS_GPIO
#define PAD_B_ODD1_IS_GPIO BALL_AF16_IS_GPIO
#endif
#ifndef BALL_E4_IS_GPIO
#define BALL_E4_IS_GPIO 0
#endif
#ifndef PAD_SAR3_IS_GPIO
#define PAD_SAR3_IS_GPIO BALL_E4_IS_GPIO
#endif
#ifndef BALL_W4_IS_GPIO
#define BALL_W4_IS_GPIO 0
#endif
#ifndef PAD_PCM_IORD_N_IS_GPIO
#define PAD_PCM_IORD_N_IS_GPIO BALL_W4_IS_GPIO
#endif
#ifndef BALL_C8_IS_GPIO
#define BALL_C8_IS_GPIO 0
#endif
#ifndef PAD_I2S_IN_SD_IS_GPIO
#define PAD_I2S_IN_SD_IS_GPIO BALL_C8_IS_GPIO
#endif
#ifndef BALL_A1_IS_GPIO
#define BALL_A1_IS_GPIO 0
#endif
#ifndef PAD_DDCDA_DA_IS_GPIO
#define PAD_DDCDA_DA_IS_GPIO BALL_A1_IS_GPIO
#endif
#ifndef BALL_C6_IS_GPIO
#define BALL_C6_IS_GPIO 0
#endif
#ifndef PAD_LVSYNC2_IS_GPIO
#define PAD_LVSYNC2_IS_GPIO BALL_C6_IS_GPIO
#endif
#ifndef BALL_C7_IS_GPIO
#define BALL_C7_IS_GPIO 0
#endif
#ifndef PAD_I2S_OUT_BCK_IS_GPIO
#define PAD_I2S_OUT_BCK_IS_GPIO BALL_C7_IS_GPIO
#endif
#ifndef BALL_B7_IS_GPIO
#define BALL_B7_IS_GPIO 0
#endif
#ifndef PAD_I2S_OUT_WS_IS_GPIO
#define PAD_I2S_OUT_WS_IS_GPIO BALL_B7_IS_GPIO
#endif
#ifndef BALL_AF23_IS_GPIO
#define BALL_AF23_IS_GPIO 0
#endif
#ifndef PAD_R_ODD7_IS_GPIO
#define PAD_R_ODD7_IS_GPIO BALL_AF23_IS_GPIO
#endif
#ifndef BALL_AA15_IS_GPIO
#define BALL_AA15_IS_GPIO 0
#endif
#ifndef PAD_PCM_D1_IS_GPIO
#define PAD_PCM_D1_IS_GPIO BALL_AA15_IS_GPIO
#endif
#ifndef BALL_AD26_IS_GPIO
#define BALL_AD26_IS_GPIO 0
#endif
#ifndef PAD_G_ODD4_IS_GPIO
#define PAD_G_ODD4_IS_GPIO BALL_AD26_IS_GPIO
#endif
#ifndef BALL_AD6_IS_GPIO
#define BALL_AD6_IS_GPIO 0
#endif
#ifndef PAD_PCM_A14_IS_GPIO
#define PAD_PCM_A14_IS_GPIO BALL_AD6_IS_GPIO
#endif
#ifndef BALL_C11_IS_GPIO
#define BALL_C11_IS_GPIO 0
#endif
#ifndef PAD_ET_RXD0_IS_GPIO
#define PAD_ET_RXD0_IS_GPIO BALL_C11_IS_GPIO
#endif
#ifndef BALL_E11_IS_GPIO
#define BALL_E11_IS_GPIO 0
#endif
#ifndef PAD_ET_TXD2_IS_GPIO
#define PAD_ET_TXD2_IS_GPIO BALL_E11_IS_GPIO
#endif
#ifndef BALL_AA23_IS_GPIO
#define BALL_AA23_IS_GPIO 0
#endif
#ifndef PAD_TCON16_IS_GPIO
#define PAD_TCON16_IS_GPIO BALL_AA23_IS_GPIO
#endif
#ifndef BALL_AC6_IS_GPIO
#define BALL_AC6_IS_GPIO 0
#endif
#ifndef PAD_PCM_D3_IS_GPIO
#define PAD_PCM_D3_IS_GPIO BALL_AC6_IS_GPIO
#endif
#ifndef BALL_AA16_IS_GPIO
#define BALL_AA16_IS_GPIO 0
#endif
#ifndef PAD_PCM2_CD_N_IS_GPIO
#define PAD_PCM2_CD_N_IS_GPIO BALL_AA16_IS_GPIO
#endif
#ifndef BALL_AB4_IS_GPIO
#define BALL_AB4_IS_GPIO 0
#endif
#ifndef PAD_TS0_CLK_IS_GPIO
#define PAD_TS0_CLK_IS_GPIO BALL_AB4_IS_GPIO
#endif
#ifndef BALL_AA24_IS_GPIO
#define BALL_AA24_IS_GPIO 0
#endif
#ifndef PAD_TCON12_IS_GPIO
#define PAD_TCON12_IS_GPIO BALL_AA24_IS_GPIO
#endif
#ifndef BALL_W5_IS_GPIO
#define BALL_W5_IS_GPIO 0
#endif
#ifndef PAD_UART_RX2_IS_GPIO
#define PAD_UART_RX2_IS_GPIO BALL_W5_IS_GPIO
#endif
#ifndef BALL_AA11_IS_GPIO
#define BALL_AA11_IS_GPIO 0
#endif
#ifndef PAD_PCM_D6_IS_GPIO
#define PAD_PCM_D6_IS_GPIO BALL_AA11_IS_GPIO
#endif
#ifndef BALL_AF13_IS_GPIO
#define BALL_AF13_IS_GPIO 0
#endif
#ifndef PAD_SPI_DO_IS_GPIO
#define PAD_SPI_DO_IS_GPIO BALL_AF13_IS_GPIO
#endif
#ifndef BALL_AC9_IS_GPIO
#define BALL_AC9_IS_GPIO 0
#endif
#ifndef PAD_PF_ALE_IS_GPIO
#define PAD_PF_ALE_IS_GPIO BALL_AC9_IS_GPIO
#endif
#ifndef BALL_C9_IS_GPIO
#define BALL_C9_IS_GPIO 0
#endif
#ifndef PAD_ET_RXD1_IS_GPIO
#define PAD_ET_RXD1_IS_GPIO BALL_C9_IS_GPIO
#endif
#ifndef BALL_AF15_IS_GPIO
#define BALL_AF15_IS_GPIO 0
#endif
#ifndef PAD_B_ODD4_IS_GPIO
#define PAD_B_ODD4_IS_GPIO BALL_AF15_IS_GPIO
#endif
#ifndef BALL_AC14_IS_GPIO
#define BALL_AC14_IS_GPIO 0
#endif
#ifndef PAD_PCM_A2_IS_GPIO
#define PAD_PCM_A2_IS_GPIO BALL_AC14_IS_GPIO
#endif
#ifndef BALL_AC10_IS_GPIO
#define BALL_AC10_IS_GPIO 0
#endif
#ifndef PAD_PCM_WAIT_N_IS_GPIO
#define PAD_PCM_WAIT_N_IS_GPIO BALL_AC10_IS_GPIO
#endif
#ifndef BALL_Y13_IS_GPIO
#define BALL_Y13_IS_GPIO 0
#endif
#ifndef PAD_TS1_CLK_IS_GPIO
#define PAD_TS1_CLK_IS_GPIO BALL_Y13_IS_GPIO
#endif
#ifndef BALL_AC11_IS_GPIO
#define BALL_AC11_IS_GPIO 0
#endif
#ifndef PAD_F_RBZ_IS_GPIO
#define PAD_F_RBZ_IS_GPIO BALL_AC11_IS_GPIO
#endif
#ifndef BALL_Y4_IS_GPIO
#define BALL_Y4_IS_GPIO 0
#endif
#ifndef PAD_PCM_A11_IS_GPIO
#define PAD_PCM_A11_IS_GPIO BALL_Y4_IS_GPIO
#endif
#ifndef BALL_AC13_IS_GPIO
#define BALL_AC13_IS_GPIO 0
#endif
#ifndef PAD_PCM_A4_IS_GPIO
#define PAD_PCM_A4_IS_GPIO BALL_AC13_IS_GPIO
#endif
#ifndef BALL_Y12_IS_GPIO
#define BALL_Y12_IS_GPIO 0
#endif
#ifndef PAD_PF_AD15_IS_GPIO
#define PAD_PF_AD15_IS_GPIO BALL_Y12_IS_GPIO
#endif
#ifndef BALL_AE24_IS_GPIO
#define BALL_AE24_IS_GPIO 0
#endif
#ifndef PAD_R_ODD1_IS_GPIO
#define PAD_R_ODD1_IS_GPIO BALL_AE24_IS_GPIO
#endif
#ifndef BALL_B4_IS_GPIO
#define BALL_B4_IS_GPIO 0
#endif
#ifndef PAD_SAR1_IS_GPIO
#define PAD_SAR1_IS_GPIO BALL_B4_IS_GPIO
#endif
#ifndef BALL_AD21_IS_GPIO
#define BALL_AD21_IS_GPIO 0
#endif
#ifndef PAD_LVSYNC_IS_GPIO
#define PAD_LVSYNC_IS_GPIO BALL_AD21_IS_GPIO
#endif
#ifndef BALL_AF5_IS_GPIO
#define BALL_AF5_IS_GPIO 0
#endif
#ifndef PAD_PCM2_CE_N_IS_GPIO
#define PAD_PCM2_CE_N_IS_GPIO BALL_AF5_IS_GPIO
#endif
#ifndef BALL_A2_IS_GPIO
#define BALL_A2_IS_GPIO 0
#endif
#ifndef PAD_HOTPLUGA_IS_GPIO
#define PAD_HOTPLUGA_IS_GPIO BALL_A2_IS_GPIO
#endif
#ifndef BALL_V5_IS_GPIO
#define BALL_V5_IS_GPIO 0
#endif
#ifndef PAD_UART_TX2_IS_GPIO
#define PAD_UART_TX2_IS_GPIO BALL_V5_IS_GPIO
#endif
#ifndef BALL_Y8_IS_GPIO
#define BALL_Y8_IS_GPIO 0
#endif
#ifndef PAD_TS0_D1_IS_GPIO
#define PAD_TS0_D1_IS_GPIO BALL_Y8_IS_GPIO
#endif
#ifndef BALL_AB24_IS_GPIO
#define BALL_AB24_IS_GPIO 0
#endif
#ifndef PAD_TCON9_IS_GPIO
#define PAD_TCON9_IS_GPIO BALL_AB24_IS_GPIO
#endif
#ifndef BALL_AB23_IS_GPIO
#define BALL_AB23_IS_GPIO 0
#endif
#ifndef PAD_TCON8_IS_GPIO
#define PAD_TCON8_IS_GPIO BALL_AB23_IS_GPIO
#endif
#ifndef BALL_A6_IS_GPIO
#define BALL_A6_IS_GPIO 0
#endif
#ifndef PAD_GPIO14_IS_GPIO
#define PAD_GPIO14_IS_GPIO BALL_A6_IS_GPIO
#endif
#ifndef BALL_AC24_IS_GPIO
#define BALL_AC24_IS_GPIO 0
#endif
#ifndef PAD_G_ODD3_IS_GPIO
#define PAD_G_ODD3_IS_GPIO BALL_AC24_IS_GPIO
#endif
#ifndef BALL_AE23_IS_GPIO
#define BALL_AE23_IS_GPIO 0
#endif
#ifndef PAD_R_ODD6_IS_GPIO
#define PAD_R_ODD6_IS_GPIO BALL_AE23_IS_GPIO
#endif
#ifndef BALL_AC17_IS_GPIO
#define BALL_AC17_IS_GPIO 0
#endif
#ifndef PAD_PCM_CD_N_IS_GPIO
#define PAD_PCM_CD_N_IS_GPIO BALL_AC17_IS_GPIO
#endif
#ifndef BALL_AC20_IS_GPIO
#define BALL_AC20_IS_GPIO 0
#endif
#ifndef PAD_DDCR_CLK_IS_GPIO
#define PAD_DDCR_CLK_IS_GPIO BALL_AC20_IS_GPIO
#endif
#ifndef BALL_AB15_IS_GPIO
#define BALL_AB15_IS_GPIO 0
#endif
#ifndef PAD_PCM_REG_N_IS_GPIO
#define PAD_PCM_REG_N_IS_GPIO BALL_AB15_IS_GPIO
#endif
#ifndef BALL_AE6_IS_GPIO
#define BALL_AE6_IS_GPIO 0
#endif
#ifndef PAD_PF_CE0Z_IS_GPIO
#define PAD_PF_CE0Z_IS_GPIO BALL_AE6_IS_GPIO
#endif
#ifndef BALL_AB10_IS_GPIO
#define BALL_AB10_IS_GPIO 0
#endif
#ifndef PAD_PCM_D4_IS_GPIO
#define PAD_PCM_D4_IS_GPIO BALL_AB10_IS_GPIO
#endif
#ifndef BALL_AD24_IS_GPIO
#define BALL_AD24_IS_GPIO 0
#endif
#ifndef PAD_G_ODD6_IS_GPIO
#define PAD_G_ODD6_IS_GPIO BALL_AD24_IS_GPIO
#endif
#ifndef BALL_AF14_IS_GPIO
#define BALL_AF14_IS_GPIO 0
#endif
#ifndef PAD_B_ODD7_IS_GPIO
#define PAD_B_ODD7_IS_GPIO BALL_AF14_IS_GPIO
#endif
#ifndef BALL_AB18_IS_GPIO
#define BALL_AB18_IS_GPIO 0
#endif
#ifndef PAD_PWM1_IS_GPIO
#define PAD_PWM1_IS_GPIO BALL_AB18_IS_GPIO
#endif
#ifndef BALL_AD20_IS_GPIO
#define BALL_AD20_IS_GPIO 0
#endif
#ifndef PAD_TCON1_IS_GPIO
#define PAD_TCON1_IS_GPIO BALL_AD20_IS_GPIO
#endif
#ifndef BALL_AB17_IS_GPIO
#define BALL_AB17_IS_GPIO 0
#endif
#ifndef PAD_PCM2_RESET_IS_GPIO
#define PAD_PCM2_RESET_IS_GPIO BALL_AB17_IS_GPIO
#endif
#ifndef BALL_A8_IS_GPIO
#define BALL_A8_IS_GPIO 0
#endif
#ifndef PAD_I2S_OUT_MCK_IS_GPIO
#define PAD_I2S_OUT_MCK_IS_GPIO BALL_A8_IS_GPIO
#endif
#ifndef BALL_AC5_IS_GPIO
#define BALL_AC5_IS_GPIO 0
#endif
#ifndef PAD_TS0_D7_IS_GPIO
#define PAD_TS0_D7_IS_GPIO BALL_AC5_IS_GPIO
#endif
#ifndef BALL_AE15_IS_GPIO
#define BALL_AE15_IS_GPIO 0
#endif
#ifndef PAD_B_ODD3_IS_GPIO
#define PAD_B_ODD3_IS_GPIO BALL_AE15_IS_GPIO
#endif
#ifndef BALL_AF26_IS_GPIO
#define BALL_AF26_IS_GPIO 0
#endif
#ifndef PAD_R_ODD2_IS_GPIO
#define PAD_R_ODD2_IS_GPIO BALL_AF26_IS_GPIO
#endif
#ifndef BALL_AE20_IS_GPIO
#define BALL_AE20_IS_GPIO 0
#endif
#ifndef PAD_TCON11_IS_GPIO
#define PAD_TCON11_IS_GPIO BALL_AE20_IS_GPIO
#endif
#ifndef BALL_AE12_IS_GPIO
#define BALL_AE12_IS_GPIO 0
#endif
#ifndef PAD_SPI_CK_IS_GPIO
#define PAD_SPI_CK_IS_GPIO BALL_AE12_IS_GPIO
#endif
#ifndef BALL_AA14_IS_GPIO
#define BALL_AA14_IS_GPIO 0
#endif
#ifndef PAD_PCM_RESET_IS_GPIO
#define PAD_PCM_RESET_IS_GPIO BALL_AA14_IS_GPIO
#endif
#ifndef BALL_AC15_IS_GPIO
#define BALL_AC15_IS_GPIO 0
#endif
#ifndef PAD_PCM_A1_IS_GPIO
#define PAD_PCM_A1_IS_GPIO BALL_AC15_IS_GPIO
#endif
#ifndef BALL_AA9_IS_GPIO
#define BALL_AA9_IS_GPIO 0
#endif
#ifndef PAD_PCM_A7_IS_GPIO
#define PAD_PCM_A7_IS_GPIO BALL_AA9_IS_GPIO
#endif
#ifndef BALL_AD22_IS_GPIO
#define BALL_AD22_IS_GPIO 0
#endif
#ifndef PAD_LCK_IS_GPIO
#define PAD_LCK_IS_GPIO BALL_AD22_IS_GPIO
#endif
#ifndef BALL_E9_IS_GPIO
#define BALL_E9_IS_GPIO 0
#endif
#ifndef PAD_SPDIF_OUT_IS_GPIO
#define PAD_SPDIF_OUT_IS_GPIO BALL_E9_IS_GPIO
#endif
#ifndef BALL_H5_IS_GPIO
#define BALL_H5_IS_GPIO 0
#endif
#ifndef PAD_GPIO_PM3_IS_GPIO
#define PAD_GPIO_PM3_IS_GPIO BALL_H5_IS_GPIO
#endif
#ifndef BALL_D6_IS_GPIO
#define BALL_D6_IS_GPIO 0
#endif
#ifndef PAD_ET_RX_DV_IS_GPIO
#define PAD_ET_RX_DV_IS_GPIO BALL_D6_IS_GPIO
#endif
#ifndef BALL_AB5_IS_GPIO
#define BALL_AB5_IS_GPIO 0
#endif
#ifndef PAD_PCM_A8_IS_GPIO
#define PAD_PCM_A8_IS_GPIO BALL_AB5_IS_GPIO
#endif
#ifndef BALL_AC21_IS_GPIO
#define BALL_AC21_IS_GPIO 0
#endif
#ifndef PAD_DDCR_DAT_IS_GPIO
#define PAD_DDCR_DAT_IS_GPIO BALL_AC21_IS_GPIO
#endif
#ifndef BALL_AF20_IS_GPIO
#define BALL_AF20_IS_GPIO 0
#endif
#ifndef PAD_TCON4_IS_GPIO
#define PAD_TCON4_IS_GPIO BALL_AF20_IS_GPIO
#endif
#ifndef BALL_A7_IS_GPIO
#define BALL_A7_IS_GPIO 0
#endif
#ifndef PAD_I2S_IN_WS_IS_GPIO
#define PAD_I2S_IN_WS_IS_GPIO BALL_A7_IS_GPIO
#endif
#ifndef BALL_E5_IS_GPIO
#define BALL_E5_IS_GPIO 0
#endif
#ifndef PAD_GPIO_PM0_IS_GPIO
#define PAD_GPIO_PM0_IS_GPIO BALL_E5_IS_GPIO
#endif
#ifndef BALL_F11_IS_GPIO
#define BALL_F11_IS_GPIO 0
#endif
#ifndef PAD_SPDIF_IN_IS_GPIO
#define PAD_SPDIF_IN_IS_GPIO BALL_F11_IS_GPIO
#endif
#ifndef BALL_AF24_IS_GPIO
#define BALL_AF24_IS_GPIO 0
#endif
#ifndef PAD_R_ODD4_IS_GPIO
#define PAD_R_ODD4_IS_GPIO BALL_AF24_IS_GPIO
#endif
#ifndef BALL_G5_IS_GPIO
#define BALL_G5_IS_GPIO 0
#endif
#ifndef PAD_GPIO_PM2_IS_GPIO
#define PAD_GPIO_PM2_IS_GPIO BALL_G5_IS_GPIO
#endif
#ifndef BALL_J2_IS_GPIO
#define BALL_J2_IS_GPIO 0
#endif
#ifndef PAD_DDCA_DA_IS_GPIO
#define PAD_DDCA_DA_IS_GPIO BALL_J2_IS_GPIO
#endif
#ifndef BALL_B11_IS_GPIO
#define BALL_B11_IS_GPIO 0
#endif
#ifndef PAD_ET_TXD1_IS_GPIO
#define PAD_ET_TXD1_IS_GPIO BALL_B11_IS_GPIO
#endif
#ifndef BALL_B2_IS_GPIO
#define BALL_B2_IS_GPIO 0
#endif
#ifndef PAD_DDCDA_CK_IS_GPIO
#define PAD_DDCDA_CK_IS_GPIO BALL_B2_IS_GPIO
#endif
#ifndef BALL_AE16_IS_GPIO
#define BALL_AE16_IS_GPIO 0
#endif
#ifndef PAD_B_ODD0_IS_GPIO
#define PAD_B_ODD0_IS_GPIO BALL_AE16_IS_GPIO
#endif
#define PAD_GPIO_PM5_IS_GPIO 0

// chip capbilities
#define CHIP_HAS_BT656_IN          0
#define CHIP_HAS_TS0               1 // BALL# AB4 AC4 AD5 AA8 Y8 Y9 AB7 AA6 AB6 U4 AC5
#define CHIP_HAS_TS1               1 // BALL# Y13 Y14 AA13 AB13
#define CHIP_HAS_LVDS_10BIT_X2     1
#define CHIP_HAS_LVDS_8BIT_X2      1
#define CHIP_HAS_LVDS_8BIT_X1      1
#define CHIP_HAS_CIMAX             0
#define CHIP_HAS_USB_P0            1
#define CHIP_HAS_USB_P1            1
#define CHIP_HAS_USBVBUS0          1
#define CHIP_HAS_USBVBUS1          1
#define CHIP_HAS_UART1_MODE1       1 // BALL# AB17 AA16
#define CHIP_HAS_UART1_MODE2       1 // BALL# E7 C6
#define CHIP_HAS_UART1_MODE3       1 // BALL# A6 B6
#define CHIP_HAS_PCMCIA1           1
#define CHIP_HAS_PCMCIA2           1
#define CHIP_HAS_PCMCIA            1
#define CHIP_HAS_UART2_MODE1       1 // BALL# W5 V5
#define CHIP_HAS_UART2_MODE2       1 // BALL# D11 F8
#define CHIP_HAS_UART2_MODE3       1 // BALL# F9 F10
#define CHIP_HAS_RGB_A             1 // BALL# P2 R3 R1 P3
#define CHIP_HAS_RGB_B             1 // BALL# L1 L3 K1 L2
#define CHIP_HAS_RGB_C             1 // BALL# V1 V2 U1 V3
#define CHIP_HAS_HDMI_A            1 // BALL# F2 F1 G3 G2 G1 H3 H2 H1 G4 A1 B2
#define CHIP_HAS_HDMI_B            1 // BALL# B1 C3 C2 C1 D3 D2 D1 E3 G4 E1 F3
#define CHIP_HAS_HDMI_C            1 // BALL# AD8 AE8 AF8 AD9 AE9 AF9 AE10 AF10 G4 AE7 AF7
#define CHIP_HAS_SPI_CZ1           1 // BALL# W5 AA10 B8
#define CHIP_HAS_SPI_CZ2           1 // BALL# V5 AA11 E7
#define CHIP_HAS_SPI_CZ3           1 // BALL# A7 C6 AB14
#define CHIP_HAS_DDCR              1 // BALL# AC21 AC20
#define CHIP_HAS_DDCR2             1 // BALL# D11 F8
#define CHIP_HAS_TCON              1 // BALL# AF21 AD20 AD19 AE19 AF20 AE21 AB25 AC23 AB23 AB24 AC26 AE20 AA24 AA25 AB26 AA26 AA23
#define CHIP_HAS_I2S_IN            1 // BALL# A7 B8 C8
#define CHIP_HAS_I2S_OUT           1 // BALL# B7 C7 B7 D8
#define CHIP_HAS_SPDIF_IN          1 // BALL# F11
#define CHIP_HAS_SPDIF_OUT         1 // BALL# E9
#define CHIP_HAS_DDR_A_CMD         1
#define CHIP_HAS_DDR_A_DATA        1
#define CHIP_HAS_DDR_B_CMD         1
#define CHIP_HAS_DDR_B_DATA        1
#define CHIP_USE_PCM_CDN_IN_PCM2   0
#define CHIP_USE_I2S_IN_IN_PCM     0
#define CHIP_USE_I2S_OUT_IN_PCM    0
#define CHIP_USE_SPDIF_IN_IN_PCM   0
#define CHIP_USE_SPDIF_OUT_IN_PCM  0
#define CHIP_USE_IIC_IN_DDCR2      0
#define CHIP_USE_PWM2_IN_GPIO14    0
#define CHIP_USE_PWM3_IN_GPIO15    0

// chip additional information
#define CHIP_FAMILY_TYPE           CHIP_FAMILY_S4LE

#endif /* _MSD3388GV_H_ */
