////////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 2006-2008 MStar Semiconductor, Inc.
// All rights reserved.
//
// Unless otherwise stipulated in writing, any and all information contained
// herein regardless in any format shall remain the sole proprietary of
// MStar Semiconductor Inc. and be kept in strict confidence
// (¡§MStar Confidential Information¡¨) by the recipient.
// Any unauthorized act including without limitation unauthorized disclosure,
// copying, use, reproduction, sale, distribution, modification, disassembling,
// reverse engineering and compiling of the contents of MStar Confidential
// Information is unlawful and strictly prohibited. MStar hereby reserves the
// rights to any and all damages, losses, costs and expenses resulting therefrom.
//
////////////////////////////////////////////////////////////////////////////////

// This file is generated by script, please do not edit it directly
#ifndef _MSD3108EV_H_
#define _MSD3108EV_H_

// PIN number to PAD name mapping
#define BALL_Y23            PAD_GPIO_PM5        // PAD_GPIO_PM5
#define BALL_Y24            PAD_GPIO_PM6        // PAD_GPIO_PM6
#define BALL_AA22           PAD_DDCDB_DA        // PAD_DDCDB_DA//
#define BALL_W22            PAD_HOTPLUGB        // PAD_HOTPLUGB/
#define BALL_Y22            PAD_DDCDB_CK        // PAD_DDCDB_CK
#define BALL_V22            PAD_HOTPLUGA        // PAD_HOTPLUGA
#define BALL_V26            PAD_DDCDA_DA        // PAD_DDCDA_DA
#define BALL_V25            PAD_DDCDA_CK        // PAD_DDCDA_CK
#define BALL_T26            PAD_CVBS7P          // PAD_CVBS7P
#define BALL_T25            PAD_CVBS6P          // PAD_CVBS6P
#define BALL_T23            PAD_CVBS5P          // PAD_CVBS5P
#define BALL_T24            PAD_CVBS4P          // PAD_CVBS4P
#define BALL_N24            PAD_CVBS3P          // PAD_CVBS3P
#define BALL_M25            PAD_CVBS2P          // PAD_CVBS2P
#define BALL_M26            PAD_CVBS1P          // PAD_CVBS1P
#define BALL_L23            PAD_CVBS0P          // PAD_CVBS0P
#define BALL_W24            PAD_DDCA_DA         // PAD_DDCA_DA
#define BALL_W23            PAD_DDCA_CK         // PAD_DDCA_CK
#define BALL_A26            PAD_TS0_D0          // PAD_TS0_D[0]
#define BALL_B26            PAD_TS0_D1          // PAD_TS0_D[1]
#define BALL_C26            PAD_TS0_D2          // PAD_TS0_D[2]
#define BALL_A25            PAD_TS0_D3          // PAD_TS0_D[3]
#define BALL_B25            PAD_TS0_D4          // PAD_TS0_D[4]
#define BALL_C25            PAD_TS0_D5          // PAD_TS0_D[5]
#define BALL_A24            PAD_TS0_D6          // PAD_TS0_D[6]
#define BALL_B24            PAD_TS0_D7          // PAD_TS0_D[7]
#define BALL_A23            PAD_TS0_VLD         // PAD_TS0_VLD
#define BALL_B23            PAD_TS0_SYNC        // PAD_TS0_SYNC
#define BALL_C23            PAD_TS0_CLK         // PAD_TS0_CLK
#define BALL_A22            PAD_PCM_D3          // PCM_D3/CI_D3
#define BALL_B22            PAD_PCM_D4          // PCM_D4/CI_D4
#define BALL_C22            PAD_PCM_D5          // PCM_D5/CI_D5
#define BALL_D22            PAD_PCM_D6          // PCM_D6/CI_D6
#define BALL_A21            PAD_PCM_D7          // PCM_D7/CI_D7
#define BALL_B21            PAD_PCM_CE_N        // PCM_CE_N/CI_CS
#define BALL_C21            PAD_PCM_A10         // PCM_A10/CI_A10
#define BALL_D21            PAD_PCM_OE_N        // PCM_OE_N
#define BALL_A20            PAD_PCM_A11         // PCM_A11/CI_A11
#define BALL_B20            PAD_PCM_IORD_N      // PCM_IORD_N/CI_RD
#define BALL_C20            PAD_PCM_A9          // PCM_A9/CI_A9
#define BALL_D20            PAD_PCM_IOWR_N      // PCM_IOWR_N/CI_WR
#define BALL_E20            PAD_PCM_A8          // PCM_A8/CI_A8
#define BALL_F20            PAD_PCM_A13         // PCM_A9/CI_A13
#define BALL_A19            PAD_PCM_A14         // PCM_A14/CI_A14
#define BALL_B19            PAD_PCM_WE_N        // PCM_WE_N
#define BALL_C19            PAD_PCM_IRQA_N      // PCM_IRQA_N/CI_INT
#define BALL_D19            PAD_PCM_A12         // PCM_A12/CI_A12
#define BALL_A18            PAD_PCM_A7          // PCM_A7/CI_A7
#define BALL_B18            PAD_PCM_A6          // PCM_A6/CI_A6
#define BALL_E19            PAD_PCM_A5          // PCM_A5/CI_A5
#define BALL_E18            PAD_PCM_WAIT_N      // PCM_WAIT_N/CI_WACK
#define BALL_D17            PAD_PCM_A4          // PCM_A4/CI_A4
#define BALL_A17            PAD_PCM2_CE_N       // Jupiter GPIO
#define BALL_B17            PAD_PCM2_IRQA_N     // Jupiter GPIO
#define BALL_C17            PAD_PCM2_WAIT_N     // Jupiter GPIO
#define BALL_A16            PAD_UART_RX2        // PAD_UART_RX2
#define BALL_B16            PAD_UART_TX2        // PAD_UART_TX2
#define BALL_C16            PAD_PF_AD15         // PAD_PF_AD[15]
#define BALL_A15            PAD_PF_ALE          // PAD_PF_ALE
#define BALL_B15            PAD_PF_CE0Z         // PAD_PF_CE0Z
#define BALL_C15            PAD_PF_CE1Z         // PAD_PF_CE1Z
#define BALL_A14            PAD_PF_OEZ          // PAD_PF_OEZ
#define BALL_B14            PAD_PF_WEZ          // PAD_PF_WEZ
#define BALL_D14            PAD_F_RBZ           // PAD_F_RBZ
#define BALL_E13            PAD_DDCDC_CK        // PAD_DDCDC_CK
#define BALL_C14            PAD_DDCDC_DA        // PAD_DDCDC_DA
#define BALL_C13            PAD_HOTPLUGC        // PAD_HOTPLUGC
#define BALL_C8             PAD_SPI_CK          // PAD_SPI_CK
#define BALL_A7             PAD_SPI_DI          // PAD_SPI_DI
#define BALL_B7             PAD_SPI_DO          // PAD_SPI_DO
#define BALL_C7             PAD_SPI_CZ          // PAD_SPI_CZ
#define BALL_A6             PAD_PWM0            // PAD_PWM0
#define BALL_B6             PAD_PWM1            // PAD_PWM1
#define BALL_A5             PAD_PWM2            // PAD_PWM2
#define BALL_B5             PAD_PWM3            // PAD_PWM3
#define BALL_B4             PAD_DDCR_DAT        // PAD_DDCR_DA
#define BALL_A4             PAD_DDCR_CLK        // PAD_DDCR_CK
#define BALL_A3             PAD_B_ODD0          // PAD_B_ODD[0]
#define BALL_A2             PAD_B_ODD1          // PAD_B_ODD[1]
#define BALL_A1             PAD_B_ODD2          // PAD_B_ODD[2]
#define BALL_B3             PAD_B_ODD3          // PAD_B_ODD[3]
#define BALL_B2             PAD_B_ODD4          // PAD_B_ODD[4]
#define BALL_B1             PAD_B_ODD5          // PAD_B_ODD[5]
#define BALL_C3             PAD_B_ODD6          // PAD_B_ODD[6]
#define BALL_C2             PAD_B_ODD7          // PAD_B_ODD[7]
#define BALL_C1             PAD_G_ODD0          // PAD_G_ODD[0]
#define BALL_D3             PAD_G_ODD1          // PAD_G_ODD[1]
#define BALL_D2             PAD_G_ODD2          // PAD_G_ODD[2]
#define BALL_D1             PAD_G_ODD3          // PAD_G_ODD[3]
#define BALL_E3             PAD_G_ODD4          // PAD_G_ODD[4]
#define BALL_E2             PAD_G_ODD5          // PAD_G_ODD[5]
#define BALL_E1             PAD_G_ODD6          // PAD_G_ODD[6]
#define BALL_F3             PAD_G_ODD7          // PAD_G_ODD[7]
#define BALL_F2             PAD_R_ODD0          // PAD_R_ODD[0]
#define BALL_F1             PAD_R_ODD1          // PAD_R_ODD[1]
#define BALL_G3             PAD_R_ODD2          // PAD_R_ODD[2]
#define BALL_G2             PAD_R_ODD3          // PAD_R_ODD[3]
#define BALL_G1             PAD_R_ODD4          // PAD_R_ODD[4]
#define BALL_H3             PAD_R_ODD5          // PAD_R_ODD[5]
#define BALL_H2             PAD_R_ODD6          // PAD_R_ODD[6]
#define BALL_H1             PAD_R_ODD7          // PAD_R_ODD[7]
#define BALL_E5             PAD_LCK             // PAD_LCK/Jupiter GPIO
#define BALL_E4             PAD_LDE             // PAD_LDE/Jupiter GPIO
#define BALL_F5             PAD_LHSYNC          // PAD_LHSYNC/Jupiter GPIO
#define BALL_F4             PAD_LVSYNC          // PAD_LVSYNC/Jupiter GPIO
#define BALL_G5             PAD_PCM_A3          // PAD_PCM_A3/CI_A3
#define BALL_G4             PAD_PCM_A2          // PAD_PCM_A2/CI_A2
#define BALL_H5             PAD_PCM_REG_N       // PAD_PCM_REG_N/CI_CLK
#define BALL_H4             PAD_PCM_A1          // PAD_PCM_A1/CI_A1
#define BALL_J5             PAD_PCM_A0          // PAD_PCM_A0/CI_A0
#define BALL_K5             PAD_PCM_D0          // PAD_PCM_D0/CI_D0
#define BALL_J1             PAD_PCM_D1          // PAD_PCM_D1/CI_D1
#define BALL_J2             PAD_PCM_D2          // PAD_PCM_D2/CI_D2
#define BALL_J4             PAD_PCM_RESET       // CI_RESET
#define BALL_K1             PAD_PCM2_RESET      // Jupiter GPIO
#define BALL_K2             PAD_PCM_CD_N        // CI_CD
#define BALL_K3             PAD_PCM2_CD_N       // Jupiter GPIO
#define BALL_K4             PAD_TS1_D0          // PAD_TS1_D0
#define BALL_L3             PAD_TS1_VLD         // PAD_TS1_VLD
#define BALL_L4             PAD_TS1_SYNC        // PAD_TS1_SYNC
#define BALL_M4             PAD_TS1_CLK         // PAD_TS1_CLK
#define BALL_AD6            PAD_ET_COL          // PAD_ET_COL
#define BALL_AE6            PAD_ET_TXD1         // PAD_ET_TXD1
#define BALL_AF6            PAD_ET_TXD0         // PAD_ET_TXD0
#define BALL_AE7            PAD_ET_TX_EN        // PAD_ET_TX_EN
#define BALL_AF7            PAD_ET_TX_CLK       // PAD_ET_TX_CLK
#define BALL_AA10           PAD_ET_RXD0         // PAD_ET_RXD0
#define BALL_AD8            PAD_I2S_IN_WS       // PAD_I2S_IN_WS/Jupiter GPIO
#define BALL_AE8            PAD_I2S_IN_BCK      // PAD_I2S_IN_BCK/Jupiter GPIO
#define BALL_AF8            PAD_I2S_IN_SD       // PAD_I2S_IN_SD
#define BALL_AD9            PAD_SPDIF_IN        // PAD_SPDIF_IN
#define BALL_AC9            PAD_I2S_OUT_MCK     // PAD_I2S_OUT_MCK
#define BALL_AB9            PAD_I2S_OUT_WS      // PAD_I2S_OUT_WS
#define BALL_AB10           PAD_ET_CRS          // Jupiter GPIO
#define BALL_AC10           PAD_ET_TXD3         // Jupiter GPIO
#define BALL_AA11           PAD_I2S_OUT_BCK     // PAD_I2S_OUT_BCK
#define BALL_AB11           PAD_ET_TXD2         // Jupiter GPIO
#define BALL_AC11           PAD_I2S_OUT_SD      // PAD_I2S_OUT_SD
#define BALL_AA18           PAD_ET_TXER         // Jupiter GPIO
#define BALL_AB12           PAD_SPDIF_OUT       // PAD_SPDIF_OUT
#define BALL_AA12           PAD_ET_RXER         // Jupiter GPIO
#define BALL_AB13           PAD_DDCR_DA2        // UART_RX2/PAD_SDAM
#define BALL_AA13           PAD_ET_RX_CLK       // Jupiter GPIO
#define BALL_AA14           PAD_DDCR_CK2        // UART_TX2/PAD_SCKM
#define BALL_AB15           PAD_ET_RX_DV        // Jupiter GPIO
#define BALL_AA15           PAD_LHSYNC2         // PAD_I2S_OUT_MUTE/
#define BALL_AC16           PAD_LVSYNC2         // Jupiter GPIO/UART_TX1
#define BALL_AB16           PAD_ET_RXD1         // PAD_ET_RXD1
#define BALL_AA16           PAD_GPIO12          // UART_RX2/Jupiter GPIO
#define BALL_AC17           PAD_ET_RXD2         // Jupiter GPIO
#define BALL_AB17           PAD_GPIO13          // UART_TX2/Jupiter GPIO
#define BALL_AA17           PAD_ET_RXD3         // Jupiter GPIO
#define BALL_AB18           PAD_GPIO14          // UART_RX1/Jupiter GPIO
#define BALL_AC19           PAD_ET_MDC          // PAD_ET_MDC
#define BALL_AB21           PAD_GPIO15          // UART_TX1/Jupiter GPIO
#define BALL_AC18           PAD_ET_MDIO         // PAD_ET_MDIO
#define BALL_AC23           PAD_GPIO_PM0        // PAD_GPIO_PM0
#define BALL_AB23           PAD_GPIO_PM1        // PAD_GPIO_PM1
#define BALL_AC24           PAD_GPIO_PM2        // PAD_GPIO_PM2
#define BALL_AB24           PAD_GPIO_PM3        // PAD_GPIO_PM3
#define BALL_AA24           PAD_GPIO_PM4        // PAD_GPIO_PM4

// PAD name to index
#define PAD_NC              9999
#define PAD_GND             0

#define PAD_GPIO_PM7        1
#define PAD_GPIO_PM8        2
#define PAD_GPIO_PM9        3
#define PAD_GPIO_PM10       4
#define PAD_GPIO_PM5        5
#define PAD_GPIO_PM6        6
#define PAD_DDCDB_DA        15
#define PAD_HOTPLUGB        18
#define PAD_DDCDB_CK        23
#define PAD_HOTPLUGA        32
#define PAD_DDCDA_DA        34
#define PAD_DDCDA_CK        35
#define PAD_CVBS7P          59
#define PAD_CVBS6P          60
#define PAD_CVBS5P          61
#define PAD_CVBS4P          62
#define PAD_CVBS3P          64
#define PAD_CVBS2P          65
#define PAD_CVBS1P          66
#define PAD_CVBS0P          68
#define PAD_DDCA_DA         76
#define PAD_DDCA_CK         77
#define PAD_TS0_D0          112
#define PAD_TS0_D1          113
#define PAD_TS0_D2          114
#define PAD_TS0_D3          115
#define PAD_TS0_D4          116
#define PAD_TS0_D5          117
#define PAD_TS0_D6          118
#define PAD_TS0_D7          119
#define PAD_TS0_VLD         120
#define PAD_TS0_SYNC        121
#define PAD_TS0_CLK         122
#define PAD_PCM_D3          123
#define PAD_PCM_D4          124
#define PAD_PCM_D5          125
#define PAD_PCM_D6          126
#define PAD_PCM_D7          127
#define PAD_PCM_CE_N        128
#define PAD_PCM_A10         129
#define PAD_PCM_OE_N        130
#define PAD_PCM_A11         131
#define PAD_PCM_IORD_N      132
#define PAD_PCM_A9          133
#define PAD_PCM_IOWR_N      134
#define PAD_PCM_A8          135
#define PAD_PCM_A13         136
#define PAD_PCM_A14         137
#define PAD_PCM_WE_N        138
#define PAD_PCM_IRQA_N      139
#define PAD_PCM_A12         140
#define PAD_PCM_A7          141
#define PAD_PCM_A6          142
#define PAD_PCM_A5          143
#define PAD_PCM_WAIT_N      144
#define PAD_PCM_A4          145
#define PAD_PCM2_CE_N       146
#define PAD_PCM2_IRQA_N     147
#define PAD_PCM2_WAIT_N     148
#define PAD_UART_RX2        149
#define PAD_UART_TX2        150
#define PAD_PF_AD15         151
#define PAD_PF_ALE          152
#define PAD_PF_CE0Z         153
#define PAD_PF_CE1Z         154
#define PAD_PF_OEZ          155
#define PAD_PF_WEZ          156
#define PAD_F_RBZ           157
#define PAD_DDCDC_CK        158
#define PAD_DDCDC_DA        161
#define PAD_HOTPLUGC        168
#define PAD_SPI_CK          169
#define PAD_SPI_DI          170
#define PAD_SPI_DO          171
#define PAD_SPI_CZ          172
#define PAD_PWM0            173
#define PAD_PWM1            174
#define PAD_PWM2            175
#define PAD_PWM3            176
#define PAD_DDCR_DAT        177
#define PAD_DDCR_CLK        178
#define PAD_B_ODD0          179
#define PAD_B_ODD1          180
#define PAD_B_ODD2          181
#define PAD_B_ODD3          182
#define PAD_B_ODD4          183
#define PAD_B_ODD5          184
#define PAD_B_ODD6          185
#define PAD_B_ODD7          186
#define PAD_G_ODD0          187
#define PAD_G_ODD1          188
#define PAD_G_ODD2          189
#define PAD_G_ODD3          190
#define PAD_G_ODD4          191
#define PAD_G_ODD5          192
#define PAD_G_ODD6          193
#define PAD_G_ODD7          194
#define PAD_R_ODD0          195
#define PAD_R_ODD1          196
#define PAD_R_ODD2          197
#define PAD_R_ODD3          198
#define PAD_R_ODD4          199
#define PAD_R_ODD5          200
#define PAD_R_ODD6          201
#define PAD_R_ODD7          202
#define PAD_LCK             203
#define PAD_LDE             204
#define PAD_LHSYNC          205
#define PAD_LVSYNC          206
#define PAD_PCM_A3          207
#define PAD_PCM_A2          208
#define PAD_PCM_REG_N       209
#define PAD_PCM_A1          210
#define PAD_PCM_A0          211
#define PAD_PCM_D0          212
#define PAD_PCM_D1          213
#define PAD_PCM_D2          214
#define PAD_PCM_RESET       215
#define PAD_PCM2_RESET      216
#define PAD_PCM_CD_N        217
#define PAD_PCM2_CD_N       218
#define PAD_TS1_D0          219
#define PAD_TS1_VLD         220
#define PAD_TS1_SYNC        221
#define PAD_TS1_CLK         222
#define PAD_ET_COL          329
#define PAD_ET_TXD1         330
#define PAD_ET_TXD0         331
#define PAD_ET_TX_EN        332
#define PAD_ET_TX_CLK       333
#define PAD_ET_RXD0         334
#define PAD_I2S_IN_WS       335
#define PAD_I2S_IN_BCK      336
#define PAD_I2S_IN_SD       337
#define PAD_SPDIF_IN        338
#define PAD_I2S_OUT_MCK     339
#define PAD_I2S_OUT_WS      340
#define PAD_ET_CRS          341
#define PAD_ET_TXD3         342
#define PAD_I2S_OUT_BCK     343
#define PAD_ET_TXD2         344
#define PAD_I2S_OUT_SD      345
#define PAD_ET_TXER         346
#define PAD_SPDIF_OUT       347
#define PAD_ET_RXER         348
#define PAD_DDCR_DA2        349
#define PAD_ET_RX_CLK       350
#define PAD_DDCR_CK2        351
#define PAD_ET_RX_DV        352
#define PAD_LHSYNC2         353
#define PAD_LVSYNC2         354
#define PAD_ET_RXD1         355
#define PAD_GPIO12          356
#define PAD_ET_RXD2         357
#define PAD_GPIO13          358
#define PAD_ET_RXD3         359
#define PAD_GPIO14          360
#define PAD_ET_MDC          361
#define PAD_GPIO15          362
#define PAD_ET_MDIO         363
#define PAD_GPIO_PM0        376
#define PAD_GPIO_PM1        377
#define PAD_GPIO_PM2        378
#define PAD_GPIO_PM3        379
#define PAD_GPIO_PM4        380

// PADS group name to index
#define PADS_DDCR           382
#define PADS_DDCR2          383
#define PADS_TS0            384
#define PADS_TS1            385
#define PADS_GPIO1_GPIO2    386
#define PADS_LHSYNC2_LVSYNC2 387
#define PADS_PCI_AD20_AD21  388
#define PADS_PCI            389
#define PADS_PCM            389
#define PADS_SAR            390
#define PADS_DOUT           391
#define PADS_DIN            392
#define PADS_ATCON_MODE1    393
#define PADS_ATCON_MODE2    394
#define PADS_DTCON_MODE1    395
#define PADS_FCIE_CONFIG1   396
#define PADS_FCIE_CONFIG2   397
#define PADS_I2S            398
#define PADS_PF             399
#define PADS_EMAC           400
#define PADS_UART1_MODE1    401
#define PADS_UART1_MODE2    402
#define PADS_UART1_MODE3    403
#define PADS_UART2_MODE1    404
#define PADS_UART2_MODE2    405
#define PADS_UART2_MODE3    406
#define PADS_WF_MODE1       407
#define PADS_WF_MODE2       408
#define PADS_WF_MODE3       409
#define PADS_ET_MODE0       410
#define PADS_ET_MODE1       411
#define PADS_ET_MODE2       412

// PAD index to GPIO number mapping
#define GPIO_PAD_342        GPIO90
#define GPIO_PAD_161        GPIO_DDCD2_SDA
#define GPIO_PAD_168        GPIO_HPDC
#define GPIO_PAD_353        GPIO78
#define GPIO_PAD_136        GPIO33
#define GPIO_PAD_134        GPIO31
#define GPIO_PAD_198        GPIO125
#define GPIO_PAD_181        GPIO108
#define GPIO_PAD_128        GPIO25
#define GPIO_PAD_114        GPIO4
#define GPIO_PAD_139        GPIO35
#define GPIO_PAD_117        GPIO7
#define GPIO_PAD_350        GPIO98
#define GPIO_PAD_170        GPIO81
#define GPIO_PAD_175        GPIO47
#define GPIO_PAD_357        GPIO102
#define GPIO_PAD_116        GPIO6
#define GPIO_PAD_129        GPIO26
#define GPIO_PAD_185        GPIO112
#define GPIO_PAD_172        GPIO82
#define GPIO_PAD_341        GPIO88
#define GPIO_PAD_112        GPIO2
#define GPIO_PAD_188        GPIO115
#define GPIO_PAD_348        GPIO97
#define GPIO_PAD_370        GPIO146
#define GPIO_PAD_361        GPIO104
#define GPIO_PAD_77         GPIO_DDCA0_SCL
#define GPIO_PAD_219        GPIO63
#define GPIO_PAD_121        GPIO11
#define GPIO_PAD_125        GPIO22
#define GPIO_PAD_18         GPIO_HPDB
#define GPIO_PAD_329        GPIO89
#define GPIO_PAD_336        GPIO68
#define GPIO_PAD_156        GPIO17
#define GPIO_PAD_372        GPIO148
#define GPIO_PAD_221        GPIO65
#define GPIO_PAD_214        GPIO58
#define GPIO_PAD_349        GPIO76
#define GPIO_PAD_220        GPIO64
#define GPIO_PAD_148        GPIO44
#define GPIO_PAD_195        GPIO122
#define GPIO_PAD_363        GPIO105
#define GPIO_PAD_23         GPIO_DDCD1_SCL
#define GPIO_PAD_189        GPIO116
#define GPIO_PAD_207        GPIO51
#define GPIO_PAD_332        GPIO94
#define GPIO_PAD_147        GPIO43
#define GPIO_PAD_140        GPIO36
#define GPIO_PAD_204        GPIO131
#define GPIO_PAD_358        GPIO85
#define GPIO_PAD_205        GPIO132
#define GPIO_PAD_120        GPIO10
#define GPIO_PAD_154        GPIO15
#define GPIO_PAD_380        GPIO138
#define GPIO_PAD_192        GPIO119
#define GPIO_PAD_346        GPIO96
#define GPIO_PAD_351        GPIO77
#define GPIO_PAD_173        GPIO45
#define GPIO_PAD_176        GPIO48
#define GPIO_PAD_127        GPIO24
#define GPIO_PAD_333        GPIO95
#define GPIO_PAD_142        GPIO38
#define GPIO_PAD_331        GPIO93
#define GPIO_PAD_362        GPIO87
#define GPIO_PAD_211        GPIO55
#define GPIO_PAD_143        GPIO39
#define GPIO_PAD_377        GPIO135
#define GPIO_PAD_200        GPIO127
#define GPIO_PAD_6          GPIO140
#define GPIO_PAD_187        GPIO114
#define GPIO_PAD_130        GPIO27
#define GPIO_PAD_118        GPIO8
#define GPIO_PAD_356        GPIO84
#define GPIO_PAD_115        GPIO5
#define GPIO_PAD_133        GPIO30
#define GPIO_PAD_194        GPIO121
#define GPIO_PAD_345        GPIO74
#define GPIO_PAD_359        GPIO103
#define GPIO_PAD_155        GPIO16
#define GPIO_PAD_184        GPIO111
#define GPIO_PAD_158        GPIO_DDCD2_SCL
#define GPIO_PAD_212        GPIO56
#define GPIO_PAD_15         GPIO_DDCD1_SDA
#define GPIO_PAD_180        GPIO107
#define GPIO_PAD_373        GPIO149
#define GPIO_PAD_132        GPIO29
#define GPIO_PAD_337        GPIO69
#define GPIO_PAD_34         GPIO_DDCD0_SDA
#define GPIO_PAD_354        GPIO79
#define GPIO_PAD_343        GPIO73
#define GPIO_PAD_340        GPIO72
#define GPIO_PAD_202        GPIO129
#define GPIO_PAD_213        GPIO57
#define GPIO_PAD_191        GPIO118
#define GPIO_PAD_137        GPIO34
#define GPIO_PAD_334        GPIO100
#define GPIO_PAD_344        GPIO91
#define GPIO_PAD_123        GPIO20
#define GPIO_PAD_218        GPIO62
#define GPIO_PAD_122        GPIO12
#define GPIO_PAD_149        GPIO0
#define GPIO_PAD_126        GPIO23
#define GPIO_PAD_171        GPIO83
#define GPIO_PAD_152        GPIO18
#define GPIO_PAD_355        GPIO101
#define GPIO_PAD_183        GPIO110
#define GPIO_PAD_208        GPIO52
#define GPIO_PAD_144        GPIO40
#define GPIO_PAD_222        GPIO66
#define GPIO_PAD_157        GPIO19
#define GPIO_PAD_131        GPIO28
#define GPIO_PAD_145        GPIO41
#define GPIO_PAD_151        GPIO13
#define GPIO_PAD_196        GPIO123
#define GPIO_PAD_371        GPIO147
#define GPIO_PAD_206        GPIO133
#define GPIO_PAD_146        GPIO42
#define GPIO_PAD_32         GPIO_HPDA
#define GPIO_PAD_150        GPIO1
#define GPIO_PAD_113        GPIO3
#define GPIO_PAD_360        GPIO86
#define GPIO_PAD_190        GPIO117
#define GPIO_PAD_201        GPIO128
#define GPIO_PAD_217        GPIO61
#define GPIO_PAD_178        GPIO50
#define GPIO_PAD_209        GPIO53
#define GPIO_PAD_153        GPIO14
#define GPIO_PAD_124        GPIO21
#define GPIO_PAD_193        GPIO120
#define GPIO_PAD_186        GPIO113
#define GPIO_PAD_174        GPIO46
#define GPIO_PAD_216        GPIO60
#define GPIO_PAD_339        GPIO71
#define GPIO_PAD_119        GPIO9
#define GPIO_PAD_182        GPIO109
#define GPIO_PAD_197        GPIO124
#define GPIO_PAD_169        GPIO80
#define GPIO_PAD_215        GPIO59
#define GPIO_PAD_210        GPIO54
#define GPIO_PAD_141        GPIO37
#define GPIO_PAD_203        GPIO130
#define GPIO_PAD_347        GPIO75
#define GPIO_PAD_379        GPIO137
#define GPIO_PAD_352        GPIO99
#define GPIO_PAD_135        GPIO32
#define GPIO_PAD_177        GPIO49
#define GPIO_PAD_335        GPIO67
#define GPIO_PAD_376        GPIO134
#define GPIO_PAD_338        GPIO70
#define GPIO_PAD_199        GPIO126
#define GPIO_PAD_378        GPIO136
#define GPIO_PAD_76         GPIO_DDCA0_SDA
#define GPIO_PAD_330        GPIO92
#define GPIO_PAD_35         GPIO_DDCD0_SCL
#define GPIO_PAD_179        GPIO106
#define GPIO_PAD_5          GPIO139
#define GPIO_PAD_9999       GPIO_NC

// default GPIO setting
#ifndef BALL_AC10_IS_GPIO
#define BALL_AC10_IS_GPIO 0
#endif
#ifndef PAD_ET_TXD3_IS_GPIO
#define PAD_ET_TXD3_IS_GPIO BALL_AC10_IS_GPIO
#endif
#ifndef BALL_C14_IS_GPIO
#define BALL_C14_IS_GPIO 0
#endif
#ifndef PAD_DDCDC_DA_IS_GPIO
#define PAD_DDCDC_DA_IS_GPIO BALL_C14_IS_GPIO
#endif
#ifndef BALL_C13_IS_GPIO
#define BALL_C13_IS_GPIO 0
#endif
#ifndef PAD_HOTPLUGC_IS_GPIO
#define PAD_HOTPLUGC_IS_GPIO BALL_C13_IS_GPIO
#endif
#ifndef BALL_AA15_IS_GPIO
#define BALL_AA15_IS_GPIO 0
#endif
#ifndef PAD_LHSYNC2_IS_GPIO
#define PAD_LHSYNC2_IS_GPIO BALL_AA15_IS_GPIO
#endif
#ifndef BALL_F20_IS_GPIO
#define BALL_F20_IS_GPIO 0
#endif
#ifndef PAD_PCM_A13_IS_GPIO
#define PAD_PCM_A13_IS_GPIO BALL_F20_IS_GPIO
#endif
#ifndef BALL_D20_IS_GPIO
#define BALL_D20_IS_GPIO 0
#endif
#ifndef PAD_PCM_IOWR_N_IS_GPIO
#define PAD_PCM_IOWR_N_IS_GPIO BALL_D20_IS_GPIO
#endif
#ifndef BALL_G2_IS_GPIO
#define BALL_G2_IS_GPIO 0
#endif
#ifndef PAD_R_ODD3_IS_GPIO
#define PAD_R_ODD3_IS_GPIO BALL_G2_IS_GPIO
#endif
#define PAD_GPIO_PM9_IS_GPIO 0
#ifndef BALL_A1_IS_GPIO
#define BALL_A1_IS_GPIO 0
#endif
#ifndef PAD_B_ODD2_IS_GPIO
#define PAD_B_ODD2_IS_GPIO BALL_A1_IS_GPIO
#endif
#ifndef BALL_B21_IS_GPIO
#define BALL_B21_IS_GPIO 0
#endif
#ifndef PAD_PCM_CE_N_IS_GPIO
#define PAD_PCM_CE_N_IS_GPIO BALL_B21_IS_GPIO
#endif
#ifndef BALL_C26_IS_GPIO
#define BALL_C26_IS_GPIO 0
#endif
#ifndef PAD_TS0_D2_IS_GPIO
#define PAD_TS0_D2_IS_GPIO BALL_C26_IS_GPIO
#endif
#ifndef BALL_C19_IS_GPIO
#define BALL_C19_IS_GPIO 0
#endif
#ifndef PAD_PCM_IRQA_N_IS_GPIO
#define PAD_PCM_IRQA_N_IS_GPIO BALL_C19_IS_GPIO
#endif
#ifndef BALL_C25_IS_GPIO
#define BALL_C25_IS_GPIO 0
#endif
#ifndef PAD_TS0_D5_IS_GPIO
#define PAD_TS0_D5_IS_GPIO BALL_C25_IS_GPIO
#endif
#ifndef BALL_AA13_IS_GPIO
#define BALL_AA13_IS_GPIO 0
#endif
#ifndef PAD_ET_RX_CLK_IS_GPIO
#define PAD_ET_RX_CLK_IS_GPIO BALL_AA13_IS_GPIO
#endif
#ifndef BALL_A7_IS_GPIO
#define BALL_A7_IS_GPIO 0
#endif
#ifndef PAD_SPI_DI_IS_GPIO
#define PAD_SPI_DI_IS_GPIO BALL_A7_IS_GPIO
#endif
#ifndef BALL_A5_IS_GPIO
#define BALL_A5_IS_GPIO 0
#endif
#ifndef PAD_PWM2_IS_GPIO
#define PAD_PWM2_IS_GPIO BALL_A5_IS_GPIO
#endif
#ifndef BALL_AC17_IS_GPIO
#define BALL_AC17_IS_GPIO 0
#endif
#ifndef PAD_ET_RXD2_IS_GPIO
#define PAD_ET_RXD2_IS_GPIO BALL_AC17_IS_GPIO
#endif
#ifndef BALL_B25_IS_GPIO
#define BALL_B25_IS_GPIO 0
#endif
#ifndef PAD_TS0_D4_IS_GPIO
#define PAD_TS0_D4_IS_GPIO BALL_B25_IS_GPIO
#endif
#ifndef BALL_C21_IS_GPIO
#define BALL_C21_IS_GPIO 0
#endif
#ifndef PAD_PCM_A10_IS_GPIO
#define PAD_PCM_A10_IS_GPIO BALL_C21_IS_GPIO
#endif
#ifndef BALL_C3_IS_GPIO
#define BALL_C3_IS_GPIO 0
#endif
#ifndef PAD_B_ODD6_IS_GPIO
#define PAD_B_ODD6_IS_GPIO BALL_C3_IS_GPIO
#endif
#ifndef BALL_C7_IS_GPIO
#define BALL_C7_IS_GPIO 0
#endif
#ifndef PAD_SPI_CZ_IS_GPIO
#define PAD_SPI_CZ_IS_GPIO BALL_C7_IS_GPIO
#endif
#ifndef BALL_AB10_IS_GPIO
#define BALL_AB10_IS_GPIO 0
#endif
#ifndef PAD_ET_CRS_IS_GPIO
#define PAD_ET_CRS_IS_GPIO BALL_AB10_IS_GPIO
#endif
#define PAD_GPIO_PM7_IS_GPIO 0
#ifndef BALL_A26_IS_GPIO
#define BALL_A26_IS_GPIO 0
#endif
#ifndef PAD_TS0_D0_IS_GPIO
#define PAD_TS0_D0_IS_GPIO BALL_A26_IS_GPIO
#endif
#ifndef BALL_D3_IS_GPIO
#define BALL_D3_IS_GPIO 0
#endif
#ifndef PAD_G_ODD1_IS_GPIO
#define PAD_G_ODD1_IS_GPIO BALL_D3_IS_GPIO
#endif
#ifndef BALL_AA12_IS_GPIO
#define BALL_AA12_IS_GPIO 0
#endif
#ifndef PAD_ET_RXER_IS_GPIO
#define PAD_ET_RXER_IS_GPIO BALL_AA12_IS_GPIO
#endif
#ifndef BALL_AD22_IS_GPIO
#define BALL_AD22_IS_GPIO 0
#endif
#ifndef PAD_SAR0_IS_GPIO
#define PAD_SAR0_IS_GPIO BALL_AD22_IS_GPIO
#endif
#ifndef BALL_AC19_IS_GPIO
#define BALL_AC19_IS_GPIO 0
#endif
#ifndef PAD_ET_MDC_IS_GPIO
#define PAD_ET_MDC_IS_GPIO BALL_AC19_IS_GPIO
#endif
#ifndef BALL_W23_IS_GPIO
#define BALL_W23_IS_GPIO 0
#endif
#ifndef PAD_DDCA_CK_IS_GPIO
#define PAD_DDCA_CK_IS_GPIO BALL_W23_IS_GPIO
#endif
#ifndef BALL_K4_IS_GPIO
#define BALL_K4_IS_GPIO 0
#endif
#ifndef PAD_TS1_D0_IS_GPIO
#define PAD_TS1_D0_IS_GPIO BALL_K4_IS_GPIO
#endif
#ifndef BALL_B23_IS_GPIO
#define BALL_B23_IS_GPIO 0
#endif
#ifndef PAD_TS0_SYNC_IS_GPIO
#define PAD_TS0_SYNC_IS_GPIO BALL_B23_IS_GPIO
#endif
#ifndef BALL_C22_IS_GPIO
#define BALL_C22_IS_GPIO 0
#endif
#ifndef PAD_PCM_D5_IS_GPIO
#define PAD_PCM_D5_IS_GPIO BALL_C22_IS_GPIO
#endif
#ifndef BALL_W22_IS_GPIO
#define BALL_W22_IS_GPIO 0
#endif
#ifndef PAD_HOTPLUGB_IS_GPIO
#define PAD_HOTPLUGB_IS_GPIO BALL_W22_IS_GPIO
#endif
#ifndef BALL_AD6_IS_GPIO
#define BALL_AD6_IS_GPIO 0
#endif
#ifndef PAD_ET_COL_IS_GPIO
#define PAD_ET_COL_IS_GPIO BALL_AD6_IS_GPIO
#endif
#ifndef BALL_AE8_IS_GPIO
#define BALL_AE8_IS_GPIO 0
#endif
#ifndef PAD_I2S_IN_BCK_IS_GPIO
#define PAD_I2S_IN_BCK_IS_GPIO BALL_AE8_IS_GPIO
#endif
#ifndef BALL_B14_IS_GPIO
#define BALL_B14_IS_GPIO 0
#endif
#ifndef PAD_PF_WEZ_IS_GPIO
#define PAD_PF_WEZ_IS_GPIO BALL_B14_IS_GPIO
#endif
#ifndef BALL_AE23_IS_GPIO
#define BALL_AE23_IS_GPIO 0
#endif
#ifndef PAD_SAR2_IS_GPIO
#define PAD_SAR2_IS_GPIO BALL_AE23_IS_GPIO
#endif
#ifndef BALL_L4_IS_GPIO
#define BALL_L4_IS_GPIO 0
#endif
#ifndef PAD_TS1_SYNC_IS_GPIO
#define PAD_TS1_SYNC_IS_GPIO BALL_L4_IS_GPIO
#endif
#ifndef BALL_J2_IS_GPIO
#define BALL_J2_IS_GPIO 0
#endif
#ifndef PAD_PCM_D2_IS_GPIO
#define PAD_PCM_D2_IS_GPIO BALL_J2_IS_GPIO
#endif
#ifndef BALL_AB13_IS_GPIO
#define BALL_AB13_IS_GPIO 0
#endif
#ifndef PAD_DDCR_DA2_IS_GPIO
#define PAD_DDCR_DA2_IS_GPIO BALL_AB13_IS_GPIO
#endif
#ifndef BALL_L3_IS_GPIO
#define BALL_L3_IS_GPIO 0
#endif
#ifndef PAD_TS1_VLD_IS_GPIO
#define PAD_TS1_VLD_IS_GPIO BALL_L3_IS_GPIO
#endif
#ifndef BALL_C17_IS_GPIO
#define BALL_C17_IS_GPIO 0
#endif
#ifndef PAD_PCM2_WAIT_N_IS_GPIO
#define PAD_PCM2_WAIT_N_IS_GPIO BALL_C17_IS_GPIO
#endif
#ifndef BALL_F2_IS_GPIO
#define BALL_F2_IS_GPIO 0
#endif
#ifndef PAD_R_ODD0_IS_GPIO
#define PAD_R_ODD0_IS_GPIO BALL_F2_IS_GPIO
#endif
#ifndef BALL_AC18_IS_GPIO
#define BALL_AC18_IS_GPIO 0
#endif
#ifndef PAD_ET_MDIO_IS_GPIO
#define PAD_ET_MDIO_IS_GPIO BALL_AC18_IS_GPIO
#endif
#ifndef BALL_Y22_IS_GPIO
#define BALL_Y22_IS_GPIO 0
#endif
#ifndef PAD_DDCDB_CK_IS_GPIO
#define PAD_DDCDB_CK_IS_GPIO BALL_Y22_IS_GPIO
#endif
#ifndef BALL_D2_IS_GPIO
#define BALL_D2_IS_GPIO 0
#endif
#ifndef PAD_G_ODD2_IS_GPIO
#define PAD_G_ODD2_IS_GPIO BALL_D2_IS_GPIO
#endif
#ifndef BALL_G5_IS_GPIO
#define BALL_G5_IS_GPIO 0
#endif
#ifndef PAD_PCM_A3_IS_GPIO
#define PAD_PCM_A3_IS_GPIO BALL_G5_IS_GPIO
#endif
#ifndef BALL_AE7_IS_GPIO
#define BALL_AE7_IS_GPIO 0
#endif
#ifndef PAD_ET_TX_EN_IS_GPIO
#define PAD_ET_TX_EN_IS_GPIO BALL_AE7_IS_GPIO
#endif
#ifndef BALL_B17_IS_GPIO
#define BALL_B17_IS_GPIO 0
#endif
#ifndef PAD_PCM2_IRQA_N_IS_GPIO
#define PAD_PCM2_IRQA_N_IS_GPIO BALL_B17_IS_GPIO
#endif
#ifndef BALL_D19_IS_GPIO
#define BALL_D19_IS_GPIO 0
#endif
#ifndef PAD_PCM_A12_IS_GPIO
#define PAD_PCM_A12_IS_GPIO BALL_D19_IS_GPIO
#endif
#ifndef BALL_E4_IS_GPIO
#define BALL_E4_IS_GPIO 0
#endif
#ifndef PAD_LDE_IS_GPIO
#define PAD_LDE_IS_GPIO BALL_E4_IS_GPIO
#endif
#ifndef BALL_AB17_IS_GPIO
#define BALL_AB17_IS_GPIO 0
#endif
#ifndef PAD_GPIO13_IS_GPIO
#define PAD_GPIO13_IS_GPIO BALL_AB17_IS_GPIO
#endif
#ifndef BALL_F5_IS_GPIO
#define BALL_F5_IS_GPIO 0
#endif
#ifndef PAD_LHSYNC_IS_GPIO
#define PAD_LHSYNC_IS_GPIO BALL_F5_IS_GPIO
#endif
#ifndef BALL_A23_IS_GPIO
#define BALL_A23_IS_GPIO 0
#endif
#ifndef PAD_TS0_VLD_IS_GPIO
#define PAD_TS0_VLD_IS_GPIO BALL_A23_IS_GPIO
#endif
#ifndef BALL_C15_IS_GPIO
#define BALL_C15_IS_GPIO 0
#endif
#ifndef PAD_PF_CE1Z_IS_GPIO
#define PAD_PF_CE1Z_IS_GPIO BALL_C15_IS_GPIO
#endif
#ifndef BALL_AA24_IS_GPIO
#define BALL_AA24_IS_GPIO 0
#endif
#ifndef PAD_GPIO_PM4_IS_GPIO
#define PAD_GPIO_PM4_IS_GPIO BALL_AA24_IS_GPIO
#endif
#ifndef BALL_E2_IS_GPIO
#define BALL_E2_IS_GPIO 0
#endif
#ifndef PAD_G_ODD5_IS_GPIO
#define PAD_G_ODD5_IS_GPIO BALL_E2_IS_GPIO
#endif
#ifndef BALL_AA18_IS_GPIO
#define BALL_AA18_IS_GPIO 0
#endif
#ifndef PAD_ET_TXER_IS_GPIO
#define PAD_ET_TXER_IS_GPIO BALL_AA18_IS_GPIO
#endif
#ifndef BALL_AA14_IS_GPIO
#define BALL_AA14_IS_GPIO 0
#endif
#ifndef PAD_DDCR_CK2_IS_GPIO
#define PAD_DDCR_CK2_IS_GPIO BALL_AA14_IS_GPIO
#endif
#ifndef BALL_A6_IS_GPIO
#define BALL_A6_IS_GPIO 0
#endif
#ifndef PAD_PWM0_IS_GPIO
#define PAD_PWM0_IS_GPIO BALL_A6_IS_GPIO
#endif
#ifndef BALL_B5_IS_GPIO
#define BALL_B5_IS_GPIO 0
#endif
#ifndef PAD_PWM3_IS_GPIO
#define PAD_PWM3_IS_GPIO BALL_B5_IS_GPIO
#endif
#define PAD_GPIO_PM10_IS_GPIO 0
#ifndef BALL_A21_IS_GPIO
#define BALL_A21_IS_GPIO 0
#endif
#ifndef PAD_PCM_D7_IS_GPIO
#define PAD_PCM_D7_IS_GPIO BALL_A21_IS_GPIO
#endif
#ifndef BALL_AF7_IS_GPIO
#define BALL_AF7_IS_GPIO 0
#endif
#ifndef PAD_ET_TX_CLK_IS_GPIO
#define PAD_ET_TX_CLK_IS_GPIO BALL_AF7_IS_GPIO
#endif
#ifndef BALL_B18_IS_GPIO
#define BALL_B18_IS_GPIO 0
#endif
#ifndef PAD_PCM_A6_IS_GPIO
#define PAD_PCM_A6_IS_GPIO BALL_B18_IS_GPIO
#endif
#ifndef BALL_AF6_IS_GPIO
#define BALL_AF6_IS_GPIO 0
#endif
#ifndef PAD_ET_TXD0_IS_GPIO
#define PAD_ET_TXD0_IS_GPIO BALL_AF6_IS_GPIO
#endif
#ifndef BALL_AB21_IS_GPIO
#define BALL_AB21_IS_GPIO 0
#endif
#ifndef PAD_GPIO15_IS_GPIO
#define PAD_GPIO15_IS_GPIO BALL_AB21_IS_GPIO
#endif
#ifndef BALL_J5_IS_GPIO
#define BALL_J5_IS_GPIO 0
#endif
#ifndef PAD_PCM_A0_IS_GPIO
#define PAD_PCM_A0_IS_GPIO BALL_J5_IS_GPIO
#endif
#ifndef BALL_E19_IS_GPIO
#define BALL_E19_IS_GPIO 0
#endif
#ifndef PAD_PCM_A5_IS_GPIO
#define PAD_PCM_A5_IS_GPIO BALL_E19_IS_GPIO
#endif
#ifndef BALL_AB23_IS_GPIO
#define BALL_AB23_IS_GPIO 0
#endif
#ifndef PAD_GPIO_PM1_IS_GPIO
#define PAD_GPIO_PM1_IS_GPIO BALL_AB23_IS_GPIO
#endif
#ifndef BALL_H3_IS_GPIO
#define BALL_H3_IS_GPIO 0
#endif
#ifndef PAD_R_ODD5_IS_GPIO
#define PAD_R_ODD5_IS_GPIO BALL_H3_IS_GPIO
#endif
#ifndef BALL_Y24_IS_GPIO
#define BALL_Y24_IS_GPIO 0
#endif
#ifndef PAD_GPIO_PM6_IS_GPIO
#define PAD_GPIO_PM6_IS_GPIO BALL_Y24_IS_GPIO
#endif
#ifndef BALL_C1_IS_GPIO
#define BALL_C1_IS_GPIO 0
#endif
#ifndef PAD_G_ODD0_IS_GPIO
#define PAD_G_ODD0_IS_GPIO BALL_C1_IS_GPIO
#endif
#ifndef BALL_D21_IS_GPIO
#define BALL_D21_IS_GPIO 0
#endif
#ifndef PAD_PCM_OE_N_IS_GPIO
#define PAD_PCM_OE_N_IS_GPIO BALL_D21_IS_GPIO
#endif
#ifndef BALL_A24_IS_GPIO
#define BALL_A24_IS_GPIO 0
#endif
#ifndef PAD_TS0_D6_IS_GPIO
#define PAD_TS0_D6_IS_GPIO BALL_A24_IS_GPIO
#endif
#define PAD_GPIO_PM8_IS_GPIO 0
#ifndef BALL_AA16_IS_GPIO
#define BALL_AA16_IS_GPIO 0
#endif
#ifndef PAD_GPIO12_IS_GPIO
#define PAD_GPIO12_IS_GPIO BALL_AA16_IS_GPIO
#endif
#ifndef BALL_A25_IS_GPIO
#define BALL_A25_IS_GPIO 0
#endif
#ifndef PAD_TS0_D3_IS_GPIO
#define PAD_TS0_D3_IS_GPIO BALL_A25_IS_GPIO
#endif
#ifndef BALL_C20_IS_GPIO
#define BALL_C20_IS_GPIO 0
#endif
#ifndef PAD_PCM_A9_IS_GPIO
#define PAD_PCM_A9_IS_GPIO BALL_C20_IS_GPIO
#endif
#ifndef BALL_F3_IS_GPIO
#define BALL_F3_IS_GPIO 0
#endif
#ifndef PAD_G_ODD7_IS_GPIO
#define PAD_G_ODD7_IS_GPIO BALL_F3_IS_GPIO
#endif
#ifndef BALL_AC11_IS_GPIO
#define BALL_AC11_IS_GPIO 0
#endif
#ifndef PAD_I2S_OUT_SD_IS_GPIO
#define PAD_I2S_OUT_SD_IS_GPIO BALL_AC11_IS_GPIO
#endif
#ifndef BALL_AA17_IS_GPIO
#define BALL_AA17_IS_GPIO 0
#endif
#ifndef PAD_ET_RXD3_IS_GPIO
#define PAD_ET_RXD3_IS_GPIO BALL_AA17_IS_GPIO
#endif
#ifndef BALL_A14_IS_GPIO
#define BALL_A14_IS_GPIO 0
#endif
#ifndef PAD_PF_OEZ_IS_GPIO
#define PAD_PF_OEZ_IS_GPIO BALL_A14_IS_GPIO
#endif
#ifndef BALL_B1_IS_GPIO
#define BALL_B1_IS_GPIO 0
#endif
#ifndef PAD_B_ODD5_IS_GPIO
#define PAD_B_ODD5_IS_GPIO BALL_B1_IS_GPIO
#endif
#ifndef BALL_E13_IS_GPIO
#define BALL_E13_IS_GPIO 0
#endif
#ifndef PAD_DDCDC_CK_IS_GPIO
#define PAD_DDCDC_CK_IS_GPIO BALL_E13_IS_GPIO
#endif
#ifndef BALL_K5_IS_GPIO
#define BALL_K5_IS_GPIO 0
#endif
#ifndef PAD_PCM_D0_IS_GPIO
#define PAD_PCM_D0_IS_GPIO BALL_K5_IS_GPIO
#endif
#ifndef BALL_AA22_IS_GPIO
#define BALL_AA22_IS_GPIO 0
#endif
#ifndef PAD_DDCDB_DA_IS_GPIO
#define PAD_DDCDB_DA_IS_GPIO BALL_AA22_IS_GPIO
#endif
#ifndef BALL_A2_IS_GPIO
#define BALL_A2_IS_GPIO 0
#endif
#ifndef PAD_B_ODD1_IS_GPIO
#define PAD_B_ODD1_IS_GPIO BALL_A2_IS_GPIO
#endif
#ifndef BALL_AD24_IS_GPIO
#define BALL_AD24_IS_GPIO 0
#endif
#ifndef PAD_SAR3_IS_GPIO
#define PAD_SAR3_IS_GPIO BALL_AD24_IS_GPIO
#endif
#ifndef BALL_B20_IS_GPIO
#define BALL_B20_IS_GPIO 0
#endif
#ifndef PAD_PCM_IORD_N_IS_GPIO
#define PAD_PCM_IORD_N_IS_GPIO BALL_B20_IS_GPIO
#endif
#ifndef BALL_AF8_IS_GPIO
#define BALL_AF8_IS_GPIO 0
#endif
#ifndef PAD_I2S_IN_SD_IS_GPIO
#define PAD_I2S_IN_SD_IS_GPIO BALL_AF8_IS_GPIO
#endif
#ifndef BALL_V26_IS_GPIO
#define BALL_V26_IS_GPIO 0
#endif
#ifndef PAD_DDCDA_DA_IS_GPIO
#define PAD_DDCDA_DA_IS_GPIO BALL_V26_IS_GPIO
#endif
#ifndef BALL_AC16_IS_GPIO
#define BALL_AC16_IS_GPIO 0
#endif
#ifndef PAD_LVSYNC2_IS_GPIO
#define PAD_LVSYNC2_IS_GPIO BALL_AC16_IS_GPIO
#endif
#ifndef BALL_AA11_IS_GPIO
#define BALL_AA11_IS_GPIO 0
#endif
#ifndef PAD_I2S_OUT_BCK_IS_GPIO
#define PAD_I2S_OUT_BCK_IS_GPIO BALL_AA11_IS_GPIO
#endif
#ifndef BALL_AB9_IS_GPIO
#define BALL_AB9_IS_GPIO 0
#endif
#ifndef PAD_I2S_OUT_WS_IS_GPIO
#define PAD_I2S_OUT_WS_IS_GPIO BALL_AB9_IS_GPIO
#endif
#ifndef BALL_H1_IS_GPIO
#define BALL_H1_IS_GPIO 0
#endif
#ifndef PAD_R_ODD7_IS_GPIO
#define PAD_R_ODD7_IS_GPIO BALL_H1_IS_GPIO
#endif
#ifndef BALL_J1_IS_GPIO
#define BALL_J1_IS_GPIO 0
#endif
#ifndef PAD_PCM_D1_IS_GPIO
#define PAD_PCM_D1_IS_GPIO BALL_J1_IS_GPIO
#endif
#ifndef BALL_E3_IS_GPIO
#define BALL_E3_IS_GPIO 0
#endif
#ifndef PAD_G_ODD4_IS_GPIO
#define PAD_G_ODD4_IS_GPIO BALL_E3_IS_GPIO
#endif
#ifndef BALL_A19_IS_GPIO
#define BALL_A19_IS_GPIO 0
#endif
#ifndef PAD_PCM_A14_IS_GPIO
#define PAD_PCM_A14_IS_GPIO BALL_A19_IS_GPIO
#endif
#ifndef BALL_AA10_IS_GPIO
#define BALL_AA10_IS_GPIO 0
#endif
#ifndef PAD_ET_RXD0_IS_GPIO
#define PAD_ET_RXD0_IS_GPIO BALL_AA10_IS_GPIO
#endif
#ifndef BALL_AB11_IS_GPIO
#define BALL_AB11_IS_GPIO 0
#endif
#ifndef PAD_ET_TXD2_IS_GPIO
#define PAD_ET_TXD2_IS_GPIO BALL_AB11_IS_GPIO
#endif
#ifndef BALL_A22_IS_GPIO
#define BALL_A22_IS_GPIO 0
#endif
#ifndef PAD_PCM_D3_IS_GPIO
#define PAD_PCM_D3_IS_GPIO BALL_A22_IS_GPIO
#endif
#ifndef BALL_K3_IS_GPIO
#define BALL_K3_IS_GPIO 0
#endif
#ifndef PAD_PCM2_CD_N_IS_GPIO
#define PAD_PCM2_CD_N_IS_GPIO BALL_K3_IS_GPIO
#endif
#ifndef BALL_C23_IS_GPIO
#define BALL_C23_IS_GPIO 0
#endif
#ifndef PAD_TS0_CLK_IS_GPIO
#define PAD_TS0_CLK_IS_GPIO BALL_C23_IS_GPIO
#endif
#ifndef BALL_A16_IS_GPIO
#define BALL_A16_IS_GPIO 0
#endif
#ifndef PAD_UART_RX2_IS_GPIO
#define PAD_UART_RX2_IS_GPIO BALL_A16_IS_GPIO
#endif
#ifndef BALL_D22_IS_GPIO
#define BALL_D22_IS_GPIO 0
#endif
#ifndef PAD_PCM_D6_IS_GPIO
#define PAD_PCM_D6_IS_GPIO BALL_D22_IS_GPIO
#endif
#ifndef BALL_B7_IS_GPIO
#define BALL_B7_IS_GPIO 0
#endif
#ifndef PAD_SPI_DO_IS_GPIO
#define PAD_SPI_DO_IS_GPIO BALL_B7_IS_GPIO
#endif
#ifndef BALL_A15_IS_GPIO
#define BALL_A15_IS_GPIO 0
#endif
#ifndef PAD_PF_ALE_IS_GPIO
#define PAD_PF_ALE_IS_GPIO BALL_A15_IS_GPIO
#endif
#ifndef BALL_AB16_IS_GPIO
#define BALL_AB16_IS_GPIO 0
#endif
#ifndef PAD_ET_RXD1_IS_GPIO
#define PAD_ET_RXD1_IS_GPIO BALL_AB16_IS_GPIO
#endif
#ifndef BALL_B2_IS_GPIO
#define BALL_B2_IS_GPIO 0
#endif
#ifndef PAD_B_ODD4_IS_GPIO
#define PAD_B_ODD4_IS_GPIO BALL_B2_IS_GPIO
#endif
#ifndef BALL_G4_IS_GPIO
#define BALL_G4_IS_GPIO 0
#endif
#ifndef PAD_PCM_A2_IS_GPIO
#define PAD_PCM_A2_IS_GPIO BALL_G4_IS_GPIO
#endif
#ifndef BALL_E18_IS_GPIO
#define BALL_E18_IS_GPIO 0
#endif
#ifndef PAD_PCM_WAIT_N_IS_GPIO
#define PAD_PCM_WAIT_N_IS_GPIO BALL_E18_IS_GPIO
#endif
#ifndef BALL_M4_IS_GPIO
#define BALL_M4_IS_GPIO 0
#endif
#ifndef PAD_TS1_CLK_IS_GPIO
#define PAD_TS1_CLK_IS_GPIO BALL_M4_IS_GPIO
#endif
#ifndef BALL_D14_IS_GPIO
#define BALL_D14_IS_GPIO 0
#endif
#ifndef PAD_F_RBZ_IS_GPIO
#define PAD_F_RBZ_IS_GPIO BALL_D14_IS_GPIO
#endif
#ifndef BALL_A20_IS_GPIO
#define BALL_A20_IS_GPIO 0
#endif
#ifndef PAD_PCM_A11_IS_GPIO
#define PAD_PCM_A11_IS_GPIO BALL_A20_IS_GPIO
#endif
#ifndef BALL_D17_IS_GPIO
#define BALL_D17_IS_GPIO 0
#endif
#ifndef PAD_PCM_A4_IS_GPIO
#define PAD_PCM_A4_IS_GPIO BALL_D17_IS_GPIO
#endif
#ifndef BALL_C16_IS_GPIO
#define BALL_C16_IS_GPIO 0
#endif
#ifndef PAD_PF_AD15_IS_GPIO
#define PAD_PF_AD15_IS_GPIO BALL_C16_IS_GPIO
#endif
#ifndef BALL_F1_IS_GPIO
#define BALL_F1_IS_GPIO 0
#endif
#ifndef PAD_R_ODD1_IS_GPIO
#define PAD_R_ODD1_IS_GPIO BALL_F1_IS_GPIO
#endif
#ifndef BALL_AF23_IS_GPIO
#define BALL_AF23_IS_GPIO 0
#endif
#ifndef PAD_SAR1_IS_GPIO
#define PAD_SAR1_IS_GPIO BALL_AF23_IS_GPIO
#endif
#ifndef BALL_F4_IS_GPIO
#define BALL_F4_IS_GPIO 0
#endif
#ifndef PAD_LVSYNC_IS_GPIO
#define PAD_LVSYNC_IS_GPIO BALL_F4_IS_GPIO
#endif
#ifndef BALL_A17_IS_GPIO
#define BALL_A17_IS_GPIO 0
#endif
#ifndef PAD_PCM2_CE_N_IS_GPIO
#define PAD_PCM2_CE_N_IS_GPIO BALL_A17_IS_GPIO
#endif
#ifndef BALL_V22_IS_GPIO
#define BALL_V22_IS_GPIO 0
#endif
#ifndef PAD_HOTPLUGA_IS_GPIO
#define PAD_HOTPLUGA_IS_GPIO BALL_V22_IS_GPIO
#endif
#ifndef BALL_B16_IS_GPIO
#define BALL_B16_IS_GPIO 0
#endif
#ifndef PAD_UART_TX2_IS_GPIO
#define PAD_UART_TX2_IS_GPIO BALL_B16_IS_GPIO
#endif
#ifndef BALL_B26_IS_GPIO
#define BALL_B26_IS_GPIO 0
#endif
#ifndef PAD_TS0_D1_IS_GPIO
#define PAD_TS0_D1_IS_GPIO BALL_B26_IS_GPIO
#endif
#ifndef BALL_AB18_IS_GPIO
#define BALL_AB18_IS_GPIO 0
#endif
#ifndef PAD_GPIO14_IS_GPIO
#define PAD_GPIO14_IS_GPIO BALL_AB18_IS_GPIO
#endif
#ifndef BALL_D1_IS_GPIO
#define BALL_D1_IS_GPIO 0
#endif
#ifndef PAD_G_ODD3_IS_GPIO
#define PAD_G_ODD3_IS_GPIO BALL_D1_IS_GPIO
#endif
#ifndef BALL_H2_IS_GPIO
#define BALL_H2_IS_GPIO 0
#endif
#ifndef PAD_R_ODD6_IS_GPIO
#define PAD_R_ODD6_IS_GPIO BALL_H2_IS_GPIO
#endif
#ifndef BALL_K2_IS_GPIO
#define BALL_K2_IS_GPIO 0
#endif
#ifndef PAD_PCM_CD_N_IS_GPIO
#define PAD_PCM_CD_N_IS_GPIO BALL_K2_IS_GPIO
#endif
#ifndef BALL_A4_IS_GPIO
#define BALL_A4_IS_GPIO 0
#endif
#ifndef PAD_DDCR_CLK_IS_GPIO
#define PAD_DDCR_CLK_IS_GPIO BALL_A4_IS_GPIO
#endif
#ifndef BALL_H5_IS_GPIO
#define BALL_H5_IS_GPIO 0
#endif
#ifndef PAD_PCM_REG_N_IS_GPIO
#define PAD_PCM_REG_N_IS_GPIO BALL_H5_IS_GPIO
#endif
#ifndef BALL_B15_IS_GPIO
#define BALL_B15_IS_GPIO 0
#endif
#ifndef PAD_PF_CE0Z_IS_GPIO
#define PAD_PF_CE0Z_IS_GPIO BALL_B15_IS_GPIO
#endif
#ifndef BALL_B22_IS_GPIO
#define BALL_B22_IS_GPIO 0
#endif
#ifndef PAD_PCM_D4_IS_GPIO
#define PAD_PCM_D4_IS_GPIO BALL_B22_IS_GPIO
#endif
#ifndef BALL_E1_IS_GPIO
#define BALL_E1_IS_GPIO 0
#endif
#ifndef PAD_G_ODD6_IS_GPIO
#define PAD_G_ODD6_IS_GPIO BALL_E1_IS_GPIO
#endif
#ifndef BALL_C2_IS_GPIO
#define BALL_C2_IS_GPIO 0
#endif
#ifndef PAD_B_ODD7_IS_GPIO
#define PAD_B_ODD7_IS_GPIO BALL_C2_IS_GPIO
#endif
#ifndef BALL_B6_IS_GPIO
#define BALL_B6_IS_GPIO 0
#endif
#ifndef PAD_PWM1_IS_GPIO
#define PAD_PWM1_IS_GPIO BALL_B6_IS_GPIO
#endif
#ifndef BALL_K1_IS_GPIO
#define BALL_K1_IS_GPIO 0
#endif
#ifndef PAD_PCM2_RESET_IS_GPIO
#define PAD_PCM2_RESET_IS_GPIO BALL_K1_IS_GPIO
#endif
#ifndef BALL_AC9_IS_GPIO
#define BALL_AC9_IS_GPIO 0
#endif
#ifndef PAD_I2S_OUT_MCK_IS_GPIO
#define PAD_I2S_OUT_MCK_IS_GPIO BALL_AC9_IS_GPIO
#endif
#ifndef BALL_B24_IS_GPIO
#define BALL_B24_IS_GPIO 0
#endif
#ifndef PAD_TS0_D7_IS_GPIO
#define PAD_TS0_D7_IS_GPIO BALL_B24_IS_GPIO
#endif
#ifndef BALL_B3_IS_GPIO
#define BALL_B3_IS_GPIO 0
#endif
#ifndef PAD_B_ODD3_IS_GPIO
#define PAD_B_ODD3_IS_GPIO BALL_B3_IS_GPIO
#endif
#ifndef BALL_G3_IS_GPIO
#define BALL_G3_IS_GPIO 0
#endif
#ifndef PAD_R_ODD2_IS_GPIO
#define PAD_R_ODD2_IS_GPIO BALL_G3_IS_GPIO
#endif
#ifndef BALL_C8_IS_GPIO
#define BALL_C8_IS_GPIO 0
#endif
#ifndef PAD_SPI_CK_IS_GPIO
#define PAD_SPI_CK_IS_GPIO BALL_C8_IS_GPIO
#endif
#ifndef BALL_J4_IS_GPIO
#define BALL_J4_IS_GPIO 0
#endif
#ifndef PAD_PCM_RESET_IS_GPIO
#define PAD_PCM_RESET_IS_GPIO BALL_J4_IS_GPIO
#endif
#ifndef BALL_H4_IS_GPIO
#define BALL_H4_IS_GPIO 0
#endif
#ifndef PAD_PCM_A1_IS_GPIO
#define PAD_PCM_A1_IS_GPIO BALL_H4_IS_GPIO
#endif
#ifndef BALL_A18_IS_GPIO
#define BALL_A18_IS_GPIO 0
#endif
#ifndef PAD_PCM_A7_IS_GPIO
#define PAD_PCM_A7_IS_GPIO BALL_A18_IS_GPIO
#endif
#ifndef BALL_E5_IS_GPIO
#define BALL_E5_IS_GPIO 0
#endif
#ifndef PAD_LCK_IS_GPIO
#define PAD_LCK_IS_GPIO BALL_E5_IS_GPIO
#endif
#ifndef BALL_AB12_IS_GPIO
#define BALL_AB12_IS_GPIO 0
#endif
#ifndef PAD_SPDIF_OUT_IS_GPIO
#define PAD_SPDIF_OUT_IS_GPIO BALL_AB12_IS_GPIO
#endif
#ifndef BALL_AB24_IS_GPIO
#define BALL_AB24_IS_GPIO 0
#endif
#ifndef PAD_GPIO_PM3_IS_GPIO
#define PAD_GPIO_PM3_IS_GPIO BALL_AB24_IS_GPIO
#endif
#ifndef BALL_AB15_IS_GPIO
#define BALL_AB15_IS_GPIO 0
#endif
#ifndef PAD_ET_RX_DV_IS_GPIO
#define PAD_ET_RX_DV_IS_GPIO BALL_AB15_IS_GPIO
#endif
#ifndef BALL_E20_IS_GPIO
#define BALL_E20_IS_GPIO 0
#endif
#ifndef PAD_PCM_A8_IS_GPIO
#define PAD_PCM_A8_IS_GPIO BALL_E20_IS_GPIO
#endif
#ifndef BALL_B4_IS_GPIO
#define BALL_B4_IS_GPIO 0
#endif
#ifndef PAD_DDCR_DAT_IS_GPIO
#define PAD_DDCR_DAT_IS_GPIO BALL_B4_IS_GPIO
#endif
#ifndef BALL_AD8_IS_GPIO
#define BALL_AD8_IS_GPIO 0
#endif
#ifndef PAD_I2S_IN_WS_IS_GPIO
#define PAD_I2S_IN_WS_IS_GPIO BALL_AD8_IS_GPIO
#endif
#ifndef BALL_AC23_IS_GPIO
#define BALL_AC23_IS_GPIO 0
#endif
#ifndef PAD_GPIO_PM0_IS_GPIO
#define PAD_GPIO_PM0_IS_GPIO BALL_AC23_IS_GPIO
#endif
#ifndef BALL_AD9_IS_GPIO
#define BALL_AD9_IS_GPIO 0
#endif
#ifndef PAD_SPDIF_IN_IS_GPIO
#define PAD_SPDIF_IN_IS_GPIO BALL_AD9_IS_GPIO
#endif
#ifndef BALL_G1_IS_GPIO
#define BALL_G1_IS_GPIO 0
#endif
#ifndef PAD_R_ODD4_IS_GPIO
#define PAD_R_ODD4_IS_GPIO BALL_G1_IS_GPIO
#endif
#ifndef BALL_AC24_IS_GPIO
#define BALL_AC24_IS_GPIO 0
#endif
#ifndef PAD_GPIO_PM2_IS_GPIO
#define PAD_GPIO_PM2_IS_GPIO BALL_AC24_IS_GPIO
#endif
#ifndef BALL_W24_IS_GPIO
#define BALL_W24_IS_GPIO 0
#endif
#ifndef PAD_DDCA_DA_IS_GPIO
#define PAD_DDCA_DA_IS_GPIO BALL_W24_IS_GPIO
#endif
#ifndef BALL_AE6_IS_GPIO
#define BALL_AE6_IS_GPIO 0
#endif
#ifndef PAD_ET_TXD1_IS_GPIO
#define PAD_ET_TXD1_IS_GPIO BALL_AE6_IS_GPIO
#endif
#ifndef BALL_V25_IS_GPIO
#define BALL_V25_IS_GPIO 0
#endif
#ifndef PAD_DDCDA_CK_IS_GPIO
#define PAD_DDCDA_CK_IS_GPIO BALL_V25_IS_GPIO
#endif
#ifndef BALL_A3_IS_GPIO
#define BALL_A3_IS_GPIO 0
#endif
#ifndef PAD_B_ODD0_IS_GPIO
#define PAD_B_ODD0_IS_GPIO BALL_A3_IS_GPIO
#endif
#ifndef BALL_Y23_IS_GPIO
#define BALL_Y23_IS_GPIO 0
#endif
#ifndef PAD_GPIO_PM5_IS_GPIO
#define PAD_GPIO_PM5_IS_GPIO BALL_Y23_IS_GPIO
#endif

// chip capbilities
#define CHIP_HAS_BT656_IN          0
#define CHIP_HAS_TS0               1 // BALL# C23 B23 A23 A26 B26 C26 A25 B25 C25 A24 B24
#define CHIP_HAS_TS1               1 // BALL# M4 L4 L3 K4
#define CHIP_HAS_LVDS_10BIT_X2     1
#define CHIP_HAS_LVDS_8BIT_X2      1
#define CHIP_HAS_LVDS_8BIT_X1      1
#define CHIP_HAS_DTCON_MODE1       0
#define CHIP_HAS_ATCON_MODE1       0
#define CHIP_HAS_ATCON_MODE2       0
#define CHIP_HAS_CCFL              0
#define CHIP_HAS_CIMAX             0
#define CHIP_HAS_FCIE_CONFIG1      0
#define CHIP_HAS_FCIE_CONFIG2      0
#define CHIP_HAS_USB               1
#define CHIP_HAS_UART1_MODE1       1 // BALL# K1 K3
#define CHIP_HAS_UART1_MODE2       1 // BALL# AA15 AC16
#define CHIP_HAS_UART1_MODE3       1 // BALL# AB18 AB21
#define CHIP_HAS_PCMCIA1           1
#define CHIP_HAS_PCMCIA2           1
#define CHIP_HAS_PCMCIA            1
#define CHIP_HAS_UART2_MODE1       1 // BALL# A16 B16
#define CHIP_HAS_UART2_MODE2       1 // BALL# AB13 AA14
#define CHIP_HAS_UART2_MODE3       1 // BALL# AA16 AB17
#define CHIP_HAS_RGB_A             1 // BALL# R25 P26 P24 R26
#define CHIP_HAS_RGB_B             1 // BALL# U23 U24 U26 U25
#define CHIP_HAS_RGB_C             1 // BALL# L24 L25 M24 L26
#define CHIP_HAS_HDMI_A            1 // BALL# AB26 AB25 AA26 AA25 Y26 Y25 W26 W25 N23 V26 V25
#define CHIP_HAS_HDMI_B            1 // BALL# AF26 AF25 AE26 AE25 AD26 AD25 AC26 AC25 N23 AA22 Y22
#define CHIP_HAS_HDMI_C            1 // BALL# A12 B12 A11 B11 A10 B10 A9 B9 N23 C14 E13
#define CHIP_HAS_SPI_CZ1           1 // BALL# A16 C22 AE8
#define CHIP_HAS_SPI_CZ2           1 // BALL# B16 D22 AA15
#define CHIP_HAS_SPI_CZ3           1 // BALL# AD8 AC16 G5
#define CHIP_HAS_DDCR              1 // BALL# B4 A4
#define CHIP_HAS_DDCR2             1 // BALL# AB13 AA14
#define CHIP_HAS_I2S_IN            1 // BALL# AD8 AE8 AF8
#define CHIP_HAS_I2S_OUT           1 // BALL# AB9 AA11 AB9 AC11
#define CHIP_HAS_SPDIF_IN          1 // BALL# AD9
#define CHIP_HAS_SPDIF_OUT         1 // BALL# AB12
#define CHIP_HAS_DDR_A_CMD         1
#define CHIP_HAS_DDR_A_DATA        1
#define CHIP_HAS_DDR_B_CMD         1
#define CHIP_HAS_DDR_B_DATA        1
#define CHIP_USE_PCM_CDN_IN_PCM2   0
#define CHIP_USE_I2S_IN_IN_PCM     0
#define CHIP_USE_I2S_OUT_IN_PCM    0
#define CHIP_USE_SPDIF_IN_IN_PCM   0
#define CHIP_USE_SPDIF_OUT_IN_PCM  0
#define CHIP_USE_IIC_IN_DDCR2      0
#define CHIP_USE_PWM2_IN_GPIO14    0
#define CHIP_USE_PWM3_IN_GPIO15    0

// chip additional information
#define BONDING_TYPE               BONDING_MSD3108EV
#define CHIP_FAMILY_TYPE           CHIP_FAMILY_S4L

#endif /* _MSD3108EV_H_ */
