////////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 2006-2008 MStar Semiconductor, Inc.
// All rights reserved.
//
// Unless otherwise stipulated in writing, any and all information contained
// herein regardless in any format shall remain the sole proprietary of
// MStar Semiconductor Inc. and be kept in strict confidence
// (¡§MStar Confidential Information¡¨) by the recipient.
// Any unauthorized act including without limitation unauthorized disclosure,
// copying, use, reproduction, sale, distribution, modification, disassembling,
// reverse engineering and compiling of the contents of MStar Confidential
// Information is unlawful and strictly prohibited. MStar hereby reserves the
// rights to any and all damages, losses, costs and expenses resulting therefrom.
//
////////////////////////////////////////////////////////////////////////////////

// This file is generated by script, please do not edit it directly
#ifndef _MSD3063EQ_H_
#define _MSD3063EQ_H_

// PIN number to PAD name mapping
#define PIN_3               PAD_GPIO_PM7        // PAD_GPIO_PM7
#define PIN_4               PAD_GPIO_PM8        // PAD_GPIO_PM8
#define PIN_5               PAD_GPIO_PM9        // PAD_GPIO_PM9
#define PIN_6               PAD_GPIO_PM10       // PAD_GPIO_PM10
#define PIN_7               PAD_GPIO_PM5        // PAD_GPIO_PM5
#define PIN_8               PAD_GPIO_PM6        // PAD_GPIO_PM6
#define PIN_15              PAD_DDCDB_DA        // PAD_DDCDB_DA//
#define PIN_18              PAD_HOTPLUGB        // PAD_HOTPLUGB/
#define PIN_24              PAD_DDCDB_CK        // PAD_DDCDB_CK
#define PIN_35              PAD_HOTPLUGA        // PAD_HOTPLUGA
#define PIN_37              PAD_DDCDA_DA        // PAD_DDCDA_DA
#define PIN_38              PAD_DDCDA_CK        // PAD_DDCDA_CK
#define PIN_51              PAD_CVBS3P          // PAD_CVBS3P
#define PIN_52              PAD_CVBS2P          // PAD_CVBS2P
#define PIN_53              PAD_CVBS1P          // PAD_CVBS1P
#define PIN_55              PAD_CVBS0P          // PAD_CVBS0P
#define PIN_62              PAD_DDCA_DA         // PAD_DDCA_DA
#define PIN_63              PAD_DDCA_CK         // PAD_DDCA_CK
#define PIN_88              PAD_TS0_D0          // PAD_TS0_D[0]
#define PIN_89              PAD_TS0_D1          // PAD_TS0_D[1]
#define PIN_90              PAD_TS0_D2          // PAD_TS0_D[2]
#define PIN_91              PAD_TS0_D3          // PAD_TS0_D[3]
#define PIN_92              PAD_TS0_D4          // PAD_TS0_D[4]
#define PIN_93              PAD_TS0_D5          // PAD_TS0_D[5]
#define PIN_94              PAD_TS0_D6          // PAD_TS0_D[6]
#define PIN_95              PAD_TS0_D7          // PAD_TS0_D[7]
#define PIN_96              PAD_TS0_VLD         // PAD_TS0_VLD
#define PIN_97              PAD_TS0_SYNC        // PAD_TS0_SYNC
#define PIN_98              PAD_TS0_CLK         // PAD_TS0_CLK
#define PIN_99              PAD_PCM_D5          // PAD_I2S_IN_WS
#define PIN_100             PAD_PCM_D6          // PAD_I2S_IN_BCK
#define PIN_101             PAD_PCM_D7          // PAD_I2S_IN_SD
#define PIN_102             PAD_PCM_CE_N        // PAD_SPDIF_IN0
#define PIN_103             PAD_PCM_A10         // PAD_SPDIF_OUT
#define PIN_104             PAD_PCM_OE_N        // PAD_I2S_OUT_WS
#define PIN_106             PAD_PCM_A11         // PAD_I2S_OUT_MCK
#define PIN_107             PAD_PCM_IORD_N      // PAD_I2S_OUT_BCK
#define PIN_108             PAD_PCM_A9          // PAD_I2S_OUT_SD
#define PIN_109             PAD_PCM_A14         // PAD_I2S_OUT_MUTE
#define PIN_110             PAD_PCM2_WAIT_N     // Jupiter GPIO
#define PIN_112             PAD_UART_RX2        // PAD_UART_RX2
#define PIN_113             PAD_UART_TX2        // PAD_UART_TX2
#define PIN_114             PAD_DDCDC_CK        // PAD_DDCDC_CK
#define PIN_117             PAD_DDCDC_DA        // PAD_DDCDC_DA
#define PIN_126             PAD_HOTPLUGC        // PAD_HOTPLUGC
#define PIN_127             PAD_SPI_CK          // PAD_SPI_CK
#define PIN_128             PAD_SPI_DI          // PAD_SPI_DI
#define PIN_129             PAD_SPI_DO          // PAD_SPI_DO
#define PIN_130             PAD_SPI_CZ          // PAD_SPI_CZ
#define PIN_131             PAD_PWM0            // PAD_PWM0
#define PIN_132             PAD_PWM1            // PAD_PWM1
#define PIN_133             PAD_PWM2            // PAD_PWM2
#define PIN_134             PAD_PWM3            // PAD_PWM3
#define PIN_135             PAD_DDCR_DAT        // PAD_DDCR_DA
#define PIN_136             PAD_DDCR_CLK        // PAD_DDCR_CK
#define PIN_137             PAD_B_ODD0          // PAD_B_ODD[0]
#define PIN_138             PAD_B_ODD1          // PAD_B_ODD[1]
#define PIN_139             PAD_B_ODD2          // PAD_B_ODD[2]
#define PIN_140             PAD_B_ODD3          // PAD_B_ODD[3]
#define PIN_141             PAD_B_ODD4          // PAD_B_ODD[4]
#define PIN_142             PAD_B_ODD5          // PAD_B_ODD[5]
#define PIN_143             PAD_B_ODD6          // PAD_B_ODD[6]
#define PIN_144             PAD_B_ODD7          // PAD_B_ODD[7]
#define PIN_145             PAD_G_ODD0          // PAD_G_ODD[0]
#define PIN_146             PAD_G_ODD1          // PAD_G_ODD[1]
#define PIN_147             PAD_G_ODD2          // PAD_G_ODD[2]
#define PIN_148             PAD_G_ODD3          // PAD_G_ODD[3]
#define PIN_150             PAD_G_ODD4          // PAD_G_ODD[4]
#define PIN_151             PAD_G_ODD5          // PAD_G_ODD[5]
#define PIN_152             PAD_G_ODD6          // PAD_G_ODD[6]
#define PIN_153             PAD_G_ODD7          // PAD_G_ODD[7]
#define PIN_154             PAD_R_ODD0          // PAD_R_ODD[0]
#define PIN_155             PAD_R_ODD1          // PAD_R_ODD[1]
#define PIN_156             PAD_R_ODD2          // PAD_R_ODD[2]
#define PIN_157             PAD_R_ODD3          // PAD_R_ODD[3]
#define PIN_158             PAD_R_ODD4          // PAD_R_ODD[4]
#define PIN_159             PAD_R_ODD5          // PAD_R_ODD[5]
#define PIN_160             PAD_R_ODD6          // PAD_R_ODD[6]
#define PIN_161             PAD_R_ODD7          // PAD_R_ODD[7]
#define PIN_1               PAD_GPIO_PM4        // PAD_GPIO_PM4

// PAD name to index
#define PAD_NC              9999
#define PAD_GND             0

#define PAD_GPIO_PM7        1
#define PAD_GPIO_PM8        2
#define PAD_GPIO_PM9        3
#define PAD_GPIO_PM10       4
#define PAD_GPIO_PM5        5
#define PAD_GPIO_PM6        6
#define PAD_DDCDB_DA        15
#define PAD_HOTPLUGB        18
#define PAD_DDCDB_CK        23
#define PAD_HOTPLUGA        32
#define PAD_DDCDA_DA        34
#define PAD_DDCDA_CK        35
#define PAD_CVBS7P          59
#define PAD_CVBS6P          60
#define PAD_CVBS5P          61
#define PAD_CVBS4P          62
#define PAD_CVBS3P          64
#define PAD_CVBS2P          65
#define PAD_CVBS1P          66
#define PAD_CVBS0P          68
#define PAD_DDCA_DA         76
#define PAD_DDCA_CK         77
#define PAD_TS0_D0          112
#define PAD_TS0_D1          113
#define PAD_TS0_D2          114
#define PAD_TS0_D3          115
#define PAD_TS0_D4          116
#define PAD_TS0_D5          117
#define PAD_TS0_D6          118
#define PAD_TS0_D7          119
#define PAD_TS0_VLD         120
#define PAD_TS0_SYNC        121
#define PAD_TS0_CLK         122
#define PAD_PCM_D3          123
#define PAD_PCM_D4          124
#define PAD_PCM_D5          125
#define PAD_PCM_D6          126
#define PAD_PCM_D7          127
#define PAD_PCM_CE_N        128
#define PAD_PCM_A10         129
#define PAD_PCM_OE_N        130
#define PAD_PCM_A11         131
#define PAD_PCM_IORD_N      132
#define PAD_PCM_A9          133
#define PAD_PCM_IOWR_N      134
#define PAD_PCM_A8          135
#define PAD_PCM_A13         136
#define PAD_PCM_A14         137
#define PAD_PCM_WE_N        138
#define PAD_PCM_IRQA_N      139
#define PAD_PCM_A12         140
#define PAD_PCM_A7          141
#define PAD_PCM_A6          142
#define PAD_PCM_A5          143
#define PAD_PCM_WAIT_N      144
#define PAD_PCM_A4          145
#define PAD_PCM2_CE_N       146
#define PAD_PCM2_IRQA_N     147
#define PAD_PCM2_WAIT_N     148
#define PAD_UART_RX2        149
#define PAD_UART_TX2        150
#define PAD_PF_AD15         151
#define PAD_PF_ALE          152
#define PAD_PF_CE0Z         153
#define PAD_PF_CE1Z         154
#define PAD_PF_OEZ          155
#define PAD_PF_WEZ          156
#define PAD_F_RBZ           157
#define PAD_DDCDC_CK        158
#define PAD_DDCDC_DA        161
#define PAD_HOTPLUGC        168
#define PAD_SPI_CK          169
#define PAD_SPI_DI          170
#define PAD_SPI_DO          171
#define PAD_SPI_CZ          172
#define PAD_PWM0            173
#define PAD_PWM1            174
#define PAD_PWM2            175
#define PAD_PWM3            176
#define PAD_DDCR_DAT        177
#define PAD_DDCR_CLK        178
#define PAD_B_ODD0          179
#define PAD_B_ODD1          180
#define PAD_B_ODD2          181
#define PAD_B_ODD3          182
#define PAD_B_ODD4          183
#define PAD_B_ODD5          184
#define PAD_B_ODD6          185
#define PAD_B_ODD7          186
#define PAD_G_ODD0          187
#define PAD_G_ODD1          188
#define PAD_G_ODD2          189
#define PAD_G_ODD3          190
#define PAD_G_ODD4          191
#define PAD_G_ODD5          192
#define PAD_G_ODD6          193
#define PAD_G_ODD7          194
#define PAD_R_ODD0          195
#define PAD_R_ODD1          196
#define PAD_R_ODD2          197
#define PAD_R_ODD3          198
#define PAD_R_ODD4          199
#define PAD_R_ODD5          200
#define PAD_R_ODD6          201
#define PAD_R_ODD7          202
#define PAD_LCK             203
#define PAD_LDE             204
#define PAD_LHSYNC          205
#define PAD_LVSYNC          206
#define PAD_PCM_A3          207
#define PAD_PCM_A2          208
#define PAD_PCM_REG_N       209
#define PAD_PCM_A1          210
#define PAD_PCM_A0          211
#define PAD_PCM_D0          212
#define PAD_PCM_D1          213
#define PAD_PCM_D2          214
#define PAD_PCM_RESET       215
#define PAD_PCM2_RESET      216
#define PAD_PCM_CD_N        217
#define PAD_PCM2_CD_N       218
#define PAD_TS1_D0          219
#define PAD_TS1_VLD         220
#define PAD_TS1_SYNC        221
#define PAD_TS1_CLK         222
#define PAD_ET_COL          329
#define PAD_ET_TXD1         330
#define PAD_ET_TXD0         331
#define PAD_ET_TX_EN        332
#define PAD_ET_TX_CLK       333
#define PAD_ET_RXD0         334
#define PAD_I2S_IN_WS       335
#define PAD_I2S_IN_BCK      336
#define PAD_I2S_IN_SD       337
#define PAD_SPDIF_IN        338
#define PAD_I2S_OUT_MCK     339
#define PAD_I2S_OUT_WS      340
#define PAD_ET_CRS          341
#define PAD_ET_TXD3         342
#define PAD_I2S_OUT_BCK     343
#define PAD_ET_TXD2         344
#define PAD_I2S_OUT_SD      345
#define PAD_ET_TRXER        346
#define PAD_SPDIF_OUT       347
#define PAD_ET_RXER         348
#define PAD_DDCR_DA2        349
#define PAD_ET_RX_CLK       350
#define PAD_DDCR_CK2        351
#define PAD_ET_RX_DV        352
#define PAD_LHSYNC2         353
#define PAD_LVSYNC2         354
#define PAD_ET_RXD1         355
#define PAD_GPIO12          356
#define PAD_ET_RXD2         357
#define PAD_GPIO13          358
#define PAD_ET_RXD3         359
#define PAD_GPIO14          360
#define PAD_ET_MDC          361
#define PAD_GPIO15          362
#define PAD_ET_MDIO         363
#define PAD_GPIO_PM0        376
#define PAD_GPIO_PM1        377
#define PAD_GPIO_PM2        378
#define PAD_GPIO_PM3        379
#define PAD_GPIO_PM4        380

// PADS group name to index
#define PADS_DDCR           382
#define PADS_DDCR2          383
#define PADS_TS0            384
#define PADS_TS1            385
#define PADS_GPIO1_GPIO2    386
#define PADS_LHSYNC2_LVSYNC2 387
#define PADS_PCI_AD20_AD21  388
#define PADS_PCI            389
#define PADS_PCM            389
#define PADS_SAR            390
#define PADS_DOUT           391
#define PADS_DIN            392
#define PADS_ATCON_MODE1    393
#define PADS_ATCON_MODE2    394
#define PADS_DTCON_MODE1    395
#define PADS_FCIE_CONFIG1   396
#define PADS_FCIE_CONFIG2   397
#define PADS_I2S            398
#define PADS_PF             399
#define PADS_EMAC           400
#define PADS_UART1_MODE1    401
#define PADS_UART1_MODE2    402
#define PADS_UART1_MODE3    403
#define PADS_UART2_MODE1    404
#define PADS_UART2_MODE2    405
#define PADS_UART2_MODE3    406
#define PADS_WF_MODE1       407
#define PADS_WF_MODE2       408
#define PADS_WF_MODE3       409
#define PADS_ET_MODE0       410
#define PADS_ET_MODE1       411
#define PADS_ET_MODE2       412

// PAD index to GPIO number mapping
#define GPIO_PAD_161        GPIO_DDCD2_SDA
#define GPIO_PAD_168        GPIO_HPDC
#define GPIO_PAD_198        GPIO125
#define GPIO_PAD_3          GPIO143
#define GPIO_PAD_181        GPIO108
#define GPIO_PAD_128        GPIO25
#define GPIO_PAD_114        GPIO4
#define GPIO_PAD_117        GPIO7
#define GPIO_PAD_170        GPIO81
#define GPIO_PAD_175        GPIO47
#define GPIO_PAD_116        GPIO6
#define GPIO_PAD_129        GPIO26
#define GPIO_PAD_185        GPIO112
#define GPIO_PAD_172        GPIO82
#define GPIO_PAD_1          GPIO141
#define GPIO_PAD_112        GPIO2
#define GPIO_PAD_188        GPIO115
#define GPIO_PAD_370        GPIO146
#define GPIO_PAD_77         GPIO_DDCA0_SCL
#define GPIO_PAD_121        GPIO11
#define GPIO_PAD_125        GPIO22
#define GPIO_PAD_18         GPIO_HPDB
#define GPIO_PAD_372        GPIO148
#define GPIO_PAD_148        GPIO44
#define GPIO_PAD_195        GPIO122
#define GPIO_PAD_23         GPIO_DDCD1_SCL
#define GPIO_PAD_189        GPIO116
#define GPIO_PAD_120        GPIO10
#define GPIO_PAD_380        GPIO138
#define GPIO_PAD_192        GPIO119
#define GPIO_PAD_173        GPIO45
#define GPIO_PAD_176        GPIO48
#define GPIO_PAD_4          GPIO144
#define GPIO_PAD_127        GPIO24
#define GPIO_PAD_200        GPIO127
#define GPIO_PAD_6          GPIO140
#define GPIO_PAD_187        GPIO114
#define GPIO_PAD_130        GPIO27
#define GPIO_PAD_118        GPIO8
#define GPIO_PAD_2          GPIO142
#define GPIO_PAD_115        GPIO5
#define GPIO_PAD_133        GPIO30
#define GPIO_PAD_194        GPIO121
#define GPIO_PAD_184        GPIO111
#define GPIO_PAD_158        GPIO_DDCD2_SCL
#define GPIO_PAD_15         GPIO_DDCD1_SDA
#define GPIO_PAD_180        GPIO107
#define GPIO_PAD_373        GPIO149
#define GPIO_PAD_132        GPIO29
#define GPIO_PAD_34         GPIO_DDCD0_SDA
#define GPIO_PAD_202        GPIO129
#define GPIO_PAD_191        GPIO118
#define GPIO_PAD_137        GPIO34
#define GPIO_PAD_122        GPIO12
#define GPIO_PAD_149        GPIO0
#define GPIO_PAD_126        GPIO23
#define GPIO_PAD_171        GPIO83
#define GPIO_PAD_183        GPIO110
#define GPIO_PAD_131        GPIO28
#define GPIO_PAD_196        GPIO123
#define GPIO_PAD_371        GPIO147
#define GPIO_PAD_32         GPIO_HPDA
#define GPIO_PAD_150        GPIO1
#define GPIO_PAD_113        GPIO3
#define GPIO_PAD_190        GPIO117
#define GPIO_PAD_201        GPIO128
#define GPIO_PAD_178        GPIO50
#define GPIO_PAD_193        GPIO120
#define GPIO_PAD_186        GPIO113
#define GPIO_PAD_174        GPIO46
#define GPIO_PAD_119        GPIO9
#define GPIO_PAD_182        GPIO109
#define GPIO_PAD_197        GPIO124
#define GPIO_PAD_169        GPIO80
#define GPIO_PAD_177        GPIO49
#define GPIO_PAD_199        GPIO126
#define GPIO_PAD_76         GPIO_DDCA0_SDA
#define GPIO_PAD_35         GPIO_DDCD0_SCL
#define GPIO_PAD_179        GPIO106
#define GPIO_PAD_5          GPIO139
#define GPIO_PAD_9999       GPIO_NC

// default GPIO setting
#define PAD_ET_TXD3_IS_GPIO 0
#ifndef PIN_117_IS_GPIO
#define PIN_117_IS_GPIO 0
#endif
#ifndef PAD_DDCDC_DA_IS_GPIO
#define PAD_DDCDC_DA_IS_GPIO PIN_117_IS_GPIO
#endif
#ifndef PIN_126_IS_GPIO
#define PIN_126_IS_GPIO 0
#endif
#ifndef PAD_HOTPLUGC_IS_GPIO
#define PAD_HOTPLUGC_IS_GPIO PIN_126_IS_GPIO
#endif
#define PAD_LHSYNC2_IS_GPIO 0
#define PAD_PCM_A13_IS_GPIO 0
#define PAD_PCM_IOWR_N_IS_GPIO 0
#ifndef PIN_157_IS_GPIO
#define PIN_157_IS_GPIO 0
#endif
#ifndef PAD_R_ODD3_IS_GPIO
#define PAD_R_ODD3_IS_GPIO PIN_157_IS_GPIO
#endif
#ifndef PIN_5_IS_GPIO
#define PIN_5_IS_GPIO   0
#endif
#ifndef PAD_GPIO_PM9_IS_GPIO
#define PAD_GPIO_PM9_IS_GPIO PIN_5_IS_GPIO
#endif
#ifndef PIN_139_IS_GPIO
#define PIN_139_IS_GPIO 0
#endif
#ifndef PAD_B_ODD2_IS_GPIO
#define PAD_B_ODD2_IS_GPIO PIN_139_IS_GPIO
#endif
#ifndef PIN_102_IS_GPIO
#define PIN_102_IS_GPIO 0
#endif
#ifndef PAD_PCM_CE_N_IS_GPIO
#define PAD_PCM_CE_N_IS_GPIO PIN_102_IS_GPIO
#endif
#ifndef PIN_90_IS_GPIO
#define PIN_90_IS_GPIO  0
#endif
#ifndef PAD_TS0_D2_IS_GPIO
#define PAD_TS0_D2_IS_GPIO PIN_90_IS_GPIO
#endif
#define PAD_PCM_IRQA_N_IS_GPIO 0
#ifndef PIN_93_IS_GPIO
#define PIN_93_IS_GPIO  0
#endif
#ifndef PAD_TS0_D5_IS_GPIO
#define PAD_TS0_D5_IS_GPIO PIN_93_IS_GPIO
#endif
#define PAD_ET_RX_CLK_IS_GPIO 0
#ifndef PIN_128_IS_GPIO
#define PIN_128_IS_GPIO 0
#endif
#ifndef PAD_SPI_DI_IS_GPIO
#define PAD_SPI_DI_IS_GPIO PIN_128_IS_GPIO
#endif
#ifndef PIN_133_IS_GPIO
#define PIN_133_IS_GPIO 0
#endif
#ifndef PAD_PWM2_IS_GPIO
#define PAD_PWM2_IS_GPIO PIN_133_IS_GPIO
#endif
#define PAD_ET_RXD2_IS_GPIO 0
#ifndef PIN_92_IS_GPIO
#define PIN_92_IS_GPIO  0
#endif
#ifndef PAD_TS0_D4_IS_GPIO
#define PAD_TS0_D4_IS_GPIO PIN_92_IS_GPIO
#endif
#ifndef PIN_103_IS_GPIO
#define PIN_103_IS_GPIO 0
#endif
#ifndef PAD_PCM_A10_IS_GPIO
#define PAD_PCM_A10_IS_GPIO PIN_103_IS_GPIO
#endif
#ifndef PIN_143_IS_GPIO
#define PIN_143_IS_GPIO 0
#endif
#ifndef PAD_B_ODD6_IS_GPIO
#define PAD_B_ODD6_IS_GPIO PIN_143_IS_GPIO
#endif
#ifndef PIN_130_IS_GPIO
#define PIN_130_IS_GPIO 0
#endif
#ifndef PAD_SPI_CZ_IS_GPIO
#define PAD_SPI_CZ_IS_GPIO PIN_130_IS_GPIO
#endif
#define PAD_ET_CRS_IS_GPIO 0
#ifndef PIN_3_IS_GPIO
#define PIN_3_IS_GPIO   0
#endif
#ifndef PAD_GPIO_PM7_IS_GPIO
#define PAD_GPIO_PM7_IS_GPIO PIN_3_IS_GPIO
#endif
#ifndef PIN_88_IS_GPIO
#define PIN_88_IS_GPIO  0
#endif
#ifndef PAD_TS0_D0_IS_GPIO
#define PAD_TS0_D0_IS_GPIO PIN_88_IS_GPIO
#endif
#ifndef PIN_146_IS_GPIO
#define PIN_146_IS_GPIO 0
#endif
#ifndef PAD_G_ODD1_IS_GPIO
#define PAD_G_ODD1_IS_GPIO PIN_146_IS_GPIO
#endif
#define PAD_ET_RXER_IS_GPIO 0
#ifndef PIN_290_IS_GPIO
#define PIN_290_IS_GPIO 0
#endif
#ifndef PAD_SAR0_IS_GPIO
#define PAD_SAR0_IS_GPIO PIN_290_IS_GPIO
#endif
#define PAD_ET_MDC_IS_GPIO 0
#ifndef PIN_63_IS_GPIO
#define PIN_63_IS_GPIO  0
#endif
#ifndef PAD_DDCA_CK_IS_GPIO
#define PAD_DDCA_CK_IS_GPIO PIN_63_IS_GPIO
#endif
#define PAD_TS1_D0_IS_GPIO 0
#ifndef PIN_97_IS_GPIO
#define PIN_97_IS_GPIO  0
#endif
#ifndef PAD_TS0_SYNC_IS_GPIO
#define PAD_TS0_SYNC_IS_GPIO PIN_97_IS_GPIO
#endif
#ifndef PIN_99_IS_GPIO
#define PIN_99_IS_GPIO  0
#endif
#ifndef PAD_PCM_D5_IS_GPIO
#define PAD_PCM_D5_IS_GPIO PIN_99_IS_GPIO
#endif
#ifndef PIN_18_IS_GPIO
#define PIN_18_IS_GPIO  0
#endif
#ifndef PAD_HOTPLUGB_IS_GPIO
#define PAD_HOTPLUGB_IS_GPIO PIN_18_IS_GPIO
#endif
#define PAD_ET_COL_IS_GPIO 0
#define PAD_I2S_IN_BCK_IS_GPIO 0
#define PAD_PF_WEZ_IS_GPIO 0
#ifndef PIN_292_IS_GPIO
#define PIN_292_IS_GPIO 0
#endif
#ifndef PAD_SAR2_IS_GPIO
#define PAD_SAR2_IS_GPIO PIN_292_IS_GPIO
#endif
#define PAD_TS1_SYNC_IS_GPIO 0
#define PAD_PCM_D2_IS_GPIO 0
#define PAD_DDCR_DA2_IS_GPIO 0
#define PAD_TS1_VLD_IS_GPIO 0
#ifndef PIN_110_IS_GPIO
#define PIN_110_IS_GPIO 0
#endif
#ifndef PAD_PCM2_WAIT_N_IS_GPIO
#define PAD_PCM2_WAIT_N_IS_GPIO PIN_110_IS_GPIO
#endif
#ifndef PIN_154_IS_GPIO
#define PIN_154_IS_GPIO 0
#endif
#ifndef PAD_R_ODD0_IS_GPIO
#define PAD_R_ODD0_IS_GPIO PIN_154_IS_GPIO
#endif
#define PAD_ET_MDIO_IS_GPIO 0
#ifndef PIN_24_IS_GPIO
#define PIN_24_IS_GPIO  0
#endif
#ifndef PAD_DDCDB_CK_IS_GPIO
#define PAD_DDCDB_CK_IS_GPIO PIN_24_IS_GPIO
#endif
#ifndef PIN_147_IS_GPIO
#define PIN_147_IS_GPIO 0
#endif
#ifndef PAD_G_ODD2_IS_GPIO
#define PAD_G_ODD2_IS_GPIO PIN_147_IS_GPIO
#endif
#define PAD_PCM_A3_IS_GPIO 0
#define PAD_ET_TX_EN_IS_GPIO 0
#define PAD_PCM2_IRQA_N_IS_GPIO 0
#define PAD_PCM_A12_IS_GPIO 0
#define PAD_LDE_IS_GPIO 0
#define PAD_GPIO13_IS_GPIO 0
#define PAD_LHSYNC_IS_GPIO 0
#ifndef PIN_96_IS_GPIO
#define PIN_96_IS_GPIO  0
#endif
#ifndef PAD_TS0_VLD_IS_GPIO
#define PAD_TS0_VLD_IS_GPIO PIN_96_IS_GPIO
#endif
#define PAD_PF_CE1Z_IS_GPIO 0
#ifndef PIN_1_IS_GPIO
#define PIN_1_IS_GPIO   0
#endif
#ifndef PAD_GPIO_PM4_IS_GPIO
#define PAD_GPIO_PM4_IS_GPIO PIN_1_IS_GPIO
#endif
#ifndef PIN_151_IS_GPIO
#define PIN_151_IS_GPIO 0
#endif
#ifndef PAD_G_ODD5_IS_GPIO
#define PAD_G_ODD5_IS_GPIO PIN_151_IS_GPIO
#endif
#define PAD_ET_TXER_IS_GPIO 0
#define PAD_DDCR_CK2_IS_GPIO 0
#ifndef PIN_131_IS_GPIO
#define PIN_131_IS_GPIO 0
#endif
#ifndef PAD_PWM0_IS_GPIO
#define PAD_PWM0_IS_GPIO PIN_131_IS_GPIO
#endif
#ifndef PIN_134_IS_GPIO
#define PIN_134_IS_GPIO 0
#endif
#ifndef PAD_PWM3_IS_GPIO
#define PAD_PWM3_IS_GPIO PIN_134_IS_GPIO
#endif
#ifndef PIN_6_IS_GPIO
#define PIN_6_IS_GPIO   0
#endif
#ifndef PAD_GPIO_PM10_IS_GPIO
#define PAD_GPIO_PM10_IS_GPIO PIN_6_IS_GPIO
#endif
#ifndef PIN_101_IS_GPIO
#define PIN_101_IS_GPIO 0
#endif
#ifndef PAD_PCM_D7_IS_GPIO
#define PAD_PCM_D7_IS_GPIO PIN_101_IS_GPIO
#endif
#define PAD_ET_TX_CLK_IS_GPIO 0
#define PAD_PCM_A6_IS_GPIO 0
#define PAD_ET_TXD0_IS_GPIO 0
#define PAD_GPIO15_IS_GPIO 0
#define PAD_PCM_A0_IS_GPIO 0
#define PAD_PCM_A5_IS_GPIO 0
#define PAD_GPIO_PM1_IS_GPIO 0
#ifndef PIN_159_IS_GPIO
#define PIN_159_IS_GPIO 0
#endif
#ifndef PAD_R_ODD5_IS_GPIO
#define PAD_R_ODD5_IS_GPIO PIN_159_IS_GPIO
#endif
#ifndef PIN_8_IS_GPIO
#define PIN_8_IS_GPIO   0
#endif
#ifndef PAD_GPIO_PM6_IS_GPIO
#define PAD_GPIO_PM6_IS_GPIO PIN_8_IS_GPIO
#endif
#ifndef PIN_145_IS_GPIO
#define PIN_145_IS_GPIO 0
#endif
#ifndef PAD_G_ODD0_IS_GPIO
#define PAD_G_ODD0_IS_GPIO PIN_145_IS_GPIO
#endif
#ifndef PIN_104_IS_GPIO
#define PIN_104_IS_GPIO 0
#endif
#ifndef PAD_PCM_OE_N_IS_GPIO
#define PAD_PCM_OE_N_IS_GPIO PIN_104_IS_GPIO
#endif
#ifndef PIN_94_IS_GPIO
#define PIN_94_IS_GPIO  0
#endif
#ifndef PAD_TS0_D6_IS_GPIO
#define PAD_TS0_D6_IS_GPIO PIN_94_IS_GPIO
#endif
#ifndef PIN_4_IS_GPIO
#define PIN_4_IS_GPIO   0
#endif
#ifndef PAD_GPIO_PM8_IS_GPIO
#define PAD_GPIO_PM8_IS_GPIO PIN_4_IS_GPIO
#endif
#define PAD_GPIO12_IS_GPIO 0
#ifndef PIN_91_IS_GPIO
#define PIN_91_IS_GPIO  0
#endif
#ifndef PAD_TS0_D3_IS_GPIO
#define PAD_TS0_D3_IS_GPIO PIN_91_IS_GPIO
#endif
#ifndef PIN_108_IS_GPIO
#define PIN_108_IS_GPIO 0
#endif
#ifndef PAD_PCM_A9_IS_GPIO
#define PAD_PCM_A9_IS_GPIO PIN_108_IS_GPIO
#endif
#ifndef PIN_153_IS_GPIO
#define PIN_153_IS_GPIO 0
#endif
#ifndef PAD_G_ODD7_IS_GPIO
#define PAD_G_ODD7_IS_GPIO PIN_153_IS_GPIO
#endif
#define PAD_I2S_OUT_SD_IS_GPIO 0
#define PAD_ET_RXD3_IS_GPIO 0
#define PAD_PF_OEZ_IS_GPIO 0
#ifndef PIN_142_IS_GPIO
#define PIN_142_IS_GPIO 0
#endif
#ifndef PAD_B_ODD5_IS_GPIO
#define PAD_B_ODD5_IS_GPIO PIN_142_IS_GPIO
#endif
#ifndef PIN_114_IS_GPIO
#define PIN_114_IS_GPIO 0
#endif
#ifndef PAD_DDCDC_CK_IS_GPIO
#define PAD_DDCDC_CK_IS_GPIO PIN_114_IS_GPIO
#endif
#define PAD_PCM_D0_IS_GPIO 0
#ifndef PIN_15_IS_GPIO
#define PIN_15_IS_GPIO  0
#endif
#ifndef PAD_DDCDB_DA_IS_GPIO
#define PAD_DDCDB_DA_IS_GPIO PIN_15_IS_GPIO
#endif
#ifndef PIN_138_IS_GPIO
#define PIN_138_IS_GPIO 0
#endif
#ifndef PAD_B_ODD1_IS_GPIO
#define PAD_B_ODD1_IS_GPIO PIN_138_IS_GPIO
#endif
#ifndef PIN_293_IS_GPIO
#define PIN_293_IS_GPIO 0
#endif
#ifndef PAD_SAR3_IS_GPIO
#define PAD_SAR3_IS_GPIO PIN_293_IS_GPIO
#endif
#ifndef PIN_107_IS_GPIO
#define PIN_107_IS_GPIO 0
#endif
#ifndef PAD_PCM_IORD_N_IS_GPIO
#define PAD_PCM_IORD_N_IS_GPIO PIN_107_IS_GPIO
#endif
#define PAD_I2S_IN_SD_IS_GPIO 0
#ifndef PIN_37_IS_GPIO
#define PIN_37_IS_GPIO  0
#endif
#ifndef PAD_DDCDA_DA_IS_GPIO
#define PAD_DDCDA_DA_IS_GPIO PIN_37_IS_GPIO
#endif
#define PAD_LVSYNC2_IS_GPIO 0
#define PAD_I2S_OUT_BCK_IS_GPIO 0
#define PAD_I2S_OUT_WS_IS_GPIO 0
#ifndef PIN_161_IS_GPIO
#define PIN_161_IS_GPIO 0
#endif
#ifndef PAD_R_ODD7_IS_GPIO
#define PAD_R_ODD7_IS_GPIO PIN_161_IS_GPIO
#endif
#define PAD_PCM_D1_IS_GPIO 0
#ifndef PIN_150_IS_GPIO
#define PIN_150_IS_GPIO 0
#endif
#ifndef PAD_G_ODD4_IS_GPIO
#define PAD_G_ODD4_IS_GPIO PIN_150_IS_GPIO
#endif
#ifndef PIN_109_IS_GPIO
#define PIN_109_IS_GPIO 0
#endif
#ifndef PAD_PCM_A14_IS_GPIO
#define PAD_PCM_A14_IS_GPIO PIN_109_IS_GPIO
#endif
#define PAD_ET_RXD0_IS_GPIO 0
#define PAD_ET_TXD2_IS_GPIO 0
#define PAD_PCM_D3_IS_GPIO 0
#define PAD_PCM2_CD_N_IS_GPIO 0
#ifndef PIN_98_IS_GPIO
#define PIN_98_IS_GPIO  0
#endif
#ifndef PAD_TS0_CLK_IS_GPIO
#define PAD_TS0_CLK_IS_GPIO PIN_98_IS_GPIO
#endif
#ifndef PIN_112_IS_GPIO
#define PIN_112_IS_GPIO 0
#endif
#ifndef PAD_UART_RX2_IS_GPIO
#define PAD_UART_RX2_IS_GPIO PIN_112_IS_GPIO
#endif
#ifndef PIN_100_IS_GPIO
#define PIN_100_IS_GPIO 0
#endif
#ifndef PAD_PCM_D6_IS_GPIO
#define PAD_PCM_D6_IS_GPIO PIN_100_IS_GPIO
#endif
#ifndef PIN_129_IS_GPIO
#define PIN_129_IS_GPIO 0
#endif
#ifndef PAD_SPI_DO_IS_GPIO
#define PAD_SPI_DO_IS_GPIO PIN_129_IS_GPIO
#endif
#define PAD_PF_ALE_IS_GPIO 0
#define PAD_ET_RXD1_IS_GPIO 0
#ifndef PIN_141_IS_GPIO
#define PIN_141_IS_GPIO 0
#endif
#ifndef PAD_B_ODD4_IS_GPIO
#define PAD_B_ODD4_IS_GPIO PIN_141_IS_GPIO
#endif
#define PAD_PCM_A2_IS_GPIO 0
#define PAD_PCM_WAIT_N_IS_GPIO 0
#define PAD_TS1_CLK_IS_GPIO 0
#define PAD_F_RBZ_IS_GPIO 0
#ifndef PIN_106_IS_GPIO
#define PIN_106_IS_GPIO 0
#endif
#ifndef PAD_PCM_A11_IS_GPIO
#define PAD_PCM_A11_IS_GPIO PIN_106_IS_GPIO
#endif
#define PAD_PCM_A4_IS_GPIO 0
#define PAD_PF_AD15_IS_GPIO 0
#ifndef PIN_155_IS_GPIO
#define PIN_155_IS_GPIO 0
#endif
#ifndef PAD_R_ODD1_IS_GPIO
#define PAD_R_ODD1_IS_GPIO PIN_155_IS_GPIO
#endif
#ifndef PIN_291_IS_GPIO
#define PIN_291_IS_GPIO 0
#endif
#ifndef PAD_SAR1_IS_GPIO
#define PAD_SAR1_IS_GPIO PIN_291_IS_GPIO
#endif
#define PAD_LVSYNC_IS_GPIO 0
#define PAD_PCM2_CE_N_IS_GPIO 0
#ifndef PIN_35_IS_GPIO
#define PIN_35_IS_GPIO  0
#endif
#ifndef PAD_HOTPLUGA_IS_GPIO
#define PAD_HOTPLUGA_IS_GPIO PIN_35_IS_GPIO
#endif
#ifndef PIN_113_IS_GPIO
#define PIN_113_IS_GPIO 0
#endif
#ifndef PAD_UART_TX2_IS_GPIO
#define PAD_UART_TX2_IS_GPIO PIN_113_IS_GPIO
#endif
#ifndef PIN_89_IS_GPIO
#define PIN_89_IS_GPIO  0
#endif
#ifndef PAD_TS0_D1_IS_GPIO
#define PAD_TS0_D1_IS_GPIO PIN_89_IS_GPIO
#endif
#define PAD_GPIO14_IS_GPIO 0
#ifndef PIN_148_IS_GPIO
#define PIN_148_IS_GPIO 0
#endif
#ifndef PAD_G_ODD3_IS_GPIO
#define PAD_G_ODD3_IS_GPIO PIN_148_IS_GPIO
#endif
#ifndef PIN_160_IS_GPIO
#define PIN_160_IS_GPIO 0
#endif
#ifndef PAD_R_ODD6_IS_GPIO
#define PAD_R_ODD6_IS_GPIO PIN_160_IS_GPIO
#endif
#define PAD_PCM_CD_N_IS_GPIO 0
#ifndef PIN_136_IS_GPIO
#define PIN_136_IS_GPIO 0
#endif
#ifndef PAD_DDCR_CLK_IS_GPIO
#define PAD_DDCR_CLK_IS_GPIO PIN_136_IS_GPIO
#endif
#define PAD_PCM_REG_N_IS_GPIO 0
#define PAD_PF_CE0Z_IS_GPIO 0
#define PAD_PCM_D4_IS_GPIO 0
#ifndef PIN_152_IS_GPIO
#define PIN_152_IS_GPIO 0
#endif
#ifndef PAD_G_ODD6_IS_GPIO
#define PAD_G_ODD6_IS_GPIO PIN_152_IS_GPIO
#endif
#ifndef PIN_144_IS_GPIO
#define PIN_144_IS_GPIO 0
#endif
#ifndef PAD_B_ODD7_IS_GPIO
#define PAD_B_ODD7_IS_GPIO PIN_144_IS_GPIO
#endif
#ifndef PIN_132_IS_GPIO
#define PIN_132_IS_GPIO 0
#endif
#ifndef PAD_PWM1_IS_GPIO
#define PAD_PWM1_IS_GPIO PIN_132_IS_GPIO
#endif
#define PAD_PCM2_RESET_IS_GPIO 0
#define PAD_I2S_OUT_MCK_IS_GPIO 0
#ifndef PIN_95_IS_GPIO
#define PIN_95_IS_GPIO  0
#endif
#ifndef PAD_TS0_D7_IS_GPIO
#define PAD_TS0_D7_IS_GPIO PIN_95_IS_GPIO
#endif
#ifndef PIN_140_IS_GPIO
#define PIN_140_IS_GPIO 0
#endif
#ifndef PAD_B_ODD3_IS_GPIO
#define PAD_B_ODD3_IS_GPIO PIN_140_IS_GPIO
#endif
#ifndef PIN_156_IS_GPIO
#define PIN_156_IS_GPIO 0
#endif
#ifndef PAD_R_ODD2_IS_GPIO
#define PAD_R_ODD2_IS_GPIO PIN_156_IS_GPIO
#endif
#ifndef PIN_127_IS_GPIO
#define PIN_127_IS_GPIO 0
#endif
#ifndef PAD_SPI_CK_IS_GPIO
#define PAD_SPI_CK_IS_GPIO PIN_127_IS_GPIO
#endif
#define PAD_PCM_RESET_IS_GPIO 0
#define PAD_PCM_A1_IS_GPIO 0
#define PAD_PCM_A7_IS_GPIO 0
#define PAD_LCK_IS_GPIO 0
#define PAD_SPDIF_OUT_IS_GPIO 0
#define PAD_GPIO_PM3_IS_GPIO 0
#define PAD_ET_RX_DV_IS_GPIO 0
#define PAD_PCM_A8_IS_GPIO 0
#ifndef PIN_135_IS_GPIO
#define PIN_135_IS_GPIO 0
#endif
#ifndef PAD_DDCR_DAT_IS_GPIO
#define PAD_DDCR_DAT_IS_GPIO PIN_135_IS_GPIO
#endif
#define PAD_I2S_IN_WS_IS_GPIO 0
#define PAD_GPIO_PM0_IS_GPIO 0
#define PAD_SPDIF_IN_IS_GPIO 0
#ifndef PIN_158_IS_GPIO
#define PIN_158_IS_GPIO 0
#endif
#ifndef PAD_R_ODD4_IS_GPIO
#define PAD_R_ODD4_IS_GPIO PIN_158_IS_GPIO
#endif
#define PAD_GPIO_PM2_IS_GPIO 0
#ifndef PIN_62_IS_GPIO
#define PIN_62_IS_GPIO  0
#endif
#ifndef PAD_DDCA_DA_IS_GPIO
#define PAD_DDCA_DA_IS_GPIO PIN_62_IS_GPIO
#endif
#define PAD_ET_TXD1_IS_GPIO 0
#ifndef PIN_38_IS_GPIO
#define PIN_38_IS_GPIO  0
#endif
#ifndef PAD_DDCDA_CK_IS_GPIO
#define PAD_DDCDA_CK_IS_GPIO PIN_38_IS_GPIO
#endif
#ifndef PIN_137_IS_GPIO
#define PIN_137_IS_GPIO 0
#endif
#ifndef PAD_B_ODD0_IS_GPIO
#define PAD_B_ODD0_IS_GPIO PIN_137_IS_GPIO
#endif
#ifndef PIN_7_IS_GPIO
#define PIN_7_IS_GPIO   0
#endif
#ifndef PAD_GPIO_PM5_IS_GPIO
#define PAD_GPIO_PM5_IS_GPIO PIN_7_IS_GPIO
#endif

// chip capbilities
#define CHIP_HAS_BT656_IN          0
#define CHIP_HAS_TS0               1 // PIN# 98 97 96 88 89 90 91 92 93 94 95
#define CHIP_HAS_TS1               0
#define CHIP_HAS_LVDS_10BIT_X2     1
#define CHIP_HAS_LVDS_8BIT_X2      1
#define CHIP_HAS_LVDS_8BIT_X1      1
#define CHIP_HAS_DTCON_MODE1       0
#define CHIP_HAS_ATCON_MODE1       0
#define CHIP_HAS_ATCON_MODE2       0
#define CHIP_HAS_CCFL              0
#define CHIP_HAS_CIMAX             0
#define CHIP_HAS_FCIE_CONFIG1      0
#define CHIP_HAS_FCIE_CONFIG2      0
#define CHIP_HAS_USB               1
#define CHIP_HAS_UART1_MODE1       0
#define CHIP_HAS_UART1_MODE2       0
#define CHIP_HAS_UART1_MODE3       0
#define CHIP_HAS_PCMCIA1           0
#define CHIP_HAS_PCMCIA2           0
#define CHIP_HAS_PCMCIA            0
#define CHIP_HAS_UART2_MODE1       1 // PIN# 112 113
#define CHIP_HAS_UART2_MODE2       0
#define CHIP_HAS_UART2_MODE3       0
#define CHIP_HAS_RGB_A             1 // PIN# 48 45 43 46
#define CHIP_HAS_RGB_B             0
#define CHIP_HAS_RGB_C             0
#define CHIP_HAS_HDMI_A            1 // PIN# 25 26 27 28 30 31 33 34 36 37 38
#define CHIP_HAS_HDMI_B            1 // PIN# 13 14 16 17 19 20 22 23 36 15 24
#define CHIP_HAS_HDMI_C            1 // PIN# 115 116 118 119 121 122 124 125 36 117 114
#define CHIP_HAS_SPI_CZ1           1 // PIN# 112 99
#define CHIP_HAS_SPI_CZ2           1 // PIN# 113 100
#define CHIP_HAS_SPI_CZ3           0
#define CHIP_HAS_DDCR              1 // PIN# 135 136
#define CHIP_HAS_DDCR2             0
#define CHIP_HAS_I2S_IN            1 // PIN# 99 100 101
#define CHIP_HAS_I2S_OUT           1 // PIN# 104 106 107 108
#define CHIP_HAS_SPDIF_IN          1 // PIN# 102
#define CHIP_HAS_SPDIF_OUT         1 // PIN# 103
#define CHIP_HAS_DDR_A_CMD         1
#define CHIP_HAS_DDR_A_DATA        1
#define CHIP_HAS_DDR_B_CMD         1
#define CHIP_HAS_DDR_B_DATA        1
#define CHIP_USE_PCM_CDN_IN_PCM2   0
#define CHIP_USE_I2S_IN_IN_PCM     1
#define CHIP_USE_I2S_OUT_IN_PCM    1
#define CHIP_USE_SPDIF_IN_IN_PCM   1
#define CHIP_USE_SPDIF_OUT_IN_PCM  1
#define CHIP_USE_IIC_IN_DDCR2      0
#define CHIP_USE_PWM2_IN_GPIO14    0
#define CHIP_USE_PWM3_IN_GPIO15    0

// chip additional information
#define BONDING_TYPE               BONDING_MSD3063EQ
#define CHIP_FAMILY_TYPE           CHIP_FAMILY_S4L

#endif /* _MSD3063EQ_H_ */
