/*
 * Automatically generated C config: don't edit
 * SBoot version: 1.0.0
 */
#define AUTOCONF_TIMESTAMP "2013-11-20 10:23:43 CST"

#define CONFIG_HAVE_DOT_CONFIG 1
#define ENABLE_HAVE_DOT_CONFIG 1
#define USE_HAVE_DOT_CONFIG(...) __VA_ARGS__
#define SKIP_HAVE_DOT_CONFIG(...)

/*
 * Platform Configuration
 */
#undef CONFIG_MSTAR_TITANIA4
#define ENABLE_MSTAR_TITANIA4 0
#define USE_MSTAR_TITANIA4(...)
#define SKIP_MSTAR_TITANIA4(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA7
#define ENABLE_MSTAR_TITANIA7 0
#define USE_MSTAR_TITANIA7(...)
#define SKIP_MSTAR_TITANIA7(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA8
#define ENABLE_MSTAR_TITANIA8 0
#define USE_MSTAR_TITANIA8(...)
#define SKIP_MSTAR_TITANIA8(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA9
#define ENABLE_MSTAR_TITANIA9 0
#define USE_MSTAR_TITANIA9(...)
#define SKIP_MSTAR_TITANIA9(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA12
#define ENABLE_MSTAR_TITANIA12 0
#define USE_MSTAR_TITANIA12(...)
#define SKIP_MSTAR_TITANIA12(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA13
#define ENABLE_MSTAR_TITANIA13 0
#define USE_MSTAR_TITANIA13(...)
#define SKIP_MSTAR_TITANIA13(...) __VA_ARGS__
#undef CONFIG_MSTAR_AMBER1
#define ENABLE_MSTAR_AMBER1 0
#define USE_MSTAR_AMBER1(...)
#define SKIP_MSTAR_AMBER1(...) __VA_ARGS__
#undef CONFIG_MSTAR_AMBER2
#define ENABLE_MSTAR_AMBER2 0
#define USE_MSTAR_AMBER2(...)
#define SKIP_MSTAR_AMBER2(...) __VA_ARGS__
#undef CONFIG_MSTAR_AMBER3
#define ENABLE_MSTAR_AMBER3 0
#define USE_MSTAR_AMBER3(...)
#define SKIP_MSTAR_AMBER3(...) __VA_ARGS__
#undef CONFIG_MSTAR_AMBER5
#define ENABLE_MSTAR_AMBER5 0
#define USE_MSTAR_AMBER5(...)
#define SKIP_MSTAR_AMBER5(...) __VA_ARGS__
#undef CONFIG_MSTAR_AMBER6
#define ENABLE_MSTAR_AMBER6 0
#define USE_MSTAR_AMBER6(...)
#define SKIP_MSTAR_AMBER6(...) __VA_ARGS__
#undef CONFIG_MSTAR_AMBER7
#define ENABLE_MSTAR_AMBER7 0
#define USE_MSTAR_AMBER7(...)
#define SKIP_MSTAR_AMBER7(...) __VA_ARGS__
#undef CONFIG_MSTAR_AMETHYST
#define ENABLE_MSTAR_AMETHYST 0
#define USE_MSTAR_AMETHYST(...)
#define SKIP_MSTAR_AMETHYST(...) __VA_ARGS__
#undef CONFIG_MSTAR_EAGLE
#define ENABLE_MSTAR_EAGLE 0
#define USE_MSTAR_EAGLE(...)
#define SKIP_MSTAR_EAGLE(...) __VA_ARGS__
#undef CONFIG_MSTAR_EIFFEL
#define ENABLE_MSTAR_EIFFEL 0
#define USE_MSTAR_EIFFEL(...)
#define SKIP_MSTAR_EIFFEL(...) __VA_ARGS__
#undef CONFIG_MSTAR_NIKE
#define ENABLE_MSTAR_NIKE 0
#define USE_MSTAR_NIKE(...)
#define SKIP_MSTAR_NIKE(...) __VA_ARGS__
#undef CONFIG_MSTAR_EMERALD
#define ENABLE_MSTAR_EMERALD 0
#define USE_MSTAR_EMERALD(...)
#define SKIP_MSTAR_EMERALD(...) __VA_ARGS__
#undef CONFIG_MSTAR_URANUS4
#define ENABLE_MSTAR_URANUS4 0
#define USE_MSTAR_URANUS4(...)
#define SKIP_MSTAR_URANUS4(...) __VA_ARGS__
#undef CONFIG_MSTAR_JANUS
#define ENABLE_MSTAR_JANUS 0
#define USE_MSTAR_JANUS(...)
#define SKIP_MSTAR_JANUS(...) __VA_ARGS__
#undef CONFIG_MSTAR_JANUS2
#define ENABLE_MSTAR_JANUS2 0
#define USE_MSTAR_JANUS2(...)
#define SKIP_MSTAR_JANUS2(...) __VA_ARGS__
#undef CONFIG_MSTAR_MARIA10
#define ENABLE_MSTAR_MARIA10 0
#define USE_MSTAR_MARIA10(...)
#define SKIP_MSTAR_MARIA10(...) __VA_ARGS__
#undef CONFIG_MSTAR_MACAW12
#define ENABLE_MSTAR_MACAW12 0
#define USE_MSTAR_MACAW12(...)
#define SKIP_MSTAR_MACAW12(...) __VA_ARGS__
#undef CONFIG_MSTAR_EDEN
#define ENABLE_MSTAR_EDEN 0
#define USE_MSTAR_EDEN(...)
#define SKIP_MSTAR_EDEN(...) __VA_ARGS__
#undef CONFIG_MSTAR_EULER
#define ENABLE_MSTAR_EULER 0
#define USE_MSTAR_EULER(...)
#define SKIP_MSTAR_EULER(...) __VA_ARGS__
#undef CONFIG_MSTAR_AGATE
#define ENABLE_MSTAR_AGATE 0
#define USE_MSTAR_AGATE(...)
#define SKIP_MSTAR_AGATE(...) __VA_ARGS__
#undef CONFIG_MSTAR_KRONUS
#define ENABLE_MSTAR_KRONUS 0
#define USE_MSTAR_KRONUS(...)
#define SKIP_MSTAR_KRONUS(...) __VA_ARGS__
#undef CONFIG_MSTAR_KAISERIN
#define ENABLE_MSTAR_KAISERIN 0
#define USE_MSTAR_KAISERIN(...)
#define SKIP_MSTAR_KAISERIN(...) __VA_ARGS__
#define CONFIG_MSTAR_EDISON 1
#define ENABLE_MSTAR_EDISON 1
#define USE_MSTAR_EDISON(...) __VA_ARGS__
#define SKIP_MSTAR_EDISON(...)
#undef CONFIG_MSTAR_EINSTEIN
#define ENABLE_MSTAR_EINSTEIN 0
#define USE_MSTAR_EINSTEIN(...)
#define SKIP_MSTAR_EINSTEIN(...) __VA_ARGS__
#define CONFIG_MSTAR_CHIP_NAME "edison"
#define ENABLE_MSTAR_CHIP_NAME 1
#define USE_MSTAR_CHIP_NAME(...) __VA_ARGS__
#define SKIP_MSTAR_CHIP_NAME(...)
#undef CONFIG_MCU_MIPS32
#define ENABLE_MCU_MIPS32 0
#define USE_MCU_MIPS32(...)
#define SKIP_MCU_MIPS32(...) __VA_ARGS__
#define CONFIG_MCU_ARM 1
#define ENABLE_MCU_ARM 1
#define USE_MCU_ARM(...) __VA_ARGS__
#define SKIP_MCU_ARM(...)
#undef CONFIG_MCU_AEONR2
#define ENABLE_MCU_AEONR2 0
#define USE_MCU_AEONR2(...)
#define SKIP_MCU_AEONR2(...) __VA_ARGS__
#define CONFIG_BOOTING_FROM_EXT_SPI_WITH_CPU 1
#define ENABLE_BOOTING_FROM_EXT_SPI_WITH_CPU 1
#define USE_BOOTING_FROM_EXT_SPI_WITH_CPU(...) __VA_ARGS__
#define SKIP_BOOTING_FROM_EXT_SPI_WITH_CPU(...)
#undef CONFIG_BOOTING_FROM_EXT_SPI_WITH_PM51
#define ENABLE_BOOTING_FROM_EXT_SPI_WITH_PM51 0
#define USE_BOOTING_FROM_EXT_SPI_WITH_PM51(...)
#define SKIP_BOOTING_FROM_EXT_SPI_WITH_PM51(...) __VA_ARGS__
#undef CONFIG_BOOTING_FROM_OTP_WITH_PM51
#define ENABLE_BOOTING_FROM_OTP_WITH_PM51 0
#define USE_BOOTING_FROM_OTP_WITH_PM51(...)
#define SKIP_BOOTING_FROM_OTP_WITH_PM51(...) __VA_ARGS__
#undef CONFIG_MSTAR_ROM_BOOT_WITH_NAND_FLASH
#define ENABLE_MSTAR_ROM_BOOT_WITH_NAND_FLASH 0
#define USE_MSTAR_ROM_BOOT_WITH_NAND_FLASH(...)
#define SKIP_MSTAR_ROM_BOOT_WITH_NAND_FLASH(...) __VA_ARGS__
#undef CONFIG_MSTAR_ROM_BOOT_WITH_EMMC_FLASH
#define ENABLE_MSTAR_ROM_BOOT_WITH_EMMC_FLASH 0
#define USE_MSTAR_ROM_BOOT_WITH_EMMC_FLASH(...)
#define SKIP_MSTAR_ROM_BOOT_WITH_EMMC_FLASH(...) __VA_ARGS__
#undef CONFIG_BOOTING_FROM_EXT_EMMC_WITH_CPU
#define ENABLE_BOOTING_FROM_EXT_EMMC_WITH_CPU 0
#define USE_BOOTING_FROM_EXT_EMMC_WITH_CPU(...)
#define SKIP_BOOTING_FROM_EXT_EMMC_WITH_CPU(...) __VA_ARGS__
#define CONFIG_MBOOT_IN_SPI_FLASH 1
#define ENABLE_MBOOT_IN_SPI_FLASH 1
#define USE_MBOOT_IN_SPI_FLASH(...) __VA_ARGS__
#define SKIP_MBOOT_IN_SPI_FLASH(...)
#undef CONFIG_MBOOT_IN_NAND_FLASH
#define ENABLE_MBOOT_IN_NAND_FLASH 0
#define USE_MBOOT_IN_NAND_FLASH(...)
#define SKIP_MBOOT_IN_NAND_FLASH(...) __VA_ARGS__
#undef CONFIG_MBOOT_IN_MMC_FLASH
#define ENABLE_MBOOT_IN_MMC_FLASH 0
#define USE_MBOOT_IN_MMC_FLASH(...)
#define SKIP_MBOOT_IN_MMC_FLASH(...) __VA_ARGS__
#define CONFIG_CPU_1152MHZ 1
#define ENABLE_CPU_1152MHZ 1
#define USE_CPU_1152MHZ(...) __VA_ARGS__
#define SKIP_CPU_1152MHZ(...)
#undef CONFIG_CPU_1044MHZ
#define ENABLE_CPU_1044MHZ 0
#define USE_CPU_1044MHZ(...)
#define SKIP_CPU_1044MHZ(...) __VA_ARGS__
#undef CONFIG_CPU_1008MHZ
#define ENABLE_CPU_1008MHZ 0
#define USE_CPU_1008MHZ(...)
#define SKIP_CPU_1008MHZ(...) __VA_ARGS__
#undef CONFIG_CPU_900MHZ
#define ENABLE_CPU_900MHZ 0
#define USE_CPU_900MHZ(...)
#define SKIP_CPU_900MHZ(...) __VA_ARGS__
#undef CONFIG_CPU_888MHZ
#define ENABLE_CPU_888MHZ 0
#define USE_CPU_888MHZ(...)
#define SKIP_CPU_888MHZ(...) __VA_ARGS__
#undef CONFIG_CPU_876MHZ
#define ENABLE_CPU_876MHZ 0
#define USE_CPU_876MHZ(...)
#define SKIP_CPU_876MHZ(...) __VA_ARGS__
#undef CONFIG_CPU_864MHZ
#define ENABLE_CPU_864MHZ 0
#define USE_CPU_864MHZ(...)
#define SKIP_CPU_864MHZ(...) __VA_ARGS__
#undef CONFIG_CPU_852MHZ
#define ENABLE_CPU_852MHZ 0
#define USE_CPU_852MHZ(...)
#define SKIP_CPU_852MHZ(...) __VA_ARGS__
#undef CONFIG_CPU_840MHZ
#define ENABLE_CPU_840MHZ 0
#define USE_CPU_840MHZ(...)
#define SKIP_CPU_840MHZ(...) __VA_ARGS__
#undef CONFIG_CPU_828MHZ
#define ENABLE_CPU_828MHZ 0
#define USE_CPU_828MHZ(...)
#define SKIP_CPU_828MHZ(...) __VA_ARGS__
#undef CONFIG_CPU_816MHZ
#define ENABLE_CPU_816MHZ 0
#define USE_CPU_816MHZ(...)
#define SKIP_CPU_816MHZ(...) __VA_ARGS__
#undef CONFIG_CPU_804MHZ
#define ENABLE_CPU_804MHZ 0
#define USE_CPU_804MHZ(...)
#define SKIP_CPU_804MHZ(...) __VA_ARGS__
#undef CONFIG_CPU_792MHZ
#define ENABLE_CPU_792MHZ 0
#define USE_CPU_792MHZ(...)
#define SKIP_CPU_792MHZ(...) __VA_ARGS__
#undef CONFIG_CPU_780MHZ
#define ENABLE_CPU_780MHZ 0
#define USE_CPU_780MHZ(...)
#define SKIP_CPU_780MHZ(...) __VA_ARGS__
#undef CONFIG_CPU_768MHZ
#define ENABLE_CPU_768MHZ 0
#define USE_CPU_768MHZ(...)
#define SKIP_CPU_768MHZ(...) __VA_ARGS__
#undef CONFIG_CPU_756MHZ
#define ENABLE_CPU_756MHZ 0
#define USE_CPU_756MHZ(...)
#define SKIP_CPU_756MHZ(...) __VA_ARGS__
#undef CONFIG_CPU_744MHZ
#define ENABLE_CPU_744MHZ 0
#define USE_CPU_744MHZ(...)
#define SKIP_CPU_744MHZ(...) __VA_ARGS__
#undef CONFIG_CPU_732MHZ
#define ENABLE_CPU_732MHZ 0
#define USE_CPU_732MHZ(...)
#define SKIP_CPU_732MHZ(...) __VA_ARGS__
#undef CONFIG_CPU_720MHZ
#define ENABLE_CPU_720MHZ 0
#define USE_CPU_720MHZ(...)
#define SKIP_CPU_720MHZ(...) __VA_ARGS__
#undef CONFIG_CPU_708MHZ
#define ENABLE_CPU_708MHZ 0
#define USE_CPU_708MHZ(...)
#define SKIP_CPU_708MHZ(...) __VA_ARGS__
#undef CONFIG_CPU_696MHZ
#define ENABLE_CPU_696MHZ 0
#define USE_CPU_696MHZ(...)
#define SKIP_CPU_696MHZ(...) __VA_ARGS__
#undef CONFIG_CPU_684MHZ
#define ENABLE_CPU_684MHZ 0
#define USE_CPU_684MHZ(...)
#define SKIP_CPU_684MHZ(...) __VA_ARGS__
#undef CONFIG_CPU_672MHZ
#define ENABLE_CPU_672MHZ 0
#define USE_CPU_672MHZ(...)
#define SKIP_CPU_672MHZ(...) __VA_ARGS__
#undef CONFIG_CPU_660MHZ
#define ENABLE_CPU_660MHZ 0
#define USE_CPU_660MHZ(...)
#define SKIP_CPU_660MHZ(...) __VA_ARGS__
#undef CONFIG_CPU_648MHZ
#define ENABLE_CPU_648MHZ 0
#define USE_CPU_648MHZ(...)
#define SKIP_CPU_648MHZ(...) __VA_ARGS__
#undef CONFIG_CPU_636MHZ
#define ENABLE_CPU_636MHZ 0
#define USE_CPU_636MHZ(...)
#define SKIP_CPU_636MHZ(...) __VA_ARGS__
#undef CONFIG_CPU_624MHZ
#define ENABLE_CPU_624MHZ 0
#define USE_CPU_624MHZ(...)
#define SKIP_CPU_624MHZ(...) __VA_ARGS__
#undef CONFIG_CPU_612MHZ
#define ENABLE_CPU_612MHZ 0
#define USE_CPU_612MHZ(...)
#define SKIP_CPU_612MHZ(...) __VA_ARGS__
#undef CONFIG_CPU_600MHZ
#define ENABLE_CPU_600MHZ 0
#define USE_CPU_600MHZ(...)
#define SKIP_CPU_600MHZ(...) __VA_ARGS__
#undef CONFIG_CPU_588MHZ
#define ENABLE_CPU_588MHZ 0
#define USE_CPU_588MHZ(...)
#define SKIP_CPU_588MHZ(...) __VA_ARGS__
#undef CONFIG_CPU_576MHZ
#define ENABLE_CPU_576MHZ 0
#define USE_CPU_576MHZ(...)
#define SKIP_CPU_576MHZ(...) __VA_ARGS__
#undef CONFIG_CPU_564MHZ
#define ENABLE_CPU_564MHZ 0
#define USE_CPU_564MHZ(...)
#define SKIP_CPU_564MHZ(...) __VA_ARGS__
#undef CONFIG_CPU_552MHZ
#define ENABLE_CPU_552MHZ 0
#define USE_CPU_552MHZ(...)
#define SKIP_CPU_552MHZ(...) __VA_ARGS__
#undef CONFIG_CPU_540MHZ
#define ENABLE_CPU_540MHZ 0
#define USE_CPU_540MHZ(...)
#define SKIP_CPU_540MHZ(...) __VA_ARGS__
#undef CONFIG_CPU_528MHZ
#define ENABLE_CPU_528MHZ 0
#define USE_CPU_528MHZ(...)
#define SKIP_CPU_528MHZ(...) __VA_ARGS__
#undef CONFIG_CPU_516MHZ
#define ENABLE_CPU_516MHZ 0
#define USE_CPU_516MHZ(...)
#define SKIP_CPU_516MHZ(...) __VA_ARGS__
#undef CONFIG_CPU_504MHZ
#define ENABLE_CPU_504MHZ 0
#define USE_CPU_504MHZ(...)
#define SKIP_CPU_504MHZ(...) __VA_ARGS__
#undef CONFIG_CPU_492MHZ
#define ENABLE_CPU_492MHZ 0
#define USE_CPU_492MHZ(...)
#define SKIP_CPU_492MHZ(...) __VA_ARGS__
#undef CONFIG_CPU_480MHZ
#define ENABLE_CPU_480MHZ 0
#define USE_CPU_480MHZ(...)
#define SKIP_CPU_480MHZ(...) __VA_ARGS__
#undef CONFIG_CPU_456MHZ
#define ENABLE_CPU_456MHZ 0
#define USE_CPU_456MHZ(...)
#define SKIP_CPU_456MHZ(...) __VA_ARGS__
#undef CONFIG_CPU_432MHZ
#define ENABLE_CPU_432MHZ 0
#define USE_CPU_432MHZ(...)
#define SKIP_CPU_432MHZ(...) __VA_ARGS__
#undef CONFIG_CPU_408MHZ
#define ENABLE_CPU_408MHZ 0
#define USE_CPU_408MHZ(...)
#define SKIP_CPU_408MHZ(...) __VA_ARGS__
#undef CONFIG_CPU_384MHZ
#define ENABLE_CPU_384MHZ 0
#define USE_CPU_384MHZ(...)
#define SKIP_CPU_384MHZ(...) __VA_ARGS__
#undef CONFIG_CPU_360MHZ
#define ENABLE_CPU_360MHZ 0
#define USE_CPU_360MHZ(...)
#define SKIP_CPU_360MHZ(...) __VA_ARGS__
#undef CONFIG_CPU_336MHZ
#define ENABLE_CPU_336MHZ 0
#define USE_CPU_336MHZ(...)
#define SKIP_CPU_336MHZ(...) __VA_ARGS__
#undef CONFIG_CPU_312MHZ
#define ENABLE_CPU_312MHZ 0
#define USE_CPU_312MHZ(...)
#define SKIP_CPU_312MHZ(...) __VA_ARGS__
#undef CONFIG_CPU_288MHZ
#define ENABLE_CPU_288MHZ 0
#define USE_CPU_288MHZ(...)
#define SKIP_CPU_288MHZ(...) __VA_ARGS__
#undef CONFIG_CPU_264MHZ
#define ENABLE_CPU_264MHZ 0
#define USE_CPU_264MHZ(...)
#define SKIP_CPU_264MHZ(...) __VA_ARGS__
#undef CONFIG_CPU_240MHZ
#define ENABLE_CPU_240MHZ 0
#define USE_CPU_240MHZ(...)
#define SKIP_CPU_240MHZ(...) __VA_ARGS__
#undef CONFIG_CPU_216MHZ
#define ENABLE_CPU_216MHZ 0
#define USE_CPU_216MHZ(...)
#define SKIP_CPU_216MHZ(...) __VA_ARGS__
#undef CONFIG_MSTAR_MANUAL
#define ENABLE_MSTAR_MANUAL 0
#define USE_MSTAR_MANUAL(...)
#define SKIP_MSTAR_MANUAL(...) __VA_ARGS__
#define CONFIG_MSTAR_OTHERS 0
#define ENABLE_MSTAR_OTHERS 1
#define USE_MSTAR_OTHERS(...) __VA_ARGS__
#define SKIP_MSTAR_OTHERS(...)
#undef CONFIG_MSTAR_TITANIA_BD_FPGA
#define ENABLE_MSTAR_TITANIA_BD_FPGA 0
#define USE_MSTAR_TITANIA_BD_FPGA(...)
#define SKIP_MSTAR_TITANIA_BD_FPGA(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST098A_D01A_S
#define ENABLE_MSTAR_TITANIA_BD_MST098A_D01A_S 0
#define USE_MSTAR_TITANIA_BD_MST098A_D01A_S(...)
#define SKIP_MSTAR_TITANIA_BD_MST098A_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST098B_D01A_S
#define ENABLE_MSTAR_TITANIA_BD_MST098B_D01A_S 0
#define USE_MSTAR_TITANIA_BD_MST098B_D01A_S(...)
#define SKIP_MSTAR_TITANIA_BD_MST098B_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST098B_D01A
#define ENABLE_MSTAR_TITANIA_BD_MST098B_D01A 0
#define USE_MSTAR_TITANIA_BD_MST098B_D01A(...)
#define SKIP_MSTAR_TITANIA_BD_MST098B_D01A(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST098C_D01A_S
#define ENABLE_MSTAR_TITANIA_BD_MST098C_D01A_S 0
#define USE_MSTAR_TITANIA_BD_MST098C_D01A_S(...)
#define SKIP_MSTAR_TITANIA_BD_MST098C_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST098D_D01A_S
#define ENABLE_MSTAR_TITANIA_BD_MST098D_D01A_S 0
#define USE_MSTAR_TITANIA_BD_MST098D_D01A_S(...)
#define SKIP_MSTAR_TITANIA_BD_MST098D_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST098E_D01A
#define ENABLE_MSTAR_TITANIA_BD_MST098E_D01A 0
#define USE_MSTAR_TITANIA_BD_MST098E_D01A(...)
#define SKIP_MSTAR_TITANIA_BD_MST098E_D01A(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST098E_D01B
#define ENABLE_MSTAR_TITANIA_BD_MST098E_D01B 0
#define USE_MSTAR_TITANIA_BD_MST098E_D01B(...)
#define SKIP_MSTAR_TITANIA_BD_MST098E_D01B(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_ZDT300_V01
#define ENABLE_MSTAR_TITANIA_BD_ZDT300_V01 0
#define USE_MSTAR_TITANIA_BD_ZDT300_V01(...)
#define SKIP_MSTAR_TITANIA_BD_ZDT300_V01(...) __VA_ARGS__
#undef CONFIG_MSTAR_KRONUS_BD_MST124A_D01A_S
#define ENABLE_MSTAR_KRONUS_BD_MST124A_D01A_S 0
#define USE_MSTAR_KRONUS_BD_MST124A_D01A_S(...)
#define SKIP_MSTAR_KRONUS_BD_MST124A_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_KRONUS_BD_MST124A_D02A_S
#define ENABLE_MSTAR_KRONUS_BD_MST124A_D02A_S 0
#define USE_MSTAR_KRONUS_BD_MST124A_D02A_S(...)
#define SKIP_MSTAR_KRONUS_BD_MST124A_D02A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_KRONUS_BD_MST124B_D01A_S
#define ENABLE_MSTAR_KRONUS_BD_MST124B_D01A_S 0
#define USE_MSTAR_KRONUS_BD_MST124B_D01A_S(...)
#define SKIP_MSTAR_KRONUS_BD_MST124B_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_KRONUS_BD_MST124B_D02A_S
#define ENABLE_MSTAR_KRONUS_BD_MST124B_D02A_S 0
#define USE_MSTAR_KRONUS_BD_MST124B_D02A_S(...)
#define SKIP_MSTAR_KRONUS_BD_MST124B_D02A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_KRONUS_BD_MST124B_D02A
#define ENABLE_MSTAR_KRONUS_BD_MST124B_D02A 0
#define USE_MSTAR_KRONUS_BD_MST124B_D02A(...)
#define SKIP_MSTAR_KRONUS_BD_MST124B_D02A(...) __VA_ARGS__
#undef CONFIG_MSTAR_KRONUS_BD_MST124C_D01A_S
#define ENABLE_MSTAR_KRONUS_BD_MST124C_D01A_S 0
#define USE_MSTAR_KRONUS_BD_MST124C_D01A_S(...)
#define SKIP_MSTAR_KRONUS_BD_MST124C_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_KRONUS_BD_MST124D_D01A
#define ENABLE_MSTAR_KRONUS_BD_MST124D_D01A 0
#define USE_MSTAR_KRONUS_BD_MST124D_D01A(...)
#define SKIP_MSTAR_KRONUS_BD_MST124D_D01A(...) __VA_ARGS__
#undef CONFIG_MSTAR_KRONUS_BD_MST124D_D02A_S
#define ENABLE_MSTAR_KRONUS_BD_MST124D_D02A_S 0
#define USE_MSTAR_KRONUS_BD_MST124D_D02A_S(...)
#define SKIP_MSTAR_KRONUS_BD_MST124D_D02A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_KRONUS_BD_MST124SZ
#define ENABLE_MSTAR_KRONUS_BD_MST124SZ 0
#define USE_MSTAR_KRONUS_BD_MST124SZ(...)
#define SKIP_MSTAR_KRONUS_BD_MST124SZ(...) __VA_ARGS__
#undef CONFIG_MSTAR_KRONUS_BD_MST124E_D01A_S
#define ENABLE_MSTAR_KRONUS_BD_MST124E_D01A_S 0
#define USE_MSTAR_KRONUS_BD_MST124E_D01A_S(...)
#define SKIP_MSTAR_KRONUS_BD_MST124E_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_KRONUS_BD_MST124E_D01A_SZ
#define ENABLE_MSTAR_KRONUS_BD_MST124E_D01A_SZ 0
#define USE_MSTAR_KRONUS_BD_MST124E_D01A_SZ(...)
#define SKIP_MSTAR_KRONUS_BD_MST124E_D01A_SZ(...) __VA_ARGS__
#undef CONFIG_MSTAR_KAISERIN_BD_MST138A_D01A_S
#define ENABLE_MSTAR_KAISERIN_BD_MST138A_D01A_S 0
#define USE_MSTAR_KAISERIN_BD_MST138A_D01A_S(...)
#define SKIP_MSTAR_KAISERIN_BD_MST138A_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_KAISERIN_BD_MST138B_D01A_S
#define ENABLE_MSTAR_KAISERIN_BD_MST138B_D01A_S 0
#define USE_MSTAR_KAISERIN_BD_MST138B_D01A_S(...)
#define SKIP_MSTAR_KAISERIN_BD_MST138B_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_KAISERIN_BD_MST138B_D01A
#define ENABLE_MSTAR_KAISERIN_BD_MST138B_D01A 0
#define USE_MSTAR_KAISERIN_BD_MST138B_D01A(...)
#define SKIP_MSTAR_KAISERIN_BD_MST138B_D01A(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST090A_D01A_S
#define ENABLE_MSTAR_TITANIA_BD_MST090A_D01A_S 0
#define USE_MSTAR_TITANIA_BD_MST090A_D01A_S(...)
#define SKIP_MSTAR_TITANIA_BD_MST090A_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST090B_D01A_S
#define ENABLE_MSTAR_TITANIA_BD_MST090B_D01A_S 0
#define USE_MSTAR_TITANIA_BD_MST090B_D01A_S(...)
#define SKIP_MSTAR_TITANIA_BD_MST090B_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST090C_D01A_S
#define ENABLE_MSTAR_TITANIA_BD_MST090C_D01A_S 0
#define USE_MSTAR_TITANIA_BD_MST090C_D01A_S(...)
#define SKIP_MSTAR_TITANIA_BD_MST090C_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST090D_D01A_S
#define ENABLE_MSTAR_TITANIA_BD_MST090D_D01A_S 0
#define USE_MSTAR_TITANIA_BD_MST090D_D01A_S(...)
#define SKIP_MSTAR_TITANIA_BD_MST090D_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST090E_D01A_S
#define ENABLE_MSTAR_TITANIA_BD_MST090E_D01A_S 0
#define USE_MSTAR_TITANIA_BD_MST090E_D01A_S(...)
#define SKIP_MSTAR_TITANIA_BD_MST090E_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST090F_C01A
#define ENABLE_MSTAR_TITANIA_BD_MST090F_C01A 0
#define USE_MSTAR_TITANIA_BD_MST090F_C01A(...)
#define SKIP_MSTAR_TITANIA_BD_MST090F_C01A(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MSD380B_D01A
#define ENABLE_MSTAR_TITANIA_BD_MSD380B_D01A 0
#define USE_MSTAR_TITANIA_BD_MSD380B_D01A(...)
#define SKIP_MSTAR_TITANIA_BD_MSD380B_D01A(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MSD523B_D01A
#define ENABLE_MSTAR_TITANIA_BD_MSD523B_D01A 0
#define USE_MSTAR_TITANIA_BD_MSD523B_D01A(...)
#define SKIP_MSTAR_TITANIA_BD_MSD523B_D01A(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_CUS08VL_17MB60
#define ENABLE_MSTAR_TITANIA_BD_CUS08VL_17MB60 0
#define USE_MSTAR_TITANIA_BD_CUS08VL_17MB60(...)
#define SKIP_MSTAR_TITANIA_BD_CUS08VL_17MB60(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST091A_D01A_S
#define ENABLE_MSTAR_TITANIA_BD_MST091A_D01A_S 0
#define USE_MSTAR_TITANIA_BD_MST091A_D01A_S(...)
#define SKIP_MSTAR_TITANIA_BD_MST091A_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST091B_D01A_S
#define ENABLE_MSTAR_TITANIA_BD_MST091B_D01A_S 0
#define USE_MSTAR_TITANIA_BD_MST091B_D01A_S(...)
#define SKIP_MSTAR_TITANIA_BD_MST091B_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST091C_D01A_S
#define ENABLE_MSTAR_TITANIA_BD_MST091C_D01A_S 0
#define USE_MSTAR_TITANIA_BD_MST091C_D01A_S(...)
#define SKIP_MSTAR_TITANIA_BD_MST091C_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MSD441C_T7_10A
#define ENABLE_MSTAR_TITANIA_BD_MSD441C_T7_10A 0
#define USE_MSTAR_TITANIA_BD_MSD441C_T7_10A(...)
#define SKIP_MSTAR_TITANIA_BD_MSD441C_T7_10A(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST093A_D01A_S
#define ENABLE_MSTAR_TITANIA_BD_MST093A_D01A_S 0
#define USE_MSTAR_TITANIA_BD_MST093A_D01A_S(...)
#define SKIP_MSTAR_TITANIA_BD_MST093A_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST087F_D01A_T8
#define ENABLE_MSTAR_TITANIA_BD_MST087F_D01A_T8 0
#define USE_MSTAR_TITANIA_BD_MST087F_D01A_T8(...)
#define SKIP_MSTAR_TITANIA_BD_MST087F_D01A_T8(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST105A_D01A_S
#define ENABLE_MSTAR_TITANIA_BD_MST105A_D01A_S 0
#define USE_MSTAR_TITANIA_BD_MST105A_D01A_S(...)
#define SKIP_MSTAR_TITANIA_BD_MST105A_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST105B_D01A_S
#define ENABLE_MSTAR_TITANIA_BD_MST105B_D01A_S 0
#define USE_MSTAR_TITANIA_BD_MST105B_D01A_S(...)
#define SKIP_MSTAR_TITANIA_BD_MST105B_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST105C_D01A_S
#define ENABLE_MSTAR_TITANIA_BD_MST105C_D01A_S 0
#define USE_MSTAR_TITANIA_BD_MST105C_D01A_S(...)
#define SKIP_MSTAR_TITANIA_BD_MST105C_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST105D_D01A_S
#define ENABLE_MSTAR_TITANIA_BD_MST105D_D01A_S 0
#define USE_MSTAR_TITANIA_BD_MST105D_D01A_S(...)
#define SKIP_MSTAR_TITANIA_BD_MST105D_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST116A_D01A_S
#define ENABLE_MSTAR_TITANIA_BD_MST116A_D01A_S 0
#define USE_MSTAR_TITANIA_BD_MST116A_D01A_S(...)
#define SKIP_MSTAR_TITANIA_BD_MST116A_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST011B_20ASV_S
#define ENABLE_MSTAR_TITANIA_BD_MST011B_20ASV_S 0
#define USE_MSTAR_TITANIA_BD_MST011B_20ASV_S(...)
#define SKIP_MSTAR_TITANIA_BD_MST011B_20ASV_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST011B_20ASV_DVB
#define ENABLE_MSTAR_TITANIA_BD_MST011B_20ASV_DVB 0
#define USE_MSTAR_TITANIA_BD_MST011B_20ASV_DVB(...)
#define SKIP_MSTAR_TITANIA_BD_MST011B_20ASV_DVB(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST120A_D01A_S
#define ENABLE_MSTAR_TITANIA_BD_MST120A_D01A_S 0
#define USE_MSTAR_TITANIA_BD_MST120A_D01A_S(...)
#define SKIP_MSTAR_TITANIA_BD_MST120A_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST003D_10ASV_10294
#define ENABLE_MSTAR_TITANIA_BD_MST003D_10ASV_10294 0
#define USE_MSTAR_TITANIA_BD_MST003D_10ASV_10294(...)
#define SKIP_MSTAR_TITANIA_BD_MST003D_10ASV_10294(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST120A_D01A_SKY
#define ENABLE_MSTAR_TITANIA_BD_MST120A_D01A_SKY 0
#define USE_MSTAR_TITANIA_BD_MST120A_D01A_SKY(...)
#define SKIP_MSTAR_TITANIA_BD_MST120A_D01A_SKY(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST120A_D01A_HAIER
#define ENABLE_MSTAR_TITANIA_BD_MST120A_D01A_HAIER 0
#define USE_MSTAR_TITANIA_BD_MST120A_D01A_HAIER(...)
#define SKIP_MSTAR_TITANIA_BD_MST120A_D01A_HAIER(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST105C_D01A_A2
#define ENABLE_MSTAR_TITANIA_BD_MST105C_D01A_A2 0
#define USE_MSTAR_TITANIA_BD_MST105C_D01A_A2(...)
#define SKIP_MSTAR_TITANIA_BD_MST105C_D01A_A2(...) __VA_ARGS__
#undef CONFIG_MSTAR_BD_MST147A_D01A_S_AGATE
#define ENABLE_MSTAR_BD_MST147A_D01A_S_AGATE 0
#define USE_MSTAR_BD_MST147A_D01A_S_AGATE(...)
#define SKIP_MSTAR_BD_MST147A_D01A_S_AGATE(...) __VA_ARGS__
#undef CONFIG_MSTAR_BD_MST147B_D01A_S_AGATE
#define ENABLE_MSTAR_BD_MST147B_D01A_S_AGATE 0
#define USE_MSTAR_BD_MST147B_D01A_S_AGATE(...)
#define SKIP_MSTAR_BD_MST147B_D01A_S_AGATE(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST129F_D01A1_S
#define ENABLE_MSTAR_TITANIA_BD_MST129F_D01A1_S 0
#define USE_MSTAR_TITANIA_BD_MST129F_D01A1_S(...)
#define SKIP_MSTAR_TITANIA_BD_MST129F_D01A1_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST145A_D01A1_S
#define ENABLE_MSTAR_TITANIA_BD_MST145A_D01A1_S 0
#define USE_MSTAR_TITANIA_BD_MST145A_D01A1_S(...)
#define SKIP_MSTAR_TITANIA_BD_MST145A_D01A1_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST142A_D01A_S_A3
#define ENABLE_MSTAR_TITANIA_BD_MST142A_D01A_S_A3 0
#define USE_MSTAR_TITANIA_BD_MST142A_D01A_S_A3(...)
#define SKIP_MSTAR_TITANIA_BD_MST142A_D01A_S_A3(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST145B_D01A_S
#define ENABLE_MSTAR_TITANIA_BD_MST145B_D01A_S 0
#define USE_MSTAR_TITANIA_BD_MST145B_D01A_S(...)
#define SKIP_MSTAR_TITANIA_BD_MST145B_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST028B_10AFX_A3
#define ENABLE_MSTAR_TITANIA_BD_MST028B_10AFX_A3 0
#define USE_MSTAR_TITANIA_BD_MST028B_10AFX_A3(...)
#define SKIP_MSTAR_TITANIA_BD_MST028B_10AFX_A3(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST029B_10AFVA_A3
#define ENABLE_MSTAR_TITANIA_BD_MST029B_10AFVA_A3 0
#define USE_MSTAR_TITANIA_BD_MST029B_10AFVA_A3(...)
#define SKIP_MSTAR_TITANIA_BD_MST029B_10AFVA_A3(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MS801_MAA2XG_A3
#define ENABLE_MSTAR_TITANIA_BD_MS801_MAA2XG_A3 0
#define USE_MSTAR_TITANIA_BD_MS801_MAA2XG_A3(...)
#define SKIP_MSTAR_TITANIA_BD_MS801_MAA2XG_A3(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST029B_CUS37_A3
#define ENABLE_MSTAR_TITANIA_BD_MST029B_CUS37_A3 0
#define USE_MSTAR_TITANIA_BD_MST029B_CUS37_A3(...)
#define SKIP_MSTAR_TITANIA_BD_MST029B_CUS37_A3(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST029B_CUS18_A3
#define ENABLE_MSTAR_TITANIA_BD_MST029B_CUS18_A3 0
#define USE_MSTAR_TITANIA_BD_MST029B_CUS18_A3(...)
#define SKIP_MSTAR_TITANIA_BD_MST029B_CUS18_A3(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST029B_CUS18_A3_ATSC
#define ENABLE_MSTAR_TITANIA_BD_MST029B_CUS18_A3_ATSC 0
#define USE_MSTAR_TITANIA_BD_MST029B_CUS18_A3_ATSC(...)
#define SKIP_MSTAR_TITANIA_BD_MST029B_CUS18_A3_ATSC(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MSTCUS23_6A801_A3
#define ENABLE_MSTAR_TITANIA_BD_MSTCUS23_6A801_A3 0
#define USE_MSTAR_TITANIA_BD_MSTCUS23_6A801_A3(...)
#define SKIP_MSTAR_TITANIA_BD_MSTCUS23_6A801_A3(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST029B_CUS36_A3
#define ENABLE_MSTAR_TITANIA_BD_MST029B_CUS36_A3 0
#define USE_MSTAR_TITANIA_BD_MST029B_CUS36_A3(...)
#define SKIP_MSTAR_TITANIA_BD_MST029B_CUS36_A3(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST032B_10AFX_A3
#define ENABLE_MSTAR_TITANIA_BD_MST032B_10AFX_A3 0
#define USE_MSTAR_TITANIA_BD_MST032B_10AFX_A3(...)
#define SKIP_MSTAR_TITANIA_BD_MST032B_10AFX_A3(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_CUS28_6A800
#define ENABLE_MSTAR_TITANIA_BD_CUS28_6A800 0
#define USE_MSTAR_TITANIA_BD_CUS28_6A800(...)
#define SKIP_MSTAR_TITANIA_BD_CUS28_6A800(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_CUS28_6A801
#define ENABLE_MSTAR_TITANIA_BD_CUS28_6A801 0
#define USE_MSTAR_TITANIA_BD_CUS28_6A801(...)
#define SKIP_MSTAR_TITANIA_BD_CUS28_6A801(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST029B_BOX_A3
#define ENABLE_MSTAR_TITANIA_BD_MST029B_BOX_A3 0
#define USE_MSTAR_TITANIA_BD_MST029B_BOX_A3(...)
#define SKIP_MSTAR_TITANIA_BD_MST029B_BOX_A3(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST127A_D01A_S_A5
#define ENABLE_MSTAR_TITANIA_BD_MST127A_D01A_S_A5 0
#define USE_MSTAR_TITANIA_BD_MST127A_D01A_S_A5(...)
#define SKIP_MSTAR_TITANIA_BD_MST127A_D01A_S_A5(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST129A_D01A_S
#define ENABLE_MSTAR_TITANIA_BD_MST129A_D01A_S 0
#define USE_MSTAR_TITANIA_BD_MST129A_D01A_S(...)
#define SKIP_MSTAR_TITANIA_BD_MST129A_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST129B_D01A_S
#define ENABLE_MSTAR_TITANIA_BD_MST129B_D01A_S 0
#define USE_MSTAR_TITANIA_BD_MST129B_D01A_S(...)
#define SKIP_MSTAR_TITANIA_BD_MST129B_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST129C_D01A_S
#define ENABLE_MSTAR_TITANIA_BD_MST129C_D01A_S 0
#define USE_MSTAR_TITANIA_BD_MST129C_D01A_S(...)
#define SKIP_MSTAR_TITANIA_BD_MST129C_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST129D_D01A_S
#define ENABLE_MSTAR_TITANIA_BD_MST129D_D01A_S 0
#define USE_MSTAR_TITANIA_BD_MST129D_D01A_S(...)
#define SKIP_MSTAR_TITANIA_BD_MST129D_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST129E_D01A_S
#define ENABLE_MSTAR_TITANIA_BD_MST129E_D01A_S 0
#define USE_MSTAR_TITANIA_BD_MST129E_D01A_S(...)
#define SKIP_MSTAR_TITANIA_BD_MST129E_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST016B_10AA5_11165
#define ENABLE_MSTAR_TITANIA_BD_MST016B_10AA5_11165 0
#define USE_MSTAR_TITANIA_BD_MST016B_10AA5_11165(...)
#define SKIP_MSTAR_TITANIA_BD_MST016B_10AA5_11165(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST105A_D01A_S_T8
#define ENABLE_MSTAR_TITANIA_BD_MST105A_D01A_S_T8 0
#define USE_MSTAR_TITANIA_BD_MST105A_D01A_S_T8(...)
#define SKIP_MSTAR_TITANIA_BD_MST105A_D01A_S_T8(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST106A_D01A_S
#define ENABLE_MSTAR_TITANIA_BD_MST106A_D01A_S 0
#define USE_MSTAR_TITANIA_BD_MST106A_D01A_S(...)
#define SKIP_MSTAR_TITANIA_BD_MST106A_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST087E_D01A_T9
#define ENABLE_MSTAR_TITANIA_BD_MST087E_D01A_T9 0
#define USE_MSTAR_TITANIA_BD_MST087E_D01A_T9(...)
#define SKIP_MSTAR_TITANIA_BD_MST087E_D01A_T9(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST106B_D01A_S
#define ENABLE_MSTAR_TITANIA_BD_MST106B_D01A_S 0
#define USE_MSTAR_TITANIA_BD_MST106B_D01A_S(...)
#define SKIP_MSTAR_TITANIA_BD_MST106B_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST110A_D01A_S
#define ENABLE_MSTAR_TITANIA_BD_MST110A_D01A_S 0
#define USE_MSTAR_TITANIA_BD_MST110A_D01A_S(...)
#define SKIP_MSTAR_TITANIA_BD_MST110A_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST087E_D01A_T13
#define ENABLE_MSTAR_TITANIA_BD_MST087E_D01A_T13 0
#define USE_MSTAR_TITANIA_BD_MST087E_D01A_T13(...)
#define SKIP_MSTAR_TITANIA_BD_MST087E_D01A_T13(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST119A_D01A_S
#define ENABLE_MSTAR_TITANIA_BD_MST119A_D01A_S 0
#define USE_MSTAR_TITANIA_BD_MST119A_D01A_S(...)
#define SKIP_MSTAR_TITANIA_BD_MST119A_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST119A_D01A_S_COMBO
#define ENABLE_MSTAR_TITANIA_BD_MST119A_D01A_S_COMBO 0
#define USE_MSTAR_TITANIA_BD_MST119A_D01A_S_COMBO(...)
#define SKIP_MSTAR_TITANIA_BD_MST119A_D01A_S_COMBO(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST119A_D01A_S_TCL
#define ENABLE_MSTAR_TITANIA_BD_MST119A_D01A_S_TCL 0
#define USE_MSTAR_TITANIA_BD_MST119A_D01A_S_TCL(...)
#define SKIP_MSTAR_TITANIA_BD_MST119A_D01A_S_TCL(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST119A_D01A_S_SKY
#define ENABLE_MSTAR_TITANIA_BD_MST119A_D01A_S_SKY 0
#define USE_MSTAR_TITANIA_BD_MST119A_D01A_S_SKY(...)
#define SKIP_MSTAR_TITANIA_BD_MST119A_D01A_S_SKY(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST008B_10ATX_10405
#define ENABLE_MSTAR_TITANIA_BD_MST008B_10ATX_10405 0
#define USE_MSTAR_TITANIA_BD_MST008B_10ATX_10405(...)
#define SKIP_MSTAR_TITANIA_BD_MST008B_10ATX_10405(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST6358_D01A_S_XOC
#define ENABLE_MSTAR_TITANIA_BD_MST6358_D01A_S_XOC 0
#define USE_MSTAR_TITANIA_BD_MST6358_D01A_S_XOC(...)
#define SKIP_MSTAR_TITANIA_BD_MST6358_D01A_S_XOC(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST119A_D01A_S_KON
#define ENABLE_MSTAR_TITANIA_BD_MST119A_D01A_S_KON 0
#define USE_MSTAR_TITANIA_BD_MST119A_D01A_S_KON(...)
#define SKIP_MSTAR_TITANIA_BD_MST119A_D01A_S_KON(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST119A_D01A_S_HISENSE
#define ENABLE_MSTAR_TITANIA_BD_MST119A_D01A_S_HISENSE 0
#define USE_MSTAR_TITANIA_BD_MST119A_D01A_S_HISENSE(...)
#define SKIP_MSTAR_TITANIA_BD_MST119A_D01A_S_HISENSE(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST110B_D01A_S
#define ENABLE_MSTAR_TITANIA_BD_MST110B_D01A_S 0
#define USE_MSTAR_TITANIA_BD_MST110B_D01A_S(...)
#define SKIP_MSTAR_TITANIA_BD_MST110B_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST119C_D01A_S
#define ENABLE_MSTAR_TITANIA_BD_MST119C_D01A_S 0
#define USE_MSTAR_TITANIA_BD_MST119C_D01A_S(...)
#define SKIP_MSTAR_TITANIA_BD_MST119C_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_BD_MST127A_D01A_S
#define ENABLE_MSTAR_BD_MST127A_D01A_S 0
#define USE_MSTAR_BD_MST127A_D01A_S(...)
#define SKIP_MSTAR_BD_MST127A_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_BD_MST127B_D01A_S
#define ENABLE_MSTAR_BD_MST127B_D01A_S 0
#define USE_MSTAR_BD_MST127B_D01A_S(...)
#define SKIP_MSTAR_BD_MST127B_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_BD_MST127C_D01A_S
#define ENABLE_MSTAR_BD_MST127C_D01A_S 0
#define USE_MSTAR_BD_MST127C_D01A_S(...)
#define SKIP_MSTAR_BD_MST127C_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_BD_MST127E_C01A_S
#define ENABLE_MSTAR_BD_MST127E_C01A_S 0
#define USE_MSTAR_BD_MST127E_C01A_S(...)
#define SKIP_MSTAR_BD_MST127E_C01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_BD_MST132A_D01A_S_A1
#define ENABLE_MSTAR_BD_MST132A_D01A_S_A1 0
#define USE_MSTAR_BD_MST132A_D01A_S_A1(...)
#define SKIP_MSTAR_BD_MST132A_D01A_S_A1(...) __VA_ARGS__
#undef CONFIG_MSTAR_BD_MST132H_D01A_S
#define ENABLE_MSTAR_BD_MST132H_D01A_S 0
#define USE_MSTAR_BD_MST132H_D01A_S(...)
#define SKIP_MSTAR_BD_MST132H_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_BD_MST131A_D01A_S
#define ENABLE_MSTAR_BD_MST131A_D01A_S 0
#define USE_MSTAR_BD_MST131A_D01A_S(...)
#define SKIP_MSTAR_BD_MST131A_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_BD_MST131B_D01A_S
#define ENABLE_MSTAR_BD_MST131B_D01A_S 0
#define USE_MSTAR_BD_MST131B_D01A_S(...)
#define SKIP_MSTAR_BD_MST131B_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_BD_MST018B_10ADS
#define ENABLE_MSTAR_BD_MST018B_10ADS 0
#define USE_MSTAR_BD_MST018B_10ADS(...)
#define SKIP_MSTAR_BD_MST018B_10ADS(...) __VA_ARGS__
#undef CONFIG_MSTAR_BD_MST132A_D01A_S_A7
#define ENABLE_MSTAR_BD_MST132A_D01A_S_A7 0
#define USE_MSTAR_BD_MST132A_D01A_S_A7(...)
#define SKIP_MSTAR_BD_MST132A_D01A_S_A7(...) __VA_ARGS__
#undef CONFIG_MSTAR_BD_MST132B_D01A_S
#define ENABLE_MSTAR_BD_MST132B_D01A_S 0
#define USE_MSTAR_BD_MST132B_D01A_S(...)
#define SKIP_MSTAR_BD_MST132B_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_BD_MST132C_D01A_S
#define ENABLE_MSTAR_BD_MST132C_D01A_S 0
#define USE_MSTAR_BD_MST132C_D01A_S(...)
#define SKIP_MSTAR_BD_MST132C_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_BD_MST132D_D01A_S
#define ENABLE_MSTAR_BD_MST132D_D01A_S 0
#define USE_MSTAR_BD_MST132D_D01A_S(...)
#define SKIP_MSTAR_BD_MST132D_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_BD_MST132E_D01A_S
#define ENABLE_MSTAR_BD_MST132E_D01A_S 0
#define USE_MSTAR_BD_MST132E_D01A_S(...)
#define SKIP_MSTAR_BD_MST132E_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_BD_MST132F_D01A_S
#define ENABLE_MSTAR_BD_MST132F_D01A_S 0
#define USE_MSTAR_BD_MST132F_D01A_S(...)
#define SKIP_MSTAR_BD_MST132F_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_BD_MST132G_D01A_S
#define ENABLE_MSTAR_BD_MST132G_D01A_S 0
#define USE_MSTAR_BD_MST132G_D01A_S(...)
#define SKIP_MSTAR_BD_MST132G_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_BD_MST157D_D01A_S_A7
#define ENABLE_MSTAR_BD_MST157D_D01A_S_A7 0
#define USE_MSTAR_BD_MST157D_D01A_S_A7(...)
#define SKIP_MSTAR_BD_MST157D_D01A_S_A7(...) __VA_ARGS__
#undef CONFIG_MSTAR_BD_MST142D_D01A_S_A7
#define ENABLE_MSTAR_BD_MST142D_D01A_S_A7 0
#define USE_MSTAR_BD_MST142D_D01A_S_A7(...)
#define SKIP_MSTAR_BD_MST142D_D01A_S_A7(...) __VA_ARGS__
#undef CONFIG_MSTAR_BD_MST024B_10ABT
#define ENABLE_MSTAR_BD_MST024B_10ABT 0
#define USE_MSTAR_BD_MST024B_10ABT(...)
#define SKIP_MSTAR_BD_MST024B_10ABT(...) __VA_ARGS__
#undef CONFIG_MSTAR_BD_MST142A_D01A_S
#define ENABLE_MSTAR_BD_MST142A_D01A_S 0
#define USE_MSTAR_BD_MST142A_D01A_S(...)
#define SKIP_MSTAR_BD_MST142A_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_BD_MST142B_D01A_S
#define ENABLE_MSTAR_BD_MST142B_D01A_S 0
#define USE_MSTAR_BD_MST142B_D01A_S(...)
#define SKIP_MSTAR_BD_MST142B_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_BD_MST142C_D01A_S
#define ENABLE_MSTAR_BD_MST142C_D01A_S 0
#define USE_MSTAR_BD_MST142C_D01A_S(...)
#define SKIP_MSTAR_BD_MST142C_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_BD_MST142D_D01A_S
#define ENABLE_MSTAR_BD_MST142D_D01A_S 0
#define USE_MSTAR_BD_MST142D_D01A_S(...)
#define SKIP_MSTAR_BD_MST142D_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_BD_MST142E_D01A_S
#define ENABLE_MSTAR_BD_MST142E_D01A_S 0
#define USE_MSTAR_BD_MST142E_D01A_S(...)
#define SKIP_MSTAR_BD_MST142E_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_BD_MST028B_10AFX_11455_DVB
#define ENABLE_MSTAR_BD_MST028B_10AFX_11455_DVB 0
#define USE_MSTAR_BD_MST028B_10AFX_11455_DVB(...)
#define SKIP_MSTAR_BD_MST028B_10AFX_11455_DVB(...) __VA_ARGS__
#undef CONFIG_MSTAR_BD_MST028B_10AFX_11455_ISDB
#define ENABLE_MSTAR_BD_MST028B_10AFX_11455_ISDB 0
#define USE_MSTAR_BD_MST028B_10AFX_11455_ISDB(...)
#define SKIP_MSTAR_BD_MST028B_10AFX_11455_ISDB(...) __VA_ARGS__
#undef CONFIG_MSTAR_BD_MST028B_10AFX_11455
#define ENABLE_MSTAR_BD_MST028B_10AFX_11455 0
#define USE_MSTAR_BD_MST028B_10AFX_11455(...)
#define SKIP_MSTAR_BD_MST028B_10AFX_11455(...) __VA_ARGS__
#undef CONFIG_MSTAR_BD_MST015B_10ABX
#define ENABLE_MSTAR_BD_MST015B_10ABX 0
#define USE_MSTAR_BD_MST015B_10ABX(...)
#define SKIP_MSTAR_BD_MST015B_10ABX(...) __VA_ARGS__
#undef CONFIG_MSTAR_BD_MST015B_10ABX_DVB
#define ENABLE_MSTAR_BD_MST015B_10ABX_DVB 0
#define USE_MSTAR_BD_MST015B_10ABX_DVB(...)
#define SKIP_MSTAR_BD_MST015B_10ABX_DVB(...) __VA_ARGS__
#undef CONFIG_MSTAR_BD_MST017B_10ABT
#define ENABLE_MSTAR_BD_MST017B_10ABT 0
#define USE_MSTAR_BD_MST017B_10ABT(...)
#define SKIP_MSTAR_BD_MST017B_10ABT(...) __VA_ARGS__
#undef CONFIG_MSTAR_BD_MST015B_10ABX_ISDB
#define ENABLE_MSTAR_BD_MST015B_10ABX_ISDB 0
#define USE_MSTAR_BD_MST015B_10ABX_ISDB(...)
#define SKIP_MSTAR_BD_MST015B_10ABX_ISDB(...) __VA_ARGS__
#undef CONFIG_MSTAR_BD_MST569M_10HVT
#define ENABLE_MSTAR_BD_MST569M_10HVT 0
#define USE_MSTAR_BD_MST569M_10HVT(...)
#define SKIP_MSTAR_BD_MST569M_10HVT(...) __VA_ARGS__
#undef CONFIG_MSTAR_BD_MST142A_D01A_S_EAGLE
#define ENABLE_MSTAR_BD_MST142A_D01A_S_EAGLE 0
#define USE_MSTAR_BD_MST142A_D01A_S_EAGLE(...)
#define SKIP_MSTAR_BD_MST142A_D01A_S_EAGLE(...) __VA_ARGS__
#undef CONFIG_MSTAR_BD_MST147A_D01A_S_EAGLE
#define ENABLE_MSTAR_BD_MST147A_D01A_S_EAGLE 0
#define USE_MSTAR_BD_MST147A_D01A_S_EAGLE(...)
#define SKIP_MSTAR_BD_MST147A_D01A_S_EAGLE(...) __VA_ARGS__
#undef CONFIG_MSTAR_BD_MST152A_D01A_S_EAGLE
#define ENABLE_MSTAR_BD_MST152A_D01A_S_EAGLE 0
#define USE_MSTAR_BD_MST152A_D01A_S_EAGLE(...)
#define SKIP_MSTAR_BD_MST152A_D01A_S_EAGLE(...) __VA_ARGS__
#undef CONFIG_MSTAR_BD_MST038B_10AHT_EAGLE
#define ENABLE_MSTAR_BD_MST038B_10AHT_EAGLE 0
#define USE_MSTAR_BD_MST038B_10AHT_EAGLE(...)
#define SKIP_MSTAR_BD_MST038B_10AHT_EAGLE(...) __VA_ARGS__
#undef CONFIG_MSTAR_BD_MST028B_10AFX_EAGLE
#define ENABLE_MSTAR_BD_MST028B_10AFX_EAGLE 0
#define USE_MSTAR_BD_MST028B_10AFX_EAGLE(...)
#define SKIP_MSTAR_BD_MST028B_10AFX_EAGLE(...) __VA_ARGS__
#undef CONFIG_MSTAR_BD_MSTCUS28_800C_EAGLE
#define ENABLE_MSTAR_BD_MSTCUS28_800C_EAGLE 0
#define USE_MSTAR_BD_MSTCUS28_800C_EAGLE(...)
#define SKIP_MSTAR_BD_MSTCUS28_800C_EAGLE(...) __VA_ARGS__
#undef CONFIG_MSTAR_BD_MST152A_D01A_S_EIFFEL
#define ENABLE_MSTAR_BD_MST152A_D01A_S_EIFFEL 0
#define USE_MSTAR_BD_MST152A_D01A_S_EIFFEL(...)
#define SKIP_MSTAR_BD_MST152A_D01A_S_EIFFEL(...) __VA_ARGS__
#undef CONFIG_MSTAR_BD_MST169A_D01A_S_EIFFEL
#define ENABLE_MSTAR_BD_MST169A_D01A_S_EIFFEL 0
#define USE_MSTAR_BD_MST169A_D01A_S_EIFFEL(...)
#define SKIP_MSTAR_BD_MST169A_D01A_S_EIFFEL(...) __VA_ARGS__
#undef CONFIG_MSTAR_BD_MST152A_D01A_S_NIKE
#define ENABLE_MSTAR_BD_MST152A_D01A_S_NIKE 0
#define USE_MSTAR_BD_MST152A_D01A_S_NIKE(...)
#define SKIP_MSTAR_BD_MST152A_D01A_S_NIKE(...) __VA_ARGS__
#undef CONFIG_MSTAR_JANUS_BD_MST092A_D01A_S
#define ENABLE_MSTAR_JANUS_BD_MST092A_D01A_S 0
#define USE_MSTAR_JANUS_BD_MST092A_D01A_S(...)
#define SKIP_MSTAR_JANUS_BD_MST092A_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_JANUS_BD_MST092B_D01A_S
#define ENABLE_MSTAR_JANUS_BD_MST092B_D01A_S 0
#define USE_MSTAR_JANUS_BD_MST092B_D01A_S(...)
#define SKIP_MSTAR_JANUS_BD_MST092B_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_JANUS_BD_MST092C_D01A_S
#define ENABLE_MSTAR_JANUS_BD_MST092C_D01A_S 0
#define USE_MSTAR_JANUS_BD_MST092C_D01A_S(...)
#define SKIP_MSTAR_JANUS_BD_MST092C_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_JANUS_BD_MST216A_JNS_10A_9463
#define ENABLE_MSTAR_JANUS_BD_MST216A_JNS_10A_9463 0
#define USE_MSTAR_JANUS_BD_MST216A_JNS_10A_9463(...)
#define SKIP_MSTAR_JANUS_BD_MST216A_JNS_10A_9463(...) __VA_ARGS__
#undef CONFIG_MSTAR_JANUS_BD_MST092A_D01A
#define ENABLE_MSTAR_JANUS_BD_MST092A_D01A 0
#define USE_MSTAR_JANUS_BD_MST092A_D01A(...)
#define SKIP_MSTAR_JANUS_BD_MST092A_D01A(...) __VA_ARGS__
#undef CONFIG_MSTAR_JANUS_BD_MST092B_D01A
#define ENABLE_MSTAR_JANUS_BD_MST092B_D01A 0
#define USE_MSTAR_JANUS_BD_MST092B_D01A(...)
#define SKIP_MSTAR_JANUS_BD_MST092B_D01A(...) __VA_ARGS__
#undef CONFIG_MSTAR_JANUS_BD_MST092B_D02A
#define ENABLE_MSTAR_JANUS_BD_MST092B_D02A 0
#define USE_MSTAR_JANUS_BD_MST092B_D02A(...)
#define SKIP_MSTAR_JANUS_BD_MST092B_D02A(...) __VA_ARGS__
#undef CONFIG_MSTAR_CONFIG_MSTAR_BD_JANUS2_FPGA
#define ENABLE_MSTAR_CONFIG_MSTAR_BD_JANUS2_FPGA 0
#define USE_MSTAR_CONFIG_MSTAR_BD_JANUS2_FPGA(...)
#define SKIP_MSTAR_CONFIG_MSTAR_BD_JANUS2_FPGA(...) __VA_ARGS__
#undef CONFIG_MSTAR_JANUS2_BD_MST120A_D01A_S
#define ENABLE_MSTAR_JANUS2_BD_MST120A_D01A_S 0
#define USE_MSTAR_JANUS2_BD_MST120A_D01A_S(...)
#define SKIP_MSTAR_JANUS2_BD_MST120A_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_JANUS2_BD_MST120A_D01A_SKY
#define ENABLE_MSTAR_JANUS2_BD_MST120A_D01A_SKY 0
#define USE_MSTAR_JANUS2_BD_MST120A_D01A_SKY(...)
#define SKIP_MSTAR_JANUS2_BD_MST120A_D01A_SKY(...) __VA_ARGS__
#undef CONFIG_MSTAR_JANUS2_BD_MST120B_D01A_S
#define ENABLE_MSTAR_JANUS2_BD_MST120B_D01A_S 0
#define USE_MSTAR_JANUS2_BD_MST120B_D01A_S(...)
#define SKIP_MSTAR_JANUS2_BD_MST120B_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_JANUS2_BD_MST012B_10AAV
#define ENABLE_MSTAR_JANUS2_BD_MST012B_10AAV 0
#define USE_MSTAR_JANUS2_BD_MST012B_10AAV(...)
#define SKIP_MSTAR_JANUS2_BD_MST012B_10AAV(...) __VA_ARGS__
#undef CONFIG_MSTAR_MARIA10_BD_MST109A_D01A_S
#define ENABLE_MSTAR_MARIA10_BD_MST109A_D01A_S 0
#define USE_MSTAR_MARIA10_BD_MST109A_D01A_S(...)
#define SKIP_MSTAR_MARIA10_BD_MST109A_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_MARIA10_BD_MST109C_D01A_S
#define ENABLE_MSTAR_MARIA10_BD_MST109C_D01A_S 0
#define USE_MSTAR_MARIA10_BD_MST109C_D01A_S(...)
#define SKIP_MSTAR_MARIA10_BD_MST109C_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_MARIA10_BD_MST109D_D01A_S
#define ENABLE_MSTAR_MARIA10_BD_MST109D_D01A_S 0
#define USE_MSTAR_MARIA10_BD_MST109D_D01A_S(...)
#define SKIP_MSTAR_MARIA10_BD_MST109D_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_MARIA10_BD_MST109E_D01A_S
#define ENABLE_MSTAR_MARIA10_BD_MST109E_D01A_S 0
#define USE_MSTAR_MARIA10_BD_MST109E_D01A_S(...)
#define SKIP_MSTAR_MARIA10_BD_MST109E_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_MARIA10_BD_MST109F_D01A_S
#define ENABLE_MSTAR_MARIA10_BD_MST109F_D01A_S 0
#define USE_MSTAR_MARIA10_BD_MST109F_D01A_S(...)
#define SKIP_MSTAR_MARIA10_BD_MST109F_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_MARIA10_BD_MST004B_20AVS_10306
#define ENABLE_MSTAR_MARIA10_BD_MST004B_20AVS_10306 0
#define USE_MSTAR_MARIA10_BD_MST004B_20AVS_10306(...)
#define SKIP_MSTAR_MARIA10_BD_MST004B_20AVS_10306(...) __VA_ARGS__
#undef CONFIG_MSTAR_MARIA10_BD_MST006B_10AVS_10315
#define ENABLE_MSTAR_MARIA10_BD_MST006B_10AVS_10315 0
#define USE_MSTAR_MARIA10_BD_MST006B_10AVS_10315(...)
#define SKIP_MSTAR_MARIA10_BD_MST006B_10AVS_10315(...) __VA_ARGS__
#undef CONFIG_MSTAR_MARIA10_BD_MST006B_20AVS_10313
#define ENABLE_MSTAR_MARIA10_BD_MST006B_20AVS_10313 0
#define USE_MSTAR_MARIA10_BD_MST006B_20AVS_10313(...)
#define SKIP_MSTAR_MARIA10_BD_MST006B_20AVS_10313(...) __VA_ARGS__
#undef CONFIG_MSTAR_MARIA10_BD_MST6M181_TCL
#define ENABLE_MSTAR_MARIA10_BD_MST6M181_TCL 0
#define USE_MSTAR_MARIA10_BD_MST6M181_TCL(...)
#define SKIP_MSTAR_MARIA10_BD_MST6M181_TCL(...) __VA_ARGS__
#undef CONFIG_MSTAR_MARIA10_BD_MST136A_D01A_S
#define ENABLE_MSTAR_MARIA10_BD_MST136A_D01A_S 0
#define USE_MSTAR_MARIA10_BD_MST136A_D01A_S(...)
#define SKIP_MSTAR_MARIA10_BD_MST136A_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_MACAW12_BD_MST149A_D01A_S
#define ENABLE_MSTAR_MACAW12_BD_MST149A_D01A_S 0
#define USE_MSTAR_MACAW12_BD_MST149A_D01A_S(...)
#define SKIP_MSTAR_MACAW12_BD_MST149A_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_MACAW12_BD_MST149B_D01A_S
#define ENABLE_MSTAR_MACAW12_BD_MST149B_D01A_S 0
#define USE_MSTAR_MACAW12_BD_MST149B_D01A_S(...)
#define SKIP_MSTAR_MACAW12_BD_MST149B_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_MACAW12_BD_MST149C_D01A_S
#define ENABLE_MSTAR_MACAW12_BD_MST149C_D01A_S 0
#define USE_MSTAR_MACAW12_BD_MST149C_D01A_S(...)
#define SKIP_MSTAR_MACAW12_BD_MST149C_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_MACAW12_BD_MST149D_D01A_S
#define ENABLE_MSTAR_MACAW12_BD_MST149D_D01A_S 0
#define USE_MSTAR_MACAW12_BD_MST149D_D01A_S(...)
#define SKIP_MSTAR_MACAW12_BD_MST149D_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_MACAW12_BD_MST149E_D01A_S
#define ENABLE_MSTAR_MACAW12_BD_MST149E_D01A_S 0
#define USE_MSTAR_MACAW12_BD_MST149E_D01A_S(...)
#define SKIP_MSTAR_MACAW12_BD_MST149E_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_EDEN_BD_MST165A_D01A_S
#define ENABLE_MSTAR_EDEN_BD_MST165A_D01A_S 0
#define USE_MSTAR_EDEN_BD_MST165A_D01A_S(...)
#define SKIP_MSTAR_EDEN_BD_MST165A_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_EDEN_BD_MST165B_D01A_S
#define ENABLE_MSTAR_EDEN_BD_MST165B_D01A_S 0
#define USE_MSTAR_EDEN_BD_MST165B_D01A_S(...)
#define SKIP_MSTAR_EDEN_BD_MST165B_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_EDEN_BD_MST165C_D01A_S
#define ENABLE_MSTAR_EDEN_BD_MST165C_D01A_S 0
#define USE_MSTAR_EDEN_BD_MST165C_D01A_S(...)
#define SKIP_MSTAR_EDEN_BD_MST165C_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_EDEN_BD_MST165C_D01B_S
#define ENABLE_MSTAR_EDEN_BD_MST165C_D01B_S 0
#define USE_MSTAR_EDEN_BD_MST165C_D01B_S(...)
#define SKIP_MSTAR_EDEN_BD_MST165C_D01B_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_EDEN_BD_MST043B_10ALB_12351
#define ENABLE_MSTAR_EDEN_BD_MST043B_10ALB_12351 0
#define USE_MSTAR_EDEN_BD_MST043B_10ALB_12351(...)
#define SKIP_MSTAR_EDEN_BD_MST043B_10ALB_12351(...) __VA_ARGS__
#undef CONFIG_MSTAR_EDEN_BD_MST043B_10BLB_12413
#define ENABLE_MSTAR_EDEN_BD_MST043B_10BLB_12413 0
#define USE_MSTAR_EDEN_BD_MST043B_10BLB_12413(...)
#define SKIP_MSTAR_EDEN_BD_MST043B_10BLB_12413(...) __VA_ARGS__
#undef CONFIG_MSTAR_EDEN_BD_MST042B_10BLU_12423
#define ENABLE_MSTAR_EDEN_BD_MST042B_10BLU_12423 0
#define USE_MSTAR_EDEN_BD_MST042B_10BLU_12423(...)
#define SKIP_MSTAR_EDEN_BD_MST042B_10BLU_12423(...) __VA_ARGS__
#undef CONFIG_MSTAR_EULER_BD_MST165A_D01B_S
#define ENABLE_MSTAR_EULER_BD_MST165A_D01B_S 0
#define USE_MSTAR_EULER_BD_MST165A_D01B_S(...)
#define SKIP_MSTAR_EULER_BD_MST165A_D01B_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_EULER_BD_MST165B_D01B_S
#define ENABLE_MSTAR_EULER_BD_MST165B_D01B_S 0
#define USE_MSTAR_EULER_BD_MST165B_D01B_S(...)
#define SKIP_MSTAR_EULER_BD_MST165B_D01B_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_EULER_BD_MST165C_D01B_S
#define ENABLE_MSTAR_EULER_BD_MST165C_D01B_S 0
#define USE_MSTAR_EULER_BD_MST165C_D01B_S(...)
#define SKIP_MSTAR_EULER_BD_MST165C_D01B_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_BD_MST157A_D01A_S
#define ENABLE_MSTAR_BD_MST157A_D01A_S 0
#define USE_MSTAR_BD_MST157A_D01A_S(...)
#define SKIP_MSTAR_BD_MST157A_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_BD_MST157B_D01A_S
#define ENABLE_MSTAR_BD_MST157B_D01A_S 0
#define USE_MSTAR_BD_MST157B_D01A_S(...)
#define SKIP_MSTAR_BD_MST157B_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_BD_MST157C_D01A_S
#define ENABLE_MSTAR_BD_MST157C_D01A_S 0
#define USE_MSTAR_BD_MST157C_D01A_S(...)
#define SKIP_MSTAR_BD_MST157C_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_BD_MST157E_D01A_S
#define ENABLE_MSTAR_BD_MST157E_D01A_S 0
#define USE_MSTAR_BD_MST157E_D01A_S(...)
#define SKIP_MSTAR_BD_MST157E_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_BD_MST157E_D01B_S
#define ENABLE_MSTAR_BD_MST157E_D01B_S 0
#define USE_MSTAR_BD_MST157E_D01B_S(...)
#define SKIP_MSTAR_BD_MST157E_D01B_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_BD_MST157E_D01C_S
#define ENABLE_MSTAR_BD_MST157E_D01C_S 0
#define USE_MSTAR_BD_MST157E_D01C_S(...)
#define SKIP_MSTAR_BD_MST157E_D01C_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_BD_MST157E_D01D_S
#define ENABLE_MSTAR_BD_MST157E_D01D_S 0
#define USE_MSTAR_BD_MST157E_D01D_S(...)
#define SKIP_MSTAR_BD_MST157E_D01D_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_BD_MST157F_D01A_S
#define ENABLE_MSTAR_BD_MST157F_D01A_S 0
#define USE_MSTAR_BD_MST157F_D01A_S(...)
#define SKIP_MSTAR_BD_MST157F_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_BD_MST159A_D01A_S
#define ENABLE_MSTAR_BD_MST159A_D01A_S 0
#define USE_MSTAR_BD_MST159A_D01A_S(...)
#define SKIP_MSTAR_BD_MST159A_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_BD_MST147A_D01B_S
#define ENABLE_MSTAR_BD_MST147A_D01B_S 0
#define USE_MSTAR_BD_MST147A_D01B_S(...)
#define SKIP_MSTAR_BD_MST147A_D01B_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_BD_MST036B_EDISON
#define ENABLE_MSTAR_BD_MST036B_EDISON 0
#define USE_MSTAR_BD_MST036B_EDISON(...)
#define SKIP_MSTAR_BD_MST036B_EDISON(...) __VA_ARGS__
#undef CONFIG_MSTAR_BD_MST036B_EDISON_CUS36
#define ENABLE_MSTAR_BD_MST036B_EDISON_CUS36 0
#define USE_MSTAR_BD_MST036B_EDISON_CUS36(...)
#define SKIP_MSTAR_BD_MST036B_EDISON_CUS36(...) __VA_ARGS__
#undef CONFIG_MSTAR_BD_MST036B_EDISON_CUS28
#define ENABLE_MSTAR_BD_MST036B_EDISON_CUS28 0
#define USE_MSTAR_BD_MST036B_EDISON_CUS28(...)
#define SKIP_MSTAR_BD_MST036B_EDISON_CUS28(...) __VA_ARGS__
#define CONFIG_MSTAR_BD_MST036B_EDISON_CUS28_AP 1
#define ENABLE_MSTAR_BD_MST036B_EDISON_CUS28_AP 1
#define USE_MSTAR_BD_MST036B_EDISON_CUS28_AP(...) __VA_ARGS__
#define SKIP_MSTAR_BD_MST036B_EDISON_CUS28_AP(...)
#undef CONFIG_MSTAR_BD_MST036B_EDISON_CUS36_AP
#define ENABLE_MSTAR_BD_MST036B_EDISON_CUS36_AP 0
#define USE_MSTAR_BD_MST036B_EDISON_CUS36_AP(...)
#define SKIP_MSTAR_BD_MST036B_EDISON_CUS36_AP(...) __VA_ARGS__
#undef CONFIG_MSTAR_BD_MST147A_D01A_S
#define ENABLE_MSTAR_BD_MST147A_D01A_S 0
#define USE_MSTAR_BD_MST147A_D01A_S(...)
#define SKIP_MSTAR_BD_MST147A_D01A_S(...) __VA_ARGS__
#undef CONFIG_PNL_FULLHD_SEC_LE32A
#define ENABLE_PNL_FULLHD_SEC_LE32A 0
#define USE_PNL_FULLHD_SEC_LE32A(...)
#define SKIP_PNL_FULLHD_SEC_LE32A(...) __VA_ARGS__
#undef CONFIG_PNL_SXGA_AU17_EN05
#define ENABLE_PNL_SXGA_AU17_EN05 0
#define USE_PNL_SXGA_AU17_EN05(...)
#define SKIP_PNL_SXGA_AU17_EN05(...) __VA_ARGS__
#undef CONFIG_PNL_WXGA_AU20_T200XW02
#define ENABLE_PNL_WXGA_AU20_T200XW02 0
#define USE_PNL_WXGA_AU20_T200XW02(...)
#define SKIP_PNL_WXGA_AU20_T200XW02(...) __VA_ARGS__
#undef CONFIG_PNL_WXGA_PLUS_CMO190_M190A1
#define ENABLE_PNL_WXGA_PLUS_CMO190_M190A1 0
#define USE_PNL_WXGA_PLUS_CMO190_M190A1(...)
#define SKIP_PNL_WXGA_PLUS_CMO190_M190A1(...) __VA_ARGS__
#undef CONFIG_PNL_WSXGA_AU22_M201EW01
#define ENABLE_PNL_WSXGA_AU22_M201EW01 0
#define USE_PNL_WSXGA_AU22_M201EW01(...)
#define SKIP_PNL_WSXGA_AU22_M201EW01(...) __VA_ARGS__
#define CONFIG_PNL_FULLHD_CMO216_H1L01 1
#define ENABLE_PNL_FULLHD_CMO216_H1L01 1
#define USE_PNL_FULLHD_CMO216_H1L01(...) __VA_ARGS__
#define SKIP_PNL_FULLHD_CMO216_H1L01(...)
#undef CONFIG_PANEL_RES_FULL_HD
#define ENABLE_PANEL_RES_FULL_HD 0
#define USE_PANEL_RES_FULL_HD(...)
#define SKIP_PANEL_RES_FULL_HD(...) __VA_ARGS__
#undef CONFIG_PNL_WUXGA_CMO260_J2
#define ENABLE_PNL_WUXGA_CMO260_J2 0
#define USE_PNL_WUXGA_CMO260_J2(...)
#define SKIP_PNL_WUXGA_CMO260_J2(...) __VA_ARGS__
#undef CONFIG_MFC120_FULLHD_CMO216_H1L01
#define ENABLE_MFC120_FULLHD_CMO216_H1L01 0
#define USE_MFC120_FULLHD_CMO216_H1L01(...)
#define SKIP_MFC120_FULLHD_CMO216_H1L01(...) __VA_ARGS__
#undef CONFIG_MFC60_FULLHD_CMO216_H1L01
#define ENABLE_MFC60_FULLHD_CMO216_H1L01 0
#define USE_MFC60_FULLHD_CMO216_H1L01(...)
#define SKIP_MFC60_FULLHD_CMO216_H1L01(...) __VA_ARGS__
#undef CONFIG_PNL_FULLHD_TCON
#define ENABLE_PNL_FULLHD_TCON 0
#define USE_PNL_FULLHD_TCON(...)
#define SKIP_PNL_FULLHD_TCON(...) __VA_ARGS__
#undef CONFIG_PNL_DACOUT_576I
#define ENABLE_PNL_DACOUT_576I 0
#define USE_PNL_DACOUT_576I(...)
#define SKIP_PNL_DACOUT_576I(...) __VA_ARGS__
#undef CONFIG_PNL_DACOUT_576P
#define ENABLE_PNL_DACOUT_576P 0
#define USE_PNL_DACOUT_576P(...)
#define SKIP_PNL_DACOUT_576P(...) __VA_ARGS__
#undef CONFIG_PNL_DACOUT_720P_50
#define ENABLE_PNL_DACOUT_720P_50 0
#define USE_PNL_DACOUT_720P_50(...)
#define SKIP_PNL_DACOUT_720P_50(...) __VA_ARGS__
#undef CONFIG_PNL_DACOUT_1080I_50
#define ENABLE_PNL_DACOUT_1080I_50 0
#define USE_PNL_DACOUT_1080I_50(...)
#define SKIP_PNL_DACOUT_1080I_50(...) __VA_ARGS__
#undef CONFIG_PNL_DACOUT_1080P_50
#define ENABLE_PNL_DACOUT_1080P_50 0
#define USE_PNL_DACOUT_1080P_50(...)
#define SKIP_PNL_DACOUT_1080P_50(...) __VA_ARGS__
#undef CONFIG_PNL_DACOUT_480I
#define ENABLE_PNL_DACOUT_480I 0
#define USE_PNL_DACOUT_480I(...)
#define SKIP_PNL_DACOUT_480I(...) __VA_ARGS__
#undef CONFIG_PNL_DACOUT_480P
#define ENABLE_PNL_DACOUT_480P 0
#define USE_PNL_DACOUT_480P(...)
#define SKIP_PNL_DACOUT_480P(...) __VA_ARGS__
#undef CONFIG_PNL_DACOUT_720P_60
#define ENABLE_PNL_DACOUT_720P_60 0
#define USE_PNL_DACOUT_720P_60(...)
#define SKIP_PNL_DACOUT_720P_60(...) __VA_ARGS__
#undef CONFIG_PNL_DACOUT_1080I_60
#define ENABLE_PNL_DACOUT_1080I_60 0
#define USE_PNL_DACOUT_1080I_60(...)
#define SKIP_PNL_DACOUT_1080I_60(...) __VA_ARGS__
#undef CONFIG_PNL_DACOUT_1080P_60
#define ENABLE_PNL_DACOUT_1080P_60 0
#define USE_PNL_DACOUT_1080P_60(...)
#define SKIP_PNL_DACOUT_1080P_60(...) __VA_ARGS__
#undef CONFIG_PNL_LG_FULLHD_120HZ
#define ENABLE_PNL_LG_FULLHD_120HZ 0
#define USE_PNL_LG_FULLHD_120HZ(...)
#define SKIP_PNL_LG_FULLHD_120HZ(...) __VA_ARGS__
#undef CONFIG_PNL_LG_FULLHD_120HZ_3DPASSIVE
#define ENABLE_PNL_LG_FULLHD_120HZ_3DPASSIVE 0
#define USE_PNL_LG_FULLHD_120HZ_3DPASSIVE(...)
#define SKIP_PNL_LG_FULLHD_120HZ_3DPASSIVE(...) __VA_ARGS__
#undef CONFIG_PNL_LG_FullHD_120HZ_3DLR_LM230WF4
#define ENABLE_PNL_LG_FullHD_120HZ_3DLR_LM230WF4 0
#define USE_PNL_LG_FullHD_120HZ_3DLR_LM230WF4(...)
#define SKIP_PNL_LG_FullHD_120HZ_3DLR_LM230WF4(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_MMAP_128MB_128MB_DEFAULT
#define ENABLE_MSTAR_TITANIA_MMAP_128MB_128MB_DEFAULT 0
#define USE_MSTAR_TITANIA_MMAP_128MB_128MB_DEFAULT(...)
#define SKIP_MSTAR_TITANIA_MMAP_128MB_128MB_DEFAULT(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_MMAP_256MB_256MB_DEFAULT
#define ENABLE_MSTAR_TITANIA_MMAP_256MB_256MB_DEFAULT 0
#define USE_MSTAR_TITANIA_MMAP_256MB_256MB_DEFAULT(...)
#define SKIP_MSTAR_TITANIA_MMAP_256MB_256MB_DEFAULT(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_MMAP_128MB_128MB
#define ENABLE_MSTAR_TITANIA_MMAP_128MB_128MB 0
#define USE_MSTAR_TITANIA_MMAP_128MB_128MB(...)
#define SKIP_MSTAR_TITANIA_MMAP_128MB_128MB(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_MMAP_128MB_256MB
#define ENABLE_MSTAR_TITANIA_MMAP_128MB_256MB 0
#define USE_MSTAR_TITANIA_MMAP_128MB_256MB(...)
#define SKIP_MSTAR_TITANIA_MMAP_128MB_256MB(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_MMAP_128MB_64MB
#define ENABLE_MSTAR_TITANIA_MMAP_128MB_64MB 0
#define USE_MSTAR_TITANIA_MMAP_128MB_64MB(...)
#define SKIP_MSTAR_TITANIA_MMAP_128MB_64MB(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_MMAP_64MB_128MB
#define ENABLE_MSTAR_TITANIA_MMAP_64MB_128MB 0
#define USE_MSTAR_TITANIA_MMAP_64MB_128MB(...)
#define SKIP_MSTAR_TITANIA_MMAP_64MB_128MB(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_MMAP_64MB_64MB
#define ENABLE_MSTAR_TITANIA_MMAP_64MB_64MB 0
#define USE_MSTAR_TITANIA_MMAP_64MB_64MB(...)
#define SKIP_MSTAR_TITANIA_MMAP_64MB_64MB(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_MMAP_128MB
#define ENABLE_MSTAR_TITANIA_MMAP_128MB 0
#define USE_MSTAR_TITANIA_MMAP_128MB(...)
#define SKIP_MSTAR_TITANIA_MMAP_128MB(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_MMAP_64MB
#define ENABLE_MSTAR_TITANIA_MMAP_64MB 0
#define USE_MSTAR_TITANIA_MMAP_64MB(...)
#define SKIP_MSTAR_TITANIA_MMAP_64MB(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_MMAP_512MB
#define ENABLE_MSTAR_TITANIA_MMAP_512MB 0
#define USE_MSTAR_TITANIA_MMAP_512MB(...)
#define SKIP_MSTAR_TITANIA_MMAP_512MB(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_MMAP_512MB_512MB
#define ENABLE_MSTAR_TITANIA_MMAP_512MB_512MB 0
#define USE_MSTAR_TITANIA_MMAP_512MB_512MB(...)
#define SKIP_MSTAR_TITANIA_MMAP_512MB_512MB(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_MMAP_256MB
#define ENABLE_MSTAR_TITANIA_MMAP_256MB 0
#define USE_MSTAR_TITANIA_MMAP_256MB(...)
#define SKIP_MSTAR_TITANIA_MMAP_256MB(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_MMAP_256MB_256MB
#define ENABLE_MSTAR_TITANIA_MMAP_256MB_256MB 0
#define USE_MSTAR_TITANIA_MMAP_256MB_256MB(...)
#define SKIP_MSTAR_TITANIA_MMAP_256MB_256MB(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_MMAP_512MB_256MB
#define ENABLE_MSTAR_TITANIA_MMAP_512MB_256MB 0
#define USE_MSTAR_TITANIA_MMAP_512MB_256MB(...)
#define SKIP_MSTAR_TITANIA_MMAP_512MB_256MB(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_MMAP_1024MB_512MB
#define ENABLE_MSTAR_TITANIA_MMAP_1024MB_512MB 0
#define USE_MSTAR_TITANIA_MMAP_1024MB_512MB(...)
#define SKIP_MSTAR_TITANIA_MMAP_1024MB_512MB(...) __VA_ARGS__
#undef CONFIG_MSTAR_EDISON_MMAP_512MB_256MB
#define ENABLE_MSTAR_EDISON_MMAP_512MB_256MB 0
#define USE_MSTAR_EDISON_MMAP_512MB_256MB(...)
#define SKIP_MSTAR_EDISON_MMAP_512MB_256MB(...) __VA_ARGS__
#define CONFIG_MSTAR_EDISON_MMAP_512MB_512MB 1
#define ENABLE_MSTAR_EDISON_MMAP_512MB_512MB 1
#define USE_MSTAR_EDISON_MMAP_512MB_512MB(...) __VA_ARGS__
#define SKIP_MSTAR_EDISON_MMAP_512MB_512MB(...)
#undef CONFIG_MSTAR_EINSTEIN_MMAP_512MB_256MB
#define ENABLE_MSTAR_EINSTEIN_MMAP_512MB_256MB 0
#define USE_MSTAR_EINSTEIN_MMAP_512MB_256MB(...)
#define SKIP_MSTAR_EINSTEIN_MMAP_512MB_256MB(...) __VA_ARGS__
#undef CONFIG_MSTAR_EINSTEIN_MMAP_512MB_512MB
#define ENABLE_MSTAR_EINSTEIN_MMAP_512MB_512MB 0
#define USE_MSTAR_EINSTEIN_MMAP_512MB_512MB(...)
#define SKIP_MSTAR_EINSTEIN_MMAP_512MB_512MB(...) __VA_ARGS__
#undef CONFIG_MSTAR_JANUS_MMAP_128MB
#define ENABLE_MSTAR_JANUS_MMAP_128MB 0
#define USE_MSTAR_JANUS_MMAP_128MB(...)
#define SKIP_MSTAR_JANUS_MMAP_128MB(...) __VA_ARGS__
#undef CONFIG_MSTAR_JANUS_MMAP_64MB
#define ENABLE_MSTAR_JANUS_MMAP_64MB 0
#define USE_MSTAR_JANUS_MMAP_64MB(...)
#define SKIP_MSTAR_JANUS_MMAP_64MB(...) __VA_ARGS__
#undef CONFIG_MSTAR_JANUS2_MMAP_128MB
#define ENABLE_MSTAR_JANUS2_MMAP_128MB 0
#define USE_MSTAR_JANUS2_MMAP_128MB(...)
#define SKIP_MSTAR_JANUS2_MMAP_128MB(...) __VA_ARGS__
#undef CONFIG_MSTAR_MARIA10_MMAP_128MB
#define ENABLE_MSTAR_MARIA10_MMAP_128MB 0
#define USE_MSTAR_MARIA10_MMAP_128MB(...)
#define SKIP_MSTAR_MARIA10_MMAP_128MB(...) __VA_ARGS__
#undef CONFIG_MSTAR_MARIA10_MMAP_64MB
#define ENABLE_MSTAR_MARIA10_MMAP_64MB 0
#define USE_MSTAR_MARIA10_MMAP_64MB(...)
#define SKIP_MSTAR_MARIA10_MMAP_64MB(...) __VA_ARGS__
#undef CONFIG_MSTAR_MARIA10_MMAP_32MB
#define ENABLE_MSTAR_MARIA10_MMAP_32MB 0
#define USE_MSTAR_MARIA10_MMAP_32MB(...)
#define SKIP_MSTAR_MARIA10_MMAP_32MB(...) __VA_ARGS__
#undef CONFIG_MSTAR_MACAW12_MMAP_128MB_DDR3
#define ENABLE_MSTAR_MACAW12_MMAP_128MB_DDR3 0
#define USE_MSTAR_MACAW12_MMAP_128MB_DDR3(...)
#define SKIP_MSTAR_MACAW12_MMAP_128MB_DDR3(...) __VA_ARGS__
#undef CONFIG_MSTAR_MACAW12_MMAP_128MB
#define ENABLE_MSTAR_MACAW12_MMAP_128MB 0
#define USE_MSTAR_MACAW12_MMAP_128MB(...)
#define SKIP_MSTAR_MACAW12_MMAP_128MB(...) __VA_ARGS__
#undef CONFIG_MSTAR_MACAW12_MMAP_64MB
#define ENABLE_MSTAR_MACAW12_MMAP_64MB 0
#define USE_MSTAR_MACAW12_MMAP_64MB(...)
#define SKIP_MSTAR_MACAW12_MMAP_64MB(...) __VA_ARGS__
#undef CONFIG_MSTAR_MACAW12_MMAP_32MB
#define ENABLE_MSTAR_MACAW12_MMAP_32MB 0
#define USE_MSTAR_MACAW12_MMAP_32MB(...)
#define SKIP_MSTAR_MACAW12_MMAP_32MB(...) __VA_ARGS__
#undef CONFIG_MSTAR_EDEN_MMAP_64MB
#define ENABLE_MSTAR_EDEN_MMAP_64MB 0
#define USE_MSTAR_EDEN_MMAP_64MB(...)
#define SKIP_MSTAR_EDEN_MMAP_64MB(...) __VA_ARGS__
#undef CONFIG_MSTAR_EDEN_MMAP_32MB
#define ENABLE_MSTAR_EDEN_MMAP_32MB 0
#define USE_MSTAR_EDEN_MMAP_32MB(...)
#define SKIP_MSTAR_EDEN_MMAP_32MB(...) __VA_ARGS__
#undef CONFIG_MSTAR_EULER_MMAP_128MB
#define ENABLE_MSTAR_EULER_MMAP_128MB 0
#define USE_MSTAR_EULER_MMAP_128MB(...)
#define SKIP_MSTAR_EULER_MMAP_128MB(...) __VA_ARGS__
#undef CONFIG_MSTAR_EULER_MMAP_64MB
#define ENABLE_MSTAR_EULER_MMAP_64MB 0
#define USE_MSTAR_EULER_MMAP_64MB(...)
#define SKIP_MSTAR_EULER_MMAP_64MB(...) __VA_ARGS__
#undef CONFIG_MSTAR_EULER_MMAP_32MB
#define ENABLE_MSTAR_EULER_MMAP_32MB 0
#define USE_MSTAR_EULER_MMAP_32MB(...)
#define SKIP_MSTAR_EULER_MMAP_32MB(...) __VA_ARGS__
#undef CONFIG_MSTAR_KRONUS_MMAP_32MB
#define ENABLE_MSTAR_KRONUS_MMAP_32MB 0
#define USE_MSTAR_KRONUS_MMAP_32MB(...)
#define SKIP_MSTAR_KRONUS_MMAP_32MB(...) __VA_ARGS__
#undef CONFIG_MSTAR_KRONUS_MMAP_64MB
#define ENABLE_MSTAR_KRONUS_MMAP_64MB 0
#define USE_MSTAR_KRONUS_MMAP_64MB(...)
#define SKIP_MSTAR_KRONUS_MMAP_64MB(...) __VA_ARGS__
#undef CONFIG_MSTAR_KRONUS_MMAP_128MB
#define ENABLE_MSTAR_KRONUS_MMAP_128MB 0
#define USE_MSTAR_KRONUS_MMAP_128MB(...)
#define SKIP_MSTAR_KRONUS_MMAP_128MB(...) __VA_ARGS__
#undef CONFIG_MSTAR_KRONUS_MMAP_256MB
#define ENABLE_MSTAR_KRONUS_MMAP_256MB 0
#define USE_MSTAR_KRONUS_MMAP_256MB(...)
#define SKIP_MSTAR_KRONUS_MMAP_256MB(...) __VA_ARGS__
#undef CONFIG_MSTAR_KAISERIN_MMAP_128MB_128MB
#define ENABLE_MSTAR_KAISERIN_MMAP_128MB_128MB 0
#define USE_MSTAR_KAISERIN_MMAP_128MB_128MB(...)
#define SKIP_MSTAR_KAISERIN_MMAP_128MB_128MB(...) __VA_ARGS__
#undef CONFIG_MSTAR_KAISERIN_MMAP_256MB_128MB
#define ENABLE_MSTAR_KAISERIN_MMAP_256MB_128MB 0
#define USE_MSTAR_KAISERIN_MMAP_256MB_128MB(...)
#define SKIP_MSTAR_KAISERIN_MMAP_256MB_128MB(...) __VA_ARGS__
#undef CONFIG_MSTAR_KAISERIN_MMAP_256MB_256MB
#define ENABLE_MSTAR_KAISERIN_MMAP_256MB_256MB 0
#define USE_MSTAR_KAISERIN_MMAP_256MB_256MB(...)
#define SKIP_MSTAR_KAISERIN_MMAP_256MB_256MB(...) __VA_ARGS__
#undef CONFIG_MSTAR_KAISERIN_MMAP_512MB_512MB
#define ENABLE_MSTAR_KAISERIN_MMAP_512MB_512MB 0
#define USE_MSTAR_KAISERIN_MMAP_512MB_512MB(...)
#define SKIP_MSTAR_KAISERIN_MMAP_512MB_512MB(...) __VA_ARGS__
#undef CONFIG_MEM2133MHz
#define ENABLE_MEM2133MHz 0
#define USE_MEM2133MHz(...)
#define SKIP_MEM2133MHz(...) __VA_ARGS__
#undef CONFIG_MEM1866MHz
#define ENABLE_MEM1866MHz 0
#define USE_MEM1866MHz(...)
#define SKIP_MEM1866MHz(...) __VA_ARGS__
#define CONFIG_MEM1600MHz 1
#define ENABLE_MEM1600MHz 1
#define USE_MEM1600MHz(...) __VA_ARGS__
#define SKIP_MEM1600MHz(...)
#undef CONFIG_MEM1300MHz
#define ENABLE_MEM1300MHz 0
#define USE_MEM1300MHz(...)
#define SKIP_MEM1300MHz(...) __VA_ARGS__
#undef CONFIG_MEM1333MHz
#define ENABLE_MEM1333MHz 0
#define USE_MEM1333MHz(...)
#define SKIP_MEM1333MHz(...) __VA_ARGS__
#undef CONFIG_MEM1066MHz
#define ENABLE_MEM1066MHz 0
#define USE_MEM1066MHz(...)
#define SKIP_MEM1066MHz(...) __VA_ARGS__
#undef CONFIG_MEM800MHz
#define ENABLE_MEM800MHz 0
#define USE_MEM800MHz(...)
#define SKIP_MEM800MHz(...) __VA_ARGS__
#undef CONFIG_MEM667MHz
#define ENABLE_MEM667MHz 0
#define USE_MEM667MHz(...)
#define SKIP_MEM667MHz(...) __VA_ARGS__
#undef CONFIG_MEM400MHz
#define ENABLE_MEM400MHz 0
#define USE_MEM400MHz(...)
#define SKIP_MEM400MHz(...) __VA_ARGS__
#undef CONFIG_DDR3_16BIT_MODE
#define ENABLE_DDR3_16BIT_MODE 0
#define USE_DDR3_16BIT_MODE(...)
#define SKIP_DDR3_16BIT_MODE(...) __VA_ARGS__
#undef CONFIG_DDR3_8BIT_MODE
#define ENABLE_DDR3_8BIT_MODE 0
#define USE_DDR3_8BIT_MODE(...)
#define SKIP_DDR3_8BIT_MODE(...) __VA_ARGS__
#undef CONFIG_MIU0_DRAM_NONE
#define ENABLE_MIU0_DRAM_NONE 0
#define USE_MIU0_DRAM_NONE(...)
#define SKIP_MIU0_DRAM_NONE(...) __VA_ARGS__
#undef CONFIG_MIU0_DDR3_2133
#define ENABLE_MIU0_DDR3_2133 0
#define USE_MIU0_DDR3_2133(...)
#define SKIP_MIU0_DDR3_2133(...) __VA_ARGS__
#undef CONFIG_MIU0_DDR3_1866
#define ENABLE_MIU0_DDR3_1866 0
#define USE_MIU0_DDR3_1866(...)
#define SKIP_MIU0_DDR3_1866(...) __VA_ARGS__
#undef CONFIG_MIU0_DDR3_1666
#define ENABLE_MIU0_DDR3_1666 0
#define USE_MIU0_DDR3_1666(...)
#define SKIP_MIU0_DDR3_1666(...) __VA_ARGS__
#undef CONFIG_MIU0_DDR3_1333
#define ENABLE_MIU0_DDR3_1333 0
#define USE_MIU0_DDR3_1333(...)
#define SKIP_MIU0_DDR3_1333(...) __VA_ARGS__
#undef CONFIG_MIU0_DDR3_1066
#define ENABLE_MIU0_DDR3_1066 0
#define USE_MIU0_DDR3_1066(...)
#define SKIP_MIU0_DDR3_1066(...) __VA_ARGS__
#undef CONFIG_MIU0_DDR2_1066
#define ENABLE_MIU0_DDR2_1066 0
#define USE_MIU0_DDR2_1066(...)
#define SKIP_MIU0_DDR2_1066(...) __VA_ARGS__
#undef CONFIG_MIU0_DDR2_800
#define ENABLE_MIU0_DDR2_800 0
#define USE_MIU0_DDR2_800(...)
#define SKIP_MIU0_DDR2_800(...) __VA_ARGS__
#undef CONFIG_MIU1_DRAM_NONE
#define ENABLE_MIU1_DRAM_NONE 0
#define USE_MIU1_DRAM_NONE(...)
#define SKIP_MIU1_DRAM_NONE(...) __VA_ARGS__
#undef CONFIG_MIU1_DDR3_2133
#define ENABLE_MIU1_DDR3_2133 0
#define USE_MIU1_DDR3_2133(...)
#define SKIP_MIU1_DDR3_2133(...) __VA_ARGS__
#undef CONFIG_MIU1_DDR3_1866
#define ENABLE_MIU1_DDR3_1866 0
#define USE_MIU1_DDR3_1866(...)
#define SKIP_MIU1_DDR3_1866(...) __VA_ARGS__
#undef CONFIG_MIU1_DDR3_1666
#define ENABLE_MIU1_DDR3_1666 0
#define USE_MIU1_DDR3_1666(...)
#define SKIP_MIU1_DDR3_1666(...) __VA_ARGS__
#undef CONFIG_MIU1_DDR3_1333
#define ENABLE_MIU1_DDR3_1333 0
#define USE_MIU1_DDR3_1333(...)
#define SKIP_MIU1_DDR3_1333(...) __VA_ARGS__
#undef CONFIG_MIU1_DDR3_1066
#define ENABLE_MIU1_DDR3_1066 0
#define USE_MIU1_DDR3_1066(...)
#define SKIP_MIU1_DDR3_1066(...) __VA_ARGS__
#undef CONFIG_MIU1_DDR2_1066
#define ENABLE_MIU1_DDR2_1066 0
#define USE_MIU1_DDR2_1066(...)
#define SKIP_MIU1_DDR2_1066(...) __VA_ARGS__
#undef CONFIG_MIU1_DDR2_800
#define ENABLE_MIU1_DDR2_800 0
#define USE_MIU1_DDR2_800(...)
#define SKIP_MIU1_DDR2_800(...) __VA_ARGS__
#undef CONFIG_ENABLE_MIU_SWAP
#define ENABLE_ENABLE_MIU_SWAP 0
#define USE_ENABLE_MIU_SWAP(...)
#define SKIP_ENABLE_MIU_SWAP(...) __VA_ARGS__
#undef CONFIG_BIST_0x0401_UNITS
#define ENABLE_BIST_0x0401_UNITS 0
#define USE_BIST_0x0401_UNITS(...)
#define SKIP_BIST_0x0401_UNITS(...) __VA_ARGS__
#define CONFIG_BIST_0x1001_UNITS 1
#define ENABLE_BIST_0x1001_UNITS 1
#define USE_BIST_0x1001_UNITS(...) __VA_ARGS__
#define SKIP_BIST_0x1001_UNITS(...)
#undef CONFIG_BIST_0x8001_UNITS
#define ENABLE_BIST_0x8001_UNITS 0
#define USE_BIST_0x8001_UNITS(...)
#define SKIP_BIST_0x8001_UNITS(...) __VA_ARGS__
#define CONFIG_MIU0_BUSADDR 0x40000000
#define ENABLE_MIU0_BUSADDR 1
#define USE_MIU0_BUSADDR(...) __VA_ARGS__
#define SKIP_MIU0_BUSADDR(...)
#define CONFIG_MIU1_BUSADDR 0xA0000000
#define ENABLE_MIU1_BUSADDR 1
#define USE_MIU1_BUSADDR(...) __VA_ARGS__
#define SKIP_MIU1_BUSADDR(...)
#define CONFIG_BOOTRAM_LOADADDR 0x40100000
#define ENABLE_BOOTRAM_LOADADDR 1
#define USE_BOOTRAM_LOADADDR(...) __VA_ARGS__
#define SKIP_BOOTRAM_LOADADDR(...)
#define CONFIG_UBOOT_LOADADDR 0x567c0000
#define ENABLE_UBOOT_LOADADDR 1
#define USE_UBOOT_LOADADDR(...) __VA_ARGS__
#define SKIP_UBOOT_LOADADDR(...)
#define CONFIG_KERNEL_START_ADDRESS 0x40200000
#define ENABLE_KERNEL_START_ADDRESS 1
#define USE_KERNEL_START_ADDRESS(...) __VA_ARGS__
#define SKIP_KERNEL_START_ADDRESS(...)
#define CONFIG_DRAM_SIZE_MB_RELOCATE 480
#define ENABLE_DRAM_SIZE_MB_RELOCATE 1
#define USE_DRAM_SIZE_MB_RELOCATE(...) __VA_ARGS__
#define SKIP_DRAM_SIZE_MB_RELOCATE(...)

/*
 * Extended CPU Configuration
 */
#undef CONFIG_ENABLE_AUTO_DQS
#define ENABLE_ENABLE_AUTO_DQS 0
#define USE_ENABLE_AUTO_DQS(...)
#define SKIP_ENABLE_AUTO_DQS(...) __VA_ARGS__
#undef CONFIG_MSTAR_DFS_ENABLE
#define ENABLE_MSTAR_DFS_ENABLE 0
#define USE_MSTAR_DFS_ENABLE(...)
#define SKIP_MSTAR_DFS_ENABLE(...) __VA_ARGS__
#define CONFIG_MSTAR_VID_ENABLE 1
#define ENABLE_MSTAR_VID_ENABLE 1
#define USE_MSTAR_VID_ENABLE(...) __VA_ARGS__
#define SKIP_MSTAR_VID_ENABLE(...)
#undef CONFIG_MSTAR_MOBF_ENABLE
#define ENABLE_MSTAR_MOBF_ENABLE 0
#define USE_MSTAR_MOBF_ENABLE(...)
#define SKIP_MSTAR_MOBF_ENABLE(...) __VA_ARGS__
#undef CONFIG_MSTAR_ASIC_EMULATION_ENABLE
#define ENABLE_MSTAR_ASIC_EMULATION_ENABLE 0
#define USE_MSTAR_ASIC_EMULATION_ENABLE(...)
#define SKIP_MSTAR_ASIC_EMULATION_ENABLE(...) __VA_ARGS__
#undef CONFIG_MSTAR_MIPS_SINGLE_CORE
#define ENABLE_MSTAR_MIPS_SINGLE_CORE 0
#define USE_MSTAR_MIPS_SINGLE_CORE(...)
#define SKIP_MSTAR_MIPS_SINGLE_CORE(...) __VA_ARGS__
#undef CONFIG_MSTAR_MIPS_DUAL_CORE
#define ENABLE_MSTAR_MIPS_DUAL_CORE 0
#define USE_MSTAR_MIPS_DUAL_CORE(...)
#define SKIP_MSTAR_MIPS_DUAL_CORE(...) __VA_ARGS__
#undef CONFIG_MSTAR_MIPS_SINGLE_VPE_PER_CORE
#define ENABLE_MSTAR_MIPS_SINGLE_VPE_PER_CORE 0
#define USE_MSTAR_MIPS_SINGLE_VPE_PER_CORE(...)
#define SKIP_MSTAR_MIPS_SINGLE_VPE_PER_CORE(...) __VA_ARGS__
#undef CONFIG_MSTAR_MIPS_DUAL_VPE_PER_CORE
#define ENABLE_MSTAR_MIPS_DUAL_VPE_PER_CORE 0
#define USE_MSTAR_MIPS_DUAL_VPE_PER_CORE(...)
#define SKIP_MSTAR_MIPS_DUAL_VPE_PER_CORE(...) __VA_ARGS__
#undef CONFIG_MSTAR_MIPS_OCP_CLOCK_RATIO_1_1
#define ENABLE_MSTAR_MIPS_OCP_CLOCK_RATIO_1_1 0
#define USE_MSTAR_MIPS_OCP_CLOCK_RATIO_1_1(...)
#define SKIP_MSTAR_MIPS_OCP_CLOCK_RATIO_1_1(...) __VA_ARGS__
#undef CONFIG_MSTAR_MIPS_OCP_CLOCK_RATIO_1_2
#define ENABLE_MSTAR_MIPS_OCP_CLOCK_RATIO_1_2 0
#define USE_MSTAR_MIPS_OCP_CLOCK_RATIO_1_2(...)
#define SKIP_MSTAR_MIPS_OCP_CLOCK_RATIO_1_2(...) __VA_ARGS__
#undef CONFIG_MSTAR_MIPS_OCP_CLOCK_RATIO_1_3
#define ENABLE_MSTAR_MIPS_OCP_CLOCK_RATIO_1_3 0
#define USE_MSTAR_MIPS_OCP_CLOCK_RATIO_1_3(...)
#define SKIP_MSTAR_MIPS_OCP_CLOCK_RATIO_1_3(...) __VA_ARGS__
#undef CONFIG_MSTAR_MIPS_OCP_CLOCK_RATIO_1_4
#define ENABLE_MSTAR_MIPS_OCP_CLOCK_RATIO_1_4 0
#define USE_MSTAR_MIPS_OCP_CLOCK_RATIO_1_4(...)
#define SKIP_MSTAR_MIPS_OCP_CLOCK_RATIO_1_4(...) __VA_ARGS__
#undef CONFIG_MSTAR_MIPS_OCP_CLOCK_RATIO_1_5
#define ENABLE_MSTAR_MIPS_OCP_CLOCK_RATIO_1_5 0
#define USE_MSTAR_MIPS_OCP_CLOCK_RATIO_1_5(...)
#define SKIP_MSTAR_MIPS_OCP_CLOCK_RATIO_1_5(...) __VA_ARGS__
#undef CONFIG_MSTAR_L2_CACHE_ENABLE
#define ENABLE_MSTAR_L2_CACHE_ENABLE 0
#define USE_MSTAR_L2_CACHE_ENABLE(...)
#define SKIP_MSTAR_L2_CACHE_ENABLE(...) __VA_ARGS__
#undef CONFIG_MSTAR_CPU_PREFETCH_ENABLE
#define ENABLE_MSTAR_CPU_PREFETCH_ENABLE 0
#define USE_MSTAR_CPU_PREFETCH_ENABLE(...)
#define SKIP_MSTAR_CPU_PREFETCH_ENABLE(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_L2_CACHE_128K_BYTES
#define ENABLE_MSTAR_TITANIA_L2_CACHE_128K_BYTES 0
#define USE_MSTAR_TITANIA_L2_CACHE_128K_BYTES(...)
#define SKIP_MSTAR_TITANIA_L2_CACHE_128K_BYTES(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_L2_CACHE_256K_BYTES
#define ENABLE_MSTAR_TITANIA_L2_CACHE_256K_BYTES 0
#define USE_MSTAR_TITANIA_L2_CACHE_256K_BYTES(...)
#define SKIP_MSTAR_TITANIA_L2_CACHE_256K_BYTES(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_L2_CACHE_WRITE_BACK
#define ENABLE_MSTAR_TITANIA_L2_CACHE_WRITE_BACK 0
#define USE_MSTAR_TITANIA_L2_CACHE_WRITE_BACK(...)
#define SKIP_MSTAR_TITANIA_L2_CACHE_WRITE_BACK(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_L2_CACHE_WRITE_THROUGH
#define ENABLE_MSTAR_TITANIA_L2_CACHE_WRITE_THROUGH 0
#define USE_MSTAR_TITANIA_L2_CACHE_WRITE_THROUGH(...)
#define SKIP_MSTAR_TITANIA_L2_CACHE_WRITE_THROUGH(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_L2_CACHE_LINE_32_BYTES
#define ENABLE_MSTAR_TITANIA_L2_CACHE_LINE_32_BYTES 0
#define USE_MSTAR_TITANIA_L2_CACHE_LINE_32_BYTES(...)
#define SKIP_MSTAR_TITANIA_L2_CACHE_LINE_32_BYTES(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_L2_CACHE_LINE_64_BYTES
#define ENABLE_MSTAR_TITANIA_L2_CACHE_LINE_64_BYTES 0
#define USE_MSTAR_TITANIA_L2_CACHE_LINE_64_BYTES(...)
#define SKIP_MSTAR_TITANIA_L2_CACHE_LINE_64_BYTES(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_L2_CACHE_LINE_128_BYTES
#define ENABLE_MSTAR_TITANIA_L2_CACHE_LINE_128_BYTES 0
#define USE_MSTAR_TITANIA_L2_CACHE_LINE_128_BYTES(...)
#define SKIP_MSTAR_TITANIA_L2_CACHE_LINE_128_BYTES(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_L2_CACHE_LINE_256_BYTES
#define ENABLE_MSTAR_TITANIA_L2_CACHE_LINE_256_BYTES 0
#define USE_MSTAR_TITANIA_L2_CACHE_LINE_256_BYTES(...)
#define SKIP_MSTAR_TITANIA_L2_CACHE_LINE_256_BYTES(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_PREFETCH_LINE_32_BYTES
#define ENABLE_MSTAR_TITANIA_PREFETCH_LINE_32_BYTES 0
#define USE_MSTAR_TITANIA_PREFETCH_LINE_32_BYTES(...)
#define SKIP_MSTAR_TITANIA_PREFETCH_LINE_32_BYTES(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_PREFETCH_LINE_64_BYTES
#define ENABLE_MSTAR_TITANIA_PREFETCH_LINE_64_BYTES 0
#define USE_MSTAR_TITANIA_PREFETCH_LINE_64_BYTES(...)
#define SKIP_MSTAR_TITANIA_PREFETCH_LINE_64_BYTES(...) __VA_ARGS__
#undef CONFIG_MSTAR_MEMORY_PREFETCH_ENABLE
#define ENABLE_MSTAR_MEMORY_PREFETCH_ENABLE 0
#define USE_MSTAR_MEMORY_PREFETCH_ENABLE(...)
#define SKIP_MSTAR_MEMORY_PREFETCH_ENABLE(...) __VA_ARGS__
#undef CONFIG_MSTAR_FORCE_REQUEST_INTO_CACHE
#define ENABLE_MSTAR_FORCE_REQUEST_INTO_CACHE 0
#define USE_MSTAR_FORCE_REQUEST_INTO_CACHE(...)
#define SKIP_MSTAR_FORCE_REQUEST_INTO_CACHE(...) __VA_ARGS__
#undef CONFIG_MSTAR_MIU_HIGHWAY_ENABLE
#define ENABLE_MSTAR_MIU_HIGHWAY_ENABLE 0
#define USE_MSTAR_MIU_HIGHWAY_ENABLE(...)
#define SKIP_MSTAR_MIU_HIGHWAY_ENABLE(...) __VA_ARGS__
#undef CONFIG_MSTAR_32BIT_RIU_MASK_ENABLE
#define ENABLE_MSTAR_32BIT_RIU_MASK_ENABLE 0
#define USE_MSTAR_32BIT_RIU_MASK_ENABLE(...)
#define SKIP_MSTAR_32BIT_RIU_MASK_ENABLE(...) __VA_ARGS__
#undef CONFIG_MSTAR_TLB_SHARE_ENABLE
#define ENABLE_MSTAR_TLB_SHARE_ENABLE 0
#define USE_MSTAR_TLB_SHARE_ENABLE(...)
#define SKIP_MSTAR_TLB_SHARE_ENABLE(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_MIU1_ENABLE
#define ENABLE_MSTAR_TITANIA_MIU1_ENABLE 0
#define USE_MSTAR_TITANIA_MIU1_ENABLE(...)
#define SKIP_MSTAR_TITANIA_MIU1_ENABLE(...) __VA_ARGS__

/*
 * General Configuration
 */

/*
 * Mmap Configuartion
 */
#undef CONFIG_HEAP_SIZE_CONFIG
#define ENABLE_HEAP_SIZE_CONFIG 0
#define USE_HEAP_SIZE_CONFIG(...)
#define SKIP_HEAP_SIZE_CONFIG(...) __VA_ARGS__
#define CONFIG_UBOOT_HEAP_SIZE 0x
#define ENABLE_UBOOT_HEAP_SIZE 1
#define USE_UBOOT_HEAP_SIZE(...) __VA_ARGS__
#define SKIP_UBOOT_HEAP_SIZE(...)
#define CONFIG_LOGO_CUSTOM_CONFIG 1
#define ENABLE_LOGO_CUSTOM_CONFIG 1
#define USE_LOGO_CUSTOM_CONFIG(...) __VA_ARGS__
#define SKIP_LOGO_CUSTOM_CONFIG(...)

/*
 * Logo custom-config
 */
#define CONFIG_JPD_READBUFF_ADR 0x001BDC2000
#define ENABLE_JPD_READBUFF_ADR 1
#define USE_JPD_READBUFF_ADR(...) __VA_ARGS__
#define SKIP_JPD_READBUFF_ADR(...)
#define CONFIG_JPD_READBUFF_LEN 0x0100000
#define ENABLE_JPD_READBUFF_LEN 1
#define USE_JPD_READBUFF_LEN(...) __VA_ARGS__
#define SKIP_JPD_READBUFF_LEN(...)
#define CONFIG_JPD_INTERBUFF_ADR 0x001BEC2000
#define ENABLE_JPD_INTERBUFF_ADR 1
#define USE_JPD_INTERBUFF_ADR(...) __VA_ARGS__
#define SKIP_JPD_INTERBUFF_ADR(...)
#define CONFIG_JPD_INTERBUFF_LEN 0x00100000
#define ENABLE_JPD_INTERBUFF_LEN 1
#define USE_JPD_INTERBUFF_LEN(...) __VA_ARGS__
#define SKIP_JPD_INTERBUFF_LEN(...)
#define CONFIG_JPD_OUT_ADR 0x001BFC2000
#define ENABLE_JPD_OUT_ADR 1
#define USE_JPD_OUT_ADR(...) __VA_ARGS__
#define SKIP_JPD_OUT_ADR(...)
#define CONFIG_JPD_OUT_LEN 0x009CA000
#define ENABLE_JPD_OUT_LEN 1
#define USE_JPD_OUT_LEN(...) __VA_ARGS__
#define SKIP_JPD_OUT_LEN(...)
#define CONFIG_LOGO_JPG_DRAM_ADDR 0x0005B2C000
#define ENABLE_LOGO_JPG_DRAM_ADDR 1
#define USE_LOGO_JPG_DRAM_ADDR(...) __VA_ARGS__
#define SKIP_LOGO_JPG_DRAM_ADDR(...)
#define CONFIG_GOP_BUFFER_ADDR 0x001E801000
#define ENABLE_GOP_BUFFER_ADDR 1
#define USE_GOP_BUFFER_ADDR(...) __VA_ARGS__
#define SKIP_GOP_BUFFER_ADDR(...)
#define CONFIG_AUDIO_CUSTOM_CONFIG 1
#define ENABLE_AUDIO_CUSTOM_CONFIG 1
#define USE_AUDIO_CUSTOM_CONFIG(...) __VA_ARGS__
#define SKIP_AUDIO_CUSTOM_CONFIG(...)

/*
 * Audio custom-config
 */
#define CONFIG_AUDIO_R2_MEM_INFO_ADR 0x12A80000
#define ENABLE_AUDIO_R2_MEM_INFO_ADR 1
#define USE_AUDIO_R2_MEM_INFO_ADR(...) __VA_ARGS__
#define SKIP_AUDIO_R2_MEM_INFO_ADR(...)
#define CONFIG_AUDIO_S_MEM_INFO_ADR 0x12BC0000
#define ENABLE_AUDIO_S_MEM_INFO_ADR 1
#define USE_AUDIO_S_MEM_INFO_ADR(...) __VA_ARGS__
#define SKIP_AUDIO_S_MEM_INFO_ADR(...)
#define CONFIG_AUDIO_D_MEM_INFO_ADR 0x12DC0000
#define ENABLE_AUDIO_D_MEM_INFO_ADR 1
#define USE_AUDIO_D_MEM_INFO_ADR(...) __VA_ARGS__
#define SKIP_AUDIO_D_MEM_INFO_ADR(...)
#define CONFIG_FEATURE_BUFFERS_USE_MALLOC 1
#define ENABLE_FEATURE_BUFFERS_USE_MALLOC 1
#define USE_FEATURE_BUFFERS_USE_MALLOC(...) __VA_ARGS__
#define SKIP_FEATURE_BUFFERS_USE_MALLOC(...)
#undef CONFIG_FEATURE_BUFFERS_GO_ON_STACK
#define ENABLE_FEATURE_BUFFERS_GO_ON_STACK 0
#define USE_FEATURE_BUFFERS_GO_ON_STACK(...)
#define SKIP_FEATURE_BUFFERS_GO_ON_STACK(...) __VA_ARGS__
#undef CONFIG_FEATURE_BUFFERS_GO_IN_BSS
#define ENABLE_FEATURE_BUFFERS_GO_IN_BSS 0
#define USE_FEATURE_BUFFERS_GO_IN_BSS(...)
#define SKIP_FEATURE_BUFFERS_GO_IN_BSS(...) __VA_ARGS__
#define CONFIG_ANDROID_BOOT 1
#define ENABLE_ANDROID_BOOT 1
#define USE_ANDROID_BOOT(...) __VA_ARGS__
#define SKIP_ANDROID_BOOT(...)
#undef CONFIG_UART1_SEL
#define ENABLE_UART1_SEL 0
#define USE_UART1_SEL(...)
#define SKIP_UART1_SEL(...) __VA_ARGS__
#undef CONFIG_EMMC_BOOT
#define ENABLE_EMMC_BOOT 0
#define USE_EMMC_BOOT(...)
#define SKIP_EMMC_BOOT(...) __VA_ARGS__
#undef CONFIG_TOP_AND_BOTTOM_BOOT
#define ENABLE_TOP_AND_BOTTOM_BOOT 0
#define USE_TOP_AND_BOTTOM_BOOT(...)
#define SKIP_TOP_AND_BOTTOM_BOOT(...) __VA_ARGS__
#undef CONFIG_TOP_BOOT_ENABLE
#define ENABLE_TOP_BOOT_ENABLE 0
#define USE_TOP_BOOT_ENABLE(...)
#define SKIP_TOP_BOOT_ENABLE(...) __VA_ARGS__
#undef CONFIG_BOTTOM_BOOT_ENABLE
#define ENABLE_BOTTOM_BOOT_ENABLE 0
#define USE_BOTTOM_BOOT_ENABLE(...)
#define SKIP_BOTTOM_BOOT_ENABLE(...) __VA_ARGS__
#undef CONFIG_SBOOT_TO_KERNEL
#define ENABLE_SBOOT_TO_KERNEL 0
#define USE_SBOOT_TO_KERNEL(...)
#define SKIP_SBOOT_TO_KERNEL(...) __VA_ARGS__
#undef CONFIG_KERNEL_2_6_28_9
#define ENABLE_KERNEL_2_6_28_9 0
#define USE_KERNEL_2_6_28_9(...)
#define SKIP_KERNEL_2_6_28_9(...) __VA_ARGS__
#undef CONFIG_KERNEL_2_6_32_15
#define ENABLE_KERNEL_2_6_32_15 0
#define USE_KERNEL_2_6_32_15(...)
#define SKIP_KERNEL_2_6_32_15(...) __VA_ARGS__
#undef CONFIG_KERNEL_2_6_35_11
#define ENABLE_KERNEL_2_6_35_11 0
#define USE_KERNEL_2_6_35_11(...)
#define SKIP_KERNEL_2_6_35_11(...) __VA_ARGS__
#undef CONFIG_KERNEL_3_0_20
#define ENABLE_KERNEL_3_0_20 0
#define USE_KERNEL_3_0_20(...)
#define SKIP_KERNEL_3_0_20(...) __VA_ARGS__
#define CONFIG_SHOW_USAGE 1
#define ENABLE_SHOW_USAGE 1
#define USE_SHOW_USAGE(...) __VA_ARGS__
#define SKIP_SHOW_USAGE(...)
#undef CONFIG_NON_OS
#define ENABLE_NON_OS 0
#define USE_NON_OS(...)
#define SKIP_NON_OS(...) __VA_ARGS__
#undef CONFIG_SBOOT_USE_BDMA_TO_CHECK_CRC
#define ENABLE_SBOOT_USE_BDMA_TO_CHECK_CRC 0
#define USE_SBOOT_USE_BDMA_TO_CHECK_CRC(...)
#define SKIP_SBOOT_USE_BDMA_TO_CHECK_CRC(...) __VA_ARGS__
#undef CONFIG_SECURE_BOOT
#define ENABLE_SECURE_BOOT 0
#define USE_SECURE_BOOT(...)
#define SKIP_SECURE_BOOT(...) __VA_ARGS__
#undef CONFIG_COMPRESSED_UBOOT
#define ENABLE_COMPRESSED_UBOOT 0
#define USE_COMPRESSED_UBOOT(...)
#define SKIP_COMPRESSED_UBOOT(...) __VA_ARGS__
#undef CONFIG_MSTAR_MARIA10_PM
#define ENABLE_MSTAR_MARIA10_PM 0
#define USE_MSTAR_MARIA10_PM(...)
#define SKIP_MSTAR_MARIA10_PM(...) __VA_ARGS__
#undef CONFIG_MSTAR_MACAW12_PM
#define ENABLE_MSTAR_MACAW12_PM 0
#define USE_MSTAR_MACAW12_PM(...)
#define SKIP_MSTAR_MACAW12_PM(...) __VA_ARGS__
#undef CONFIG_MSTAR_EDEN_PM
#define ENABLE_MSTAR_EDEN_PM 0
#define USE_MSTAR_EDEN_PM(...)
#define SKIP_MSTAR_EDEN_PM(...) __VA_ARGS__
#undef CONFIG_MSTAR_EULER_PM
#define ENABLE_MSTAR_EULER_PM 0
#define USE_MSTAR_EULER_PM(...)
#define SKIP_MSTAR_EULER_PM(...) __VA_ARGS__
#define CONFIG_DISPLAY_VERSIONINFO 1
#define ENABLE_DISPLAY_VERSIONINFO 1
#define USE_DISPLAY_VERSIONINFO(...) __VA_ARGS__
#define SKIP_DISPLAY_VERSIONINFO(...)
#define CONFIG_CHANGELIST "00112233"
#define ENABLE_CHANGELIST 1
#define USE_CHANGELIST(...) __VA_ARGS__
#define SKIP_CHANGELIST(...)

/*
 * Build Options
 */
#define CONFIG_CROSS_COMPILER_PREFIX "arm-none-eabi-"
#define ENABLE_CROSS_COMPILER_PREFIX 1
#define USE_CROSS_COMPILER_PREFIX(...) __VA_ARGS__
#define SKIP_CROSS_COMPILER_PREFIX(...)
#define CONFIG_EXTRA_CFLAGS "-march=armv7-a"
#define ENABLE_EXTRA_CFLAGS 1
#define USE_EXTRA_CFLAGS(...) __VA_ARGS__
#define SKIP_EXTRA_CFLAGS(...)
#define CONFIG_EXTRA_AFLAGS "-march=armv7-a"
#define ENABLE_EXTRA_AFLAGS 1
#define USE_EXTRA_AFLAGS(...) __VA_ARGS__
#define SKIP_EXTRA_AFLAGS(...)

/*
 * Debugging Options
 */
#undef CONFIG_DEBUG
#define ENABLE_DEBUG 0
#define USE_DEBUG(...)
#define SKIP_DEBUG(...) __VA_ARGS__
#undef CONFIG_DEBUG_PESSIMIZE
#define ENABLE_DEBUG_PESSIMIZE 0
#define USE_DEBUG_PESSIMIZE(...)
#define SKIP_DEBUG_PESSIMIZE(...) __VA_ARGS__
#undef CONFIG_WERROR
#define ENABLE_WERROR 0
#define USE_WERROR(...)
#define SKIP_WERROR(...) __VA_ARGS__
#undef CONFIG_EARLY_DISABLE_UART
#define ENABLE_EARLY_DISABLE_UART 0
#define USE_EARLY_DISABLE_UART(...)
#define SKIP_EARLY_DISABLE_UART(...) __VA_ARGS__

/*
 * Installation Options
 */
#define CONFIG_PREFIX "./_install"
#define ENABLE_PREFIX 1
#define USE_PREFIX(...) __VA_ARGS__
#define SKIP_PREFIX(...)

/*
 * Module Options
 */
#define CONFIG_COMPRESS 1
#define ENABLE_COMPRESS 1
#define USE_COMPRESS(...) __VA_ARGS__
#define SKIP_COMPRESS(...)
#define CONFIG_DONT_OVERWRITE 1
#define ENABLE_DONT_OVERWRITE 1
#define USE_DONT_OVERWRITE(...) __VA_ARGS__
#define SKIP_DONT_OVERWRITE(...)
#define CONFIG_USB 1
#define ENABLE_USB 1
#define USE_USB(...) __VA_ARGS__
#define SKIP_USB(...)
#undef CONFIG_USB_LAN
#define ENABLE_USB_LAN 0
#define USE_USB_LAN(...)
#define SKIP_USB_LAN(...) __VA_ARGS__
#define CONFIG_FLASH_TYPE 1
#define ENABLE_FLASH_TYPE 1
#define USE_FLASH_TYPE(...) __VA_ARGS__
#define SKIP_FLASH_TYPE(...)
#undef CONFIG_NAND_FLASH
#define ENABLE_NAND_FLASH 0
#define USE_NAND_FLASH(...)
#define SKIP_NAND_FLASH(...) __VA_ARGS__
#undef CONFIG_BFN_WRITE_NAND
#define ENABLE_BFN_WRITE_NAND 0
#define USE_BFN_WRITE_NAND(...)
#define SKIP_BFN_WRITE_NAND(...) __VA_ARGS__
#undef CONFIG_BOOT_FROM_NAND
#define ENABLE_BOOT_FROM_NAND 0
#define USE_BOOT_FROM_NAND(...)
#define SKIP_BOOT_FROM_NAND(...) __VA_ARGS__
#define CONFIG_MMC 1
#define ENABLE_MMC 1
#define USE_MMC(...) __VA_ARGS__
#define SKIP_MMC(...)
#undef CONFIG_SD
#define ENABLE_SD 0
#define USE_SD(...)
#define SKIP_SD(...) __VA_ARGS__
#undef CONFIG_BOOT_FROM_EMMC
#define ENABLE_BOOT_FROM_EMMC 0
#define USE_BOOT_FROM_EMMC(...)
#define SKIP_BOOT_FROM_EMMC(...) __VA_ARGS__
#define CONFIG_SPI 1
#define ENABLE_SPI 1
#define USE_SPI(...) __VA_ARGS__
#define SKIP_SPI(...)
#undef CONFIG_APP_IN_SPI
#define ENABLE_APP_IN_SPI 0
#define USE_APP_IN_SPI(...)
#define SKIP_APP_IN_SPI(...) __VA_ARGS__
#undef CONFIG_UBI
#define ENABLE_UBI 0
#define USE_UBI(...)
#define SKIP_UBI(...) __VA_ARGS__
#undef CONFIG_UBI_MLC_BACKUP_LSB
#define ENABLE_UBI_MLC_BACKUP_LSB 0
#define USE_UBI_MLC_BACKUP_LSB(...)
#define SKIP_UBI_MLC_BACKUP_LSB(...) __VA_ARGS__
#undef CONFIG_UBI_ENHANCE_INIT
#define ENABLE_UBI_ENHANCE_INIT 0
#define USE_UBI_ENHANCE_INIT(...)
#define SKIP_UBI_ENHANCE_INIT(...) __VA_ARGS__
#define CONFIG_FILE_SYSTEM 1
#define ENABLE_FILE_SYSTEM 1
#define USE_FILE_SYSTEM(...) __VA_ARGS__
#define SKIP_FILE_SYSTEM(...)
#define CONFIG_FAT 1
#define ENABLE_FAT 1
#define USE_FAT(...) __VA_ARGS__
#define SKIP_FAT(...)
#define CONFIG_FAT_WRITE 1
#define ENABLE_FAT_WRITE 1
#define USE_FAT_WRITE(...) __VA_ARGS__
#define SKIP_FAT_WRITE(...)
#undef CONFIG_UBI_FS
#define ENABLE_UBI_FS 0
#define USE_UBI_FS(...)
#define SKIP_UBI_FS(...) __VA_ARGS__
#undef CONFIG_JFFS2
#define ENABLE_JFFS2 0
#define USE_JFFS2(...)
#define SKIP_JFFS2(...) __VA_ARGS__
#define CONFIG_CMD_EXT2 1
#define ENABLE_CMD_EXT2 1
#define USE_CMD_EXT2(...) __VA_ARGS__
#define SKIP_CMD_EXT2(...)
#define CONFIG_CMD_EXT4 1
#define ENABLE_CMD_EXT4 1
#define USE_CMD_EXT4(...) __VA_ARGS__
#define SKIP_CMD_EXT4(...)
#define CONFIG_CMD_EXT4_WRITE 1
#define ENABLE_CMD_EXT4_WRITE 1
#define USE_CMD_EXT4_WRITE(...) __VA_ARGS__
#define SKIP_CMD_EXT4_WRITE(...)
#define CONFIG_KEYPAD 1
#define ENABLE_KEYPAD 1
#define USE_KEYPAD(...) __VA_ARGS__
#define SKIP_KEYPAD(...)
#undef CONFIG_KEYPAD_CUST
#define ENABLE_KEYPAD_CUST 0
#define USE_KEYPAD_CUST(...)
#define SKIP_KEYPAD_CUST(...) __VA_ARGS__
#define CONFIG_BOOT_KEYPAD 1
#define ENABLE_BOOT_KEYPAD 1
#define USE_BOOT_KEYPAD(...) __VA_ARGS__
#define SKIP_BOOT_KEYPAD(...)
#define CONFIG_IR 1
#define ENABLE_IR 1
#define USE_IR(...) __VA_ARGS__
#define SKIP_IR(...)
#define CONFIG_BOOT_IR 1
#define ENABLE_BOOT_IR 1
#define USE_BOOT_IR(...) __VA_ARGS__
#define SKIP_BOOT_IR(...)
#undef CONFIG_SECURITY_BOOT
#define ENABLE_SECURITY_BOOT 0
#define USE_SECURITY_BOOT(...)
#define SKIP_SECURITY_BOOT(...) __VA_ARGS__
#undef CONFIG_SECURITY_STORE_IN_SPI_FLASH
#define ENABLE_SECURITY_STORE_IN_SPI_FLASH 0
#define USE_SECURITY_STORE_IN_SPI_FLASH(...)
#define SKIP_SECURITY_STORE_IN_SPI_FLASH(...) __VA_ARGS__
#undef CONFIG_SECURITY_STORE_IN_NAND_FLASH
#define ENABLE_SECURITY_STORE_IN_NAND_FLASH 0
#define USE_SECURITY_STORE_IN_NAND_FLASH(...)
#define SKIP_SECURITY_STORE_IN_NAND_FLASH(...) __VA_ARGS__
#undef CONFIG_SECURITY_STORE_IN_EMMC_FLASH
#define ENABLE_SECURITY_STORE_IN_EMMC_FLASH 0
#define USE_SECURITY_STORE_IN_EMMC_FLASH(...)
#define SKIP_SECURITY_STORE_IN_EMMC_FLASH(...) __VA_ARGS__
#undef CONFIG_SECURE_AESDMA
#define ENABLE_SECURE_AESDMA 0
#define USE_SECURE_AESDMA(...)
#define SKIP_SECURE_AESDMA(...) __VA_ARGS__
#undef CONFIG_SECURE_PARTIAL_AUTHENTICATION
#define ENABLE_SECURE_PARTIAL_AUTHENTICATION 0
#define USE_SECURE_PARTIAL_AUTHENTICATION(...)
#define SKIP_SECURE_PARTIAL_AUTHENTICATION(...) __VA_ARGS__
#undef CONFIG_SECURE_USB_UPGRADE
#define ENABLE_SECURE_USB_UPGRADE 0
#define USE_SECURE_USB_UPGRADE(...)
#define SKIP_SECURE_USB_UPGRADE(...) __VA_ARGS__
#undef CONFIG_SECURE_DEBUG_MESSAGE
#define ENABLE_SECURE_DEBUG_MESSAGE 0
#define USE_SECURE_DEBUG_MESSAGE(...)
#define SKIP_SECURE_DEBUG_MESSAGE(...) __VA_ARGS__
#undef CONFIG_SECURE_SPI_PROTECT
#define ENABLE_SECURE_SPI_PROTECT 0
#define USE_SECURE_SPI_PROTECT(...)
#define SKIP_SECURE_SPI_PROTECT(...) __VA_ARGS__
#undef CONFIG_BOOTING_ACTIVE_SPI_PROTECT
#define ENABLE_BOOTING_ACTIVE_SPI_PROTECT 0
#define USE_BOOTING_ACTIVE_SPI_PROTECT(...)
#define SKIP_BOOTING_ACTIVE_SPI_PROTECT(...) __VA_ARGS__
#undef CONFIG_SECURE_SPI_PARTIAL_PROTECT
#define ENABLE_SECURE_SPI_PARTIAL_PROTECT 0
#define USE_SECURE_SPI_PARTIAL_PROTECT(...)
#define SKIP_SECURE_SPI_PARTIAL_PROTECT(...) __VA_ARGS__
#undef CONFIG_SECURE_SPI_FULL_PROTECT
#define ENABLE_SECURE_SPI_FULL_PROTECT 0
#define USE_SECURE_SPI_FULL_PROTECT(...)
#define SKIP_SECURE_SPI_FULL_PROTECT(...) __VA_ARGS__
#define CONFIG_SECURE_SPI_PROTECT_SPACE 0x
#define ENABLE_SECURE_SPI_PROTECT_SPACE 1
#define USE_SECURE_SPI_PROTECT_SPACE(...) __VA_ARGS__
#define SKIP_SECURE_SPI_PROTECT_SPACE(...)
#define CONFIG_SECURE_SPI_NON_PROTECT_SPACE 0x
#define ENABLE_SECURE_SPI_NON_PROTECT_SPACE 1
#define USE_SECURE_SPI_NON_PROTECT_SPACE(...) __VA_ARGS__
#define SKIP_SECURE_SPI_NON_PROTECT_SPACE(...)
#undef CONFIG_BACKUP_SENSITIVE_TABLE
#define ENABLE_BACKUP_SENSITIVE_TABLE 0
#define USE_BACKUP_SENSITIVE_TABLE(...)
#define SKIP_BACKUP_SENSITIVE_TABLE(...) __VA_ARGS__
#define CONFIG_SPI_OFFSET_OF_BACKUP_TABLE 0x
#define ENABLE_SPI_OFFSET_OF_BACKUP_TABLE 1
#define USE_SPI_OFFSET_OF_BACKUP_TABLE(...) __VA_ARGS__
#define SKIP_SPI_OFFSET_OF_BACKUP_TABLE(...)
#define CONFIG_LZO 1
#define ENABLE_LZO 1
#define USE_LZO(...) __VA_ARGS__
#define SKIP_LZO(...)
#define CONFIG_UNLZO_DST_ADDR 0x5f000000
#define ENABLE_UNLZO_DST_ADDR 1
#define USE_UNLZO_DST_ADDR(...) __VA_ARGS__
#define SKIP_UNLZO_DST_ADDR(...)
#undef CONFIG_HDMI_TX
#define ENABLE_HDMI_TX 0
#define USE_HDMI_TX(...)
#define SKIP_HDMI_TX(...) __VA_ARGS__
#undef CONFIG_HDMITX_NXP_TDA19988
#define ENABLE_HDMITX_NXP_TDA19988 0
#define USE_HDMITX_NXP_TDA19988(...)
#define SKIP_HDMITX_NXP_TDA19988(...) __VA_ARGS__
#undef CONFIG_URSA_6M30
#define ENABLE_URSA_6M30 0
#define USE_URSA_6M30(...)
#define SKIP_URSA_6M30(...) __VA_ARGS__
#undef CONFIG_URSA_6M40
#define ENABLE_URSA_6M40 0
#define USE_URSA_6M40(...)
#define SKIP_URSA_6M40(...) __VA_ARGS__
#undef CONFIG_3D_HWLVDSLRFLAG
#define ENABLE_3D_HWLVDSLRFLAG 0
#define USE_3D_HWLVDSLRFLAG(...)
#define SKIP_3D_HWLVDSLRFLAG(...) __VA_ARGS__
#define CONFIG_PANEL_INIT 1
#define ENABLE_PANEL_INIT 1
#define USE_PANEL_INIT(...) __VA_ARGS__
#define SKIP_PANEL_INIT(...)
#undef CONFIG_TCON_PANEL
#define ENABLE_TCON_PANEL 0
#define USE_TCON_PANEL(...)
#define SKIP_TCON_PANEL(...) __VA_ARGS__
#define CONFIG_DISPLAY_LOGO 1
#define ENABLE_DISPLAY_LOGO 1
#define USE_DISPLAY_LOGO(...) __VA_ARGS__
#define SKIP_DISPLAY_LOGO(...)
#define CONFIG_GOP_OP_PATH 1
#define ENABLE_GOP_OP_PATH 1
#define USE_GOP_OP_PATH(...) __VA_ARGS__
#define SKIP_GOP_OP_PATH(...)
#undef CONFIG_GOP_MIXER2OP_PATH
#define ENABLE_GOP_MIXER2OP_PATH 0
#define USE_GOP_MIXER2OP_PATH(...)
#define SKIP_GOP_MIXER2OP_PATH(...) __VA_ARGS__
#define CONFIG_DISPLAY_LOGO_SPACE 0x40000
#define ENABLE_DISPLAY_LOGO_SPACE 1
#define USE_DISPLAY_LOGO_SPACE(...) __VA_ARGS__
#define SKIP_DISPLAY_LOGO_SPACE(...)
#undef CONFIG_SBOOT_PROTECT
#define ENABLE_SBOOT_PROTECT 0
#define USE_SBOOT_PROTECT(...)
#define SKIP_SBOOT_PROTECT(...) __VA_ARGS__
#define CONFIG_LX1_END 0x
#define ENABLE_LX1_END 1
#define USE_LX1_END(...) __VA_ARGS__
#define SKIP_LX1_END(...)
#define CONFIG_LX2_START 0x
#define ENABLE_LX2_START 1
#define USE_LX2_START(...) __VA_ARGS__
#define SKIP_LX2_START(...)
#define CONFIG_LX2_END 0x
#define ENABLE_LX2_END 1
#define USE_LX2_END(...) __VA_ARGS__
#define SKIP_LX2_END(...)
#define CONFIG_DISPLAY_OSD 1
#define ENABLE_DISPLAY_OSD 1
#define USE_DISPLAY_OSD(...) __VA_ARGS__
#define SKIP_DISPLAY_OSD(...)
#define CONFIG_BOOTLOGO_OUT_CVBS 1
#define ENABLE_BOOTLOGO_OUT_CVBS 1
#define USE_BOOTLOGO_OUT_CVBS(...) __VA_ARGS__
#define SKIP_BOOTLOGO_OUT_CVBS(...)
#undef CONFIG_BOOTLOGO_OUT_SCART_HD_DAC
#define ENABLE_BOOTLOGO_OUT_SCART_HD_DAC 0
#define USE_BOOTLOGO_OUT_SCART_HD_DAC(...)
#define SKIP_BOOTLOGO_OUT_SCART_HD_DAC(...) __VA_ARGS__
#undef CONFIG_BOOTLOGO_OUT_SCART_SD_DAC
#define ENABLE_BOOTLOGO_OUT_SCART_SD_DAC 0
#define USE_BOOTLOGO_OUT_SCART_SD_DAC(...)
#define SKIP_BOOTLOGO_OUT_SCART_SD_DAC(...) __VA_ARGS__
#define CONFIG_POWER_MUSIC 1
#define ENABLE_POWER_MUSIC 1
#define USE_POWER_MUSIC(...) __VA_ARGS__
#define SKIP_POWER_MUSIC(...)
#undef CONFIG_DIGITAL_TI5711
#define ENABLE_DIGITAL_TI5711 0
#define USE_DIGITAL_TI5711(...)
#define SKIP_DIGITAL_TI5711(...) __VA_ARGS__
#undef CONFIG_DIGITAL_TI5707
#define ENABLE_DIGITAL_TI5707 0
#define USE_DIGITAL_TI5707(...)
#define SKIP_DIGITAL_TI5707(...) __VA_ARGS__
#undef CONFIG_DIGITAL_TI5708
#define ENABLE_DIGITAL_TI5708 0
#define USE_DIGITAL_TI5708(...)
#define SKIP_DIGITAL_TI5708(...) __VA_ARGS__
#undef CONFIG_DIGITAL_STA333
#define ENABLE_DIGITAL_STA333 0
#define USE_DIGITAL_STA333(...)
#define SKIP_DIGITAL_STA333(...) __VA_ARGS__
#define CONFIG_SIM_Amplifier 1
#define ENABLE_SIM_Amplifier 1
#define USE_SIM_Amplifier(...) __VA_ARGS__
#define SKIP_SIM_Amplifier(...)
#undef CONFIG_ACTIVE_STANDBY
#define ENABLE_ACTIVE_STANDBY 0
#define USE_ACTIVE_STANDBY(...)
#define SKIP_ACTIVE_STANDBY(...) __VA_ARGS__
#undef CONFIG_FRONT_END
#define ENABLE_FRONT_END 0
#define USE_FRONT_END(...)
#define SKIP_FRONT_END(...) __VA_ARGS__
#undef CONFIG_MSTAR_TUNER_NUTUNE_FT2125
#define ENABLE_MSTAR_TUNER_NUTUNE_FT2125 0
#define USE_MSTAR_TUNER_NUTUNE_FT2125(...)
#define SKIP_MSTAR_TUNER_NUTUNE_FT2125(...) __VA_ARGS__
#undef CONFIG_MSTAR_TUNER_NUTUNE_FJ2207
#define ENABLE_MSTAR_TUNER_NUTUNE_FJ2207 0
#define USE_MSTAR_TUNER_NUTUNE_FJ2207(...)
#define SKIP_MSTAR_TUNER_NUTUNE_FJ2207(...) __VA_ARGS__
#undef CONFIG_MSTAR_TUNER_NXP_TD1611ALF
#define ENABLE_MSTAR_TUNER_NXP_TD1611ALF 0
#define USE_MSTAR_TUNER_NXP_TD1611ALF(...)
#define SKIP_MSTAR_TUNER_NXP_TD1611ALF(...) __VA_ARGS__
#undef CONFIG_MSTAR_MSB123x_DEMOD
#define ENABLE_MSTAR_MSB123x_DEMOD 0
#define USE_MSTAR_MSB123x_DEMOD(...)
#define SKIP_MSTAR_MSB123x_DEMOD(...) __VA_ARGS__
#undef CONFIG_MSTAR_MSB122x_DEMOD
#define ENABLE_MSTAR_MSB122x_DEMOD 0
#define USE_MSTAR_MSB122x_DEMOD(...)
#define SKIP_MSTAR_MSB122x_DEMOD(...) __VA_ARGS__
#undef CONFIG_DEMUX
#define ENABLE_DEMUX 0
#define USE_DEMUX(...)
#define SKIP_DEMUX(...) __VA_ARGS__
#define CONFIG_NET 1
#define ENABLE_NET 1
#define USE_NET(...) __VA_ARGS__
#define SKIP_NET(...)
#undef CONFIG_NETUPDATE
#define ENABLE_NETUPDATE 0
#define USE_NETUPDATE(...)
#define SKIP_NETUPDATE(...) __VA_ARGS__
#define CONFIG_PHY_SELECTION 1
#define ENABLE_PHY_SELECTION 1
#define USE_PHY_SELECTION(...) __VA_ARGS__
#define SKIP_PHY_SELECTION(...)
#undef CONFIG_ALBANY
#define ENABLE_ALBANY 0
#define USE_ALBANY(...)
#define SKIP_ALBANY(...) __VA_ARGS__
#undef CONFIG_ETHERNET_ALBANY
#define ENABLE_ETHERNET_ALBANY 0
#define USE_ETHERNET_ALBANY(...)
#define SKIP_ETHERNET_ALBANY(...) __VA_ARGS__
#undef CONFIG_OAD
#define ENABLE_OAD 0
#define USE_OAD(...)
#define SKIP_OAD(...) __VA_ARGS__
#undef CONFIG_OBAMA_OAD
#define ENABLE_OBAMA_OAD 0
#define USE_OBAMA_OAD(...)
#define SKIP_OBAMA_OAD(...) __VA_ARGS__
#undef CONFIG_SUPERNOVA_OAD
#define ENABLE_SUPERNOVA_OAD 0
#define USE_SUPERNOVA_OAD(...)
#define SKIP_SUPERNOVA_OAD(...) __VA_ARGS__
#undef CONFIG_OAD_IN_MBOOT
#define ENABLE_OAD_IN_MBOOT 0
#define USE_OAD_IN_MBOOT(...)
#define SKIP_OAD_IN_MBOOT(...) __VA_ARGS__
#undef CONFIG_MTD_NAND_BBT
#define ENABLE_MTD_NAND_BBT 0
#define USE_MTD_NAND_BBT(...)
#define SKIP_MTD_NAND_BBT(...) __VA_ARGS__
#undef CONFIG_MSTARI2C
#define ENABLE_MSTARI2C 0
#define USE_MSTARI2C(...)
#define SKIP_MSTARI2C(...) __VA_ARGS__
#undef CONFIG_EEPROM
#define ENABLE_EEPROM 0
#define USE_EEPROM(...)
#define SKIP_EEPROM(...) __VA_ARGS__
#undef CONFIG_STANDBY
#define ENABLE_STANDBY 0
#define USE_STANDBY(...)
#define SKIP_STANDBY(...) __VA_ARGS__
#undef CONFIG_MICOM
#define ENABLE_MICOM 0
#define USE_MICOM(...)
#define SKIP_MICOM(...) __VA_ARGS__
#define CONFIG_WDT 1
#define ENABLE_WDT 1
#define USE_WDT(...) __VA_ARGS__
#define SKIP_WDT(...)
#define CONFIG_KERNEL_PROTECT 1
#define ENABLE_KERNEL_PROTECT 1
#define USE_KERNEL_PROTECT(...) __VA_ARGS__
#define SKIP_KERNEL_PROTECT(...)
#undef CONFIG_BACKUP_PARTITION
#define ENABLE_BACKUP_PARTITION 0
#define USE_BACKUP_PARTITION(...)
#define SKIP_BACKUP_PARTITION(...) __VA_ARGS__
#define CONFIG_LED_FLICKER_WHEN_SW_UPDATE 1
#define ENABLE_LED_FLICKER_WHEN_SW_UPDATE 1
#define USE_LED_FLICKER_WHEN_SW_UPDATE(...) __VA_ARGS__
#define SKIP_LED_FLICKER_WHEN_SW_UPDATE(...)
#undef CONFIG_SET_4K2K_MODE
#define ENABLE_SET_4K2K_MODE 0
#define USE_SET_4K2K_MODE(...)
#define SKIP_SET_4K2K_MODE(...) __VA_ARGS__
#undef CONFIG_ENABLE_4K2K_OP_DEFAULT
#define ENABLE_ENABLE_4K2K_OP_DEFAULT 0
#define USE_ENABLE_4K2K_OP_DEFAULT(...)
#define SKIP_ENABLE_4K2K_OP_DEFAULT(...) __VA_ARGS__
#define CONFIG_LOAD_ENV_FROM_SN 1
#define ENABLE_LOAD_ENV_FROM_SN 1
#define USE_LOAD_ENV_FROM_SN(...) __VA_ARGS__
#define SKIP_LOAD_ENV_FROM_SN(...)
#define CONFIG_MSTAR_STR_ENABLE 1
#define ENABLE_MSTAR_STR_ENABLE 1
#define USE_MSTAR_STR_ENABLE(...) __VA_ARGS__
#define SKIP_MSTAR_STR_ENABLE(...)
#define CONFIG_MSTAR_STR_CRC 1
#define ENABLE_MSTAR_STR_CRC 1
#define USE_MSTAR_STR_CRC(...) __VA_ARGS__
#define SKIP_MSTAR_STR_CRC(...)
#define CONFIG_MSTAR_PM_SWIR 1
#define ENABLE_MSTAR_PM_SWIR 1
#define USE_MSTAR_PM_SWIR(...) __VA_ARGS__
#define SKIP_MSTAR_PM_SWIR(...)
#undef CONFIG_MSTAR_EDINBURGH
#define ENABLE_MSTAR_EDINBURGH 0
#define USE_MSTAR_EDINBURGH(...)
#define SKIP_MSTAR_EDINBURGH(...) __VA_ARGS__
#undef CONFIG_R2_BRINGUP
#define ENABLE_R2_BRINGUP 0
#define USE_R2_BRINGUP(...)
#define SKIP_R2_BRINGUP(...) __VA_ARGS__
#define CONFIG_PM_DRAM_ADDRESS 0x
#define ENABLE_PM_DRAM_ADDRESS 1
#define USE_PM_DRAM_ADDRESS(...) __VA_ARGS__
#define SKIP_PM_DRAM_ADDRESS(...)
#define CONFIG_CUSTOMER_KEY_BANK_DRAM_ADDRESS 0x
#define ENABLE_CUSTOMER_KEY_BANK_DRAM_ADDRESS 1
#define USE_CUSTOMER_KEY_BANK_DRAM_ADDRESS(...) __VA_ARGS__
#define SKIP_CUSTOMER_KEY_BANK_DRAM_ADDRESS(...)
#define CONFIG_SECURE_INFO_DRAM_ADDRESS 0x
#define ENABLE_SECURE_INFO_DRAM_ADDRESS 1
#define USE_SECURE_INFO_DRAM_ADDRESS(...) __VA_ARGS__
#define SKIP_SECURE_INFO_DRAM_ADDRESS(...)
#undef CONFIG_LOGO_STORE_NOT_SET
#define ENABLE_LOGO_STORE_NOT_SET 0
#define USE_LOGO_STORE_NOT_SET(...)
#define SKIP_LOGO_STORE_NOT_SET(...) __VA_ARGS__
#undef CONFIG_LOGO_STORE_IN_MBOOT
#define ENABLE_LOGO_STORE_IN_MBOOT 0
#define USE_LOGO_STORE_IN_MBOOT(...)
#define SKIP_LOGO_STORE_IN_MBOOT(...) __VA_ARGS__
#define CONFIG_LOGO_STORE_IN_SPI_FLASH 1
#define ENABLE_LOGO_STORE_IN_SPI_FLASH 1
#define USE_LOGO_STORE_IN_SPI_FLASH(...) __VA_ARGS__
#define SKIP_LOGO_STORE_IN_SPI_FLASH(...)
#undef CONFIG_LOGO_STORE_IN_NAND_FLASH
#define ENABLE_LOGO_STORE_IN_NAND_FLASH 0
#define USE_LOGO_STORE_IN_NAND_FLASH(...)
#define SKIP_LOGO_STORE_IN_NAND_FLASH(...) __VA_ARGS__
#undef CONFIG_LOGO_STORE_IN_EMMC_FLASH
#define ENABLE_LOGO_STORE_IN_EMMC_FLASH 0
#define USE_LOGO_STORE_IN_EMMC_FLASH(...)
#define SKIP_LOGO_STORE_IN_EMMC_FLASH(...) __VA_ARGS__

/*
 * Env config
 */
#define CONFIG_ENV_IN_SERIAL 1
#define ENABLE_ENV_IN_SERIAL 1
#define USE_ENV_IN_SERIAL(...) __VA_ARGS__
#define SKIP_ENV_IN_SERIAL(...)
#undef CONFIG_ENV_IN_MMC
#define ENABLE_ENV_IN_MMC 0
#define USE_ENV_IN_MMC(...)
#define SKIP_ENV_IN_MMC(...) __VA_ARGS__
#undef CONFIG_ENV_IN_NAND
#define ENABLE_ENV_IN_NAND 0
#define USE_ENV_IN_NAND(...)
#define SKIP_ENV_IN_NAND(...) __VA_ARGS__
#undef CONFIG_ENV_IN_SERIAL_512K
#define ENABLE_ENV_IN_SERIAL_512K 0
#define USE_ENV_IN_SERIAL_512K(...)
#define SKIP_ENV_IN_SERIAL_512K(...) __VA_ARGS__
#undef CONFIG_ENV_IN_ERR
#define ENABLE_ENV_IN_ERR 0
#define USE_ENV_IN_ERR(...)
#define SKIP_ENV_IN_ERR(...) __VA_ARGS__
#define CONFIG_ENV_VAR_SIZE 0x10000
#define ENABLE_ENV_VAR_SIZE 1
#define USE_ENV_VAR_SIZE(...) __VA_ARGS__
#define SKIP_ENV_VAR_SIZE(...)
#undef CONFIG_FORCE_TO_ASSIGN_ENV_OFFSET
#define ENABLE_FORCE_TO_ASSIGN_ENV_OFFSET 0
#define USE_FORCE_TO_ASSIGN_ENV_OFFSET(...)
#define SKIP_FORCE_TO_ASSIGN_ENV_OFFSET(...) __VA_ARGS__
#define CONFIG_ENV_VAR_OFFSET 0x
#define ENABLE_ENV_VAR_OFFSET 1
#define USE_ENV_VAR_OFFSET(...) __VA_ARGS__
#define SKIP_ENV_VAR_OFFSET(...)
#undef CONFIG_INFO_IN_UBI_FILE
#define ENABLE_INFO_IN_UBI_FILE 0
#define USE_INFO_IN_UBI_FILE(...)
#define SKIP_INFO_IN_UBI_FILE(...) __VA_ARGS__
#define CONFIG_INFO_IN_SERIAL_ENV 1
#define ENABLE_INFO_IN_SERIAL_ENV 1
#define USE_INFO_IN_SERIAL_ENV(...) __VA_ARGS__
#define SKIP_INFO_IN_SERIAL_ENV(...)
#undef CONFIG_INFO_IN_MMC_ENV
#define ENABLE_INFO_IN_MMC_ENV 0
#define USE_INFO_IN_MMC_ENV(...)
#define SKIP_INFO_IN_MMC_ENV(...) __VA_ARGS__
#undef CONFIG_INFO_IN_ERR
#define ENABLE_INFO_IN_ERR 0
#define USE_INFO_IN_ERR(...)
#define SKIP_INFO_IN_ERR(...) __VA_ARGS__
