#
# Makefile for MStar NAND device drivers.
#

# general options
#EXTRA_CFLAGS      +=  -Idrivers/mstar/common
EXTRA_CFLAGS      +=  -Idrivers/mstar/include
EXTRA_CFLAGS      +=  -Idrivers/mstar/nand

# specific options
EXTRA_CFLAGS      +=  -DRED_LION

# files
obj-y             += drvNAND.o
