/* skyworth-tv.h - Keytable for skyworth_tv Remote Controller
 *
 * keymap imported from ir-keymaps.c
 *
 * Copyright (c) 2010 by Mauro Carvalho Chehab <mchehab@redhat.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 */


#include <media/rc-core.h>

/*
 * Jimmy Hsu <jimmy.hsu@mstarsemi.com>
 * this is the remote control that comes with the skyworth smart tv
 * which based on STAOS standard.
 */

static struct rc_map_table skyworth_tv[] = {
    // 1st IR controller.
    { 0x000C, KEY_POWER }, //KEYCODE_TV_POWER
    { 0x0001, KEY_1 }, //KEYCODE_1
    { 0x0002, KEY_2 }, //KEYCODE_2
    { 0x0003, KEY_3 }, //KEYCODE_3
    { 0x0004, KEY_4 }, //KEYCODE_4
    { 0x0005, KEY_5 }, //KEYCODE_5
    { 0x0006, KEY_6 }, //KEYCODE_6
    { 0x0007, KEY_7 }, //KEYCODE_7
    { 0x0008, KEY_8 }, //KEYCODE_8
    { 0x0009, KEY_9 }, //KEYCODE_9
    { 0x0000, KEY_0 }, //KEYCODE_0
    { 0x001D, KEY_FN }, //KEYCODE_3D_MODE
    { 0x000B, KEY_FN_ESC }, //KEYCODE_ALTERNATE
    { 0x0012, KEY_CHANNELUP }, //KEYCODE_CHANNEL_UP
    { 0x0013, KEY_CHANNELDOWN }, //KEYCODE_CHANNEL_DOWN
    { 0x0014, KEY_VOLUMEUP }, //KEYCODE_VOLUME_UP
    { 0x0015, KEY_VOLUMEDOWN }, //KEYCODE_VOLUME_DOWN
    { 0x000D, KEY_MUTE }, //KEYCODE_VOLUME_MUTE
    { 0x000F, KEY_FN_F1 }, //KEYCODE_TV_INPUT
    { 0x0046, KEY_ENTER }, //KEYCODE_DPAD_CENTER
    { 0x009B, KEY_FN_F2 }, //KEYCODE_VOICE
    { 0x0042, KEY_UP }, //KEYCODE_DPAD_UP
    { 0x0043, KEY_DOWN }, //KEYCODE_DPAD_DOWN
    { 0x0044, KEY_LEFT }, //KEYCODE_DPAD_LEFT
    { 0x0045, KEY_RIGHT }, //KEYCODE_DPAD_RIGHT
    { 0x005B, KEY_BACK }, //KEYCODE_BACK
    { 0x0011, KEY_MENU }, //KEYCODE_MENU
    { 0x0078, KEY_HOME }, //KEYCODE_HOME
    { 0x0079, KEY_FN_F3 }, //KEYCODE_SHARE
    { 0x0060, KEY_EPG }, //KEYCODE_ENTER_EPG
    { 0x0062, KEY_RED }, //KEYCODE_PROG_RED
    { 0x0063, KEY_GREEN }, //KEYCODE_PROG_GREEN
    { 0x0064, KEY_YELLOW }, //KEYCODE_PROG_YELLOW
    { 0x0065, KEY_BLUE }, //KEYCODE_PROG_BLUE
    { 0x0017, KEY_FN_F4 }, //KEYCODE_IMAGE_MODE
    { 0x0018, KEY_FN_F5 }, //KEYCODE_SOUND_MODE
    { 0x004F, KEY_FN_F6 }, //KEYCODE_DISPLAY_MODE
    { 0x0016, KEY_FN_F7 }, //KEYCODE_INFO
    { 0x0047, KEY_PREVIOUSSONG }, //KEYCODE_MEDIA_PREVIOUS
    { 0x0048, KEY_NEXTSONG }, //KEYCODE_MEDIA_NEXT
    { 0x0040, KEY_REWIND }, //KEYCODE_MEDIA_REWIND
    { 0x0041, KEY_FASTFORWARD }, //KEYCODE_MEDIA_FAST_FORWARD
    { 0x0049, KEY_PLAYPAUSE }, //KEYCODE_MEDIA_PLAY_PAUSE
    { 0x004A, KEY_STOPCD }, //KEYCODE_MEDIA_STOP
    { 0x0056, KEY_FN_F8 }, //KEYCODE_MEDIA_SONG_SYSTEM
    { 0x005D, KEY_FN_F9 }, //KEYCODE_MEDIA_RELATIONSHIP
    { 0x0055, KEY_FN_F10 }, //KEYCODE_MEDIA_BOOKING
    { 0x005C, KEY_FAVORITES }, //KEYCODE_MEDIA_FAVORITES
    { 0x0057, KEY_FN_F11 }, //KEYCODE_MEDIA_AUDIO_CONTROL
    { 0x0058, KEY_FN_F12 }, //KEYCODE_MEDIA_FUNCTION
    { 0x0054, KEY_FN_1 }, //KEYCODE_MEDIA_ORIGINAL_SOUNDTRACK
    { 0x004B, KEY_RECORD }, //KEYCODE_MEDIA_RECORD
    { 0x005A, KEY_FN_2 }, //KEYCODE_MEDIA_SELECTED_SONGS
    { 0x005E, KEY_FN_D }, //KEYCODE_MEDIA_PRIORITY
    { 0x005F, KEY_FN_E }, //KEYCODE_MEDIA_DELETE
    { 0x0059, KEY_FN_F }, //KEYCODE_MEDIA_SCORE_DISPLAY
    { 0x000A, KEY_FN_S }, //KEYCODE_NUM
    { 0x003F, KEY_NUMERIC_0 }, //KEYCODE_FACTORY_FACTORY_MODE
    { 0x003E, KEY_NUMERIC_1 }, //KEYCODE_FACTORY_RESET
    { 0x003D, KEY_NUMERIC_2 }, //KEYCODE_FACTORY_SOURCE_ADD
    { 0x003C, KEY_NUMERIC_3 }, //KEYCODE_FACTORY_SOURCE_REDUCE
    { 0x003B, KEY_NUMERIC_4 }, //KEYCODE_FACTORY_OUTSET
    { 0x003A, KEY_NUMERIC_5 }, //KEYCODE_FACTORY_BUS_OFF
    { 0x0039, KEY_NUMERIC_6 }, //KEYCODE_FACTORY_AGING_MODE
    { 0x0038, KEY_NUMERIC_7 }, //KEYCODE_FACTORY_AUTO_ADC
    { 0x0037, KEY_NUMERIC_8 }, //KEYCODE_FACTORY_AV1
    { 0x0036, KEY_NUMERIC_9 }, //KEYCODE_FACTORY_RF_AGC
    { 0x0035, KEY_NUMERIC_STAR }, //KEYCODE_FACTORY_AV2
    { 0x0034, KEY_NUMERIC_POUND }, //KEYCODE_FACTORY_AV3
    { 0x0033, BTN_TRIGGER_HAPPY }, //KEYCODE_FACTORY_S1
    { 0x0032, BTN_TRIGGER_HAPPY2 }, //KEYCODE_FACTORY_YUV1
    { 0x0031, BTN_TRIGGER_HAPPY3 }, //KEYCODE_FACTORY_YUV2
    { 0x0030, BTN_TRIGGER_HAPPY4 }, //KEYCODE_FACTORY_VGA
    { 0x002F, BTN_TRIGGER_HAPPY5 }, //KEYCODE_FACTORY_HDMI1
    { 0x002E, BTN_TRIGGER_HAPPY6 }, //KEYCODE_FACTORY_HDMI2
    { 0x002D, BTN_TRIGGER_HAPPY7 }, //KEYCODE_FACTORY_HDMI3
    { 0x002C, BTN_TRIGGER_HAPPY8 }, //KEYCODE_FACTORY_KALA_OK
    { 0x002B, BTN_TRIGGER_HAPPY9 }, //KEYCODE_FACTORY_UPLAYER
    { 0x002A, BTN_TRIGGER_HAPPY10 }, //KEYCODE_FACTORY_LAN
    { 0x0029, BTN_TRIGGER_HAPPY11 }, //KEYCODE_FACTORY_DREAM_PANEL
    { 0x0028, BTN_TRIGGER_HAPPY12 }, //KEYCODE_FACTORY_WHITE_BALANCE
    { 0x0024, BTN_TRIGGER_HAPPY13 }, //KEYCODE_FACTORY_ALONE_LISTEN
    { 0x0023, BTN_TRIGGER_HAPPY14 }, //KEYCODE_FACTORY_CA_CARD
    { 0x0022, BTN_TRIGGER_HAPPY15 }, //KEYCODE_FACTORY_BARCODE
    { 0x0021, BTN_TRIGGER_HAPPY16 }, //KEYCODE_FACTORY_SEARCH_UP
    { 0x0020, BTN_TRIGGER_HAPPY17 }, //KEYCODE_FACTORY_SEARCH_DOWN
    { 0x00C1, BTN_TRIGGER_HAPPY21 }, //KEYCODE_SHUTTLE_LEFT_SPEED_1
    { 0x00C2, BTN_TRIGGER_HAPPY22 }, //KEYCODE_SHUTTLE_LEFT_SPEED_2
    { 0x00C3, BTN_TRIGGER_HAPPY23 }, //KEYCODE_SHUTTLE_LEFT_SPEED_3
    { 0x00C4, BTN_TRIGGER_HAPPY24 }, //KEYCODE_SHUTTLE_LEFT_SPEED_4
    { 0x00C5, BTN_TRIGGER_HAPPY25 }, //KEYCODE_SHUTTLE_LEFT_SPEED_5
    { 0x00C6, BTN_TRIGGER_HAPPY26 }, //KEYCODE_SHUTTLE_LEFT_SPEED_6
    { 0x00F1, BTN_TRIGGER_HAPPY27 }, //KEYCODE_SHUTTLE_RIGHT_SPEED_1
    { 0x00F2, BTN_TRIGGER_HAPPY28 }, //KEYCODE_SHUTTLE_RIGHT_SPEED_2
    { 0x00F3, BTN_TRIGGER_HAPPY29 }, //KEYCODE_SHUTTLE_RIGHT_SPEED_3
    { 0x00F4, BTN_TRIGGER_HAPPY30 }, //KEYCODE_SHUTTLE_RIGHT_SPEED_4
    { 0x00F5, BTN_TRIGGER_HAPPY31 }, //KEYCODE_SHUTTLE_RIGHT_SPEED_5
    { 0x00F6, BTN_TRIGGER_HAPPY32 }, //KEYCODE_SHUTTLE_RIGHT_SPEED_6


    // 2nd IR controller.
};

static struct rc_map_list skyworth_tv_map = {
	.map = {
		.scan    = skyworth_tv,
		.size    = ARRAY_SIZE(skyworth_tv),
		.rc_type = RC_TYPE_UNKNOWN,	/* Legacy IR type */
		.name    = RC_MAP_SKYWORTH_TV,
	}
};

static int __init init_rc_map_skyworth_tv(void)
{
	return rc_map_register(&skyworth_tv_map);
}

static void __exit exit_rc_map_skyworth_tv(void)
{
	rc_map_unregister(&skyworth_tv_map);
}

module_init(init_rc_map_skyworth_tv)
module_exit(exit_rc_map_skyworth_tv)

MODULE_LICENSE("GPL");
MODULE_AUTHOR("Mauro Carvalho Chehab <mchehab@redhat.com>");
