////////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 2006-2009 MStar Semiconductor, Inc.
// All rights reserved.
//
// Unless otherwise stipulated in writing, any and all information contained
// herein regardless in any format shall remain the sole proprietary of
// MStar Semiconductor Inc. and be kept in strict confidence
// ("MStar Confidential Information") by the recipient.
// Any unauthorized act including without limitation unauthorized disclosure,
// copying, use, reproduction, sale, distribution, modification, disassembling,
// reverse engineering and compiling of the contents of MStar Confidential
// Information is unlawful and strictly prohibited. MStar hereby reserves the
// rights to any and all damages, losses, costs and expenses resulting therefrom.
//
////////////////////////////////////////////////////////////////////////////////

// This file is generated by script, please do not edit it directly 
#ifndef _MSD393SSXT_H_
#define _MSD393SSXT_H_

#define PAD_NC 9999
#define PAD_GND 0

#define PAD_GPIO_PM19 9999
#ifndef PAD_GPIO_PM19_IS_GPIO
#define PAD_GPIO_PM19_IS_GPIO 0
#endif 

#define PAD_GPIO_PM18 9999
#ifndef PAD_GPIO_PM18_IS_GPIO
#define PAD_GPIO_PM18_IS_GPIO 0
#endif 

#define PAD_GPIO_PM17 9999
#ifndef PAD_GPIO_PM17_IS_GPIO
#define PAD_GPIO_PM17_IS_GPIO 0
#endif 

#define PAD_GPIO_PM16 9999
#ifndef PAD_GPIO_PM16_IS_GPIO
#define PAD_GPIO_PM16_IS_GPIO 0
#endif 

#define PAD_GPIO_PM15 9999
#ifndef PAD_GPIO_PM15_IS_GPIO
#define PAD_GPIO_PM15_IS_GPIO 0
#endif 

#define PAD_GPIO_PM14 9999
#ifndef PAD_GPIO_PM14_IS_GPIO
#define PAD_GPIO_PM14_IS_GPIO 0
#endif 

#define PAD_GPIO_PM13 9999
#ifndef PAD_GPIO_PM13_IS_GPIO
#define PAD_GPIO_PM13_IS_GPIO 0
#endif 

#define PAD_GPIO_PM10 9999
#ifndef PAD_GPIO_PM10_IS_GPIO
#define PAD_GPIO_PM10_IS_GPIO 0
#endif 

#define PAD_GPIO_PM9 9999
#ifndef PAD_GPIO_PM9_IS_GPIO
#define PAD_GPIO_PM9_IS_GPIO 0
#endif 

#define BALL_C5 PAD_GPIO_PM8
#define PAD_GPIO_PM8 9
#define GPIO_PAD_9 GPIO8
#ifndef BALL_C5_IS_GPIO
#define BALL_C5_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM8_IS_GPIO
#define PAD_GPIO_PM8_IS_GPIO BALL_C5_IS_GPIO
#endif 

#define BALL_H5 PAD_IRIN
#define PAD_IRIN 21
#define GPIO_PAD_21 GPIO20
#ifndef BALL_H5_IS_GPIO
#define BALL_H5_IS_GPIO 0
#endif 
#ifndef PAD_IRIN_IS_GPIO
#define PAD_IRIN_IS_GPIO BALL_H5_IS_GPIO
#endif 

#define PAD_GPIO_PM7 9999
#ifndef PAD_GPIO_PM7_IS_GPIO
#define PAD_GPIO_PM7_IS_GPIO 0
#endif 

#define BALL_D5 PAD_GPIO_PM6
#define PAD_GPIO_PM6 7
#define GPIO_PAD_7 GPIO6
#ifndef BALL_D5_IS_GPIO
#define BALL_D5_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM6_IS_GPIO
#define PAD_GPIO_PM6_IS_GPIO BALL_D5_IS_GPIO
#endif 

#define PAD_GPIO_PM3 9999
#ifndef PAD_GPIO_PM3_IS_GPIO
#define PAD_GPIO_PM3_IS_GPIO 0
#endif 

#define BALL_Y9 PAD_GPIO_PM5
#define PAD_GPIO_PM5 6
#define GPIO_PAD_6 GPIO5
#ifndef BALL_Y9_IS_GPIO
#define BALL_Y9_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM5_IS_GPIO
#define PAD_GPIO_PM5_IS_GPIO BALL_Y9_IS_GPIO
#endif 

#define BALL_F5 PAD_GPIO_PM12
#define PAD_GPIO_PM12 13
#define GPIO_PAD_13 GPIO12
#ifndef BALL_F5_IS_GPIO
#define BALL_F5_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM12_IS_GPIO
#define PAD_GPIO_PM12_IS_GPIO BALL_F5_IS_GPIO
#endif 

#define BALL_D8 PAD_GPIO_PM4
#define PAD_GPIO_PM4 5
#define GPIO_PAD_5 GPIO4
#ifndef BALL_D8_IS_GPIO
#define BALL_D8_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM4_IS_GPIO
#define PAD_GPIO_PM4_IS_GPIO BALL_D8_IS_GPIO
#endif 

#define PAD_GPIO_PM2 9999
#ifndef PAD_GPIO_PM2_IS_GPIO
#define PAD_GPIO_PM2_IS_GPIO 0
#endif 

#define BALL_W9 PAD_GPIO_PM1
#define PAD_GPIO_PM1 2
#define GPIO_PAD_2 GPIO1
#ifndef BALL_W9_IS_GPIO
#define BALL_W9_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM1_IS_GPIO
#define PAD_GPIO_PM1_IS_GPIO BALL_W9_IS_GPIO
#endif 

#define PAD_GPIO_PM11 9999
#ifndef PAD_GPIO_PM11_IS_GPIO
#define PAD_GPIO_PM11_IS_GPIO 0
#endif 

#define BALL_E4 PAD_GPIO_PM0
#define PAD_GPIO_PM0 1
#define GPIO_PAD_1 GPIO0
#ifndef BALL_E4_IS_GPIO
#define BALL_E4_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM0_IS_GPIO
#define PAD_GPIO_PM0_IS_GPIO BALL_E4_IS_GPIO
#endif 

#define BALL_A5 PAD_SAR4
#define PAD_SAR4 38
#define GPIO_PAD_38 GPIO37
#ifndef BALL_A5_IS_GPIO
#define BALL_A5_IS_GPIO 0
#endif 
#ifndef PAD_SAR4_IS_GPIO
#define PAD_SAR4_IS_GPIO BALL_A5_IS_GPIO
#endif 

#define BALL_H6 PAD_SAR3
#define PAD_SAR3 37
#define GPIO_PAD_37 GPIO36
#ifndef BALL_H6_IS_GPIO
#define BALL_H6_IS_GPIO 0
#endif 
#ifndef PAD_SAR3_IS_GPIO
#define PAD_SAR3_IS_GPIO BALL_H6_IS_GPIO
#endif 

#define BALL_F4 PAD_SAR2
#define PAD_SAR2 36
#define GPIO_PAD_36 GPIO35
#ifndef BALL_F4_IS_GPIO
#define BALL_F4_IS_GPIO 0
#endif 
#ifndef PAD_SAR2_IS_GPIO
#define PAD_SAR2_IS_GPIO BALL_F4_IS_GPIO
#endif 

#define BALL_G4 PAD_SAR1
#define PAD_SAR1 35
#define GPIO_PAD_35 GPIO34
#ifndef BALL_G4_IS_GPIO
#define BALL_G4_IS_GPIO 0
#endif 
#ifndef PAD_SAR1_IS_GPIO
#define PAD_SAR1_IS_GPIO BALL_G4_IS_GPIO
#endif 

#define BALL_G5 PAD_SAR0
#define PAD_SAR0 34
#define GPIO_PAD_34 GPIO33
#ifndef BALL_G5_IS_GPIO
#define BALL_G5_IS_GPIO 0
#endif 
#ifndef PAD_SAR0_IS_GPIO
#define PAD_SAR0_IS_GPIO BALL_G5_IS_GPIO
#endif 

#define BALL_C7 PAD_PM_SPI_CZ
#define PAD_PM_SPI_CZ 23
#define GPIO_PAD_23 GPIO22
#ifndef BALL_C7_IS_GPIO
#define BALL_C7_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_CZ_IS_GPIO
#define PAD_PM_SPI_CZ_IS_GPIO BALL_C7_IS_GPIO
#endif 

#define BALL_B6 PAD_PM_SPI_DO
#define PAD_PM_SPI_DO 26
#define GPIO_PAD_26 GPIO25
#ifndef BALL_B6_IS_GPIO
#define BALL_B6_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_DO_IS_GPIO
#define PAD_PM_SPI_DO_IS_GPIO BALL_B6_IS_GPIO
#endif 

#define BALL_B5 PAD_PM_SPI_DI
#define PAD_PM_SPI_DI 25
#define GPIO_PAD_25 GPIO24
#ifndef BALL_B5_IS_GPIO
#define BALL_B5_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_DI_IS_GPIO
#define PAD_PM_SPI_DI_IS_GPIO BALL_B5_IS_GPIO
#endif 

#define BALL_C6 PAD_PM_SPI_CK
#define PAD_PM_SPI_CK 24
#define GPIO_PAD_24 GPIO23
#ifndef BALL_C6_IS_GPIO
#define BALL_C6_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_CK_IS_GPIO
#define PAD_PM_SPI_CK_IS_GPIO BALL_C6_IS_GPIO
#endif 

#define BALL_AC1 PAD_TGPIO0
#define PAD_TGPIO0 180
#define GPIO_PAD_180 GPIO179
#ifndef BALL_AC1_IS_GPIO
#define BALL_AC1_IS_GPIO 0
#endif 
#ifndef PAD_TGPIO0_IS_GPIO
#define PAD_TGPIO0_IS_GPIO BALL_AC1_IS_GPIO
#endif 

#define BALL_AD4 PAD_TGPIO1
#define PAD_TGPIO1 181
#define GPIO_PAD_181 GPIO180
#ifndef BALL_AD4_IS_GPIO
#define BALL_AD4_IS_GPIO 0
#endif 
#ifndef PAD_TGPIO1_IS_GPIO
#define PAD_TGPIO1_IS_GPIO BALL_AD4_IS_GPIO
#endif 

#define BALL_AE4 PAD_TGPIO2
#define PAD_TGPIO2 182
#define GPIO_PAD_182 GPIO181
#ifndef BALL_AE4_IS_GPIO
#define BALL_AE4_IS_GPIO 0
#endif 
#ifndef PAD_TGPIO2_IS_GPIO
#define PAD_TGPIO2_IS_GPIO BALL_AE4_IS_GPIO
#endif 

#define PAD_TGPIO3 9999
#ifndef PAD_TGPIO3_IS_GPIO
#define PAD_TGPIO3_IS_GPIO 0
#endif 

#define BALL_L5 PAD_DDCDA_CK
#define PAD_DDCDA_CK 206
#define GPIO_PAD_206 GPIO205
#ifndef BALL_L5_IS_GPIO
#define BALL_L5_IS_GPIO 0
#endif 
#ifndef PAD_DDCDA_CK_IS_GPIO
#define PAD_DDCDA_CK_IS_GPIO BALL_L5_IS_GPIO
#endif 

#define BALL_M6 PAD_DDCDA_DA
#define PAD_DDCDA_DA 207
#define GPIO_PAD_207 GPIO206
#ifndef BALL_M6_IS_GPIO
#define BALL_M6_IS_GPIO 0
#endif 
#ifndef PAD_DDCDA_DA_IS_GPIO
#define PAD_DDCDA_DA_IS_GPIO BALL_M6_IS_GPIO
#endif 

#define BALL_K4 PAD_DDCDB_CK
#define PAD_DDCDB_CK 208
#define GPIO_PAD_208 GPIO207
#ifndef BALL_K4_IS_GPIO
#define BALL_K4_IS_GPIO 0
#endif 
#ifndef PAD_DDCDB_CK_IS_GPIO
#define PAD_DDCDB_CK_IS_GPIO BALL_K4_IS_GPIO
#endif 

#define BALL_K5 PAD_DDCDB_DA
#define PAD_DDCDB_DA 209
#define GPIO_PAD_209 GPIO208
#ifndef BALL_K5_IS_GPIO
#define BALL_K5_IS_GPIO 0
#endif 
#ifndef PAD_DDCDB_DA_IS_GPIO
#define PAD_DDCDB_DA_IS_GPIO BALL_K5_IS_GPIO
#endif 

#define BALL_L6 PAD_HOTPLUGB
#define PAD_HOTPLUGB 28
#define GPIO_PAD_28 GPIO27
#ifndef BALL_L6_IS_GPIO
#define BALL_L6_IS_GPIO 0
#endif 
#ifndef PAD_HOTPLUGB_IS_GPIO
#define PAD_HOTPLUGB_IS_GPIO BALL_L6_IS_GPIO
#endif 

#define BALL_AD6 PAD_DDCDC_DA
#define PAD_DDCDC_DA 31
#define GPIO_PAD_31 GPIO30
#ifndef BALL_AD6_IS_GPIO
#define BALL_AD6_IS_GPIO 0
#endif 
#ifndef PAD_DDCDC_DA_IS_GPIO
#define PAD_DDCDC_DA_IS_GPIO BALL_AD6_IS_GPIO
#endif 

#define BALL_AC6 PAD_DDCDC_CK
#define PAD_DDCDC_CK 30
#define GPIO_PAD_30 GPIO29
#ifndef BALL_AC6_IS_GPIO
#define BALL_AC6_IS_GPIO 0
#endif 
#ifndef PAD_DDCDC_CK_IS_GPIO
#define PAD_DDCDC_CK_IS_GPIO BALL_AC6_IS_GPIO
#endif 

#define BALL_AD5 PAD_HOTPLUGC
#define PAD_HOTPLUGC 210
#define GPIO_PAD_210 GPIO209
#ifndef BALL_AD5_IS_GPIO
#define BALL_AD5_IS_GPIO 0
#endif 
#ifndef PAD_HOTPLUGC_IS_GPIO
#define PAD_HOTPLUGC_IS_GPIO BALL_AD5_IS_GPIO
#endif 

#define BALL_J4 PAD_DDCDD_DA
#define PAD_DDCDD_DA 33
#define GPIO_PAD_33 GPIO32
#ifndef BALL_J4_IS_GPIO
#define BALL_J4_IS_GPIO 0
#endif 
#ifndef PAD_DDCDD_DA_IS_GPIO
#define PAD_DDCDD_DA_IS_GPIO BALL_J4_IS_GPIO
#endif 

#define BALL_J5 PAD_DDCDD_CK
#define PAD_DDCDD_CK 32
#define GPIO_PAD_32 GPIO31
#ifndef BALL_J5_IS_GPIO
#define BALL_J5_IS_GPIO 0
#endif 
#ifndef PAD_DDCDD_CK_IS_GPIO
#define PAD_DDCDD_CK_IS_GPIO BALL_J5_IS_GPIO
#endif 

#define BALL_K6 PAD_HOTPLUGD
#define PAD_HOTPLUGD 29
#define GPIO_PAD_29 GPIO28
#ifndef BALL_K6_IS_GPIO
#define BALL_K6_IS_GPIO 0
#endif 
#ifndef PAD_HOTPLUGD_IS_GPIO
#define PAD_HOTPLUGD_IS_GPIO BALL_K6_IS_GPIO
#endif 

#define BALL_M5 PAD_HOTPLUGA
#define PAD_HOTPLUGA 27
#define GPIO_PAD_27 GPIO26
#ifndef BALL_M5_IS_GPIO
#define BALL_M5_IS_GPIO 0
#endif 
#ifndef PAD_HOTPLUGA_IS_GPIO
#define PAD_HOTPLUGA_IS_GPIO BALL_M5_IS_GPIO
#endif 

#define BALL_J6 PAD_CEC
#define PAD_CEC 22
#define GPIO_PAD_22 GPIO21
#ifndef BALL_J6_IS_GPIO
#define BALL_J6_IS_GPIO 0
#endif 
#ifndef PAD_CEC_IS_GPIO
#define PAD_CEC_IS_GPIO BALL_J6_IS_GPIO
#endif 

#define PAD_TS2_D0 9999
#ifndef PAD_TS2_D0_IS_GPIO
#define PAD_TS2_D0_IS_GPIO 0
#endif 

#define PAD_TS2_VLD 9999
#ifndef PAD_TS2_VLD_IS_GPIO
#define PAD_TS2_VLD_IS_GPIO 0
#endif 

#define PAD_TS2_CLK 9999
#ifndef PAD_TS2_CLK_IS_GPIO
#define PAD_TS2_CLK_IS_GPIO 0
#endif 

#define PAD_TS2_SYNC 9999
#ifndef PAD_TS2_SYNC_IS_GPIO
#define PAD_TS2_SYNC_IS_GPIO 0
#endif 

#define BALL_P19 PAD_TS0_D0
#define PAD_TS0_D0 67
#define GPIO_PAD_67 GPIO66
#ifndef BALL_P19_IS_GPIO
#define BALL_P19_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D0_IS_GPIO
#define PAD_TS0_D0_IS_GPIO BALL_P19_IS_GPIO
#endif 

#define BALL_P21 PAD_TS0_D1
#define PAD_TS0_D1 68
#define GPIO_PAD_68 GPIO67
#ifndef BALL_P21_IS_GPIO
#define BALL_P21_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D1_IS_GPIO
#define PAD_TS0_D1_IS_GPIO BALL_P21_IS_GPIO
#endif 

#define BALL_P22 PAD_TS0_D2
#define PAD_TS0_D2 69
#define GPIO_PAD_69 GPIO68
#ifndef BALL_P22_IS_GPIO
#define BALL_P22_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D2_IS_GPIO
#define PAD_TS0_D2_IS_GPIO BALL_P22_IS_GPIO
#endif 

#define BALL_Y12 PAD_TS0_D3
#define PAD_TS0_D3 70
#define GPIO_PAD_70 GPIO69
#ifndef BALL_Y12_IS_GPIO
#define BALL_Y12_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D3_IS_GPIO
#define PAD_TS0_D3_IS_GPIO BALL_Y12_IS_GPIO
#endif 

#define BALL_AA13 PAD_TS0_D4
#define PAD_TS0_D4 71
#define GPIO_PAD_71 GPIO70
#ifndef BALL_AA13_IS_GPIO
#define BALL_AA13_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D4_IS_GPIO
#define PAD_TS0_D4_IS_GPIO BALL_AA13_IS_GPIO
#endif 

#define BALL_AB14 PAD_TS0_D5
#define PAD_TS0_D5 72
#define GPIO_PAD_72 GPIO71
#ifndef BALL_AB14_IS_GPIO
#define BALL_AB14_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D5_IS_GPIO
#define PAD_TS0_D5_IS_GPIO BALL_AB14_IS_GPIO
#endif 

#define BALL_AA15 PAD_TS0_D6
#define PAD_TS0_D6 73
#define GPIO_PAD_73 GPIO72
#ifndef BALL_AA15_IS_GPIO
#define BALL_AA15_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D6_IS_GPIO
#define PAD_TS0_D6_IS_GPIO BALL_AA15_IS_GPIO
#endif 

#define BALL_AC15 PAD_TS0_D7
#define PAD_TS0_D7 74
#define GPIO_PAD_74 GPIO73
#ifndef BALL_AC15_IS_GPIO
#define BALL_AC15_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D7_IS_GPIO
#define PAD_TS0_D7_IS_GPIO BALL_AC15_IS_GPIO
#endif 

#define BALL_T20 PAD_TS0_VLD
#define PAD_TS0_VLD 75
#define GPIO_PAD_75 GPIO74
#ifndef BALL_T20_IS_GPIO
#define BALL_T20_IS_GPIO 0
#endif 
#ifndef PAD_TS0_VLD_IS_GPIO
#define PAD_TS0_VLD_IS_GPIO BALL_T20_IS_GPIO
#endif 

#define BALL_R19 PAD_TS0_SYNC
#define PAD_TS0_SYNC 76
#define GPIO_PAD_76 GPIO75
#ifndef BALL_R19_IS_GPIO
#define BALL_R19_IS_GPIO 0
#endif 
#ifndef PAD_TS0_SYNC_IS_GPIO
#define PAD_TS0_SYNC_IS_GPIO BALL_R19_IS_GPIO
#endif 

#define BALL_U19 PAD_TS0_CLK
#define PAD_TS0_CLK 77
#define GPIO_PAD_77 GPIO76
#ifndef BALL_U19_IS_GPIO
#define BALL_U19_IS_GPIO 0
#endif 
#ifndef PAD_TS0_CLK_IS_GPIO
#define PAD_TS0_CLK_IS_GPIO BALL_U19_IS_GPIO
#endif 

#define BALL_W19 PAD_TS1_CLK
#define PAD_TS1_CLK 78
#define GPIO_PAD_78 GPIO77
#ifndef BALL_W19_IS_GPIO
#define BALL_W19_IS_GPIO 0
#endif 
#ifndef PAD_TS1_CLK_IS_GPIO
#define PAD_TS1_CLK_IS_GPIO BALL_W19_IS_GPIO
#endif 

#define BALL_AA18 PAD_TS1_SYNC
#define PAD_TS1_SYNC 79
#define GPIO_PAD_79 GPIO78
#ifndef BALL_AA18_IS_GPIO
#define BALL_AA18_IS_GPIO 0
#endif 
#ifndef PAD_TS1_SYNC_IS_GPIO
#define PAD_TS1_SYNC_IS_GPIO BALL_AA18_IS_GPIO
#endif 

#define BALL_AA21 PAD_TS1_VLD
#define PAD_TS1_VLD 80
#define GPIO_PAD_80 GPIO79
#ifndef BALL_AA21_IS_GPIO
#define BALL_AA21_IS_GPIO 0
#endif 
#ifndef PAD_TS1_VLD_IS_GPIO
#define PAD_TS1_VLD_IS_GPIO BALL_AA21_IS_GPIO
#endif 

#define BALL_W21 PAD_TS1_D7
#define PAD_TS1_D7 88
#define GPIO_PAD_88 GPIO87
#ifndef BALL_W21_IS_GPIO
#define BALL_W21_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D7_IS_GPIO
#define PAD_TS1_D7_IS_GPIO BALL_W21_IS_GPIO
#endif 

#define BALL_V20 PAD_TS1_D6
#define PAD_TS1_D6 87
#define GPIO_PAD_87 GPIO86
#ifndef BALL_V20_IS_GPIO
#define BALL_V20_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D6_IS_GPIO
#define PAD_TS1_D6_IS_GPIO BALL_V20_IS_GPIO
#endif 

#define BALL_W20 PAD_TS1_D5
#define PAD_TS1_D5 86
#define GPIO_PAD_86 GPIO85
#ifndef BALL_W20_IS_GPIO
#define BALL_W20_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D5_IS_GPIO
#define PAD_TS1_D5_IS_GPIO BALL_W20_IS_GPIO
#endif 

#define BALL_Y21 PAD_TS1_D4
#define PAD_TS1_D4 85
#define GPIO_PAD_85 GPIO84
#ifndef BALL_Y21_IS_GPIO
#define BALL_Y21_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D4_IS_GPIO
#define PAD_TS1_D4_IS_GPIO BALL_Y21_IS_GPIO
#endif 

#define BALL_Y19 PAD_TS1_D3
#define PAD_TS1_D3 84
#define GPIO_PAD_84 GPIO83
#ifndef BALL_Y19_IS_GPIO
#define BALL_Y19_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D3_IS_GPIO
#define PAD_TS1_D3_IS_GPIO BALL_Y19_IS_GPIO
#endif 

#define BALL_AA20 PAD_TS1_D2
#define PAD_TS1_D2 83
#define GPIO_PAD_83 GPIO82
#ifndef BALL_AA20_IS_GPIO
#define BALL_AA20_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D2_IS_GPIO
#define PAD_TS1_D2_IS_GPIO BALL_AA20_IS_GPIO
#endif 

#define BALL_AA19 PAD_TS1_D1
#define PAD_TS1_D1 82
#define GPIO_PAD_82 GPIO81
#ifndef BALL_AA19_IS_GPIO
#define BALL_AA19_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D1_IS_GPIO
#define PAD_TS1_D1_IS_GPIO BALL_AA19_IS_GPIO
#endif 

#define BALL_Y18 PAD_TS1_D0
#define PAD_TS1_D0 81
#define GPIO_PAD_81 GPIO80
#ifndef BALL_Y18_IS_GPIO
#define BALL_Y18_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D0_IS_GPIO
#define PAD_TS1_D0_IS_GPIO BALL_Y18_IS_GPIO
#endif 

#define BALL_AA11 PAD_PCM_D3
#define PAD_PCM_D3 105
#define GPIO_PAD_105 GPIO104
#ifndef BALL_AA11_IS_GPIO
#define BALL_AA11_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D3_IS_GPIO
#define PAD_PCM_D3_IS_GPIO BALL_AA11_IS_GPIO
#endif 

#define BALL_AA12 PAD_PCM_D4
#define PAD_PCM_D4 106
#define GPIO_PAD_106 GPIO105
#ifndef BALL_AA12_IS_GPIO
#define BALL_AA12_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D4_IS_GPIO
#define PAD_PCM_D4_IS_GPIO BALL_AA12_IS_GPIO
#endif 

#define BALL_Y13 PAD_PCM_D5
#define PAD_PCM_D5 107
#define GPIO_PAD_107 GPIO106
#ifndef BALL_Y13_IS_GPIO
#define BALL_Y13_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D5_IS_GPIO
#define PAD_PCM_D5_IS_GPIO BALL_Y13_IS_GPIO
#endif 

#define BALL_Y14 PAD_PCM_D6
#define PAD_PCM_D6 108
#define GPIO_PAD_108 GPIO107
#ifndef BALL_Y14_IS_GPIO
#define BALL_Y14_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D6_IS_GPIO
#define PAD_PCM_D6_IS_GPIO BALL_Y14_IS_GPIO
#endif 

#define BALL_AA14 PAD_PCM_D7
#define PAD_PCM_D7 109
#define GPIO_PAD_109 GPIO108
#ifndef BALL_AA14_IS_GPIO
#define BALL_AA14_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D7_IS_GPIO
#define PAD_PCM_D7_IS_GPIO BALL_AA14_IS_GPIO
#endif 

#define BALL_Y15 PAD_PCM_CE_N
#define PAD_PCM_CE_N 110
#define GPIO_PAD_110 GPIO109
#ifndef BALL_Y15_IS_GPIO
#define BALL_Y15_IS_GPIO 0
#endif 
#ifndef PAD_PCM_CE_N_IS_GPIO
#define PAD_PCM_CE_N_IS_GPIO BALL_Y15_IS_GPIO
#endif 

#define BALL_AD15 PAD_PCM_A10
#define PAD_PCM_A10 111
#define GPIO_PAD_111 GPIO110
#ifndef BALL_AD15_IS_GPIO
#define BALL_AD15_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A10_IS_GPIO
#define PAD_PCM_A10_IS_GPIO BALL_AD15_IS_GPIO
#endif 

#define BALL_AC16 PAD_PCM_OE_N
#define PAD_PCM_OE_N 112
#define GPIO_PAD_112 GPIO111
#ifndef BALL_AC16_IS_GPIO
#define BALL_AC16_IS_GPIO 0
#endif 
#ifndef PAD_PCM_OE_N_IS_GPIO
#define PAD_PCM_OE_N_IS_GPIO BALL_AC16_IS_GPIO
#endif 

#define BALL_Y16 PAD_PCM_A11
#define PAD_PCM_A11 113
#define GPIO_PAD_113 GPIO112
#ifndef BALL_Y16_IS_GPIO
#define BALL_Y16_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A11_IS_GPIO
#define PAD_PCM_A11_IS_GPIO BALL_Y16_IS_GPIO
#endif 

#define BALL_AA16 PAD_PCM_IORD_N
#define PAD_PCM_IORD_N 114
#define GPIO_PAD_114 GPIO113
#ifndef BALL_AA16_IS_GPIO
#define BALL_AA16_IS_GPIO 0
#endif 
#ifndef PAD_PCM_IORD_N_IS_GPIO
#define PAD_PCM_IORD_N_IS_GPIO BALL_AA16_IS_GPIO
#endif 

#define BALL_AB16 PAD_PCM_A9
#define PAD_PCM_A9 115
#define GPIO_PAD_115 GPIO114
#ifndef BALL_AB16_IS_GPIO
#define BALL_AB16_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A9_IS_GPIO
#define PAD_PCM_A9_IS_GPIO BALL_AB16_IS_GPIO
#endif 

#define BALL_AA17 PAD_PCM_IOWR_N
#define PAD_PCM_IOWR_N 116
#define GPIO_PAD_116 GPIO115
#ifndef BALL_AA17_IS_GPIO
#define BALL_AA17_IS_GPIO 0
#endif 
#ifndef PAD_PCM_IOWR_N_IS_GPIO
#define PAD_PCM_IOWR_N_IS_GPIO BALL_AA17_IS_GPIO
#endif 

#define BALL_AB17 PAD_PCM_A8
#define PAD_PCM_A8 117
#define GPIO_PAD_117 GPIO116
#ifndef BALL_AB17_IS_GPIO
#define BALL_AB17_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A8_IS_GPIO
#define PAD_PCM_A8_IS_GPIO BALL_AB17_IS_GPIO
#endif 

#define BALL_Y17 PAD_PCM_A13
#define PAD_PCM_A13 118
#define GPIO_PAD_118 GPIO117
#ifndef BALL_Y17_IS_GPIO
#define BALL_Y17_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A13_IS_GPIO
#define PAD_PCM_A13_IS_GPIO BALL_Y17_IS_GPIO
#endif 

#define BALL_AB19 PAD_PCM_A14
#define PAD_PCM_A14 119
#define GPIO_PAD_119 GPIO118
#ifndef BALL_AB19_IS_GPIO
#define BALL_AB19_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A14_IS_GPIO
#define PAD_PCM_A14_IS_GPIO BALL_AB19_IS_GPIO
#endif 

#define BALL_AB20 PAD_PCM_WE_N
#define PAD_PCM_WE_N 120
#define GPIO_PAD_120 GPIO119
#ifndef BALL_AB20_IS_GPIO
#define BALL_AB20_IS_GPIO 0
#endif 
#ifndef PAD_PCM_WE_N_IS_GPIO
#define PAD_PCM_WE_N_IS_GPIO BALL_AB20_IS_GPIO
#endif 

#define PAD_PCM_IRQA_N 9999
#ifndef PAD_PCM_IRQA_N_IS_GPIO
#define PAD_PCM_IRQA_N_IS_GPIO 0
#endif 

#define BALL_V19 PAD_PCM_A12
#define PAD_PCM_A12 122
#define GPIO_PAD_122 GPIO121
#ifndef BALL_V19_IS_GPIO
#define BALL_V19_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A12_IS_GPIO
#define PAD_PCM_A12_IS_GPIO BALL_V19_IS_GPIO
#endif 

#define BALL_Y20 PAD_PCM_A7
#define PAD_PCM_A7 123
#define GPIO_PAD_123 GPIO122
#ifndef BALL_Y20_IS_GPIO
#define BALL_Y20_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A7_IS_GPIO
#define PAD_PCM_A7_IS_GPIO BALL_Y20_IS_GPIO
#endif 

#define BALL_AC13 PAD_PCM_A6
#define PAD_PCM_A6 124
#define GPIO_PAD_124 GPIO123
#ifndef BALL_AC13_IS_GPIO
#define BALL_AC13_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A6_IS_GPIO
#define PAD_PCM_A6_IS_GPIO BALL_AC13_IS_GPIO
#endif 

#define BALL_AD12 PAD_PCM_A5
#define PAD_PCM_A5 125
#define GPIO_PAD_125 GPIO124
#ifndef BALL_AD12_IS_GPIO
#define BALL_AD12_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A5_IS_GPIO
#define PAD_PCM_A5_IS_GPIO BALL_AD12_IS_GPIO
#endif 

#define PAD_PCM_WAIT_N 9999
#ifndef PAD_PCM_WAIT_N_IS_GPIO
#define PAD_PCM_WAIT_N_IS_GPIO 0
#endif 

#define BALL_AE13 PAD_PCM_A4
#define PAD_PCM_A4 127
#define GPIO_PAD_127 GPIO126
#ifndef BALL_AE13_IS_GPIO
#define BALL_AE13_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A4_IS_GPIO
#define PAD_PCM_A4_IS_GPIO BALL_AE13_IS_GPIO
#endif 

#define BALL_U20 PAD_PCM_A3
#define PAD_PCM_A3 128
#define GPIO_PAD_128 GPIO127
#ifndef BALL_U20_IS_GPIO
#define BALL_U20_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A3_IS_GPIO
#define PAD_PCM_A3_IS_GPIO BALL_U20_IS_GPIO
#endif 

#define BALL_AD13 PAD_PCM_A2
#define PAD_PCM_A2 129
#define GPIO_PAD_129 GPIO128
#ifndef BALL_AD13_IS_GPIO
#define BALL_AD13_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A2_IS_GPIO
#define PAD_PCM_A2_IS_GPIO BALL_AD13_IS_GPIO
#endif 

#define PAD_PCM_REG_N 9999
#ifndef PAD_PCM_REG_N_IS_GPIO
#define PAD_PCM_REG_N_IS_GPIO 0
#endif 

#define BALL_AB13 PAD_PCM_A1
#define PAD_PCM_A1 131
#define GPIO_PAD_131 GPIO130
#ifndef BALL_AB13_IS_GPIO
#define BALL_AB13_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A1_IS_GPIO
#define PAD_PCM_A1_IS_GPIO BALL_AB13_IS_GPIO
#endif 

#define BALL_T19 PAD_PCM_A0
#define PAD_PCM_A0 132
#define GPIO_PAD_132 GPIO131
#ifndef BALL_T19_IS_GPIO
#define BALL_T19_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A0_IS_GPIO
#define PAD_PCM_A0_IS_GPIO BALL_T19_IS_GPIO
#endif 

#define BALL_AC14 PAD_PCM_D0
#define PAD_PCM_D0 133
#define GPIO_PAD_133 GPIO132
#ifndef BALL_AC14_IS_GPIO
#define BALL_AC14_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D0_IS_GPIO
#define PAD_PCM_D0_IS_GPIO BALL_AC14_IS_GPIO
#endif 

#define BALL_AD14 PAD_PCM_D1
#define PAD_PCM_D1 134
#define GPIO_PAD_134 GPIO133
#ifndef BALL_AD14_IS_GPIO
#define BALL_AD14_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D1_IS_GPIO
#define PAD_PCM_D1_IS_GPIO BALL_AD14_IS_GPIO
#endif 

#define BALL_AE14 PAD_PCM_D2
#define PAD_PCM_D2 135
#define GPIO_PAD_135 GPIO134
#ifndef BALL_AE14_IS_GPIO
#define BALL_AE14_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D2_IS_GPIO
#define PAD_PCM_D2_IS_GPIO BALL_AE14_IS_GPIO
#endif 

#define PAD_PCM_RESET 9999
#ifndef PAD_PCM_RESET_IS_GPIO
#define PAD_PCM_RESET_IS_GPIO 0
#endif 

#define PAD_PCM_CD_N 9999
#ifndef PAD_PCM_CD_N_IS_GPIO
#define PAD_PCM_CD_N_IS_GPIO 0
#endif 

#define BALL_P20 PAD_PCM2_CE_N
#define PAD_PCM2_CE_N 138
#define GPIO_PAD_138 GPIO137
#ifndef BALL_P20_IS_GPIO
#define BALL_P20_IS_GPIO 0
#endif 
#ifndef PAD_PCM2_CE_N_IS_GPIO
#define PAD_PCM2_CE_N_IS_GPIO BALL_P20_IS_GPIO
#endif 

#define BALL_R20 PAD_PCM2_IRQA_N
#define PAD_PCM2_IRQA_N 139
#define GPIO_PAD_139 GPIO138
#ifndef BALL_R20_IS_GPIO
#define BALL_R20_IS_GPIO 0
#endif 
#ifndef PAD_PCM2_IRQA_N_IS_GPIO
#define PAD_PCM2_IRQA_N_IS_GPIO BALL_R20_IS_GPIO
#endif 

#define BALL_U21 PAD_PCM2_WAIT_N
#define PAD_PCM2_WAIT_N 140
#define GPIO_PAD_140 GPIO139
#ifndef BALL_U21_IS_GPIO
#define BALL_U21_IS_GPIO 0
#endif 
#ifndef PAD_PCM2_WAIT_N_IS_GPIO
#define PAD_PCM2_WAIT_N_IS_GPIO BALL_U21_IS_GPIO
#endif 

#define BALL_N21 PAD_PCM2_RESET
#define PAD_PCM2_RESET 141
#define GPIO_PAD_141 GPIO140
#ifndef BALL_N21_IS_GPIO
#define BALL_N21_IS_GPIO 0
#endif 
#ifndef PAD_PCM2_RESET_IS_GPIO
#define PAD_PCM2_RESET_IS_GPIO BALL_N21_IS_GPIO
#endif 

#define BALL_N20 PAD_PCM2_CD_N
#define PAD_PCM2_CD_N 142
#define GPIO_PAD_142 GPIO141
#ifndef BALL_N20_IS_GPIO
#define BALL_N20_IS_GPIO 0
#endif 
#ifndef PAD_PCM2_CD_N_IS_GPIO
#define PAD_PCM2_CD_N_IS_GPIO BALL_N20_IS_GPIO
#endif 

#define PAD_NAND_CEZ 9999
#ifndef PAD_NAND_CEZ_IS_GPIO
#define PAD_NAND_CEZ_IS_GPIO 0
#endif 

#define PAD_NAND_CEZ1 9999
#ifndef PAD_NAND_CEZ1_IS_GPIO
#define PAD_NAND_CEZ1_IS_GPIO 0
#endif 

#define BALL_AC11 PAD_ONE_A15
#define PAD_ONE_A15 161
#define GPIO_PAD_161 GPIO160
#ifndef BALL_AC11_IS_GPIO
#define BALL_AC11_IS_GPIO 0
#endif 
#ifndef PAD_ONE_A15_IS_GPIO
#define PAD_ONE_A15_IS_GPIO BALL_AC11_IS_GPIO
#endif 

#define BALL_AB22 PAD_ONE_D13
#define PAD_ONE_D13 162
#define GPIO_PAD_162 GPIO161
#ifndef BALL_AB22_IS_GPIO
#define BALL_AB22_IS_GPIO 0
#endif 
#ifndef PAD_ONE_D13_IS_GPIO
#define PAD_ONE_D13_IS_GPIO BALL_AB22_IS_GPIO
#endif 

#define BALL_Y10 PAD_ONE_D14
#define PAD_ONE_D14 163
#define GPIO_PAD_163 GPIO162
#ifndef BALL_Y10_IS_GPIO
#define BALL_Y10_IS_GPIO 0
#endif 
#ifndef PAD_ONE_D14_IS_GPIO
#define PAD_ONE_D14_IS_GPIO BALL_Y10_IS_GPIO
#endif 

#define BALL_AC24 PAD_ONE_D15
#define PAD_ONE_D15 164
#define GPIO_PAD_164 GPIO163
#ifndef BALL_AC24_IS_GPIO
#define BALL_AC24_IS_GPIO 0
#endif 
#ifndef PAD_ONE_D15_IS_GPIO
#define PAD_ONE_D15_IS_GPIO BALL_AC24_IS_GPIO
#endif 

#define BALL_AB11 PAD_ONE_CLK
#define PAD_ONE_CLK 165
#define GPIO_PAD_165 GPIO164
#ifndef BALL_AB11_IS_GPIO
#define BALL_AB11_IS_GPIO 0
#endif 
#ifndef PAD_ONE_CLK_IS_GPIO
#define PAD_ONE_CLK_IS_GPIO BALL_AB11_IS_GPIO
#endif 

#define BALL_AA10 PAD_ONE_CEN
#define PAD_ONE_CEN 166
#define GPIO_PAD_166 GPIO165
#ifndef BALL_AA10_IS_GPIO
#define BALL_AA10_IS_GPIO 0
#endif 
#ifndef PAD_ONE_CEN_IS_GPIO
#define PAD_ONE_CEN_IS_GPIO BALL_AA10_IS_GPIO
#endif 

#define BALL_Y11 PAD_ONE_OEN
#define PAD_ONE_OEN 167
#define GPIO_PAD_167 GPIO166
#ifndef BALL_Y11_IS_GPIO
#define BALL_Y11_IS_GPIO 0
#endif 
#ifndef PAD_ONE_OEN_IS_GPIO
#define PAD_ONE_OEN_IS_GPIO BALL_Y11_IS_GPIO
#endif 

#define BALL_AD11 PAD_ONE_WEN
#define PAD_ONE_WEN 168
#define GPIO_PAD_168 GPIO167
#ifndef BALL_AD11_IS_GPIO
#define BALL_AD11_IS_GPIO 0
#endif 
#ifndef PAD_ONE_WEN_IS_GPIO
#define PAD_ONE_WEN_IS_GPIO BALL_AD11_IS_GPIO
#endif 

#define BALL_AC12 PAD_ONE_RPN
#define PAD_ONE_RPN 169
#define GPIO_PAD_169 GPIO168
#ifndef BALL_AC12_IS_GPIO
#define BALL_AC12_IS_GPIO 0
#endif 
#ifndef PAD_ONE_RPN_IS_GPIO
#define PAD_ONE_RPN_IS_GPIO BALL_AC12_IS_GPIO
#endif 

#define BALL_AE11 PAD_ONE_AVDN
#define PAD_ONE_AVDN 170
#define GPIO_PAD_170 GPIO169
#ifndef BALL_AE11_IS_GPIO
#define BALL_AE11_IS_GPIO 0
#endif 
#ifndef PAD_ONE_AVDN_IS_GPIO
#define PAD_ONE_AVDN_IS_GPIO BALL_AE11_IS_GPIO
#endif 

#define BALL_AE10 PAD_ONE_INT
#define PAD_ONE_INT 171
#define GPIO_PAD_171 GPIO170
#ifndef BALL_AE10_IS_GPIO
#define BALL_AE10_IS_GPIO 0
#endif 
#ifndef PAD_ONE_INT_IS_GPIO
#define PAD_ONE_INT_IS_GPIO BALL_AE10_IS_GPIO
#endif 

#define BALL_AC25 PAD_ONE_RDY
#define PAD_ONE_RDY 172
#define GPIO_PAD_172 GPIO171
#ifndef BALL_AC25_IS_GPIO
#define BALL_AC25_IS_GPIO 0
#endif 
#ifndef PAD_ONE_RDY_IS_GPIO
#define PAD_ONE_RDY_IS_GPIO BALL_AC25_IS_GPIO
#endif 

#define PAD_GPIO0 9999
#ifndef PAD_GPIO0_IS_GPIO
#define PAD_GPIO0_IS_GPIO 0
#endif 

#define PAD_GPIO1 9999
#ifndef PAD_GPIO1_IS_GPIO
#define PAD_GPIO1_IS_GPIO 0
#endif 

#define PAD_GPIO2 9999
#ifndef PAD_GPIO2_IS_GPIO
#define PAD_GPIO2_IS_GPIO 0
#endif 

#define PAD_GPIO3 9999
#ifndef PAD_GPIO3_IS_GPIO
#define PAD_GPIO3_IS_GPIO 0
#endif 

#define PAD_GPIO4 9999
#ifndef PAD_GPIO4_IS_GPIO
#define PAD_GPIO4_IS_GPIO 0
#endif 

#define PAD_GPIO5 9999
#ifndef PAD_GPIO5_IS_GPIO
#define PAD_GPIO5_IS_GPIO 0
#endif 

#define PAD_GPIO6 9999
#ifndef PAD_GPIO6_IS_GPIO
#define PAD_GPIO6_IS_GPIO 0
#endif 

#define PAD_GPIO7 9999
#ifndef PAD_GPIO7_IS_GPIO
#define PAD_GPIO7_IS_GPIO 0
#endif 

#define PAD_GPIO8 9999
#ifndef PAD_GPIO8_IS_GPIO
#define PAD_GPIO8_IS_GPIO 0
#endif 

#define PAD_GPIO9 9999
#ifndef PAD_GPIO9_IS_GPIO
#define PAD_GPIO9_IS_GPIO 0
#endif 

#define PAD_GPIO10 9999
#ifndef PAD_GPIO10_IS_GPIO
#define PAD_GPIO10_IS_GPIO 0
#endif 

#define PAD_GPIO11 9999
#ifndef PAD_GPIO11_IS_GPIO
#define PAD_GPIO11_IS_GPIO 0
#endif 

#define PAD_GPIO12 9999
#ifndef PAD_GPIO12_IS_GPIO
#define PAD_GPIO12_IS_GPIO 0
#endif 

#define PAD_GPIO13 9999
#ifndef PAD_GPIO13_IS_GPIO
#define PAD_GPIO13_IS_GPIO 0
#endif 

#define PAD_GPIO14 9999
#ifndef PAD_GPIO14_IS_GPIO
#define PAD_GPIO14_IS_GPIO 0
#endif 

#define PAD_GPIO15 9999
#ifndef PAD_GPIO15_IS_GPIO
#define PAD_GPIO15_IS_GPIO 0
#endif 

#define PAD_GPIO16 9999
#ifndef PAD_GPIO16_IS_GPIO
#define PAD_GPIO16_IS_GPIO 0
#endif 

#define PAD_GPIO17 9999
#ifndef PAD_GPIO17_IS_GPIO
#define PAD_GPIO17_IS_GPIO 0
#endif 

#define PAD_GPIO18 9999
#ifndef PAD_GPIO18_IS_GPIO
#define PAD_GPIO18_IS_GPIO 0
#endif 

#define PAD_GPIO19 9999
#ifndef PAD_GPIO19_IS_GPIO
#define PAD_GPIO19_IS_GPIO 0
#endif 

#define PAD_GPIO20 9999
#ifndef PAD_GPIO20_IS_GPIO
#define PAD_GPIO20_IS_GPIO 0
#endif 

#define PAD_GPIO21 9999
#ifndef PAD_GPIO21_IS_GPIO
#define PAD_GPIO21_IS_GPIO 0
#endif 

#define PAD_GPIO22 9999
#ifndef PAD_GPIO22_IS_GPIO
#define PAD_GPIO22_IS_GPIO 0
#endif 

#define PAD_GPIO23 9999
#ifndef PAD_GPIO23_IS_GPIO
#define PAD_GPIO23_IS_GPIO 0
#endif 

#define PAD_GPIO24 9999
#ifndef PAD_GPIO24_IS_GPIO
#define PAD_GPIO24_IS_GPIO 0
#endif 

#define PAD_GPIO25 9999
#ifndef PAD_GPIO25_IS_GPIO
#define PAD_GPIO25_IS_GPIO 0
#endif 

#define PAD_GPIO26 9999
#ifndef PAD_GPIO26_IS_GPIO
#define PAD_GPIO26_IS_GPIO 0
#endif 

#define PAD_GPIO27 9999
#ifndef PAD_GPIO27_IS_GPIO
#define PAD_GPIO27_IS_GPIO 0
#endif 

#define PAD_PWM0 9999
#ifndef PAD_PWM0_IS_GPIO
#define PAD_PWM0_IS_GPIO 0
#endif 

#define PAD_PWM3 9999
#ifndef PAD_PWM3_IS_GPIO
#define PAD_PWM3_IS_GPIO 0
#endif 

#define PAD_PWM1 9999
#ifndef PAD_PWM1_IS_GPIO
#define PAD_PWM1_IS_GPIO 0
#endif 

#define PAD_PWM4 9999
#ifndef PAD_PWM4_IS_GPIO
#define PAD_PWM4_IS_GPIO 0
#endif 

#define BALL_AC23 PAD_PWM2
#define PAD_PWM2 177
#define GPIO_PAD_177 GPIO176
#ifndef BALL_AC23_IS_GPIO
#define BALL_AC23_IS_GPIO 0
#endif 
#ifndef PAD_PWM2_IS_GPIO
#define PAD_PWM2_IS_GPIO BALL_AC23_IS_GPIO
#endif 

#define BALL_Y22 PAD_DDCR_DA
#define PAD_DDCR_DA 173
#define GPIO_PAD_173 GPIO172
#ifndef BALL_Y22_IS_GPIO
#define BALL_Y22_IS_GPIO 0
#endif 
#ifndef PAD_DDCR_DA_IS_GPIO
#define PAD_DDCR_DA_IS_GPIO BALL_Y22_IS_GPIO
#endif 

#define BALL_AA22 PAD_DDCR_CK
#define PAD_DDCR_CK 174
#define GPIO_PAD_174 GPIO173
#ifndef BALL_AA22_IS_GPIO
#define BALL_AA22_IS_GPIO 0
#endif 
#ifndef PAD_DDCR_CK_IS_GPIO
#define PAD_DDCR_CK_IS_GPIO BALL_AA22_IS_GPIO
#endif 

#define BALL_A3 PAD_I2S_IN_WS
#define PAD_I2S_IN_WS 93
#define GPIO_PAD_93 GPIO92
#ifndef BALL_A3_IS_GPIO
#define BALL_A3_IS_GPIO 0
#endif 
#ifndef PAD_I2S_IN_WS_IS_GPIO
#define PAD_I2S_IN_WS_IS_GPIO BALL_A3_IS_GPIO
#endif 

#define BALL_AA9 PAD_I2S_IN_BCK
#define PAD_I2S_IN_BCK 94
#define GPIO_PAD_94 GPIO93
#ifndef BALL_AA9_IS_GPIO
#define BALL_AA9_IS_GPIO 0
#endif 
#ifndef PAD_I2S_IN_BCK_IS_GPIO
#define PAD_I2S_IN_BCK_IS_GPIO BALL_AA9_IS_GPIO
#endif 

#define BALL_D4 PAD_I2S_IN_SD
#define PAD_I2S_IN_SD 95
#define GPIO_PAD_95 GPIO94
#ifndef BALL_D4_IS_GPIO
#define BALL_D4_IS_GPIO 0
#endif 
#ifndef PAD_I2S_IN_SD_IS_GPIO
#define PAD_I2S_IN_SD_IS_GPIO BALL_D4_IS_GPIO
#endif 

#define BALL_W8 PAD_I2S_OUT_MCK
#define PAD_I2S_OUT_MCK 99
#define GPIO_PAD_99 GPIO98
#ifndef BALL_W8_IS_GPIO
#define BALL_W8_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_MCK_IS_GPIO
#define PAD_I2S_OUT_MCK_IS_GPIO BALL_W8_IS_GPIO
#endif 

#define BALL_Y8 PAD_I2S_OUT_WS
#define PAD_I2S_OUT_WS 98
#define GPIO_PAD_98 GPIO97
#ifndef BALL_Y8_IS_GPIO
#define BALL_Y8_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_WS_IS_GPIO
#define PAD_I2S_OUT_WS_IS_GPIO BALL_Y8_IS_GPIO
#endif 

#define PAD_I2S_OUT_SD1 9999
#ifndef PAD_I2S_OUT_SD1_IS_GPIO
#define PAD_I2S_OUT_SD1_IS_GPIO 0
#endif 

#define BALL_AA8 PAD_I2S_OUT_BCK
#define PAD_I2S_OUT_BCK 100
#define GPIO_PAD_100 GPIO99
#ifndef BALL_AA8_IS_GPIO
#define BALL_AA8_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_BCK_IS_GPIO
#define PAD_I2S_OUT_BCK_IS_GPIO BALL_AA8_IS_GPIO
#endif 

#define BALL_AB8 PAD_I2S_OUT_SD
#define PAD_I2S_OUT_SD 101
#define GPIO_PAD_101 GPIO100
#ifndef BALL_AB8_IS_GPIO
#define BALL_AB8_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_SD_IS_GPIO
#define PAD_I2S_OUT_SD_IS_GPIO BALL_AB8_IS_GPIO
#endif 

#define PAD_I2S_OUT_SD2 9999
#ifndef PAD_I2S_OUT_SD2_IS_GPIO
#define PAD_I2S_OUT_SD2_IS_GPIO 0
#endif 

#define PAD_I2S_OUT_SD3 9999
#ifndef PAD_I2S_OUT_SD3_IS_GPIO
#define PAD_I2S_OUT_SD3_IS_GPIO 0
#endif 

#define PAD_TCON0 9999
#ifndef PAD_TCON0_IS_GPIO
#define PAD_TCON0_IS_GPIO 0
#endif 

#define PAD_TCON10 9999
#ifndef PAD_TCON10_IS_GPIO
#define PAD_TCON10_IS_GPIO 0
#endif 

#define PAD_TCON11 9999
#ifndef PAD_TCON11_IS_GPIO
#define PAD_TCON11_IS_GPIO 0
#endif 

#define PAD_TCON12 9999
#ifndef PAD_TCON12_IS_GPIO
#define PAD_TCON12_IS_GPIO 0
#endif 

#define PAD_TCON13 9999
#ifndef PAD_TCON13_IS_GPIO
#define PAD_TCON13_IS_GPIO 0
#endif 

#define PAD_TCON14 9999
#ifndef PAD_TCON14_IS_GPIO
#define PAD_TCON14_IS_GPIO 0
#endif 

#define PAD_TCON15 9999
#ifndef PAD_TCON15_IS_GPIO
#define PAD_TCON15_IS_GPIO 0
#endif 

#define PAD_TCON16 9999
#ifndef PAD_TCON16_IS_GPIO
#define PAD_TCON16_IS_GPIO 0
#endif 

#define PAD_TCON17 9999
#ifndef PAD_TCON17_IS_GPIO
#define PAD_TCON17_IS_GPIO 0
#endif 

#define PAD_TCON18 9999
#ifndef PAD_TCON18_IS_GPIO
#define PAD_TCON18_IS_GPIO 0
#endif 

#define PAD_TCON19 9999
#ifndef PAD_TCON19_IS_GPIO
#define PAD_TCON19_IS_GPIO 0
#endif 

#define PAD_TCON20 9999
#ifndef PAD_TCON20_IS_GPIO
#define PAD_TCON20_IS_GPIO 0
#endif 

#define PAD_TCON21 9999
#ifndef PAD_TCON21_IS_GPIO
#define PAD_TCON21_IS_GPIO 0
#endif 

#define PAD_MPIF_CLK 9999
#ifndef PAD_MPIF_CLK_IS_GPIO
#define PAD_MPIF_CLK_IS_GPIO 0
#endif 

#define PAD_MPIF_D3 9999
#ifndef PAD_MPIF_D3_IS_GPIO
#define PAD_MPIF_D3_IS_GPIO 0
#endif 

#define PAD_MPIF_D2 9999
#ifndef PAD_MPIF_D2_IS_GPIO
#define PAD_MPIF_D2_IS_GPIO 0
#endif 

#define PAD_MPIF_D1 9999
#ifndef PAD_MPIF_D1_IS_GPIO
#define PAD_MPIF_D1_IS_GPIO 0
#endif 

#define PAD_MPIF_D0 9999
#ifndef PAD_MPIF_D0_IS_GPIO
#define PAD_MPIF_D0_IS_GPIO 0
#endif 

#define PAD_MPIF_CS_N 9999
#ifndef PAD_MPIF_CS_N_IS_GPIO
#define PAD_MPIF_CS_N_IS_GPIO 0
#endif 

#define PAD_MPIF_BUSY_ERR 9999
#ifndef PAD_MPIF_BUSY_ERR_IS_GPIO
#define PAD_MPIF_BUSY_ERR_IS_GPIO 0
#endif 

#define BALL_AB10 PAD_SPDIF_IN
#define PAD_SPDIF_IN 96
#define GPIO_PAD_96 GPIO95
#ifndef BALL_AB10_IS_GPIO
#define BALL_AB10_IS_GPIO 0
#endif 
#ifndef PAD_SPDIF_IN_IS_GPIO
#define PAD_SPDIF_IN_IS_GPIO BALL_AB10_IS_GPIO
#endif 

#define BALL_Y5 PAD_SPDIF_OUT
#define PAD_SPDIF_OUT 97
#define GPIO_PAD_97 GPIO96
#ifndef BALL_Y5_IS_GPIO
#define BALL_Y5_IS_GPIO 0
#endif 
#ifndef PAD_SPDIF_OUT_IS_GPIO
#define PAD_SPDIF_OUT_IS_GPIO BALL_Y5_IS_GPIO
#endif 

#define BALL_F8 PAD_ET_COL
#define PAD_ET_COL 151
#define GPIO_PAD_151 GPIO150
#ifndef BALL_F8_IS_GPIO
#define BALL_F8_IS_GPIO 0
#endif 
#ifndef PAD_ET_COL_IS_GPIO
#define PAD_ET_COL_IS_GPIO BALL_F8_IS_GPIO
#endif 

#define BALL_F7 PAD_ET_TXD1
#define PAD_ET_TXD1 149
#define GPIO_PAD_149 GPIO148
#ifndef BALL_F7_IS_GPIO
#define BALL_F7_IS_GPIO 0
#endif 
#ifndef PAD_ET_TXD1_IS_GPIO
#define PAD_ET_TXD1_IS_GPIO BALL_F7_IS_GPIO
#endif 

#define BALL_E7 PAD_ET_TXD0
#define PAD_ET_TXD0 148
#define GPIO_PAD_148 GPIO147
#ifndef BALL_E7_IS_GPIO
#define BALL_E7_IS_GPIO 0
#endif 
#ifndef PAD_ET_TXD0_IS_GPIO
#define PAD_ET_TXD0_IS_GPIO BALL_E7_IS_GPIO
#endif 

#define BALL_F6 PAD_ET_TX_EN
#define PAD_ET_TX_EN 150
#define GPIO_PAD_150 GPIO149
#ifndef BALL_F6_IS_GPIO
#define BALL_F6_IS_GPIO 0
#endif 
#ifndef PAD_ET_TX_EN_IS_GPIO
#define PAD_ET_TX_EN_IS_GPIO BALL_F6_IS_GPIO
#endif 

#define BALL_G6 PAD_ET_TX_CLK
#define PAD_ET_TX_CLK 147
#define GPIO_PAD_147 GPIO146
#ifndef BALL_G6_IS_GPIO
#define BALL_G6_IS_GPIO 0
#endif 
#ifndef PAD_ET_TX_CLK_IS_GPIO
#define PAD_ET_TX_CLK_IS_GPIO BALL_G6_IS_GPIO
#endif 

#define BALL_D6 PAD_ET_RXD0
#define PAD_ET_RXD0 145
#define GPIO_PAD_145 GPIO144
#ifndef BALL_D6_IS_GPIO
#define BALL_D6_IS_GPIO 0
#endif 
#ifndef PAD_ET_RXD0_IS_GPIO
#define PAD_ET_RXD0_IS_GPIO BALL_D6_IS_GPIO
#endif 

#define BALL_D7 PAD_ET_MDC
#define PAD_ET_MDC 144
#define GPIO_PAD_144 GPIO143
#ifndef BALL_D7_IS_GPIO
#define BALL_D7_IS_GPIO 0
#endif 
#ifndef PAD_ET_MDC_IS_GPIO
#define PAD_ET_MDC_IS_GPIO BALL_D7_IS_GPIO
#endif 

#define BALL_E8 PAD_ET_MDIO
#define PAD_ET_MDIO 143
#define GPIO_PAD_143 GPIO142
#ifndef BALL_E8_IS_GPIO
#define BALL_E8_IS_GPIO 0
#endif 
#ifndef PAD_ET_MDIO_IS_GPIO
#define PAD_ET_MDIO_IS_GPIO BALL_E8_IS_GPIO
#endif 

#define BALL_E6 PAD_ET_RXD1
#define PAD_ET_RXD1 146
#define GPIO_PAD_146 GPIO145
#ifndef BALL_E6_IS_GPIO
#define BALL_E6_IS_GPIO 0
#endif 
#ifndef PAD_ET_RXD1_IS_GPIO
#define PAD_ET_RXD1_IS_GPIO BALL_E6_IS_GPIO
#endif 


#define GPIO_PAD_182 GPIO181
#define GPIO_PAD_183 GPIO182
#define GPIO_PAD_53 GPIO52
#define GPIO_PAD_54 GPIO53



// PADS group name to index
#define PADS_DDCR           1223
#define PADS_DDCR2          1224
#define PADS_TS0            1225
#define PADS_TS1            1226
#define PADS_GPIO1_GPIO2    1227
#define PADS_LHSYNC2_LVSYNC2 1228
#define PADS_PCI_AD20_AD21  1229
#define PADS_PCI            1230
#define PADS_PCM            1231
#define PADS_SAR            1232
#define PADS_DOUT           1233
#define PADS_DIN            1234
#define PADS_I2S            1235
#define PADS_PF             1236
#define PADS_EMAC           1237
#define PADS_TCON           1238
#define PADS_UART1_MODE1    1239
#define PADS_UART1_MODE2    1240
#define PADS_UART1_MODE3    1241
#define PADS_UART2_MODE1    1242
#define PADS_UART2_MODE2    1243
#define PADS_UART2_MODE3    1244
#define PADS_ET_MODE0       1245
#define PADS_ET_MODE1       1246
#define PADS_ET_MODE2       1247
#define PADS_ET_MODE3       1248
#define PADS_MIIC           1249
#define PADS_PF_MODE1       1250
#define PADS_PF_MODE2       1251
#define PADS_PF_MODE3       1252
#define PADS_SPI_CZ1        1253
#define PADS_SPI_CZ2        1254
#define PADS_SPI_CZ3        1255
#define PADS_DDCR3          1256

// chip capbilities
#define CHIP_HAS_BT656_IN          0
#define CHIP_HAS_TS0               1
#define CHIP_HAS_TS1               0 
#define CHIP_HAS_LVDS_10BIT_X2     1
#define CHIP_HAS_LVDS_8BIT_X2      1
#define CHIP_HAS_LVDS_8BIT_X1      1
#define CHIP_HAS_CIMAX             0
#define CHIP_HAS_USB_P0            1
#define CHIP_HAS_USB_P1            1
#define CHIP_HAS_USBVBUS0          0
#define CHIP_HAS_USBVBUS1          0
#define CHIP_HAS_UART1_MODE1       1 
#define CHIP_HAS_UART1_MODE2       1
#define CHIP_HAS_UART1_MODE3       1 
#define CHIP_HAS_PCMCIA1           0
#define CHIP_HAS_PCMCIA2           0
#define CHIP_HAS_PCMCIA            0
#define CHIP_HAS_UART2_MODE1       1 
#define CHIP_HAS_UART2_MODE2       1 
#define CHIP_HAS_UART2_MODE3       1 
#define CHIP_HAS_RGB_A             1 
#define CHIP_HAS_RGB_B             1 
#define CHIP_HAS_RGB_C             1 
#define CHIP_HAS_HDMI_A            1 
#define CHIP_HAS_HDMI_B            1 
#define CHIP_HAS_HDMI_C            1 
#define CHIP_HAS_SPI_CZ1           1 
#define CHIP_HAS_SPI_CZ2           0 
#define CHIP_HAS_SPI_CZ3           0
#define CHIP_HAS_DDCR              1 
#define CHIP_HAS_DDCR2             1 
#define CHIP_HAS_TCON              1
#define CHIP_HAS_ET_MODE0_MII      1 
#define CHIP_HAS_ET_MODE0_RMII     1 
#define CHIP_HAS_ET_MODE1_MII      1 
#define CHIP_HAS_ET_MODE1_RMII     1 
#define CHIP_HAS_ET_MODE2_MII      1
#define CHIP_HAS_ET_MODE2_RMII     1
#define CHIP_HAS_I2S_IN            1 
#define CHIP_HAS_I2S_OUT           1
#define CHIP_HAS_SPDIF_IN          0 
#define CHIP_HAS_SPDIF_OUT         1
#define CHIP_HAS_DDR_A_CMD         1
#define CHIP_HAS_DDR_A_DATA        1
#define CHIP_HAS_DDR_B_CMD         1
#define CHIP_HAS_DDR_B_DATA        1
#define CHIP_USE_PCM_CDN_IN_PCM2   0
#define CHIP_USE_I2S_IN_IN_PCM     0
#define CHIP_USE_I2S_OUT_IN_PCM    0
#define CHIP_USE_SPDIF_IN_IN_PCM   0
#define CHIP_USE_SPDIF_OUT_IN_PCM  0
#define CHIP_USE_IIC_IN_DDCR2      0
#define CHIP_USE_PWM2_IN_GPIO14    0
#define CHIP_USE_PWM3_IN_GPIO15    0

// chip additional information
#define CHIP_FAMILY_TYPE           CHIP_FAMILY_S8

#endif /* _MSD393SSXT_H_*/
