#ifndef _UPGRADE_UI_H
#define _UPGRADE_UI_H

typedef enum 
{
	UPGRADE_INIT_USB_FAIL = 0,
	UPGRADE_SEARCH_STORAGE,
	UPGRADE_SEARCH_STORAGE_FAIL,	
	UPGRADE_SEARCH_UPGARDE_FILE,	
	UPGRADE_SEARCH_UPGARDE_FILE_FAIL,	
	UPGRADE_LOAD_UPGARDE_FILE,	
	UPGRADE_LOAD_UPGARDE_FILE_FAIL,	
	UPGRADE_PROGRESS,	
	UPGRADE_SUCCEED,
	UPGRADE_FAIL,
}ENUM_UPGRADE_STATUS;

typedef enum _E_UPGRADE_UI_INIT_STAT {
	E_UPGRADE_UI_UNINIT = 0,
	E_UPGRADE_UI_INIT_OK,
	E_UPGRADE_UI_INIT_FAILED,
} E_UPGRADE_UI_INIT_STAT;

int draw_upgrade_status(ENUM_UPGRADE_STATUS eStatus, unsigned short percent );
#endif

