#
# Makefile for MStar TSP HAL drivers.
#

# general options
EXTRA_CFLAGS      +=  -Idrivers/mstar/include
EXTRA_CFLAGS      +=  -Idrivers/mstar/sc
EXTRA_CFLAGS      +=  -Idrivers/mstar/sc/$(CONFIG_MSTAR_CHIP_NAME)

# files
obj-y             += mhal_sc.o
