#
# Makefile for MStar device drivers.
#

obj-$(CONFIG_MSTAR_IOMAP)                           += iomap/
obj-$(CONFIG_MSTAR_MSYSTEM)                         += msystem/
obj-$(CONFIG_MSTAR_FW)                              += firmware/
obj-$(CONFIG_MSTAR_MPOOL)                           += mpool/
obj-$(CONFIG_MSTAR_IIC)                             += iic/
obj-$(CONFIG_MSTAR_GPIO)                            += gpio/
obj-$(CONFIG_MSTAR_EMAC)                            += emac/
obj-$(CONFIG_MSTAR_SYSTEM)                          += system/
obj-$(CONFIG_MSTAR_IR)                              += ir/
obj-$(CONFIG_MSTAR_SOFTWARE_IR)                     += software_ir/
obj-$(CONFIG_MSTAR_NAND)                            += nand/
obj-$(CONFIG_MSTAR_SDMMC)                           += sdmmc/
obj-$(CONFIG_MMC_MSTAR_MMC_EMMC)                    += mmc/
obj-$(CONFIG_MSTAR_MBX)                             += mbx/
obj-$(CONFIG_MSTAR_FUSION_8_7)                      += fusion_8_7/
obj-$(CONFIG_MSTAR_FUSION)                          += fusion/
obj-$(CONFIG_MSTAR_ONENAND)                         += onenand/
obj-$(CONFIG_MSTAR_GFLIP)                           += gflip/
obj-$(CONFIG_MSTAR_RFID)                            += rfid/
obj-$(CONFIG_MSTAR_SPI_FLASH)                       += flash/
obj-$(CONFIG_MSTAR_VPOOL)                           += vid_pre_alloc_mem/
obj-$(CONFIG_MSTAR_MSGLOG)                          += msglog/
obj-$(CONFIG_MSTAR_MSGIO)                           += msgio/
obj-$(CONFIG_MSTAR_TSP)                             += tsp/
obj-$(CONFIG_MSTAR_SC)                              += sc/
obj-$(CONFIG_MSTAR_G3D)                             += g3d/
obj-$(CONFIG_MSTAR_MPIF)                            += mpif/
obj-$(CONFIG_MSTAR_ALSA_AUDIO_DRIVER_DRV)           += alsa_audio_driver/drv/
obj-$(CONFIG_MSTAR_ALSA_AUDIO_DRIVER_HAL)           += alsa_audio_driver/hal/
obj-$(CONFIG_MSTAR_SEMUTEX)           				+= semutex/
obj-$(CONFIG_MSTAR_GMAC)                            += gmac/
obj-$(CONFIG_TZ_SUPPORT)			    += trustzone/
obj-$(CONFIG_MSTAR_FB)           				    += mstar_fb/
obj-y	      += uarttp/
