#
# Makefile for MSTP drivers.
#
# files

EXTRA_CFLAGS      +=  -Idrivers/mstar/include

obj-$(CONFIG_MSTP)	+= mstp.o
mstp-y			+= mstar_ts_msg20xx.o drv_touch_screen.o hal_touch_screen_c_msg20xx.o drvUART.o halUART.o

